### ISSUE TITLE
Crash on multiple left side controller menu

### ISSUE THREAD

**Issue by rosevinod** [jonkykong/SideMenu#1]
SideMenuManager.menuLeftNavigationController  = Table 1 .. Dashboard 1

SideMenuManager.menuLeftNavigationController  = Table 2 .. Dashboard 2

Crash.. 

I have used following to avoid above error!

INSTEAD OF using this -
presentViewController(SideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)
I have used this -
        performSegueWithIdentifier("segue_menu_controller", sender: self)

**Comment by jonkykong** [comment]
Thanks for finding this issue, @rosevinod.

I'm guessing that you were calling presentViewController from `viewWillAppear` or `viewDidAppear`, which were being called twice. This was most likely due to adding/removing the viewControllers to the transition context.

I've checked in a fix in 0.1.6.
