### ISSUE TITLE
Carthage update not Working

### ISSUE THREAD

**Issue by andre991** [jonkykong/SideMenu#101]
![captura de tela 2016-11-20 as 23 16 50](https://cloud.githubusercontent.com/assets/8302454/20467926/942af55a-af77-11e6-885c-e7ef3ede3cc3.png)

**Comment by jonkykong** [comment]
[This](http://stackoverflow.com/questions/31069315/carthage-errors-no-tagged-versions-found-for-github) will probably solve your problem.

**Comment by andre991** [comment]
Thanks jonkykong.

**Comment by pidjay** [comment]
What is the reasoning for not using tags?
