### ISSUE TITLE
Carthage Update not Working II

### ISSUE THREAD

**Issue by andre991** [jonkykong/SideMenu#102]
Hello it's me again!! lol

![captura de tela 2016-11-21 as 08 40 11](https://cloud.githubusercontent.com/assets/8302454/20479688/4ca89328-afc6-11e6-8cd1-051610d01e4d.png)

**Comment by faviomob** [comment]
Same issue with me:
<img width="835" alt="screen shot 2016-11-21 at 14 07 38" src="https://cloud.githubusercontent.com/assets/8747506/20480529/f0478750-aff3-11e6-9cce-b383c5e0255d.png">

**Comment by andre991** [comment]
I maked a Pull Request #103 to solve this problem.

**Comment by juegas** [comment]
👍  https://github.com/jonkykong/SideMenu/pull/103

**Comment by jonkykong** [comment]
Fixed in 2.0.7.
