### ISSUE TITLE
Presented And Dismissed Event

### ISSUE THREAD

**Issue by gunantosteven** [jonkykong/SideMenu#104]
I have posted what I want on stackoverflow but no one answer my question. [http://stackoverflow.com/questions/40841452/how-do-i-get-events-presented-and-dismissed-from-sidemenu](http://stackoverflow.com/questions/40841452/how-do-i-get-events-presented-and-dismissed-from-sidemenu)

**Comment by jonkykong** [comment]
#58. This is covered in the README: "Menus can be presented and dismissed the same as any other View Controller since this control uses custom transitions."

Be patient, you won't always get an answer in less than 24 hours.

**Comment by gunantosteven** [comment]
Can you give an example ? please...
I have read it but I don't know how to implement it.

**Comment by jonkykong** [comment]
http://stackoverflow.com/questions/7386333/guidelines-for-viewwillappear-viewdidappear-viewwilldisappear-viewdiddisappea

**Comment by gunantosteven** [comment]
I don't want to change code in UISideMenuNavigationController class but in MainViewController class. How do i do that ? thanks

**Comment by jonkykong** [comment]
@gunantosteven sorry, I'm going to have to leave you to figure this one out on your own. I understand it's frustrating and taking a lot of time to get right; I've been there. The answer is out there.
