### ISSUE TITLE
side menu won't show 

### ISSUE THREAD

**Issue by athemer** [jonkykong/SideMenu#108]
Hi, first of all, thanks for making this awesome side menu.

I am now having some problem and wondering if you could point out what might goes wrong.

so I followed the tutorial and build the project.
when I click on the "Button" to show side menu, the side menu is just pure black and Xcode saying 

"Warning: Attempt to present <SideMenu.UISideMenuNavigationController: 0x7ff7fa80a200>  on <rensyu.theMain: 0x7ff7f7d0cb90> which is already presenting <SideMenu.UISideMenuNavigationController: 0x7ff7f802e000>"

I'm pretty new to programming so even though I've been trying to tackle this for hours,
I still don't quite get what I want.

It would be awesome if you can help out a little bit here 
I've left a star at Github, nice work and thanks !!!

**Comment by jonkykong** [comment]
#58
