### ISSUE TITLE
Is it possible to show the menu inside a container view?

### ISSUE THREAD

**Issue by Querschlag** [jonkykong/SideMenu#109]
I have a main viewcontroller in my app with a container view which embeds another view controller with the actual content and below this container view a have an ad banner. This banner is always visible and only the content inside the container view changes.
Would it now be possible to show the menu from INSIDE the container view so that my ad banner would be still in the same position an fully visible?

**Comment by jonkykong** [comment]
@Querschlag have you attempted to get it to work yet?

**Comment by Querschlag** [comment]
Yes, I implemented this already as described.
The problem is that the side menu appears below the main viewcontroller and pushes the whole viewport to the right (container view + banner).
From what I understand the transition works like a modal presentation, so the presented viewcontroller (menu) becomes the topmost item, like a modal VC is sliding above the VC that presented it.
I call presentViewController(_:animated:completion:) from the VC embedded in the content view.

**Comment by jonkykong** [comment]
@Querschlag your understanding is correct.

To keep your banner stationary + topmost, you would either need to modify or subclass the transition, or add your banner to the window layer. There might be other solutions but these come top of mind.
