### ISSUE TITLE
Root view controller of UISideMenuNavigationController not being diaplayed

### ISSUE THREAD

**Issue by AkshayNG** [jonkykong/SideMenu#110]
Hi,

I don't know if this is issue or not. As mentioned in description I have UISideMenuNavigationController in my storyboard and one UIViewController as its root view controller. Everything was just ok except that UIViewControler (Say MenuVC) was not being displayed when side menu appeared.

I found the issue and it is this line : 
`let leftNavigationController = UISideMenuNavigationController()` 

So I just changed this to : 
`let leftNavigationController = UISideMenuNavigationController.init(rootViewController: MenuVC())`

**More efficiently:**
```
let menu = MAIN_STORYBOARD.instantiateViewController(withIdentifier: "Menu") as? MenuVC
let leftNavigationController = UISideMenuNavigationController.init(rootViewController: menu!)
```

Now its getting displayed. Why so ? I have set MenuVC as rootViewcontroller of UISideMenuNavigationController in storyboard. 

Thanks for SideMenu ! Its nice one.

**Comment by jonkykong** [comment]
#58

It appears you don't fully understand the difference between instantiating through code vs. through storyboard. You should read up on these more specifically to understand. The library is working as expected.
