### ISSUE TITLE
disable right menu

### ISSUE THREAD

**Issue by aqeelhashem** [jonkykong/SideMenu#114]
Hello,
 thanks for great extension.
 
how can disable the right menu ? , i only want the app to slide to left menu.

I'm using this code in viewdidload : 
`SideMenuManager.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? UISideMenuNavigationController
                
 SideMenuManager.menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? UISideMenuNavigationController
SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)`

I mean disable (Gesture) for the right side.

**Comment by jonkykong** [comment]
`menuAddPanGestureToPresent` and `menuAddScreenEdgePanGesturesToPresent` add gestures for both sides as the most likely intent by most developers. If you would like to enable it for only one side, you can use `menuAddScreenEdgePanGesturesToPresent` and set the only side. The pan gesture does not allow this. Your alternatives are to subclass the appropriate classes and override their behaviors.

**Comment by aqeelhashem** [comment]
thanks very much
