### ISSUE TITLE
Advice hiding status bar when presenting SideMenu

### ISSUE THREAD

**Issue by Laptopmini** [jonkykong/SideMenu#115]
Hi, I was wondering if I could get some input on hiding the status bar when presenting the SideMenu.

When I originally implemented the SideBar, I overwrote `prefersStatusBarHidden` to `true` so the status bar wouldn't be awkwardly be presented above 2 separate views (as you might of experienced). This worked fine until I recently migrated to Swift 3, where now, when the SideMenu is presented, its frame jumps up once its fully open.

Here is a screenshot, which shows how the 2 views are offset:
[http://imgur.com/a/pB8Rm](http://imgur.com/a/pB8Rm)

Previously, this wasn't an issue as the frame change would be animated, but it isn't anymore for some reason.

Have you had any experience with this? Is there a way to prevent jumping of the SideMenu's view when presented and the status bar hides itself?

I've looked into this problem on stackoverflow, trying to override `preferredStatusBarUpdateAnimation` or implementing custom animations, but without any success. I imagine I'm not the first person to run into this issue, so I thought I'd ask here. 

I've also tried using 
```
SideMenuManager.menuFadeStatusBar = true
SideMenuManager.menuAnimationBackgroundColor = UIColor.myCustomBlueColor
```
But it seeing as my SideMenu and main ViewController have different header colors, it just looks really odd.
[http://imgur.com/a/HcPCZ](http://imgur.com/a/HcPCZ)

**Comment by jonkykong** [comment]
@Laptopmini I haven't had that experience because I don't design for that; I think it's better to holistically show or hide the status bar instead of basing it on a subscreen (I modeled it after Facebook and that's what they do). You are the first person to mention this issue here.

I'm not sure how to go about solving your particular design. I have seen another [SideMenuController](https://github.com/teodorpatras/SideMenuController) that does what you're looking for. You can either try that, or investigate how it goes about smoothly animating the status bar to see if it can be incorporated here.

**Comment by jonkykong** [comment]
@Laptopmini the SideMenuManager properties you referenced are working as expected. This library isn't doing anything crazy when it comes to revealing the screens. It leaves everything up to UIKit for the most part, so I don't believe there's any behavioral problem with SideMenu.

**Comment by Laptopmini** [comment]
@jonkykong Thanks for the reply.

I didn't mean to insinuate there was anything wrong with the library, its working fine. I will look into the library you mentioned, but for the time being I'll keep this one as I have more pressing tasks then making sure the status bar is displaying nicely. :)

**Comment by jonkykong** [comment]
@Laptopmini no worries. It's always possible that it's a bug with the library, but all I mean to communicate is that it's not doing anything special that would seem to interfere with the animation, which is particularly evident if it was working in a prior iOS version and suddenly stopped. This library uses Interactive Transitions, which were initially buggy when they were introduced, and I suspect there's something going on there that changed this behavior.
