### ISSUE TITLE
menuReplaceOnPush in documentation but not in project

### ISSUE THREAD

**Issue by saltyskip** [jonkykong/SideMenu#116]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

In the documentation we have `open static var menuReplaceOnPush: Bool = false` which as I understand is meant to be able to continue the navigation stack after a menuItem is selected on the LeftMenu, but it seems to not be present in the code. Was there a reason for it's removal?

**Comment by saltyskip** [comment]
Looks like it is present in the 2.0.7 branch rather than the master branch, the docs are slightly ahead rather than behind.

**Comment by saltyskip** [comment]
So I think the issue is that actually the changes from the 2.0.7 branch are present in the cocoapod but not propagated to Carthage, can anyone else confirm?

**Comment by jonkykong** [comment]
I updated the latest tag. Try again and report back...

**Comment by jonkykong** [comment]
@saltyskip is it working now?

**Comment by saltyskip** [comment]
Sorry for the long delay, I went on holiday before I got to this. Fixed.

**Comment by zinlinphyo** [comment]
Is it still support in 6.0?
Is there any option to set the menu still remain on push?
