### ISSUE TITLE
TabbarController使用出现Warning

### ISSUE THREAD

**Issue by yinchenghc** [jonkykong/SideMenu#12]
I use sidemenu in the tabbarcontroller, when i click the tablecell in the sidemenu, the console display "warning：attempting to push a viewcontroller from a viewcontroller that doesn't have a NavigationController...."

**Comment by jonkykong** [comment]
Check to see how you've set up your segue for the TableViewCell. If you're
trying to push a view controller, but your TabBarController doesn't have a
navigation controller, then it can't be pushed. TabBarControllers don't
support PushViewController. You have to have a NavigationController inside
of the TabBarController to push.

**Comment by yinchenghc** [comment]
![2016-04-08 09 45 56](https://cloud.githubusercontent.com/assets/16238547/14372334/1ecfa4b6-fd72-11e5-9fef-9a71d1a70d30.png)
This is my TabbarController, you said "You have to have a NavigationController inside
of the TabBarController to push.", what should i do?

**Comment by jonkykong** [comment]
Those NavigationControllers are for the side menu. You need to display them
from a NavigationController to perform pushes.
