### ISSUE TITLE
Hide/Show side menu programmatically

### ISSUE THREAD

**Issue by harshvishu** [jonkykong/SideMenu#121]
Is there any way to programmatically **Hide/Show Side Menu**?

Proj Settings
-------------
pod 'SideMenu', '~> 2.1'
Xcode version: 8
Swift version: 3.0

**Comment by jonkykong** [comment]
All of the answers you need are in the README.

**Comment by hemangshah** [comment]
@jonkykong, it's not there in README that's why we have to come here to open an issue.

**Comment by jonkykong** [comment]
@hemangshah it is and can be found at https://github.com/jonkykong/SideMenu#code-implementation. Please read more carefully before opening issues and tagging other developers needlessly.

**Comment by tharindu** [comment]
Looks like there's no way to hide the menu programmatically, could you elaborate please?
