### ISSUE TITLE
Problem about push viewController from root viewcontroller of sideMunu

### ISSUE THREAD

**Issue by ricpi** [jonkykong/SideMenu#124]
In Objective-C, when i push viewController with code [self.navigationController pushViewController:viewController animated:YES], Xcode appears warning：SideMenu Warning: attempt to push a View Controller from Optional(<UITabBarController: 0x127a6d800>) where its navigationController == nil. It must be embedded in a Navigation Controller for this to work.
How to push view controller in Objective-C？

**Comment by jonkykong** [comment]
The warning message is self-explanatory.

**Comment by agates4** [comment]
clearly the warning message is not self-explanatory if someone feels the need to ask for an explanation

**Comment by jonkykong** [comment]
@agates4 @ricpi I'm open to suggestions.

**Comment by jonkykong** [comment]
@ricpi run `pod update` to get version 2.1.4 which has better dummy-proofed the problem you've encountered here.

**Comment by itali43** [comment]
Yeah, I'm getting the same issue as well, any help would be appreciated.  Not dummy-proofed enough for me :), I don't understand problem from the error message.

**Comment by jonkykong** [comment]
Put your view controller in a navigation controller.

**Comment by itali43** [comment]
I have my sidemenu in a navigation controller already.  The trouble comes when I try to push into a "submenu" view controller when I click on one of the Sidemenu items.  Is there a good way to do this?
(so it goes Home --> LeftSideMenuNav --> SidemenuVC -?-> SubmenuVC)

**Comment by jonkykong** [comment]
No. Put your main view controller in a navigation controller.

**Comment by itali43** [comment]
Ah, Ok, will do so now.

**Comment by itali43** [comment]
Ok, so this got rid of the error, but it doesn't do what I want it to.  I'll try to explain it a bit better, I think I was not clear enough before, apologies. 

Basically I want the sidemenu to show up like below (it does, works great):

![mainsidemenu](https://cloud.githubusercontent.com/assets/5652687/26601892/7b86e0ea-4536-11e7-858a-77718bc84e61.png)

However when someone clicks on an item, I want a "subMenu" to show up looking like so: 
![subsidemenu 2ndlayer](https://cloud.githubusercontent.com/assets/5652687/26601933/ac786e6c-4536-11e7-980e-c4e6d1650b47.png)

After you click on a submenu item it will transfer to the destination VC, like the above solution did.

current Storyboard looks like this: 
![screen shot 2017-05-30 at 12 45 14 pm](https://cloud.githubusercontent.com/assets/5652687/26602070/14ed8428-4537-11e7-9f97-444b1e938252.png)

**Comment by agates4** [comment]
you aren't doing it right

**Comment by itali43** [comment]
@agates4, That seems to be the case, are you able to point me in the right direction?

**Comment by jonkykong** [comment]
@itali43 I am asked these kinds of questions very often. Plain and simple: I don't have the time to help everyone. You need to read the README carefully as I've put a lot of time into making sure that it addresses these issues.

**Comment by itali43** [comment]
Thank you @jonkykong, while a bit cryptic, I found what you are referring to.  

If anyone comes across the same issue as me, CTRL + F on the readme and type in "submenu".  If you put that in your Navigation VC it should work make your submenu appear upon clicking and you won't get the error I was running into.  

Thanks again for your time @jonkykong, and a great library.

**Comment by serhiisol** [comment]
Hi Guys, I have question. I've tried to set .subMenu as .menuPushStyle but I've stuck into another problem. Submenu works as a charm, but now I have a problem pushing the view controller into main stack. I've tried ```navigationController?.pushViewController(detailsViewController, animated: true);``` and ```SideMenuManager.menuLeftNavigationController?.pushViewController(teamInfoViewController, animated: true)``` also tried via ```presentingViewController``` but I've got the same .subMenu navigation or missing behavior (nothing happens basically). Am I doing something wrong ?

**Comment by jonkykong** [comment]
@serhiisol calling push on presentingViewController should do the trick as long as presentingViewController is a navigation controller. Other than that, you can change the `menuPushStyle` right before you do the push.

**Comment by serhiisol** [comment]
ah, my apologies, I've used wrong controller, basically I've used
```presentingViewController.navigationController?.pushViewController(teamInfoViewController, animated: true)```
instead of 
```presentingViewController.pushViewController(teamInfoViewController, animated: true)````
