### ISSUE TITLE
black space on top - how to get rid

### ISSUE THREAD

**Issue by gulzatique** [jonkykong/SideMenu#126]
Hi I wonder how I could avoid this dark line to appear? and make it the same as nav bar color or view background color

thanks
<img width="322" alt="side menu" src="https://cloud.githubusercontent.com/assets/21258164/21693663/f23f76c2-d3ab-11e6-9b45-2b49d8b5a51c.png">

**Comment by jonkykong** [comment]
Closed for ignoring the issue template.

**Comment by agates4** [comment]
SideMenuManager.menuFadeStatusBar = false
