### ISSUE TITLE
Feature request (already coded) to create more of a 'tab' experience

### ISSUE THREAD

**Issue by agates4** [jonkykong/SideMenu#131]
I've coded a custom segue that will rearrange the navigation stack so that the destination view controller rises to the top of the stack - instead of constantly pushing view controllers onto the stack.

Advantages: 
- each view is maintained and will be left as it was when the user returns to that view through the SideMenu
- creates a 'tabbed' experience, changing view instantly after the segue is performed, without cluttered animations
- more of a traditional sidemenu experience found in professional applications

How to use:
1. Link any of the cells in the SideMenu to whatever controller you'd like with the class of "ReplaceImmediate" (the class name can change to your discretion) and with the segue kind of "custom"
2. make sure the module selected with the segue is where you can find "ReplaceImmediate"
3. done

The code:
```
import UIKit
import SideMenu

class ReplaceImmediate: UIStoryboardSegue {
    override func perform() {
        let source = self.source
        let destination = self.destination
        
        if let nav = source.navigationController as? UISideMenuNavigationController,
            let presentingNav = nav.presentingViewController as? UINavigationController {
            presentingNav.dismiss(animated: true, completion: nil)
            
            // if the destination controller is already in stack, we will bring it
            // to the front of the stack while maintaining the items that are already
            // in the stack
            if(isInStack(navController: presentingNav, viewController: destination))
            {
                var storedController:[UIViewController] = []
                var theController:UIViewController!
                for controller in presentingNav.viewControllers {
                    if(controller.nibName == destination.nibName)
                    {
                        theController = controller
                    }
                    else
                    {
                        storedController.append(controller)
                    }
                }
                storedController.append(theController)
                presentingNav.popToRootViewController(animated: false)
                
                for controller in storedController {
                    if(isInStack(navController: presentingNav, viewController: controller))
                    {
                        continue
                    }
                    presentingNav.pushViewController(controller, animated: false)
                }
            }
            // if the destination controller is not in the stack, we will
            // simple push it to the stack
            else
            {
                presentingNav.pushViewController(destination, animated: false)
            }
        }
        
    }
    
    // simple function to determine whether the viewcontroller is in the stack or not
    private func isInStack(navController: UINavigationController, viewController: UIViewController) -> Bool
    {
        for controller in navController.viewControllers {
            if(controller.nibName == viewController.nibName)
            {
                return true
            }
        }
        return false
    }
}
```

It would be nice to see this implemented, or for an option within the SideMenu of 'MenuRearrangeNavigationStack = true' but the animation itself with the segue (I believe) can only be performed through a custom segue.

**Comment by jonkykong** [comment]
I understand the gist of what you're trying to accomplish here.

There are some disadvantages to this approach as well, most notably in the form of memory pressure. The key advantage is not needing to save and reload the visual state, and potentially faster performance from memory.

Animations are possible without segues. SideMenu uses custom transitions to animate, which makes it work regardless of if the app is developed using Storyboard or pure code. Segues are primarily targeted at developers using Storyboard. `nibName` is also specific to **Interface Builder** and potentially disregards developers that prefer not to use it -- I'd rely on something like class names (as already done in SideMenu's `menuAllowPushOfSameClassTwice` functionality).

I would simplify this logic and rely on the navigation controller's existing `viewControllers` property to retain the view controller stack. Simply inspect the `viewControllers` stack to see if the desired view controller is already present (using array's `.filter` method) and bump that to the end of the array.

**Comment by agates4** [comment]
I've got it optimized now using filter (instead of the silly logic I was using earlier)

But is it best done through a segue? Like you said, segues are primarily targeted at developers using storyboard. Perhaps a native integration with SideMenu would be best. What do you think?

**Comment by jonkykong** [comment]
@agates4 As a developer that uses storyboards, it may be best done through a segue for **you**. However, there are many developers that prefer not to use storyboards for various reasons, and my goal was to provide a library that works regardless of the project setup. This is why SideMenu uses custom transitions; they work regardless if storyboards are used or not.

As described in the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md), I've specifically stated that I am willing to accept pull requests from other developers wanting to add functionality from SideMenu. However, I personally am **not** adding requests made by developers at this time. Creating this library has taken a tremendous amount of my time, and maintaining it continues to eat up more and more of it, all for free. I need to prioritize other work that provides me with an income over making updates here.

If you would like to contribute to this repository, please read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and open a pull request with your proposed changes. For the greatest chance at having your changes accepted, I highly suggest that you take my recommendations in this thread into consideration as I am trying to ensure the best quality code to all developers relying on this library.

If you don't feel up to making the proposed changes, we can leave this issue open as a feature request for another developer to take a shot at when they have time.

**Comment by jonkykong** [comment]
Closing as this is not an active-issue. All feature requests have been tagged and are searchable in closed issues.

**Comment by stealdre** [comment]
not working...
