### ISSUE TITLE
Converting to Swift 3.0

### ISSUE THREAD

**Issue by kawaxman** [jonkykong/SideMenu#132]
Hey,

I have been looking for a good framework to incorporate into my app, and I think that yours is the one I have been looking for. But, I cannot seem to get it working for Swift 3.0 compatibility. Am I doing something wrong? Please help!

**Comment by jonkykong** [comment]
@kawaxman yes, I think you're doing something wrong as Swift 3 has been supported for a long time. Please go through the README thoroughly.
