### ISSUE TITLE
side menu is not loaded when swiped

### ISSUE THREAD

**Issue by gulzatique** [jonkykong/SideMenu#133]
I have read the [guidelines for contributing]  and I understand:
- [ TRUE] My issue was **not** solved in the [README] 
- [TRUE ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com) 
- [ TRUE] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request. 
- [FALSE, because it has different structure ] My issue **is** reproducible in the [demo project] - 

## Issue Description
1) When my app is first launched and I swipe from left to right to pop the side menu, i see black screen 
2) when I choose menu item and it has child view controller, I go to that child controller, then I go back, then doing step 1 results in messy side menu- something clearly goes wrong. 
Info: the blue background if the side menu is a UIimageView stretched all over the View, with aspect fill so I do not know how it is been showed as chunks of images

How could I fix it? thanks

screenshot of storyboard:
1) initial navigation controller http://joxi.net/eAOGGOVuPkBVAo
2) case with child view controllers http://joxi.ru/xAe66odUGXwPry 

link to youtube video https://youtu.be/PRk-WsShGlM

**Comment by jonkykong** [comment]
@gulzatique this problem can be resolved by following the README or by
asking on Stackoverflow.

You have properly set up the menus in storyboard for the menu buttons,
however you have failed to programmatically set them up properly for the
gestures. This has nothing to do with how SideMenu works. You're doing
something wrong when you instantiate them programmatically.

**Comment by djdance** [comment]
The same ussue. First swipes is black, if press menu then swipes are correct

**Comment by jonkykong** [comment]
There are thousands of other developers using this repository successfully. If they're able to get it to work, then you also have the ability to work things out.

If you guys would have looked at the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example), you would have seen the proper instantiation for view controllers from storyboard when setting up gestures. If you are instantiating them using just `UISideMenuNavigationController()`, you'll get a black menu.

```swift
// Define the menus
SideMenuManager.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
SideMenuManager.menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as! UISideMenuNavigationController
        
// Enable gestures. The left and/or right menus must be set up above for these to work.
// Note that these continue to work on the Navigation Controller independent of the View Controller it displays!
SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
```

**Comment by djdance** [comment]
_> If you are instantiating them using just UISideMenuNavigationController(), you'll get a black menu._
...and it will stay black on next button click. I know. But in our case button click corrects menu (until next app restart). And of course, all code from example and readme was copypasted properly. 

I thought it is something in lib init procedure, which depends on hardware, in mycase FYI it is ipad mini, landscape, iOS 10.2, maybe it will useful for another developer.... I've gone to another sidemenu.

**Comment by jonkykong** [comment]
For awareness for others:

Button clicks update the menu properly because the menu is set (changed
from a black menu) from the storyboard. Again, nothing wrong with SideMenu
here. This is a bug in your setup.
