### ISSUE TITLE
Important Questions

### ISSUE THREAD

**Issue by kawaxman** [jonkykong/SideMenu#137]
Hello Jon,

I managed to implement your framework, and now I have a few questions.

1) How can I close the slide menu programmatically? (basically reversing the animation)

2) How can I get rid of the shadow created from the main vc to the slide vc? I have experimented and I am not able to solve this problem.

Please Help! Thanks

**Comment by kawaxman** [comment]
Hey,

Can you just tell me if I am doing anything wrong? I just need to know how to close the side menu. I am running the newest version of the framework, but still I cannot find a way to close the menu. Thanks!

**Comment by anonym24** [comment]
@kawaxman did you solve this issue?

**Comment by anonym24** [comment]
@kawaxman found out: `dismiss(animated: true, completion: nil)` in UITableViewController's didSelectRowAt
