### ISSUE TITLE
Cells becoming unselectable once connecting to TableViewController.

### ISSUE THREAD

**Issue by mckriel** [jonkykong/SideMenu#140]
Hi Dev,

Firstly, thank you so much for your great work on this slide menu.

I am encountering a problem and I know I am probably being really stupid but I have tried resolving this for just over two hours with no solution.

Basically what is happening is that as soon as I connect up the table view which holds my menu into a table view controller, the menu items are no longer selectable. In other words, I cannot select any of the table view cells.

I have tried setting them to both dynamic and static cells and this didn't change anything. Please help me understand where I am going wrong. I would really appreciate it.

I have attached a zip of a simple project where this is happening to me.

[HomiFinal.zip](https://github.com/jonkykong/SideMenu/files/732576/HomiFinal.zip)

**Comment by mckriel** [comment]
Just to add to this, the screenshot below is when I have no custom class set:

![unnamed-4](https://cloud.githubusercontent.com/assets/19168665/22336055/a4b003e2-e3e9-11e6-860a-80046eb990dd.jpg)

The second image is when I connect the view up to tvc_menu.swift (Which is of type UITableViewController). You will notice that not only are the cells not selectable but also that the text and image in them disappears as well.

![unnamed-5](https://cloud.githubusercontent.com/assets/19168665/22336061/a9ba48ac-e3e9-11e6-9c87-70e7410caa13.jpg)

I know I am probably being an idiot somewhere here.

**Comment by mckriel** [comment]
I have to be able to set that image and the user name dynamically based on who logs into my application, hence the need for the tvc_home TableViewController.

**Comment by mckriel** [comment]
Jonkykong please explain where I went wrong?

**Comment by jonkykong** [comment]
@mckriel sorry, but giving you a dose of tough love. You can figure it out.

This isn't likely to be a bug with SideMenu, and I don't have time to help/teach you otherwise. I get lots of requests for code help.
