### ISSUE TITLE
Dismiss gesture 

### ISSUE THREAD

**Issue by Engheangtouch** [jonkykong/SideMenu#142]
I just learn swift. I don't know how to dismiss gesture. I want to hide menu left when I touch on table of menu left and stay on main screen. Can you give me an example about it ?

<img src= "https://cloud.githubusercontent.com/assets/16093499/22460273/a09e8ec2-e7d6-11e6-9cbe-108c423a6bae.PNG" height="300" width="160">

<img src= "https://cloud.githubusercontent.com/assets/16093499/22460359/138dbd04-e7d7-11e6-9885-30c14b6753e1.PNG" height="300" width="160">

/// The left menu swipe to dismiss gesture.
open static weak var menuLeftSwipeToDismissGesture: UIPanGestureRecognizer?

**Comment by jonkykong** [comment]
Sorry, I'm not your teacher. Everything is in the README. You'll have to figure this out or try stackoverflow.com.
