### ISSUE TITLE
SideMenu disappears upon presenting or pushing a view or navigation controller

### ISSUE THREAD

**Issue by yinonar** [jonkykong/SideMenu#144]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I initialize SideMenuManager with properties:
```
SideMenuManager.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? UISideMenuNavigationController
SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.view)
SideMenuManager.menuPresentMode = .menuSlideIn
SideMenuManager.menuFadeStatusBar = false
SideMenuManager.menuShadowOpacity = 0.3
SideMenuManager.menuShadowRadius = 3
```

Within the sidemenu, I present a navigation controller like so:
```
let vc = storyboard!.instantiateViewController(withIdentifier: "navigationStoryboardID") as! UINavigationController
present(vc, animated: true)
```

All works as expected, except that upon dismissing my presented navigation controller, the side menu is no longer presented. It appears that the side menu dismisses itself when I present or push a view/navigation controller from within the side menu. I've reproduced this in the example app as well. 

How do I avoid this behavior? I'd like to avoid the behavior because it's confusing UX to tap on an item within a navigation interface and no longer have access to the navigation after you've dismissed the screen you've navigated to.

**Comment by jonkykong** [comment]
Hi @yinonar, this behavior is by design and meets the vast majority of developers' needs currently. The reason being that menus are commonly used for navigation and settings.

Your options are to subclass the menu and override this behavior, or contribute to this repository with a setting that allows the behavior you're looking for.

**Comment by yinonar** [comment]
@jonkykong thank you for the quick response. Understood on the design decision.

We can subclass the menu and override the behavior, and if we end up using the behavior and testing it, I'd be happy to contribute to the repo with a setting. Could you point me to the function/line/general area in the code that handles this? Really appreciate it.

**Comment by jonkykong** [comment]
You'll have to take a look at `UISideMenuNavigationController`. There are several places in there that handle dismissing the menu for presenting and pushing.

**Comment by shirakaba** [comment]
@yinonar Did you ever make any progress on this? I'm interested in this feature in order to match the behaviour of the major dictionary app, Pleco. Had a quick play with the code (mainly looking at the `self.dismiss(animated: true, completion: nil)` line in the `pushViewController()` function in `UISideMenuNavigationController`), but sadly couldn't get the behaviour to change.

**Comment by magneticrob** [comment]
Having a bit of a nightmare trying to implement this behaviour (that is, keeping the side menu open after presenting a view controller from the menu).

I've managed to keep it open but on dismissal, the menu appears full width. Any pointers would be greatly appreciated!

To get the behaviour I mention above, comment out the viewDidDisappear function in UISideMenuNavigationController.swift.

**Comment by magneticrob** [comment]
OK, So I've got the issue working. To keep the side menu open after presenting a view controller from it, and subsequently dismissing it:

1 - Remove the code in viewDidDisappear in UISideMenuNavigationController.swift
2 - Add two constraints in viewDidLoad for size and height in viewDidLoad in UISideMenuNavigationController.swift - code below

`        if let newFrame = UIApplication.shared.keyWindow?.bounds {
            self.view.translatesAutoresizingMaskIntoConstraints = false
            self.view.addConstraint(NSLayoutConstraint.init(item: self.view, attribute: .width, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1.0, constant: SideMenuManager.menuWidth))
            self.view.addConstraint(NSLayoutConstraint.init(item: self.view, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1.0, constant: newFrame.size.height))
        }`

Hope that helps. @shirakaba @yinonar

**Comment by shirakaba** [comment]
@magneticrob Stellar work! Hopefully I can make use of this still 🙂 do you have a fork of this project, with a commit number (if not the head), that I could `pod install` from to try out?

GitHub's Markdown has problems writing a code section after a bulleted/numbered list. I usually enter three dashes (`---`) in between the list and the code to create a ruled line to get the formatting to work. Looks like this:

---

**Comment by magneticrob** [comment]
@shirakaba Unfortunately no fork, and also the 3 dash trick didn't seem to work! My change is quite lightweight, literally just commenting out viewDidDisappear and pasting in my gist. Good luck :)

**Comment by chathuralakmal** [comment]
Issue is still in 2018

**Comment by martinstojchev** [comment]
@magneticrob I've implemented your code(trick) to not dismiss the side menu but still not working...
