### ISSUE TITLE
Programmatically open and close the side menu?

### ISSUE THREAD

**Issue by HarikrishnaPai** [jonkykong/SideMenu#148]
Is there a way to programmatically open and close the side menu?

**Comment by hemangshah** [comment]
@HarikrishnaPai, have you ever able to do this? If yes, please help! @jonkykong has closed this issue without providing any solution.

**Comment by hemangshah** [comment]
if (SideMenuManager.menuLeftNavigationController?.isViewLoaded)! {
            dismiss(animated: true, completion: nil)
        } else {
            self.present(SideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)
        }

**Comment by jonkykong** [comment]
@hemangshah This is not likely to work as the `menuLeftNavigationController` stays loaded after the menu is hidden.

Your subclass(es) of UISideMenuNavigationController have `viewWillAppear`, `viewDidAppear`, `viewWillDisappear`, and `viewDidDisappear` like any other view controller. Use those to discern if the menu is visible or not or set a property that indicates its status.

**Comment by hemangshah** [comment]
@jonkykong – Yes, you're right. Initially, it worked for me and then some requirements/flow changed that causes a problem in closing the SideMenu like I suggested.

Everyone, **please don't use my solution. This is a workaround but not a solution!**

**Comment by haroldogtf** [comment]
Is there a way to check programmatically if the Menu is Open or Closed?

**Comment by anonym24** [comment]
So how can we close left or right sidebar menu programmatically?

**Comment by anonym24** [comment]
found out: `dismiss(animated: true, completion: nil)` in UITableViewController's didSelectRowAt
