### ISSUE TITLE
CATransaction interfering with subview appearances

### ISSUE THREAD

**Issue by agates4** [jonkykong/SideMenu#150]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X ] My issue is happening in the **latest version** of SideMenu.
- [X ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

This code block:

```
        CATransaction.begin()
        CATransaction.setCompletionBlock( { () -> Void in
            self.dismiss(animated: true, completion: nil)
            self.visibleViewController?.viewWillAppear(false) // Hack: force selection to get cleared on UITableViewControllers when reappearing using custom transitions
        })
```

interferes with new subviews created in the destination controller within "viewDid" and "viewWill" appear methods. At the end of the transition animation when the 'SideMenu' is dismissed - this is where subviews will abruptly be dismissed.

[bug.zip](https://github.com/jonkykong/SideMenu/files/762297/SwiftSpinTest3.zip)

this project is an example of this bug - but, after removing the CATransaction altogether, the issue is fixed

**Comment by jonkykong** [comment]
@agates4 are you able to demonstrate a problem without using a 3rd party library? I am inclined not to troubleshoot issues that may be due to the design of a 3rd party's code.

Just to note: it's not guaranteed that SideMenu is compatible with all other libraries.

**Comment by agates4** [comment]
[super view.zip](https://github.com/jonkykong/SideMenu/files/762474/super.view.zip)

Here's a simple function - creates a super view, adds a subview. After loading the table view controller and reaching the `viewWillAppear` function, that super view is initialized. Using breakpoints I was able to see that the subview is presented every time the cell is pressed, but is then instantly dismissed at the end of the transition animation when the 'SideMenu' is dismissed

**Comment by jonkykong** [comment]
@agates4 If you debug the view hierarchy, you will see that the view you created is still in the stack but has been pushed to the very back so it is not visible. My assumption is this is what happens naturally by the transition APIs when they complete, though it's possible there's something in SideMenu's code that is adding the views over top of it. I'm not sure without investigating further.

Either way, this is an edge case so I'm not inclined to debug it. If you wanted to produce a solution, it won't be removing the CATransaction (its necessary for the library to function as expected), but instead something to do with the view layer hierarchy when the transition completes.

A workaround for you would be to bring your view back up to the top when the menu dismisses.

**Comment by jonkykong** [comment]
A quick hack at `SideMenuTransition.swift:446` adding this line will fix it:
```swift
topView.superview?.sendSubview(toBack: topView)
```
Not a pretty solution and I'm not sure if it breaks multiple view controllers being in the hierarchy.

**Comment by mohkin** [comment]
I do have the same problem, hope there is a workaround
