### ISSUE TITLE
Umbrella header "SideMenu.h" not found error in Swift3

### ISSUE THREAD

**Issue by lak-16** [jonkykong/SideMenu#151]
HI,

After adding SideMenu framework to my project and when i try to build, it is giving below errors.

Umbrella header "SideMenu.h" not found
could not build Objective-C module 'SideMenu'

Can you please help me to get rid of this issue?

**Comment by soheilbm** [comment]
there is no need for modulemap in SideMenu framework. Fork the project and remove module from framework. That's how I fixed it. @lak-16

**Comment by bryan1anderson** [comment]
I'm running into this issue as well running it from Carthage. Is there any way to fix this?
