### ISSUE TITLE
XIB can't load UISideMenuNavigationController

### ISSUE THREAD

**Issue by ilhammalik** [jonkykong/SideMenu#152]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
@ilhammalik only if you can check off all of the above will I help you resolve this iss. Try taking your problem to stackoverflow.com.

**Comment by ilhammalik** [comment]
let vc = RefferalController(nibName: "Refferal", bundle: nil)
        let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: vc)
      
        menuLeftNavigationController.leftSide = true
        // UISideMenuNavigationController is a subclass of UINavigationController, so do any additional configuration of it here like setting its viewControllers.
        SideMenuManager.menuLeftNavigationController = menuLeftNavigationController
        
        let menuRightNavigationController = UISideMenuNavigationController()
        // UISideMenuNavigationController is a subclass of UINavigationController, so do any additional configuration of it here like setting its viewControllers.
        SideMenuManager.menuRightNavigationController = menuRightNavigationController
        
        // Enable gestures. The left and/or right menus must be set up above for these to work.
        // Note that these continue to work on the Navigation Controller independent of the View Controller it displays!
        SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
       
        presentViewController(SideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)
        
        

@jonkykong  i still error how i can fix can't load view

**Comment by jonkykong** [comment]
Whatever your problem is, I'm confident it's not specific to SideMenu. Please try your problem on stackoverflow.com.
