### ISSUE TITLE
Localisation issue for LTH & RTH

### ISSUE THREAD

**Issue by souiOS** [jonkykong/SideMenu#153]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
 Hope you are doing well!

I am using you side menu library in my app (iOS 9 & 10) which support localisation i.e English and Arabic so need to support LTR & RTL accordingly.

I used the menu through storyboard, which is perfect in english i.e LTH but when changing the language to Arabic, the bar button item appear on right side but clicking on it menu is coming from left as in storyboard "left side = ON". Kindly help me how can I change the menu with change in language for my app.

Thanks in advance!

**Comment by jonkykong** [comment]
https://github.com/jonkykong/SideMenu#customization

**Comment by souiOS** [comment]
Sorry Jon. My bad
I gone through the customisation part but unable to solve the issue.

**Comment by jonkykong** [comment]
@souiOS, you've got to try and become more self-sufficient. The reason I am giving you short answers is because I don't have the time to address every question that comes my way about this library.

You either need to set up two menus for each side and disable the one you don't need, or swap the menu to the other side. It's very simple -- the README describes all the properties you need.

**Comment by UsmanZiaSDSOL** [comment]
@souiOS  I have the same issue but solve this I can share with you you can simply drag and drop a new  navigation controller and the and assign storyboard id "RightMenuNavigationController" then go to user controller and little bit management of code then you got what you want here is the example 
if Localize.currentLanguage() == "ar"
        {
             SideMenuManager.default.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? UISideMenuNavigationController
        }else{
             SideMenuManager.default.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? UISideMenuNavigationController
        }
