### ISSUE TITLE
No possibility to disable swipes which present menu. Misleading property name or documentation

### ISSUE THREAD

**Issue by oleghnidets** [jonkykong/SideMenu#156]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I added the pan and edge gestures to my navigation controller.
In `-viewWillAppear` method I enable the gestures using `SideMenuManager.menuEnableSwipeGestures = true`. According to documentation:

> Enable or disable gestures that would swipe to present or dismiss the menu. Default is true.

I want to disable opening menu swipe gestures in `-viewWillDisappear`. Actually, it doesn't disable the pan and edge gestures added. Moreover, these gestures are not saved anywhere in framework. 
So is it expected? Or is a documentation wrong? 

My configurations:
```
SideMenuManager.menuAddPanGestureToPresent(toView: navigationController!.navigationBar)
SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: navigationController!.view)
SideMenuManager.menuFadeStatusBar = false
SideMenuManager.menuAllowPushOfSameClassTwice = false
SideMenuManager.menuShadowRadius = 0

```

Thanks in advance

**Comment by jonkykong** [comment]
@oleghnidets I understand your confusion with the documentation. It should read, "Enable or disable gestures that would swipe to **dismiss** the menu. Default is true."

Both `menuAddPanGestureToPresent` and `menuAddScreenEdgePanGesturesToPresent` return gestures that you can enable or disable as you desire for prevent swipe for **presenting** only. You'll need to keep references to them inside your view controller to access them across methods.

I'll have the documentation updated in the near future for clarity.

**Comment by alok1upadhyay** [comment]
Not sure about your scenario, but in my case when user logs out and reach on login screen i wanted to disable gesture from left to right.

At th etime user clicks on logout i set below property to 0.0 and that's it.
SideMenuManager.default.menuWidth = 0.0

Now again reset it to 85% after user re-login.
