### ISSUE TITLE
SideMenu Pod File Error 

### ISSUE THREAD

**Issue by junaidjp** [jonkykong/SideMenu#159]
Not able to Install the Dependency from POD 

I used this command in Pod 

target 'MyApp' do
  pod 'SideMenu', '~> 2.2'
end

[!] Unable to satisfy the following requirements:

- `SideMenu (~> 2.2)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SideMenu (~> 2.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by jonkykong** [comment]
2.2.0

**Comment by junaidjp** [comment]
Jon Thank you 

I just tried 2.2.0 

My Pod file is 

target 'SideBar' do
  pod 'SideMenu', '~>2.2.0'
end


!] Unable to satisfy the following requirements:

- `SideMenu (~> 2.2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SideMenu (~> 2.2.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

I recieved the same error. 


thank you

**Comment by jonkykong** [comment]
Does it work without the version requirement?

**Comment by junaidjp** [comment]
thanks it works without the version requirement. 

Appreciate the help
