### ISSUE TITLE
Don't use OverFullScreen in modalPresentationStyle

### ISSUE THREAD

**Issue by souzainf3** [jonkykong/SideMenu#16]
The modalPresentationStyle configured with OverFullScreen cause window hierarchy when present another viewController over this.

Replace all .OverFullScreen to .OverCurrentContext to fix it.

Thanks. :-)

**Comment by jonkykong** [comment]
Hi @souzainf3, can you please explain the problem this is causing? A screenshot might help if there is a visual issue.

**Comment by souzainf3** [comment]
An UIViewController can presenting only 1(one) other UIViewController.

Presentation context example:
vc1 -----> vc2 ---> vc3

vc1 don't can present other UIViewController, if you try this an error log is printed "Warning: Attempt to present <> whose view is not in the window hierarchy!".

Using the .OverFullScreen, the presented View Controller don't can present other view Controller. If you try this It occurs the same error above and UIViewController don't be presented.

**Comment by souzainf3** [comment]
Sorry! The fist test they took this approach.
But I think I'm wrong. 
Sorry.

**Comment by jonkykong** [comment]
No worries! I appreciate you taking the time to report and follow-up.
