### ISSUE TITLE
Need some more clarification on how to make this work

### ISSUE THREAD

**Issue by junaidjp** [jonkykong/SideMenu#160]
First of I believe this is a good POD to use for a complex functionality of SideMenu and thank you for the good work. 
I am new to IOS , Swift and Xcode but I am learning and my questions might sound very stupid but I thought its better to ask that to waste hours trying to make this work. 

I followed the approach as you suggested for doing all this in XCODE and all I get is a Blank Dark Screen. 

Here is what I did 

1) Create a Navigation Controller ( Change this class to UISideMenuNavigationController) on Storyboard , Which created me a TableViewController. I inserted a MapView on this TableView.

2) Created a new View Controller and added a Button and create a Segue to modally present it to the NavigationController A.K.A UISideMenuNavigationController. 

P.S I did set the ViewController as my InitialScreen Because I was getting 

Failed to instantiate the default view controller for UIMainStoryboardFile 'Main' - perhaps the designated entry point is not set?

All I see is a Dark Screen. 

I apologize in advance if this is a Silly Question.

**Comment by jonkykong** [comment]
https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md

**Comment by jonkykong** [comment]
To be fair -- by choosing not to waste your time, you're choosing to waste mine instead. You will learn better if you try and solve this on your own.

**Comment by junaidjp** [comment]
Jon 

You are right and I appreciate the help. I will figure this out somehow 
thank you again for the help
