### ISSUE TITLE
Can't disable pan gestures on new viewcontroller

### ISSUE THREAD

**Issue by aco314** [jonkykong/SideMenu#161]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When I move from the main viewcontroller that holds the sidemenu to another viewcontroller, I can still open the sidemenu from there. How do i disable the pan gestures on the navigation bar and the screen edge?
I found a similar issue: https://github.com/jonkykong/SideMenu/issues/156 but there is no solution.
Any way you could help me out?
Thanks!

**Comment by jonkykong** [comment]
@aco314 the problem you're having is not the same as #156. You need to retain the gestures you add to the navigation bar (returned by the method that adds them) and disable them once you move to another screen. Read the README for more information.

**Comment by aco314** [comment]
My question was how do i disable them? I cant find nowhere in the README about that.

**Comment by jonkykong** [comment]
`menuAddPanGestureToPresent` and `menuAddScreenEdgePanGesturesToPresent` return the gestures added to those views. Simply set those gestures `isEnabled` properties to false or true as needed.

**Comment by aco314** [comment]
I am really sorry for bugging you this much, but could you please tell me exactly how to do that? I'm new to programming.
This is the way i thought it would be:
`SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar).isEnabled = false`

`SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view).isEnabled = false`

**Comment by jonkykong** [comment]
@aco314 as noted in my [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md), I am not a teacher. I recommend searching or posting on stackoverflow.com, or reading up on Apple's documentation for further assistance. Good luck!

**Comment by Sai628** [comment]
@aco314 I have the some problem as you. the following help for me:

in viewController which setup SideMenu, 
```swift
fileprivate var recognizers: [UIScreenEdgePanGestureRecognizer]!

override func viewDidLoad()
{
    // something init

    recognizers = SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
}

override func viewWillAppear(_ animated: Bool)
{
    super.viewWillAppear(animated)
    recognizers.forEachEnumerated { (_, recognizer) in
        recognizer.isEnabled = true
    }
}    

override func viewWillDisappear(_ animated: Bool)
{
    super.viewWillDisappear(animated)
    recognizers.forEachEnumerated { (_, recognizer) in
        recognizer.isEnabled = false
    }
}
```

good luck!
