### ISSUE TITLE
Notificaion alert hides on page present

### ISSUE THREAD

**Issue by rlxone** [jonkykong/SideMenu#163]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

First of all, thank you for your awesome project.
So, i need to show notification alert on page present. I used custom library for notification alert, but alert view hides after some time when page is present (about 1 second). its working with ```menuPushStyle = .subMenu```, but its not what i want. How can i solve it?
Thanks

**Comment by jonkykong** [comment]
@rlxone It's not guaranteed that SideMenu will work nicely with some other library, so you'll need to spend more time investigating what's happening and coming up with a solution yourself.

I simple solution would be to wait until after the page is finished presenting to show the notification instead of showing it before it finishes presenting.

**Comment by rlxone** [comment]
Thanks, I replace my notification alert code to `viewDidAppear` of ViewController and its works fine. 
Sorry for wasting your time.

**Comment by askari01** [comment]
I had the similar issue, thanks @jonkykong for the comment.

**Comment by anelad** [comment]
unfortunately, viewDidAppear is not saving me. Any other solutions do you know guys?
