### ISSUE TITLE
Cannot find a way to send data via segue from Main to Table

### ISSUE THREAD

**Issue by sebastianvirlan** [jonkykong/SideMenu#164]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ x] My issue is happening in the **latest version** of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi, I didn't find a way to send data to the TableViewController since is the 3rd view and the MainViewController goes to `SideMenuNavigationController`.

**Comment by jonkykong** [comment]
@sebastianvirlan your request is vague, but there's nothing special needed to "send data" between view controllers. It's the same you process you would do if you were not using SideMenu. Data is most commonly passed between view controllers using delegates or notifications. You must take your problem to [stackoverflow.com](stackoverflow.com) for help.

**Comment by tjvanpat** [comment]
The issue is that there doesn't appear to be any way to do prepareForSegue() to set up the view controllers that are being presented.   For example, the menu would be very useful if prepareForSegue() was called within the side menu view controller before returning back to the main view controller, so we could modify an object within the main view controller based on what selection the user just made.

**Comment by jonkykong** [comment]
This is an easily solved problem. From any of your view controllers, override `viewWillAppear` to set  or get the appropriate data you want based on the `presentingViewController` or `presentedViewController`. If you need more help please go to stackoverflow.

**Comment by hardikamal** [comment]
@sebastianvirlan @tjvanpat Any solution found to this issue?

**Comment by tjvanpat** [comment]
Yes, the answer is to use observers and notifications just like he says.   The context for this code isn't important, just pay attention to the `addObserver()` calls.

```swift
    private func setupSideMenu() {
        // Define the menu
        if let smnc = storyboard?.instantiateViewController(withIdentifier: Constants.sbidSideMenuLeftMapOptions) as? UISideMenuNavigationController {
            SideMenuManager.default.menuLeftNavigationController = smnc

            // Enable gestures
            guard (self.navigationController != nil) else {
                log.error("self.navigationController is nil.")
                return
            }
            SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
        } else {
            assertionFailure("Unable to get SideMenu navigation controller: '\(type(of: storyboard?.instantiateViewController(withIdentifier: Constants.sbidSideMenuLeftMapOptions)))'")
        }
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)

        setupSideMenu()

        NotificationCenter.default.addObserver(self,
                                               selector: #selector(self.handleMapTypeSelected(_:)),
                                               name: NSNotification.Name(Constants.notificationMapOptionsSetMapType),
                                               object: nil)
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(self.handleRemoveAllLocations(_:)),
                                               name: NSNotification.Name(Constants.notificationMapOptionsRemoveLocations),
                                               object: nil)
    }
```

And then in the SideMenu TableViewController you `post()` the notification:

```swift
                    DispatchQueue.main.async {
                        NotificationCenter.default.post(name: NSNotification.Name(Constants.notificationMapOptionsSetMapType),
                                                        object: nil,
                                                        userInfo: [Constants.notificationDictMapOptionsMapType : MKMapType.standard])
                    }
```
