### ISSUE TITLE
Using with horizontal scrollview

### ISSUE THREAD

**Issue by 2fours** [jonkykong/SideMenu#165]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ x] My issue is happening in the **latest version** of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ nope] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Thanks for creating this awesome control. I'm trying to use it with a horizontal scroll view. The problem is if I add the pan gesture to the scrollview, the sidemenu swallows all of the gestures across the whole screen. So you can make a swipe in left gesture all the way on the right side of the screen and the menu will slide in. The scrollview does not react to any of the gestures. Is there a way to specify say the "hot" part of the screen for the sidemenu so for example the left menu comes in if the gesture occurred on the left 25th percent (user settable) of the screen. Otherwise the underlying control would get the gesture.

**Comment by jonkykong** [comment]
@2fours the difference you're describing is between the `UIScreen​Edge​Pan​Gesture​Recognizer` and the `UIPan​Gesture​Recognizer`. The different calls to `menuAddPanGestureToPresent` vs 
`menuAddScreenEdgePanGesturesToPresent` in the library implement those gestures. I'd suggest not using `menuAddPanGestureToPresent` in your case. Read up more on `UIScreen​Edge​Pan​Gesture​Recognizer` to see if you can alter the amount of area it uses to be triggered.

**Comment by 2fours** [comment]
Thanks for the quick response. I'm using the control from Objective C and those methods don't seem to be exposed in the auto generated header file, only: menuAddPanGestureToPresentToView, which is what I'm using.

**Comment by jonkykong** [comment]
@2fours someone reported that problem earlier. Unfortunately, I'm not explicitly supporting objective-C because I prefer to keep the library simpler for Swift. You can look through the pull-requests history to see changes they submitted to expose this in your own private fork.

**Comment by sherm4n90** [comment]
Im having the same issue and `UIScreen​Edge​Pan​Gesture​Recognizer` does not allow to change the recognition area. What would you recommend?

**Comment by 2fours** [comment]
@sherm4n90 I ended up getting it working the way by prioritizing the side menu screen edge pan gesture recognizers over the horizontal scroll view's gesture recognizers. Check out requireGestureRecognizerToFail:.

**Comment by sherm4n90** [comment]
@2fours It worked perfectly. Thanks a lot.

 Im still thinking in how to get like 50-50% of the screen to work for every gesture. If you have any news on this I will appreciate it, I will do the same.

**Comment by intellignt-idiot** [comment]
@2fours @glm4  Hi, I am also using side menu with ScrollView (Vertical) , but it does not accept the touch. Can you please tell me how to override the touch to my scrollView ? I have tried disabling the gestures. Do I need to change in the library's source code or I can code in my own viewcontroller ?
I did not understand your solution of prioritizing the gesture recognizer.

Thanks
