### ISSUE TITLE
When side menu is presented, the status bar turns black (except for green charging batter)

### ISSUE THREAD

**Issue by WillBishop** [jonkykong/SideMenu#166]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [?] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [?] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When I modally present (programmatically) the side menu, the status turns completely black, until the side menu is hidden again. However the green battery icon still shows)

**Comment by PrasenjitGiri** [comment]
I too am facing the same problem.

**Comment by jonkykong** [comment]
Please read the README. `SideMenuManager. menuFadeStatusBar = false`.

**Comment by anirudhamahale** [comment]
This worked.

**Comment by nidhinp** [comment]
Works like a charm

**Comment by veersr9** [comment]
Woking well.

**Comment by Mackatttack123** [comment]
perfect!

**Comment by jmjoshua** [comment]
Thanks for this!

**Comment by sanjeev141985** [comment]
> Please read the README. `SideMenuManager.menuFadeStatusBar = false`.

SideMenuManager.default.menuFadeStatusBar = false

**Comment by patriksharma** [comment]
it is saying this property is moved to SidemenuNavigationController class but its not showing up as property

**Comment by hamzaozturk** [comment]
> it is saying this property is moved to `SidemenuNavigationController` class but its not showing up as property

statusBarEndAlpha = 0

**Comment by kaiserabliz** [comment]
> > it is saying this property is moved to `SidemenuNavigationController` class but its not showing up as property
> 
> statusBarEndAlpha = 0

This didn't work for me, still having the black satatusBar.

**Comment by hamzaozturk** [comment]
Which one is black? The text or the background of the status bar?

**Comment by kaiserabliz** [comment]
> Which one is black? The text or the background of the status bar?

Both are black, I have also a custom navigation bar color, I am still trying to figure out a better look.

**Comment by iAmita** [comment]
I am also facing same issue

**Comment by kaiserabliz** [comment]
> I am also facing same issue

I think this is a known issue, ignore the black background and change status bar color to white.

**Comment by hamzaozturk** [comment]
Could you please share a screenshot?

**Comment by kaiserabliz** [comment]
> Could you please share a screenshot?

You can download the demo project

**Comment by triptisaxenak** [comment]
I am still facing the issue despite using statusBarEndAlpha = 0 in Xcode 11.3

**Comment by iAmita** [comment]
> > I am also facing same issue
> 
> I think this is a known issue, ignore the black background and change status bar color to white.

I just resolved the issue
Just use 
  func intializeSideMenu()
    {
       
        let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuViewController") as! SideMenuNavigationController
        SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
        menuLeftNavigationController.statusBarEndAlpha = 0
        menuLeftNavigationController.alwaysAnimate = true
        menuLeftNavigationController.presentationStyle = SideMenuPresentationStyle.menuSlideIn;
        menuLeftNavigationController.presentationStyle.presentingEndAlpha = 0.8
        menuLeftNavigationController.presentationStyle.onTopShadowOpacity = 0.5
        menuLeftNavigationController.presentationStyle.onTopShadowRadius = 5
        menuLeftNavigationController.presentationStyle.onTopShadowColor = .black
        menuLeftNavigationController.pushStyle = .popWhenPossible;
        menuLeftNavigationController.menuWidth = view.frame.width * 0.75;
        SideMenuManager.default.rightMenuNavigationController = nil
        SideMenuManager.default.addPanGestureToPresent(toView: view)
    
    }
to initialise the drawer.
Happy coding! :)

**Comment by udayBabariya** [comment]
> > > I am also facing same issue
> > 
> > 
> > I think this is a known issue, ignore the black background and change status bar color to white.
> 
> I just resolved the issue
> Just use
> func intializeSideMenu()
> {
> 
> ```
>     let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuViewController") as! SideMenuNavigationController
>     SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
>     menuLeftNavigationController.statusBarEndAlpha = 0
>     menuLeftNavigationController.alwaysAnimate = true
>     menuLeftNavigationController.presentationStyle = SideMenuPresentationStyle.menuSlideIn;
>     menuLeftNavigationController.presentationStyle.presentingEndAlpha = 0.8
>     menuLeftNavigationController.presentationStyle.onTopShadowOpacity = 0.5
>     menuLeftNavigationController.presentationStyle.onTopShadowRadius = 5
>     menuLeftNavigationController.presentationStyle.onTopShadowColor = .black
>     menuLeftNavigationController.pushStyle = .popWhenPossible;
>     menuLeftNavigationController.menuWidth = view.frame.width * 0.75;
>     SideMenuManager.default.rightMenuNavigationController = nil
>     SideMenuManager.default.addPanGestureToPresent(toView: view)
> 
> }
> ```
> 
> to initialise the drawer.
> Happy coding! :)

Thannxxx...Saved my day.

**Comment by safecan** [comment]
> > > I am also facing same issue
> > 
> > 
> > I think this is a known issue, ignore the black background and change status bar color to white.
> 
> I just resolved the issue
> Just use
> func intializeSideMenu()
> {
> 
> ```
>     let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuViewController") as! SideMenuNavigationController
>     SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
>     menuLeftNavigationController.statusBarEndAlpha = 0
>     menuLeftNavigationController.alwaysAnimate = true
>     menuLeftNavigationController.presentationStyle = SideMenuPresentationStyle.menuSlideIn;
>     menuLeftNavigationController.presentationStyle.presentingEndAlpha = 0.8
>     menuLeftNavigationController.presentationStyle.onTopShadowOpacity = 0.5
>     menuLeftNavigationController.presentationStyle.onTopShadowRadius = 5
>     menuLeftNavigationController.presentationStyle.onTopShadowColor = .black
>     menuLeftNavigationController.pushStyle = .popWhenPossible;
>     menuLeftNavigationController.menuWidth = view.frame.width * 0.75;
>     SideMenuManager.default.rightMenuNavigationController = nil
>     SideMenuManager.default.addPanGestureToPresent(toView: view)
> 
> }
> ```
> 
> to initialise the drawer.
> Happy coding! :)

statusBarEndAlpha only fixes the issue when side menu is opened with that gesture. I'm still getting the same black status bar error when I open the menu via bar button. Help pls

**Comment by nn75** [comment]
> > > I am also facing same issue
> > 
> > 
> > I think this is a known issue, ignore the black background and change status bar color to white.
> 
> I just resolved the issue
> Just use
> func intializeSideMenu()
> {
> 
> ```
>     let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuViewController") as! SideMenuNavigationController
>     SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
>     menuLeftNavigationController.statusBarEndAlpha = 0
>     menuLeftNavigationController.alwaysAnimate = true
>     menuLeftNavigationController.presentationStyle = SideMenuPresentationStyle.menuSlideIn;
>     menuLeftNavigationController.presentationStyle.presentingEndAlpha = 0.8
>     menuLeftNavigationController.presentationStyle.onTopShadowOpacity = 0.5
>     menuLeftNavigationController.presentationStyle.onTopShadowRadius = 5
>     menuLeftNavigationController.presentationStyle.onTopShadowColor = .black
>     menuLeftNavigationController.pushStyle = .popWhenPossible;
>     menuLeftNavigationController.menuWidth = view.frame.width * 0.75;
>     SideMenuManager.default.rightMenuNavigationController = nil
>     SideMenuManager.default.addPanGestureToPresent(toView: view)
> 
> }
> ```
> 
> to initialise the drawer.
> Happy coding! :)

I used this method, but the background is still all black.

**Comment by Purnima2912** [comment]
Make sure in the storyboard under Attributes Inspector also the StatusBarEndAlpha is set to 0
<img width="260" alt="Screenshot 2020-06-04 at 14 12 31" src="https://user-images.githubusercontent.com/64306356/83735119-8dddf080-a66d-11ea-9987-f65d316723fd.png">

**Comment by rkris1** [comment]
> > > I am also facing same issue
> > 
> > 
> > I think this is a known issue, ignore the black background and change status bar color to white.
> 
> I just resolved the issue
> Just use
> func intializeSideMenu()
> {
> 
> ```
|> }
> ```
> 
> to initialise the drawer.
> Happy coding! :)

Thanks. This solved my issue.
