### ISSUE TITLE
actually i dont know how to disable swipe gesture for the perticular view controller when i am using via storyboard  

### ISSUE THREAD

**Issue by AzharNaaz** [jonkykong/SideMenu#168]
actually i dont know how to disable swipe gesture for the perticular view controller when i am using via storyboard  

i am trying this code to disable swipe gesture for the internal screens!

**For enable swipe gesture i am using this code** 
let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
          SideMenuManager.menuLeftNavigationController = menuLeftNavigationController
          menuLeftNavigationController.leftSide = true
          SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
          SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)

**and to disable for the specific viewcontroller**

let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
     SideMenuManager.menuLeftNavigationController = menuLeftNavigationController
     menuLeftNavigationController.leftSide = true
     SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
     SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
     SideMenuManager.menuEnableSwipeGestures = true

**Comment by jonkykong** [comment]
@AzharNaaz everything you need is described in the README. Please take your question to stackoverflow.com.
