### ISSUE TITLE
How to detect if the sideMenu.menuLeftNavigationController is being presented?

### ISSUE THREAD

**Issue by Veronique** [jonkykong/SideMenu#170]
I don't have a change. I have a question
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I need to know if the sideMenu is currently open. I am not able to find a way to detect this state. I tried all of the following without any success:
`sideMenuManager.menuLeftNavigationController?.presentedViewController == nil`
`sideMenuManager.menuRightNavigationController?.presentingViewController == nil`
`sideMenuManager.menuLeftNavigationController?.isBeingPresented`
`sideMenuManager.menuLeftNavigationController?.isToolbarHidden`
`sideMenuManager.menuLeftNavigationController.topViewController.view.isHidden`

**Comment by jonkykong** [comment]
@Veronique inspect `presentedViewController` of the controller you display the menu from or `presentingViewController` of the menu. They will not be nil.

**Comment by Veronique** [comment]
@jonkykong I figured out why I couldn't get the state of the sideMenu. I was testing it along with deep linking. The sideMenu dismisses itself when the app goes to the background (unless it is displaying another view controller).
