### ISSUE TITLE
menuRightNavigationController cannot be modified while it's presented

### ISSUE THREAD

**Issue by shahryarjb** [jonkykong/SideMenu#171]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

hi
`Installing SideMenu (2.3.0)`

error log  : 
`SideMenu Warning: menuRightNavigationController cannot be modified while it's presented.
2017-03-24 16:20:51.696 Trangell[54206:703340] Warning: Attempt to present <SideMenu.UISideMenuNavigationController: 0x7fdc2b03d800> on <Trangell.DashbordVC: 0x7fdc2ae04400> while a presentation is in progress!`

![Uploading Screen Shot 2017-03-24 at 4.22.39 pm.png…]()

**Comment by jonkykong** [comment]
@shahryarjb This is by design.

**Comment by shahryarjb** [comment]
please help me ! What should I do ?

**Comment by Gantaios** [comment]
@jonkykong @shahryarjb  How to resolve this have you found the solution? can you elaborate this
