### ISSUE TITLE
Change colour of static table side menu

### ISSUE THREAD

**Issue by WillBishop** [jonkykong/SideMenu#172]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ n] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ?] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How do I change the colour of the tableview? I am using static cells, but I found nothing in the read me about it

**Comment by jonkykong** [comment]
Take this question to stackoverflow.com.
