### ISSUE TITLE
How to replace present viewController

### ISSUE THREAD

**Issue by stealdre** [jonkykong/SideMenu#176]
Hi, 

I have initiated my `sideMenu`. It works perfectly. I also created a `tableView` inside of the menu with different items. I want to show some `viewControllers` accorded to the tableView menu items. 

I used 2 ways yet. Both are hiding the the `sideMenu` without animation: the `viewControllers` are initiated above my `sideMenu` `navigationController`. 

I want a sideMenu that shows viewControllers without hiding it and with continuity. How is it possible? Thanks.

**Comment by stealdre** [comment]
Wtf

**Comment by dongkaipo** [comment]
+1
