### ISSUE TITLE
Issue with Modulemap

### ISSUE THREAD

**Issue by soheilbm** [jonkykong/SideMenu#177]
Building fails when using Carthage.

## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I'm using Carthage version 0.19.1. The building of sidemenu fails with below message: 

```

/Users/soheilbm/Documents/mobile-ios/Carthage/Checkouts/SideMenu/./SideMenu/module.modulemap:2:21: error: umbrella header 'SideMenu.h' not found
    umbrella header "SideMenu.h"
                    ^
<unknown>:0: error: could not build Objective-C module 'SideMenu'

```

I believe if you remove modulemap from source code, will solve the carthage problem.

**Comment by jonkykong** [comment]
Interestingly enough, in the comments of SideMenu.h:

```swift
//  Created by Soheil on 31/10/16.
//  Copyright © 2016 jonkykong. All rights reserved.
```

I believe when you contributed to this repro you left this artifact behind?

**Comment by soheilbm** [comment]
If is ok, I'll make another pull request to fix this

**Comment by jonkykong** [comment]
Sure! Are you sure that's the problem? I'm not sure if you've been updating consistently since your last contribution.

**Comment by jonkykong** [comment]
@soheilbm any updates?

**Comment by jonkykong** [comment]
@soheilbm I'm going to close this for now unless I hear further that there's a problem. Keep me posted!

**Comment by bryan1anderson** [comment]
@jonkykong This is an issue for me with Carthage

**Comment by jonkykong** [comment]
@bryan1anderson if you want to prepare a fix in a PR, I can merge it.
