### ISSUE TITLE
when i double tap on side menu item it push view 2 times , it msut be single times.

### ISSUE THREAD

**Issue by ganeshpadole55** [jonkykong/SideMenu#179]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
You did not fill out the checklist, which means you haven't done the appropriate background work to investigate.

**Comment by ganeshpadole55** [comment]
when i double tap on side menu item it push view 2 times , it msut be single times. what should i do.

**Comment by jonkykong** [comment]
You should search stackoverflow.com as this problem is not specific to SideMenu.

**Comment by ganeshpadole55** [comment]
how to set MenuPresentMode viewSlideInOut to custom button

**Comment by ganeshpadole55** [comment]
hi problem solved i used SideMenuManager.menuAllowPushOfSameClassTwice = false
        this property. This is very cool side menu .I impressed very much.Quick response from ur team.
