### ISSUE TITLE
Problems with iPad and iPhone 4s

### ISSUE THREAD

**Issue by igoravila93** [jonkykong/SideMenu#18]
Hello,
Congratulations on your work, works fine for iPhone 5+, but fot iPad and iPhone 4s when I am using at landscape the menu doesn't get the right size, neither the main view controller.
If you can help me solve this, or give tips where I can correct it myself I will be very happy.

Kind Regards

**Comment by jonkykong** [comment]
Hi @igoravila93, SideMenu appears to work as expected on iPhone 4S and iPad when run in the simulator. Please provide a screenshot or video that demonstrates your problem, and what you expected to see instead.

**Comment by igoravila93** [comment]
There are 5 images attached, all in simulator, 2 are at iPhone 6, working fine, and then 3
<img width="478" alt="iphone 4s - right table view" src="https://cloud.githubusercontent.com/assets/13837633/14648432/a64fbac4-0638-11e6-9227-99dde1aa7dcd.png">
<img width="665" alt="iphone 6 - main view" src="https://cloud.githubusercontent.com/assets/13837633/14648435/a68ceafc-0638-11e6-9f69-b683248a288b.png">
<img width="665" alt="iphone 6 - table view" src="https://cloud.githubusercontent.com/assets/13837633/14648433/a68c56d2-0638-11e6-8fe2-be43f5acf1c8.png">
<img width="479" alt="iphone 4s - main view" src="https://cloud.githubusercontent.com/assets/13837633/14648434/a68ca5d8-0638-11e6-920f-c0dc6c0f43d1.png">
<img width="480" alt="iphone 4s - left table view" src="https://cloud.githubusercontent.com/assets/13837633/14648436/a68d8872-0638-11e6-8560-0d0bdd38a477.png">




 at 4S, showing that the table view is not at the right frame

**Comment by jonkykong** [comment]
Ah. You need to set `SideMenuManager. menuWidth` to a specific value. By default, it is always calculated to be 75% of the screen width, and iPhone 4 have smaller screen widths.

**Comment by igoravila93** [comment]
Still not fine here.
I think the problem is somehow related to this area marked in red at the image

<img width="478" alt="iphone 4s - right table view" src="https://cloud.githubusercontent.com/assets/13837633/14650190/02df95e0-0641-11e6-8105-749b6ed30f51.png">

This part should be the table view of the side menu, but it is only the background UIImageView

**Comment by igoravila93** [comment]
It was a complete different problem, my image was bigger than the UIView, I dont know why, but now it is solved, sorry to disturb you

**Comment by jonkykong** [comment]
No worries! Glad you solved it.
