### ISSUE TITLE
How I can show the side menu without segue?

### ISSUE THREAD

**Issue by MervinFlores** [jonkykong/SideMenu#180]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by MervinFlores** [comment]
I do something like this 
`let VC1: SideMenuTableViewController = SideMenuTableViewController()
        let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: VC1)
        SideMenuManager.menuLeftNavigationController = menuLeftNavigationController)
        self.viewController.present(SideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)`

but doesn't work, I follow the instructions in the description of side menu but does't work, any idea?

**Comment by jonkykong** [comment]
You're not following the README correctly.
