### ISSUE TITLE
UISideMenuNavigationController barTintColor

### ISSUE THREAD

**Issue by codwam** [jonkykong/SideMenu#181]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

`let sideNav = UISideMenuNavigationController(rootViewController: vc)
 sideNav.navigationBar.barTintColor = .white
 
SideMenuManager.menuBlurEffectStyle = .dark`

barTintColor was no effect?

**Comment by jonkykong** [comment]
Set the bar tint color inside the vc.
