### ISSUE TITLE
black menu pop when tap gesture on the entire view solution not working

### ISSUE THREAD

**Issue by aznelite89** [jonkykong/SideMenu#182]
## **New Issue Checklist**

I have read the guidelines for contributing and I understand:

 My issue is happening in the latest version of SideMenu.
 My issue was not solved in the README.
 My issue can not be answered on stackoverflow.com.
 My issue is not a request for new functionality that I am unwilling to build and contribute with a pull request.
 My issue is reproducible in the demo project.

## **Issue Description**

I had follow the instructions and trying to resolve the black navigation bar keep popping when using tap gestures, however it did not work, in my viewdidload:-

let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
        
        SideMenuManager.menuLeftNavigationController = menuLeftNavigationController
        let menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
        SideMenuManager.menuRightNavigationController = menuRightNavigationController
        
        SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)

**Comment by jonkykong** [comment]
Everything you need to know is in the README.

**Comment by aznelite89** [comment]
had set the navigation bar by using sidemenumanager but not working. whenever tap on the side menu , navigation bar animate in

**Comment by prasen-ftech** [comment]
I am also facing same issue, in my case white navigation-bar pops up on tap of cell of tableview inside sidemenu @jonkykong 
![topnavpopup](https://user-images.githubusercontent.com/5945140/42318744-a09bbe46-806d-11e8-9f86-cdbf61d87122.png)

**Comment by jonkykong** [comment]
@prasen-ftech please reproduce this problem using the example project, without that I'm inclined to believe this is an error in your code and not an issue with SideMenu.

**Comment by prasen-ftech** [comment]
@jonkykong , I have resolved the issue. It was navigationbar issue. So I hide it with following code.
```
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        // Hide the navigation bar on the this view controller
        self.navigationController?.setNavigationBarHidden(true, animated: animated)
    }
```

**Comment by moldis** [comment]
@shayanaghajan Thank you, you save a lot of my time!
