### ISSUE TITLE
Black menu when app is woke up from background

### ISSUE THREAD

**Issue by yMiecie** [jonkykong/SideMenu#185]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello,

If i run the demo app, open one side menu, send the app to background and then wake it up, the side menu turns black.

I'm testing on an iPad device with iOS 10.1

Best Regards,

Yann

**Comment by jonkykong** [comment]
@yMiecie you found a localized issue to iOS 10 on iPad. Thanks for reporting it. I've fixed this in 2.3.2.

**Comment by kohdesmond** [comment]
@jonkykong i have same issues with using SideMenu (2.3.3) on my iPhone 6s 10.3.3

**Comment by jonkykong** [comment]
@kohdesmond please debug further. I am unable to reproduce this on 10.3.1.

**Comment by kohdesmond** [comment]
@jonkykong i found out that if i dismissed with 
`self.window?.rootViewController?.dismiss(animated: false, completion: nil)` in    ` func applicationDidEnterBackground(_ application: UIApplication)` i will get the black screen.

**Comment by jonkykong** [comment]
@kohdesmond Yes... that is not a bug with SideMenu. You're dismissing your rootViewController. Don't do that.

**Comment by kohdesmond** [comment]
@jonkykong sure, it works now after i removed that line.
