### ISSUE TITLE
UISplitViewController - push detail segue from master to detail

### ISSUE THREAD

**Issue by 48clyde** [jonkykong/SideMenu#186]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When attempting to configure SideMenu with a UISplitViewController I'm getting the error "SideMenu Warning: attempt to push a View Controller from \(String(describing: presentingViewController.self)) where its navigationController == nil. It must be embedded in a Navigation Controller for this to work."

However, both the Master and Detail views **are embedded** in Navigation Controllers. The master view I'm pushing from is embedded in a UISideMenuViewController and the detail view being pushed to is embedded in a UINavigationController (as per attached image). The segue is from the Master view to the navigation controller of the detail view (the blue segue in the image) . This is all standard stuff configured in the Storyboard, and SideMenu is connected up in the Master viewDidLoad based on the code from the Readme.

* iOS 10.3, iPhone 7plus landscape - there are no issues and the application works as expected!  The push detail segue does what it is supposed to do.

* iOS 10.3, iPhone 7plus portrait - I get the error message and no segue occurring so the detail view is not seen.  

What I think may be happening - thought I'm still coming to grips with Swift and UI programming in general and could be completely wrong;  is the detail view controller is being instantiated from the storyboard and UISideMenuNavigationController.pushViewController is being called before the view is fully configured with it's navigation controller - hence the error.  In landscape, the detail view is already on screen and fully configured so no error.

To work around this, I've changed UISideMenuNavigationController.pushViewController line #140 and removed the `print("Side...` and replaced with  `super.pushViewController(viewController, animated: animated)` so that the default actions of pushViewController occur. 

Is this an appropriate change to make to SideMenu? Or have I completely messed up the configuration or is this a bug?

<img width="989" alt="storyboard-svc-with-sidemenu" src="https://cloud.githubusercontent.com/assets/20831514/25455829/385b0efc-2b25-11e7-8ecc-15aa71f15674.png">

**Comment by xxtesaxx** [comment]
I think you made a slight mistake. The SideMenuNavigationController must not point to your master view controller. Instead you must do the following:

- Your SplitViewController must point to 2 normal UINavigationControllers
- The UINavigationControllers point to your master and detail view controllers 
- Your master now need a "present modal" segue to the SideMenuNavigationController

I know that feels kind of strange but the SideMenuNavigationController is not infront of your master as one would expect but it comes after it. Simply add a bar button to your masters navigation bar and drag a segue to the SideMenuNavigationController and use present modally. Then the SideMenuNavigationController points to a viewcontroller which is the drawer menu.

I hope you understand what I mean

**Comment by xxtesaxx** [comment]
<img width="773" alt="bildschirmfoto 2017-04-26 um 17 17 37" src="https://cloud.githubusercontent.com/assets/3000808/25457435/4f436c62-2aa4-11e7-9d62-43228b941820.png">

**Comment by 48clyde** [comment]
Hi xxtesaxx,

Thanks, I misunderstood what had to be embedded in a UISideMenuNavigationController.  It is the SideMenu view controller that needs to be embedded in the UISideMenuNavigationController!  I've changed the storyboard so like yours the UISplitViewController has two embedded UINavigationControllers.

Also, in my code I was already creating a UISideMenuNavigationController and putting the purple menu view in it, so I had that bit correct and working as expected at least!

![storyboard-svc-with-sidemenu-fixed](https://cloud.githubusercontent.com/assets/20831514/25459816/42924f34-2b34-11e7-8ef9-6c39b6fca2ac.png)
