### ISSUE TITLE
CentralViewController

### ISSUE THREAD

**Issue by YevhenHerasymenko** [jonkykong/SideMenu#19]
How can I get central view controller from left or right menu controller?

**Comment by jonkykong** [comment]
Hi @YevhenHerasymenko. Side menus are displayed no differently than standard system calls, like using `presentViewController`. As such, there's no special coding needed to figure out the central view controller as you can use standard system methods. I'd suggest looking in to `presentingViewController`.

**Comment by YevhenHerasymenko** [comment]
Thanks. **presentingViewController** works correctly.
