### ISSUE TITLE
SideMenu is not presented modally

### ISSUE THREAD

**Issue by MFJones21** [jonkykong/SideMenu#190]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the latest version of SideMenu.
- [x] My issue was not solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can not be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is not a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue is somehow not reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

So what I am trying to achieve is to control multiple view controllers with one side menu and every one of those can open the side menu. So every view controller has a Segue that modally presents the Side Menu. And the the Side Menu has a show-Segue to every one of those viewcontrollers. One of the ViewControllers is the initial. The first time I open the SideMenu everything works fine. But when I navigate to one of the other ViewControllers and then open the side menu it just pushes on to the screen like its "shown" not presented modally. I read through the entire example but couldn't find drastic differences. What am I doing wrong ? 
 
Thanks for your help and sharing this awesome project !

Greetings from Germany

**Comment by jonkykong** [comment]
Everything you need to know is in the README. Please read it carefully.
