### ISSUE TITLE
Performance issue with shadowRadius

### ISSUE THREAD

**Issue by xuaninbox** [jonkykong/SideMenu#191]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

My project has a lot of ui components and layer.shadowRadius with its live rendering is causing some performance issue when open and close the menu, maybe switch to layer.shadowPath could help?

**Comment by jonkykong** [comment]
Hi @xuaninbox,

This is the first reporting of this performance issue, which may suggest it's not a problem for the vast majority of developers. Does performance improve when the shadow is turned off? Can you test switching to a layer.shadowPath to see if that improves performance?

**Comment by jonkykong** [comment]
@xuaninbox I'm closing this for now. Please add any additional insights you may have and we can reopen this as necessary. Thanks!
