### ISSUE TITLE
Dismiss closes all viewcontorller in the stack

### ISSUE THREAD

**Issue by SinaAfshar** [jonkykong/SideMenu#193]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

So I am attempting to present a viewController on top of the present view controller which is presented using the sideMenu navigation. However after presenting, upon dismissing the new view controller both the presentedViewController and the one underneath are dismissed. I have tried calling the presentedViewController value before dismissing but I receive the same result. This newly presented view controller is a GMSAutocompleteViewController() downloaded from google and attempts to present it using a sideMenuNavigation have also failed prompting 'Application tried to present modally an active controller'. 

Thanks for your concern,

**Comment by jonkykong** [comment]
I am not quite sure what to make of your problem based on your description. Anything could be wrong, and it may have nothing to do with SideMenu. Please investigate further to determine what is dismissing each controller by using breakpoints.

**Comment by jonkykong** [comment]
Also you have checked that this occurs in the demo project but not explained whether or not this is true. Please verify.
