### ISSUE TITLE
SideMenu Warning: menuLeftNavigationController cannot be modified while it's presented.

### ISSUE THREAD

**Issue by Gantaios** [jonkykong/SideMenu#194]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi am facing the issue
SideMenu Warning: menuLeftNavigationController cannot be modified while it's presented.how to resolve this where am i doing wrong. It happens only when the app is still in the background once removed from the back ground it works as expected.

**Comment by jonkykong** [comment]
The warning is that the menu is presented and you're trying to change it. You are probably presenting something from SideMenu and reinitializing it on return from background. Instead initialize it from you app delegate or root view controller to only do it once.

**Comment by Gantaios** [comment]
Hi @jonkykong  can you tell me how to do that i am using via storyboards.
Thanks

**Comment by jonkykong** [comment]
Sorry, but I unfortunately am not able to spend time teaching how to code
on iOS here. This question is better suited for stackoverflow.com.

**Comment by bokhary3** [comment]
@Gantaios The problem is the presenting controller of Menu still live although SidMenu go away , so you should make it nil , to do that call self.dismiss(animated: false, completion: nil) method when you want go away from SideMenu.

**Comment by j0cker** [comment]
let newViewController = storyBoard.instantiateViewController(withIdentifier: controller)
        
        self.dismiss(animated: true) { () -> Void in
            //Perform segue or push some view with your code
            UIApplication.shared.keyWindow?.rootViewController = newViewController
        }

**Comment by j0cker** [comment]
```
        let newViewController = storyBoard.instantiateViewController(withIdentifier: controller)
        
        self.dismiss(animated: true) { () -> Void in
            //Perform segue or push some view with your code
            UIApplication.shared.keyWindow?.rootViewController = newViewController
        }
```

**Comment by naveedahmad99** [comment]
@j0cker @bokhary3 Thank you so much, you both saved my day.

**Comment by shayanaghajan** [comment]
@j0cker I have copied your code but it's not working for me . Do you have any idea how to handle that ?

**Comment by masgarifor2** [comment]
> @j0cker I have copied your code but it's not working for me . Do you have any idea how to handle that ?

`        let newViewController = storyboard?.instantiateViewController(withIdentifier: "MainTabBarController")
        SideMenuManager.default.menuRightNavigationController?.dismiss(animated: true) { () -> Void in
            UIApplication.shared.keyWindow?.rootViewController = newViewController
        }`

**Comment by barrylachapelle** [comment]
@jonkykong I completely understand that you are not an iOS instructor and that you it is tons of work to run a library like this... but man... I cannot believe the tone of your responses in issue after issue .... How hard of an answer was it (you could have literally said 'dismiss the view') with seemingly enough traffic to warrant a humane response. Thank you @bokhary3 and @j0cker

**Comment by jonkykong** [comment]
@barrylachapelle I appreciate your response. It’s a “principle of thing” for me. I know like it seems like it only takes a second here and there, but all I can tell you is that I get questions like this _all the time_, and if I spend a few minutes here and there helping every developer with a fundamentals question it would seriously add up over time. In my book, this is a teachable moment - rather than me being obligated to help people, people should also feel empowered to take the few seconds to research on google for questions like this which is answered really fast. My reply is simply to help encourage self-help behaviors, rather than foster dependencies on me to respond to them directly (which means they wait for me, and take both my and their time).

I hope this makes sense. If it doesn’t, the only thing I can say is that you’ll understand if you put up a popular code repo and realize how much activity comes your way as a result.

**Comment by tu6778** [comment]
> > @j0cker I have copied your code but it's not working for me . Do you have any idea how to handle that ?
> 
> ` let newViewController = storyboard?.instantiateViewController(withIdentifier: "MainTabBarController") SideMenuManager.default.menuRightNavigationController?.dismiss(animated: true) { () -> Void in UIApplication.shared.keyWindow?.rootViewController = newViewController }`

Hi! I used your code but the slide menu are still full screen until I close it after several times. Is there anyway I can always avoid the slide menu into full screen in the app? Thank you!

**Comment by tu6778** [comment]
> > @j0cker I have copied your code but it's not working for me . Do you have any idea how to handle that ?
> 
> ` let newViewController = storyboard?.instantiateViewController(withIdentifier: "MainTabBarController") SideMenuManager.default.menuRightNavigationController?.dismiss(animated: true) { () -> Void in UIApplication.shared.keyWindow?.rootViewController = newViewController }`



> ```
>         let newViewController = storyBoard.instantiateViewController(withIdentifier: controller)
>         
>         self.dismiss(animated: true) { () -> Void in
>             //Perform segue or push some view with your code
>             UIApplication.shared.keyWindow?.rootViewController = newViewController
>         }
> ```

Hi! I used your code but it seems doesn't work. Could you provide instructions how to use these code? Thank you!

**Comment by parveenBanuS** [comment]
what do you want to do this view controller? and navigation controller?

**Comment by Hassan143** [comment]
Goto SideMenuManager.swift file and comment the
