### ISSUE TITLE
Change Root View Controller

### ISSUE THREAD

**Issue by Bat-Orshikh** [jonkykong/SideMenu#195]
Hi. I'm trying to change RootViewController with another ViewController. But I can't figure it out. I'm facing some problems that are

1. After changed rootViewController by above code then **new** viewController is **_disappear_**.
2. In console log : **Presenting view controllers on detached view controllers is discouraged <Taxi.UserMainViewController: 0x10222e5d0>.**

Please help me!

My code is : 
`func changeRootView(){
        guard let delegate = UIApplication.shared.delegate else {
            return
        }
        guard let window = (delegate as! AppDelegate).window else {
            return
        }
        
        UIView.transition(with: window, duration: 0.3, options: .transitionCrossDissolve, animations: {
            let lgv = DriverMainViewController()
            window.rootViewController = UINavigationViewController(rootViewController: lgv)
        }, completion: { completed in
            SideMenuManager.menuLeftNavigationController!.dismiss(animated: true, completion: nil)
            print ("changed")
        })
}`

Picture before change RootviewController
When I clicked that gray button then **changeRootView** function will run.
![1 006](https://cloud.githubusercontent.com/assets/18459116/26009461/df7618d4-3783-11e7-861d-ab368835edd9.jpg)

Then **changeRootView** function changed App keyWindow's rootViewController
![2 003](https://cloud.githubusercontent.com/assets/18459116/26009516/25a2f91c-3784-11e7-9701-88eb3b00f8ac.jpg)

But this blue backgrounded viewController is disappeared in 1 second.
This screen shot is after disappeared new root view controller.
![18471894_1263017420479641_350949885_o-2](https://cloud.githubusercontent.com/assets/18459116/26009507/18ce0ce0-3784-11e7-97a2-4c260e003cce.jpg)

**Please help me! Please.**

**Comment by jonkykong** [comment]
This question is more appropriate for stackoverflow.com.
