### ISSUE TITLE
Using menu gestures with a UIPageViewController?

### ISSUE THREAD

**Issue by L4grange** [jonkykong/SideMenu#196]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello and thank you for this amazing library!

I've implemented my SideMenu in code to be able to use the screen edge gestures to open it. However, my app uses an embedded UIPageViewController that takes over the "open menu" gestures. Opening the menu using a gesture from the navBar still works fine.

Is there a way to keep both the menu gestures as well as the UIPageViewController swipes? Maybe by disabling the PagViewController's gestures at the areas that the menu gestures operate?

Thank you

**Comment by xxtesaxx** [comment]
My guess is that you have to intercept the gesture and make a decision by yourself if your page controller should handle the gesture or if you want the pang gesture from the SideMenu to kick in. Have a look at UIGestureRecognizerDelegate.

**Comment by L4grange** [comment]
Thank you for your response. I tried (almost) everything regarding the UIGestureRecognizerDelegate, but UIPageViewController really likes having control over it's gestures, and since It's an underlying ScrollView I could not set its delegate to my custom VC. My tacky solution was to create a dummyView with 15 width at the left edge of the screen and add it as the top child of my view.

```swift
//Overlay a dummyView to stop the UIPageViewController from capturing
//the input at the left edge of the screen so the side menu gestures can work
let dummyView = UIView(frame: CGRect(x: 0, y: 0, width: 15, height: UIScreen.main.bounds.height))
self.view.addSubview(dummyView)
```

This way the dummyView prevents the UIPageViewController from capturing the input and the SideMenu gesture is working fine :)

**Comment by xxtesaxx** [comment]
Have you tried subclassing the UIPageViewController?

**Comment by jonkykong** [comment]
@L4grange you'll to modify the gestures of either SideMenu or PageViewController to require the other one to fail when it is activated. 

My personal opinion, for what it's worth: the swipe in gestures of SideMenu aren't intuitive when a UIPageViewController is front and center, so you should leave SideMenu gestures off and just have it revealable through the navigation bar buttons.

**Comment by L4grange** [comment]
In my particular case I only need the swipe gestures in the middle of the screen, so having a little bit of the side of the screen for the menu gestures is OK. I'll advise with the designers of the team as well and reach a mutual decision on this. Thank you for your input guys!
