### ISSUE TITLE
Status Bar background color turns BLACK

### ISSUE THREAD

**Issue by tush010** [jonkykong/SideMenu#198]
- My issue is happening in the latest version of SideMenu.
- My issue was not solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- My issue cannot be answered on [stackoverflow.com](stackoverflow.com).
- My issue is not a request for new functionality that I am unwilling to build and contribute with a pull request.
- My issue is reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

When the SideMenu is presented, the status bar background color automatically turns black.

I haven't set any status bar background color for my app, still when the side menu is presented, the status bar background color automatically turns black. Please see the screenshot.
![example](https://cloud.githubusercontent.com/assets/20920626/26116965/978b245e-3a82-11e7-80b5-8ed5947036fc.png)

**Comment by xxtesaxx** [comment]
You did not read the Readme. It clearly tells you why this happens and what you have to do to change the behavior.

**Comment by tush010** [comment]
Well, Readme tells why the view controller background color appears black, not the STATUS BAR BACKGROUND COLOR

**Comment by NikKovIos** [comment]
You could even tell exactly where it is, because there are no troubleshooting guide in the readme.

**Comment by sanjeev141985** [comment]
> You could even tell exactly where it is, because there are no troubleshooting guide in the readme.
> `SideMenuManager.menuFadeStatusBar = false`

SideMenuManager.default.menuFadeStatusBar = false
