### ISSUE TITLE
status bar issue, need a method to check return and "not use" the menu bar.

### ISSUE THREAD

**Issue by magonicolas** [jonkykong/SideMenu#199]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi, I have a view controller that has the .default status bar, and when I do to side Menu, I use a .lightContent status bar. I need something to detect when user goes back to the view controller that it was (So, Im on VC1, I Click menu button, then I click VC1 to return to id and don`t do any action at side menu bar) and my statusbar stays .lightContent, and I need it to be .default. So, My question is, is there a way to detect that the user has returned to the VC1? Because viewWillAppear or ViewDidAppear doesn't`t recognize that action.

**Comment by jonkykong** [comment]
ViewWillAppear and viewDidAppear work in the menu.

**Comment by magonicolas** [comment]
But not on VC1, so When i Return, I can't have my original status bar.

**Comment by jonkykong** [comment]
@magonicolas this is by design, because when the menu appears the underlying view controller is not going away, so there is no need to trigger those events. You need to try a different approach to solve your problem; there are many. Try asking on stackoverflow.com if you cannot think of any.
