### ISSUE TITLE
Uses modal animation on second tap

### ISSUE THREAD

**Issue by Junaid6305** [jonkykong/SideMenu#200]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When ti run the app and tap the button to open the sideMenu it works fine, the view slide to the side to reveal the TableView (sideMenu) but when I tap on an item in the tableView it presents the next view using the "present modally" animation, and now when i press the button to show the sideMenu it uses the "present modally" and not slide to the side like it initially did. I tried setting the animations in code but it didn't make a difference.

**Comment by jonkykong** [comment]
Please follow the README exactly.

**Comment by Junaid6305** [comment]
I did follow it exactly but the problem still persists. Any ideas? @jonkykong

**Comment by jonkykong** [comment]
Your segues are set up to present instead of show. This is all described in the README.

**Comment by Junaid6305** [comment]
My segues are set up correctly (according to readme). The SideMenu navigation controller is rooted to the tableView. The first item in the tableView ‘Shows’ the home ViewController (The home view controller is rooted to another navigation controller so the segue points to the nav controller). There’s a bar button in the home viewcontroller to show the side menu. This button ‘Presents modally’ and is connected to the Side Menu Navigation Controller.

When I run this and tap the button the side menu opens fine, then I tap the item in the tableView and I get the ‘present modally animation’ yet using ‘Show’
@jonkykong

**Comment by jonkykong** [comment]
@Junaid6305 you are very likely doing something wrong as you are the only one reporting this problem. Check the README and compare the demo project to yours to see what you might be doing wrong. Let me know what you find.

**Comment by jonkykong** [comment]
Simply put: since the demo project is working fine, it's not a bug in the library, so you'll need to troubleshoot this yourself.

**Comment by negarTolou** [comment]
hi jonkyKong
i have this problem too. do u have any idea? @jonkykong 
what about you? @Junaid6305

**Comment by Junaid6305** [comment]
I did manage to solve the issue. I had multiple navigations controllers in my project and it turned out that this was causing the issue. Initially I’d pointed the segue to the navigation controller of the destination view controller, by doing this I ended up with that problem. By pointing the segue to the viewcontroller itself and not the navigation controller it worked fine.
