### ISSUE TITLE
How to display viewcontroller without navigation bar

### ISSUE THREAD

**Issue by nonesc** [jonkykong/SideMenu#201]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Here is my screenshot of my application
http://imgur.com/a/8FayM
It shows navigation bar not like your example.

I just want to remove navigation bar. Is there a way to achieve that?

Thank you

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.

**Comment by tylerbobella** [comment]
Was this asked on StackOverflow? Can the OP post the link to StackOverflow?

**Comment by tylerbobella** [comment]
Ah sorry. The answer to this question is 
`viewController.setNavigationBarHidden(true, animated: false)`

**Comment by gregoireLem** [comment]
Hey : here is my code : 
`// Define the menus
        let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: slideViewController)
        menuLeftNavigationController.navigationController?.setNavigationBarHidden(true, animated: false)
        SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController
        SideMenuManager.default.menuPresentMode = .menuSlideIn
        SideMenuManager.default.menuWidth = self.view.frame.size.width - 50
        // status bar color
        SideMenuManager.default.menuAnimationBackgroundColor = UIColor.gray.withAlphaComponent(0.2)
        SideMenuManager.default.menuAnimationPresentDuration = 0.10
        SideMenuManager.default.menuAnimationOptions = .curveEaseOut
        SideMenuManager.default.menuDismissOnPush = true`

but the navigation bar style shows up. 

Any ideas ?

**Comment by gregoireLem** [comment]
ok I did it that way : 
`menuLeftNavigationController.navigationBar.isHidden = true
`
