### ISSUE TITLE
Black screen after dismiss after viewWillTransition

### ISSUE THREAD

**Issue by SIDGEY** [jonkykong/SideMenu#203]
HI, 

i want to dismiss the menu if the screen is on landscape.

` override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        if(UIDevice.current.orientation.isLandscape){
            dismiss(animated: false, completion: nil)
        }
    }
`

but I have black screen, and App no work.

**Comment by jonkykong** [comment]
This isn't a bug; this is a design change which I am not supporting. You'll have to figure this one out for yourself.

**Comment by Ro4ch** [comment]
@jonkykong Actually he is asking for a design change and pointing out a bug. When I open SideMenu then bring down Apple's notification center and come back to the app, the view is black and becomes unresponsive.

**Comment by jonkykong** [comment]
@Ro4ch I am unable to reproduce that issue using the demo project on iOS 10. Make sure you're using the latest SideMenu code.
