### ISSUE TITLE
Side menu controller with tableview

### ISSUE THREAD

**Issue by JayachandraA** [jonkykong/SideMenu#204]
I'm using this sidemenu controller in my project but there is an issue while using it. I have setup a side menu view controller at left and right, the controller have a tableview and when I try to reorder the cells I'm unable to perform the action.

![simulator screen shot 31-may-2017 3 51 35 pm](https://cloud.githubusercontent.com/assets/5477301/26627886/a2a97154-4619-11e7-8651-a5b58fdb18fb.png)

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.

**Comment by seanbarney** [comment]
@JayachandraA were you able to resolve this issue? I'm experiencing the same issue myself. My table view works perfectly if I disconnect it from the SideViewNavigationController, but as soon as I set it back up the rows will not move past their initial position. Would love any help / guidance you could provide.

**Comment by JayachandraA** [comment]
@seanbarney I have tried multiple ways of fixing this problem, but I couldn't able to fix this issue.

**Comment by jonkykong** [comment]
The best advice I can give you is to try turning the `menuEnableSwipeGestures` to `false`. If that doesn't work, you'll have to try inspecting/subclassing all of the gestures to see which one is preventing others from activating, or use a custom drag/drop library.

**Comment by seanbarney** [comment]
@jonkykong Thanks for the suggestion! Setting `SideMenuManager.menuEnableSwipeGestures = false` fixed the issue. Much appreciated!

**Comment by jonkykong** [comment]
@seanbarney no problem.

I'm sure I sound like a broken record, but for anyone who reads this thread in the future: this is why I often redirect people to re-read the README carefully or take their questions to stackoverflow.com instead of providing answers for every question myself.
