### ISSUE TITLE
alertcontroller show only one time from any menu option in any class.

### ISSUE THREAD

**Issue by ravi6880** [jonkykong/SideMenu#207]
I am using the slidemenu, but it stuck my work , because i am using alert
[Demo.zip](https://github.com/jonkykong/SideMenu/files/1056194/Demo.zip)
controller from everyscreen "ViewController" for different purpose. 
But it appear only one time from any view after this its  not appear
Here i am attaching a demo , please check it and resolve the issue.

**Comment by ravi6880** [comment]
Hi jonkykong,
Whats the issue ? 
Its serious problem . please check the demo and let me know what i do ?

**Comment by jonkykong** [comment]
You did not complete the new issue template, which I require to look at any issue to save myself a lot of time.
