### ISSUE TITLE
alert is not being appear every time from any menu option

### ISSUE THREAD

**Issue by ravi6880** [jonkykong/SideMenu#208]
When i want to show alert from every view controller.
From any screen it work first time, but after one time if i again click the left side menu same  option then same view controller appear but alert not being show and i am get the below error 
message  
Warning: Attempt to present <UIAlertController: 0x7f8467f34c00>  on <viewController: 0x7f8467f31ad0> which is already presenting (null)

**Comment by jonkykong** [comment]
Again, you have not completed the template:



## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
