### ISSUE TITLE
Is it possible to open the Menu from ViewControllers in the navigation stack?

### ISSUE THREAD

**Issue by VBasinovas** [jonkykong/SideMenu#209]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello,

So far your library looks really neat, but there's one functionality I'm interested in, which I don't know is possible. Basically, is it possible to open the SideMenu from the View Controllers that have been pushed onto the navigation stack from the Side Menu itself like in the Example app? And if it's not possible, would it require a lot of effort to make it happen myself? 

I'm asking instead of researching myself, because I'm trying to save time (it's a bit urgent) and since you know how it works, I would really appreciate a Yes or No answer 😄 (directions wouldn't hurt)

Thanks!

**Comment by jonkykong** [comment]
@VBasinovas understand that by asking instead of reading, you're expecting me to spend my time so you don't have to, which isn't fair to me. You would also have gotten your answer far faster if you had read the README and tried implementing it yourself.

The majority of my knowledge is in the README and I wrote it so I wouldn't have to spend so much time answering people's questions. Please respect this.

**Comment by VBasinovas** [comment]
@jonkykong I understand this, and I even ticked the checkbox where it says that I have read the README (kind of makes you think if the template is even necessary). I did not find any documentation on this. When a VC is pushed from the SideMenu, inside of it, when I swipe from left to right, it pops the VC instead of opening the SideMenu. Have played around with the properties, even though none of them looked like they change this behavior. A simple YES/NO answer would have been even a less waste of time for you and me.
