### ISSUE TITLE
Carthage: Code-less Storyboard implementation not working ?

### ISSUE THREAD

**Issue by jofvr** [jonkykong/SideMenu#210]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have tried to use this framework with my project. I followed the step to install it with Carthage, I think the installation with Carthage has worked.
The trouble is when I tried to use it. I follow the usage paragraph in the ReadMe, and the first point not working with me. When I try to set the custom class of my navigation controller to UISideMenuNavigationController, Xcode doesn't know the class.
I have tried to reinstall the framework with Carthage and to export the framework my self (in the Derived Data) manually the project and it's always not working.
The only way when it has work it's when I have copy the files (in Pods/Classes): 
- SideMenumanager.swift ;
- SideMenuTransition.swift ;
- UISideMenuNavigationController.swift.

So I think, for one reason (Carthage failed ?), this file is not included into the framework.

**Comment by justin-nodeboy** [comment]
+1, I had to manually drag those files into the project

**Comment by jonkykong** [comment]
Did you specify the Module as SideMenu in Storyboard?

**Comment by jonkykong** [comment]
@soheilbm Carthage problems being reported?

**Comment by justin-nodeboy** [comment]
@jonkykong I followed the instructions, dropped the framework in as per usual carthage installations, but unfortunately the class didn't appear when dropping a UINavigationController onto the storyboard, even with specifying the module. When adding the present modal segue the Nav Controller just sprung up from the bottom like a standard modal.

After adding the classes manually it worked as expected. Hope that helps. I can't speak for @jofvr this is just my own experiences this evening

**Comment by jofvr** [comment]
@jonkykong @justin-nodeboy It's just a Carthage problems, because, when SideMenu is install with Carthage, in fact it's working. There is juste some problem : We don't have the "LeftSide" IBInspectable, and the Storybord does not recognize the CustomClass "UISideMenuNavigationController" and the module "SideMenu" automatically.
So, i juste have to copy paste the custom class and the module and SideMenu is working.

**Comment by jonkykong** [comment]
@jofvr @justin-nodeboy Carthage support was added by @soheilbm a while back. Any chance either of you are interested in correcting the issue as a contribution to this repo? If left up to me it's going to be a while, my plate is full at the moment.

**Comment by jofvr** [comment]
I don't think the problem is on your FrameWork, i think a Carthage problem is back (see : https://github.com/Carthage/Carthage/issues/335#issuecomment-223761898)
