### ISSUE TITLE
Buildtime issue with swift 4 and iOS11

### ISSUE THREAD

**Issue by alejandroaap** [jonkykong/SideMenu#211]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I am trying to use the library but I am encountering compilation errors. I currently use xcode-beta version 9, swift 4 and ios11. It gives me nine compilation errors like the following:
"Argument of '#selector' refers to class method 'handleHideMenuPan' that is not exposed to Objective-C"
Can anyone help me solve it? Thank you

**Comment by JPwharton** [comment]
@alejandroaap go to the method that is throwing the error and add @objc before calling it. 
ex.  func handleMenu{}  =>  @objc  func handleMenu{} .

**Comment by jonkykong** [comment]
As @JPwharton commented, this is not a Swift 4 issue, but an objective-c compatibility issue that I've deliberately not supported. A simple change will enable it, along with removing default values.

**Comment by bushev** [comment]
@jonkykong Hello! It seems I have a similar problem.

1. Created a new single page project (Swift 4 project)
2. pod init
3. added line: `pod 'SideMenu'`
4. `pod install`
5. Opened `proj.xcworkspace`
6. Click Run

Got the errors:

![image](https://user-images.githubusercontent.com/7535766/31363986-d58f5c38-ad6a-11e7-92ae-439851b9827c.png)

**Comment by braandl** [comment]
I have the exact same issue too
