### ISSUE TITLE
Crash on `handleNotification`

### ISSUE THREAD

**Issue by alimoeeny** [jonkykong/SideMenu#212]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

On rare occasions, I get a crash on handleNotification that says: 
> Fatal Exception: NSInvalidArgumentException
> Can't add self as subview

I assume this happens on line 376 `originalSuperview.addSubview(mainViewController.view)`

I don't know how or when this is even possible. Usually the menu works very well. And I don't think I have code that messes around with the view controllers and view that are attached to the sideMenu.
One possible solution is to check. If originalSuperview is the same as the mainViewController.view 
Which is silly but it prevents crashes .

Regardless, thanks for the excellent library.

Feel free to close this if you think it is rare and not worth adding the check.

**Comment by jonkykong** [comment]
@alimoeeny Thanks for reporting this. So far, this is the first incidence being reported. I'll keep an eye out for additional reports.
