### ISSUE TITLE
Close the side menu from the side menu view controller

### ISSUE THREAD

**Issue by mateo666** [jonkykong/SideMenu#215]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How can one close the side menu from the side menu itself ? 
I use dismiss on the UISideMenuNavigationController but it is dismissed very slowly compared to when pushing view controllers.
Having a look inside the class i see an animation block going on when a view controller is pushed, so i guess this is not executed when dismissed...
Can you provide any help ?

on a side note i must say this issue checklist is a pain in the ass.
first time i see this on GitHub.

**Comment by jonkykong** [comment]
Dismiss is the supported way. There are also properties to control this speed of the animation. You will need to provide more information if you think the behavior is unexpected from what you see in the sample screenshots in the README. We will reopen this issue if needed.

**Comment by jonkykong** [comment]
@mateo666 regarding the checklist, it's far more painful for me to get open issues from people providing no useful information or doing their own background investigations before involving me. If you disagree, I suggest you create your own free library and see what happens :)

**Comment by mateo666** [comment]
Problem with your sample project is that it is all set up in storyboard.
try adding a custom button in one menu and handling the dismiss or push from code.
would help your users im sure.

**Comment by jonkykong** [comment]
There's no problem with storyboard that I'm aware of, it's very commonly used these days.

I just did a quick test of putting a dismiss call in the Example Project menu and it worked as expected with no speed problems. You'll have to provide more information about what's going wrong.
