### ISSUE TITLE
Swipe Gesture of side view gets lost after right swipe if menuRightNavigationController is not init

### ISSUE THREAD

**Issue by linbo8303** [jonkykong/SideMenu#217]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How to reproduce:
1. only initialise SideMenuManager.menuLeftNavigationController (modify the example code)
2. swipe from left edge can invoke side view.
**3. swipe from right edge of screen**
4. then SideMenuManager.menuLeftNavigationController cannot invoke by swipe from left edge of screen -- the swipe gestures are lost.

however, if both menuLeftNavigationController and menuRightNavigationController are initialised, there is no such issue.

**Comment by jonkykong** [comment]
Fixed in 2.3.3.
