### ISSUE TITLE
SideMenu when logout

### ISSUE THREAD

**Issue by mrsnax** [jonkykong/SideMenu#218]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi,

I tried the Side Menu to load into my app, everything is work fine (as my storyboard below) : 
<img width="620" alt="screen shot 2017-06-30 at 16 33 55" src="https://user-images.githubusercontent.com/6369589/27729995-fc376b86-5db1-11e7-847a-724af6c56583.png">

But when user trigger clicked Logout, Side Menu going transpert and show as segue not a sliding (as images below) : 

![simulator screen shot 30 jun 2017 16 38 25](https://user-images.githubusercontent.com/6369589/27730249-cb3791cc-5db2-11e7-8a22-764d703b0d50.png)

How to fix that? 
Thank you

**Comment by jonkykong** [comment]
Please follow the README carefully.
