### ISSUE TITLE
How to disable swipe dismiss

### ISSUE THREAD

**Issue by CrazyDavis** [jonkykong/SideMenu#220]
i set the 
SideMenuManager.menuEnableSwipeGestures = false
but it's not working

**Comment by alok1upadhyay** [comment]
You can use this property:
Not sure about your scenario, but in my case when user logs out and reach on login screen i wanted to disable gesture from left to right.

At th etime user clicks on logout i set below property to 0.0 and that's it.
SideMenuManager.default.menuWidth = 0.0

Now again reset it to 85% after user re-login.
