### ISSUE TITLE
Many errors in swift 4

### ISSUE THREAD

**Issue by yahyatabba** [jonkykong/SideMenu#224]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Thank you for your library, it's too easy and simple.
I tried it in **swift 4** and it's **show many errors** and i can't use it in project!
please what can i do to run??
thank you

**Comment by jonkykong** [comment]
It has yet to be upgraded to Swift 4. You're welcome to submit this change yourself or upgrade it locally.

**Comment by RajChanchal** [comment]
Meanwhile it upgrades to Swift 4, we can use following code in podfile:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'SideMenu'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
```
