### ISSUE TITLE
How to use with embedded navigation controller

### ISSUE THREAD

**Issue by adamteller117** [jonkykong/SideMenu#227]
## New Issue Checklist

I have read the [guidelines for contributing][x](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu. [x]
- [x] My issue was **not** solved in the [README] [x](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com). [x]
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request. [x]
- [ ] My issue **is** reproducible in the [demo project] [x](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I would like to know how to use this while having an embedded navigation controller. When I use a non embedded navigation controller, my app works well except I would like my other storyboards to inherit the navigation controller that I have set up.  I have attached some screenshots to help. I would like my contact form to have a back button to go back to the main screen it came from but it will not inherit the navigation bar. I have attached a screenshot of how I have my storyboards setup.
<img width="367" alt="screen shot 2017-07-12 at 12 41 06 pm" src="https://user-images.githubusercontent.com/28907532/28131649-2ea88526-6700-11e7-803f-bad2c23827bc.png">
<img width="600" alt="screen shot 2017-07-12 at 12 46 41 pm" src="https://user-images.githubusercontent.com/28907532/28131651-2fe14400-6700-11e7-979a-62c0172ea619.png">

**Comment by jonkykong** [comment]
@adamteller117 This isn't a bug with SideMenu, this is a question on how to use it. Your question is better suited for stackoverflow.com or following the README carefully.

**Comment by ShvetsJr** [comment]
Omg whats your deal @jonkykong? Why is it so hard to help people who are interested in your project? People spend their time and try to explain to you a problem and hope that you will help them but instead, you send them to your stupid README that doesn't cover most cases... What a horrible repo

**Comment by toseefkhilji** [comment]
Agree with @ShvetsJr.
@jonkykong : I know you have some other important tasks rather than answer/ helping general questions. What I think is you are right person to people help or give proper advice to achieve their functionality because you have created this lib.

If you have no time then you can make this lib as **archived** or add some  title **NOT Maintaining/ Support anymore**. So people will search some other lib.

Thanks again for Great Lib. Sorry if it hurts you.
