### ISSUE TITLE
Side menu transition build failed

### ISSUE THREAD

**Issue by mjurfest** [jonkykong/SideMenu#229]
## Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I am trying to build a project on Xcode 7.3.1 using the pod version 1.2.1 because my project has SWIFT_VERSION 2.3.

The build failed showing the following errors:

![screen shot 2017-07-20 at 16 21 20](https://user-images.githubusercontent.com/17320967/28434930-90c5ba0e-6d67-11e7-85c8-50b1c2656b8e.png)

![screen shot 2017-07-20 at 16 21 32](https://user-images.githubusercontent.com/17320967/28434931-90cbe06e-6d67-11e7-91df-69301868cc13.png)

I hope you can help me, thanks!

**Comment by jonkykong** [comment]
@mjurfest Sorry, but I'm only supporting the latest version of SideMenu. You'll have to fix the SideMenu code as suggested by Xcode -- shouldn't be hard.
