### ISSUE TITLE
Informs when Side Menu start presenting menu and end presenting menu

### ISSUE THREAD

**Issue by munfai** [jonkykong/SideMenu#23]
Hi, do you think it is possible to add in a delegate, to inform the view controllers about when it will start presenting the side menu, and also when the side menu has been completely presented? Same goes to when closing the side menu. It would be help if that's added. Many thanks.

**Comment by jonkykong** [comment]
Do you have a specific scenario that cannot be solved by the standard
present/dismiss view controller calls? Since this control uses custom
transitions it does not have any special calls for display and dismiss,
therefor you can use the normal system calls.

**Comment by munfai** [comment]
I was wondering, when the side menu has been presented, then now when I would like to dismiss the side menu, via a pan gesture towards to the left, or simply tap on the origin view's area, would my view controller be informed on the events? Since the pan and tap are handled by Side Menu.

**Comment by jonkykong** [comment]
@munfai I'm still not understand the scenario of _why_ you would need to do that. You may be able to accomplish this by overriding `viewWillAppear`, `viewDidAppear`, `viewWillDisappear`, and `viewDidDisappear` in the view controller you use as your menu. That won't give you dynamic progress of how much the transition has appeared, but will let you know start and end.

I also encourage people to contribute to this control. If you create a pull request, I can take your changes to the library to support this.
