### ISSUE TITLE
Cannot set left menu in Storyboard only setup

### ISSUE THREAD

**Issue by markprovan** [jonkykong/SideMenu#230]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi there,

It seems in Xcode 8 I cannot set the menu to be on the left, as in the screenshot below:

![](https://github.com/jonkykong/SideMenu/raw/master/etc/Screenshot2.png)

I instead end up with:

![screenshot 2017-07-24 00 05 30](https://user-images.githubusercontent.com/70797/28503778-9aabc028-7004-11e7-8d03-548a08367ee0.png)

Is this a project issue, or an issue with my setup? I could not see the option either in the demo.

I should also probably mention that the menu works completely as expected otherwise, on the right hand side.

Thanks

**Comment by jonkykong** [comment]
Seems like an issue with your setup. Make sure you've set the navigation control to be a UISideMenuNavigationController as described in the README.

**Comment by muni510** [comment]
Having the same issue for me also... I have set custom class UISideMenuNavigationController and Module SideMenu.

But not showing on Attribute Inspector on Xcode 9
Kindly help me.

**Comment by jonkykong** [comment]
@muni510 If you see the property in the demo project, you will see it in your project. Chances are you're not following the README carefully enough. I see the property without issue in Xcode 9.

**Comment by muni510** [comment]
@jonkykong I have sorted it by setting User Defined Runtime Attribute as leftSide = true(Boolean).

**Comment by jonkykong** [comment]
@muni510 I appreciate the update, but that shouldn't have been necessary. I see the property in Xcode 9 in all of my projects. There's probably something else that's not right.
