### ISSUE TITLE
Is it possible to have 2 distinct SideMenus?

### ISSUE THREAD

**Issue by nmdias** [jonkykong/SideMenu#231]
From what I'm gathering SideMenu is completely static. It seems that I have no control over using more than once instance of this. 

Is this not possible? Here's what I'm trying to do:

- Login 
  - Side Menu (Apps Context)
    - App Context 1
    - App Context 2
        - Side Menu (Presented Modally) 

Thanks

**Comment by jonkykong** [comment]
@nmdias SideMenu is a singleton for simplicity, meaning it is only meant to be set up one time.

You can change the configuration for each of your contexts back and forth as long as SideMenu is not in the view hierarchy.

**Comment by nmdias** [comment]
You don't really gain simplicity by making a complex project like this static. You loose flexibility, however.

**Comment by jonkykong** [comment]
That's incorrect. Since it is a single instance, it's not necessary to create your own global references or set up the menu again for every screen you want to show it on. It was my design choice, and given the popularity of this library, I feel confident it's the right one for the majority of developers. The more flexibility or customization a library has, the more complicated it becomes to maintain and setup.

**Comment by nmdias** [comment]
You can have a singleton without making all classes methods and variables static. It's unrelated. Static has its place, sure, but abusing it like this just throws base oop concepts out the window.

Your statement last could also be true in a different context.

**Comment by jonkykong** [comment]
You'll have to be more specific on how static variables ignores OOP best practices. For reference, you can learn more about variable declarations, including when it's appropriate to use static variables, [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Properties.html).

Regardless, in its current form, this library is _still_ flexible enough to accommodate your design needs, so I see no reason to make any changes.

**Comment by nmdias** [comment]
Not best practices, concepts. You lost inheritance, reusability, possibly testability.

I'm not suggesting a change. I have 2 side menus in my view hierarchy, so it won't be possible. Again, you didn't gain simplicity by that design choice, you lost flexibility.

I'm not trying to be rude, clearly this framework helps tons of developers and asks nothing in return 🙏 I was just pointing out a road taken by myself before.

Cheers

**Comment by wdcurry** [comment]
I would LOVE a way to display a second-level menu pop from the first, leaving the first as is. There seems to be no such menus in Swift.  I would burn a whole night ripping my current menu implementation out of an in app-contract for this, as it is a design target that is tough to meet in this short contract i have.

**Comment by jonkykong** [comment]
@wdcurry if that's true, then I'm willing to entertain any pull request that alters this repo away from a singleton towards individual instances. I'd still want the singleton or some altered version of it with appropriate deprecation notices to continue working as a default global menu.

**Comment by wdcurry** [comment]
I will consider it for sure, but only after this current very frenetic contract. I am going to have to roll out my own pseudo menu structure that lacks the funky animation and gloss but achieves the look of a client prototype. 

I suspect the major consideration will be to offer a reduction in first menu structure when showing the second, and ensuring the second emerges from the right side of the first. Hell, i would settle for no emerge/animation but a straight appearance. This is the approach i am currently taking.
