### ISSUE TITLE
Shawdow not possible with any effect

### ISSUE THREAD

**Issue by romanr** [jonkykong/SideMenu#232]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Running the demo project it is impossible to have menu with shadow. Same parameters as in screenshots in Readme produce different result, without shadow.

iOS 10.3

**Comment by jonkykong** [comment]
This is by design. Shadow effects break vibrancy effects, see http://www.openradar.me/28083614.

The non-vibrancy menu does show the shadow but that is also affected by the overall alpha level of the view it's applied to, so for the demo project it's very faint to see.
