### ISSUE TITLE
Side menu removes whenever the app goes in background.

### ISSUE THREAD

**Issue by TTNNehaJain** [jonkykong/SideMenu#236]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [Y] My issue is happening in the **latest version** of SideMenu.
- [Y] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [Y] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [Y] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [Y] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Side menu removes whenever the app goes in background.
Steps to repro --
1. Open the app (Your sample app)
2. Open side menu
3. Keep the app in background
4. Open app
5. Side menu will not be visible.

**Comment by jonkykong** [comment]
@TTNNehaJain this is by design. If you don't want this behavior you can modify it to prevent the behavior.

**Comment by hemangshah** [comment]
@jonkykong where to modify about this?

**Comment by gmann1** [comment]
@TTNNehaJain @jonkykong hey guys I'm having this issue as well. I'm not sure how you modify to prevent this behavior?
