### ISSUE TITLE
Split View Controller issue

### ISSUE THREAD

**Issue by bokhary3** [jonkykong/SideMenu#237]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I get this error when try to push ViewController fro Menu that is 
attempt to push a View Controller from Optional(<UISplitViewController: 0x1022084e0>) where its navigationController == nil. It must be embedded in a Navigation Controller for this to work. 
but I changed the code in UISideMenuNavigationController class to 
        guard let splitVC = (tabBarController?.selectedViewController ?? presentingViewController) as? UISplitViewController else {
            print("SideMenu Warning: attempt to push a View Controller from \(String(describing: presentingViewController.self)) where its navigationController == nil. It must be embedded in a Navigation Controller for this to work.")
            return
        }
        let navigationController = UINavigationController(rootViewController: splitVC)
and it worked

**Comment by jonkykong** [comment]
@bokhary3 I do not understand what any of the code you provided does or how your project is architected. Please provide more clarity.

**Comment by bokhary3** [comment]
Hi @jonkykong
I am sorry for that you didn't understand me,
My project consists of splitviewcontrller as  root and call SideMenu from Master controller then when try to open any view controller from side menu I get that error "attempt to push a view controller from split view controller where its navigationcontroller  == nil it must be embedded in navigation controller to work" but split view controller has navigation controller so I fixed that by ignor the check the get this error and make navigation like that 
Let splitVC = presentingViewController as! UISplitViewController
Let navigationController = splitVC.viewControllers[splitVC.viewControllers.count-1]
And then used this navigation to push and it worked ,hope you get what I want to tell you .
But I want to thank you  so much for your wonderful library.

**Comment by jonkykong** [comment]
Your detail controller has a navigation controller, but your master controller does not. Your master controller needs to be embedded in a navigation controller, and the navigation controller needs to be your master controller to solve this problem. Without this, you won't be able to push any screens from the SideMenu, only present, that's why you see the warning. This is by design. Please follow the README.

**Comment by bokhary3** [comment]
But both of Madter and Details are embedded in Navigation

**Comment by jonkykong** [comment]
Okay, now I understand the issue. However, if you're using a SplitViewController, why would you want to show SideMenu over top of this? Isn't the SplitViewController already showing a Side Menu?

It seems to me that you would only want to use SideMenu for smaller device sizes and use SplitViewController for larger ones. Perhaps this is your design, but you are trying to make Storyboard work for both?

**Comment by bokhary3** [comment]
Yes I want side menus work for small and large devices.
