### ISSUE TITLE
 Failed to set (leftSide) user defined inspected property on (UINavigationController): [<UINavigationController  setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key leftSide.

### ISSUE THREAD

**Issue by kishor010** [jonkykong/SideMenu#239]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
Please follow the README carefully.

**Comment by kishor010** [comment]
I read but didn't get idea. Thanks

**Comment by DeepnetSecurity** [comment]
I got the same problem after some upgrade. Fixed it by changing the class UISideMenuNavigationController  to SideMenuNavigationController
