### ISSUE TITLE
Detect when menu is open/close

### ISSUE THREAD

**Issue by Prims47** [jonkykong/SideMenu#240]
## New Issue Checklist
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project]

## Issue Description
Hi,

I would like know if it's possible to detect when menu is open/close in order to change my leftBarButtonItem image.  If it not implement i can create a pull request :)

Thanks

**Comment by jonkykong** [comment]
Please see the example project.

**Comment by Prims47** [comment]
Ty, sorry for this issues
