### ISSUE TITLE
Swift - jonkykong SideMenu UISideMenuNavigationController not found

### ISSUE THREAD

**Issue by guidupas** [jonkykong/SideMenu#241]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I have downloaded jonkykong SideMenu using Carthage and I imported the framework inside my project.
![n4x9a](https://user-images.githubusercontent.com/12818273/29325907-766323b8-81b7-11e7-88ef-7a4fa0cad3b6.jpg)
When I try to define the custom class of the navigation controller in my storyboard to UISideMenuNavigationController as I need to do following the instructions of the library on GitHub the class is not found.
![12ufa](https://user-images.githubusercontent.com/12818273/29325906-7632ca10-81b7-11e7-904e-0ae79e2ab8ce.jpg)
The framework in working fine when I import it inside a swift file.
How can I reference this class inside the storyboard

**Comment by jonkykong** [comment]
Did you specify the module? Have you tried typing it in manually?

**Comment by guidupas** [comment]
Yes, I did. I tried now typing all manually and it's working. But it's with a black bar where the status bar is located.

**Comment by jonkykong** [comment]
Please follow the README carefully.

**Comment by guidupas** [comment]
Yes, about the black bar is ok. But I still receive a message like this 

> Unknown class _TtC11WoodFactory26SideBarTableViewController in Interface Builder file.

**Comment by jonkykong** [comment]
There is no class called "SideBarTableView", so you have entered the name incorrectly. Please follow the README carefully, I have put all the instructions there so I don't have to repeat them here.

**Comment by Borming** [comment]
Why is this closed and not resolved?  I have the same problem with Xcode 9, its not finding UISideMenuNavigationController even when i set the Module to SideMenu.

**Comment by guidupas** [comment]
If you have used Carthage to download the library you have to set it manually.
