### ISSUE TITLE
Set navigation item title on a TableViewController child of UISideMenuNavigationController not working

### ISSUE THREAD

**Issue by guidupas** [jonkykong/SideMenu#243]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I am trying to set a title to my rootViewController programmatically but it is not working.

```
func configurarMenuRightNavigationController() {
        
        SideMenuManager.menuFadeStatusBar = false
        
        let menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as! UISideMenuNavigationController
        
        //let menuRightNavigationController = UISideMenuNavigationController(rootViewController: YourViewController)
        // UISideMenuNavigationController is a subclass of UINavigationController, so do any additional configuration
        // of it here like setting its viewControllers. If you're using storyboards, you'll want to do something like:
        
        SideMenuManager.menuRightNavigationController = menuRightNavigationController
        
        SideMenuManager.menuRightNavigationController?.viewControllers[0].navigationItem.title = "Teste"
        
        SideMenuManager.menuPresentMode = .viewSlideOut
    }
```

The title doesn't change.

It works when I try in another project without Side Menu on a regular UINavigationController.

<img width="261" alt="captura de tela 2017-08-16 as 13 54 13" src="https://user-images.githubusercontent.com/12818273/29378061-b633d3be-828b-11e7-9096-24de68a3844b.png">

![img_3772](https://user-images.githubusercontent.com/12818273/29378112-e29bcc0e-828b-11e7-9b05-5f874568425e.png)

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.

**Comment by agordeev** [comment]
I'm having the same problem. I think this is related to the library, as the standard UINavigationController displays title as expected
