### ISSUE TITLE
"Use of unresolved identifier 'YourViewController'"

### ISSUE THREAD

**Issue by renan-neb** [jonkykong/SideMenu#244]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When trying to build, I am gettinf=g this error: "Use of unresolved identifier 'YourViewController'"

**Comment by jonkykong** [comment]
This is a question for Stackoverflow.com.
