### ISSUE TITLE
How to stop from right side. It is opening from right side also and I want to open it from left side only. 

### ISSUE THREAD

**Issue by kishor010** [jonkykong/SideMenu#245]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

fileprivate func setUpMenu() {
        let YourViewController = self.storyboard?.instantiateViewController(withIdentifier: "slideMenuViewController") as! slideMenuViewController
        
        // Define the menus
        let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: YourViewController)
        
        menuLeftNavigationController.leftSide = false
        menuLeftNavigationController.closeRight()

        SideMenuManager.menuLeftNavigationController = menuLeftNavigationController
       
        SideMenuManager.menuPresentMode = .menuSlideIn
        SideMenuManager.menuWidth = self.view.frame.size.width - 80
        SideMenuManager.menuAnimationFadeStrength = 0.8
        SideMenuManager.menuEnableSwipeGestures = false
        SideMenuManager.menuShadowColor = UIColor.black
        SideMenuManager.menuAnimationBackgroundColor = UIColor.white//UIColor.black.withAlphaComponent(0.6)
    
        SideMenuManager.menuAddPanGestureToPresent(toView: self.view)//self.navigationController!.navigationBar)
        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView:self.view) 
    }

**Comment by jonkykong** [comment]
Please read the README carefully.

**Comment by kishor010** [comment]
I didn't get it in README.
Please help
Thanks @jonkykong 
@joshfriend 
@leoneparise 
@jlukanta

**Comment by joshfriend** [comment]
@kishor010 please dont @ spam random users on github issues
