### ISSUE TITLE
menuAddScreenEdgePanGesturesToPresent to my view will open both side and from right side it is a different animation while close menu?

### ISSUE THREAD

**Issue by kishor010** [jonkykong/SideMenu#246]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I am doing set up of my menu view and I don't want it to open from right side. But thing is in my view if I will try from right side edge then also it is opening Drawer and If I will try to close menu the animation is totally different. 

I don't know its a bug or what? 

Below is my setUp code :-  

let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: YourViewController)
        
        menuLeftNavigationController.leftSide = false
        menuLeftNavigationController.closeRight()
        //menuLeftNavigationController.
        SideMenuManager.menuLeftNavigationController = menuLeftNavigationController
       
        SideMenuManager.menuPresentMode = .viewSlideOut
        SideMenuManager.menuWidth = self.view.frame.size.width - 80
        SideMenuManager.menuAnimationFadeStrength = 0.8
        SideMenuManager.menuEnableSwipeGestures = false
        SideMenuManager.menuShadowColor = UIColor.black
        SideMenuManager.menuAnimationBackgroundColor = UIColor.white

        //SideMenuManager.menuAddPanGestureToPresent(toView: self.view)

        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView:self.view)

Please help me because I want to open it from left side with left edge gesture only. 
Thanks

**Comment by jonkykong** [comment]
Please read the README carefully.

**Comment by kishor010** [comment]
I didn't get it in README that's why I am asking. 
Thanks
