### ISSUE TITLE
Cannot run the example code provided. Please refer screenshot

### ISSUE THREAD

**Issue by aromal-sasidharan** [jonkykong/SideMenu#247]
<img width="1406" alt="screen shot 2017-08-18 at 12 01 09 pm" src="https://user-images.githubusercontent.com/5155674/29446976-03a82500-840d-11e7-8d51-030b29ee6437.png"/>

## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
Clear your derived data and build again.

**Comment by aromal-sasidharan** [comment]
Issue Still exist. Even after cleaning the derived data

**Comment by jonkykong** [comment]
I'm not sure what the issue is, but it's almost certainly nothing to do with SideMenu, but something is wrong with Xcode or your project. Try taking this question to Stackoverflow.com.

**Comment by jonkykong** [comment]
Try reinstalling SideMenu as well (and cleaning DerivedData again).
