### ISSUE TITLE
menuAddScreenEdgePanGesturesToPresent is not present in SideMenu-Swift.h file

### ISSUE THREAD

**Issue by Prabhat-Emorphis** [jonkykong/SideMenu#249]
I am using this framework in Objective-C and getting error in:
[SideMenuManager menuAddScreenEdgePanGesturesToPresent:self.navigationController.view];
![screen shot 2017-08-23 at 1 52 36 pm](https://user-images.githubusercontent.com/23358685/29605973-67cd1db4-880a-11e7-9e22-e8e6b7403d62.png)

According to doc menuAddScreenEdgePanGesturesToPresent method should available in SideMenu-Swift.h file, but this is not the case there is only menuAddPanGestureToPresent method is available.

![screen shot 2017-08-23 at 1 56 52 pm](https://user-images.githubusercontent.com/23358685/29606140-f3f88b8e-880a-11e7-873f-8059e9b2bc1e.png)

**Comment by Prabhat-Emorphis** [comment]
In @discardableResult open class func menuAddScreenEdgePanGesturesToPresent(toView: UIView, forMenu:UIRectEdge? = nil) -> [UIScreenEdgePanGestureRecognizer] method Swift compiler unable to convert it into this
+ (NSArray<UIScreenEdgePanGestureRecognizer *> * _Nonnull)menuAddScreenEdgePanGesturesToPresentToView:(UIView * _Nonnull)toView forMenu:(UIRectEdge)forMenu;

Problem is in "forMenu:UIRectEdge? = nil" I change it manually to "forMenu:UIRectEdge" and my code is working fine now.

**Comment by jonkykong** [comment]
Unfortunately this change is not supported. I've decided to make the library best designed for Swift, and optional parameters are not supported in Objective-C.
