### ISSUE TITLE
How to change/remove status bar when showing SideMenu 

### ISSUE THREAD

**Issue by fajaradiwa** [jonkykong/SideMenu#25]
i want remove the status bar when sideMenu showed

<img width="1026" alt="screen shot 2016-05-10 at 11 42 26 am" src="https://cloud.githubusercontent.com/assets/2561679/15135763/56207d64-16a4-11e6-9c7f-b9dfe92d37fa.png">

**Comment by jonkykong** [comment]
Please google the solution to this; it's a basic problem and not specific to SideMenu.
