### ISSUE TITLE
Incorrect behaviour of the library

### ISSUE THREAD

**Issue by oleghnidets** [jonkykong/SideMenu#252]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I found the issue that right menu opens in some cases. But I set up only left menu.
It appears when you swipes to left. I tried to debug and found the place (see attached). For some reason `SideMenuTransition.presentDirection` becomes `.right` as a result `direction = -1`.

I attached sample project. In this project you can reproduce enabling breakpoint in `handlePresentMenuPan(_ pan: )`. I have no idea why but the method is being invoked few times for one gesture. It is difficult to reproduce for the first time. 

In my real applications it even causes a crash. And I can reproduce it much more easier (guess because of complex UI). Please, fix that.

<img width="688" alt="screen shot 2017-08-30 at 17 26 30" src="https://user-images.githubusercontent.com/7702033/29880800-04a77d2a-8da9-11e7-9b33-dc771818f8c1.png">

[CrashSideMenu2.zip](https://github.com/jonkykong/SideMenu/files/1264227/CrashSideMenu2.zip)

**Comment by oleghnidets** [comment]
One more thing, `SideMenuManager.menuRightNavigationController` is not `nil` it is the same object of `SideMenuManager.menuRightNavigationController`. I strongly believe that it is incorrect, right?

**Comment by jonkykong** [comment]
@oleghnidets:

1. Are you able to demonstrate an issue in the Demo project? If not, then chances are you're doing something wrong in your code. Please follow the README carefully.
2. Do not set up gestures in `viewWillAppear`. That method can be called multiple times, causing multiple gestures to be added.

Please report back with an update and if there's still an issue I'll investigate.
