### ISSUE TITLE
Error: SideMenu Warning: attempt to push a View Controller from nil where its navigationController == nil. It must be embedded in a Navigation Controller for this to work.

### ISSUE THREAD

**Issue by jackdem** [jonkykong/SideMenu#255]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I instantiate the sidemenu views like so before setting as root due to already having an existing nav controller so needing to replace it:

```
func createHomeView() {
        // present view -- switches the root to the new navigation controller
        let homeViewController = HomeScreenViewController.init(homeView: HomeScreenView(frame: UIScreen.main.bounds))
        let menuViewController = SideMenuViewController.init(sideMenuView: SideMenuView(frame: UIScreen.main.bounds))
        // menu
        let leftNavigationController = UISideMenuNavigationController(rootViewController: menuViewController)
        leftNavigationController.leftSide = true
        SideMenuManager.menuLeftNavigationController = leftNavigationController
        // home
        let rightNavigationController = UISideMenuNavigationController(rootViewController: homeViewController)
        SideMenuManager.menuRightNavigationController = rightNavigationController
        // slide style
        SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.view)
        SideMenuManager.menuPresentMode = .viewSlideInOut
        SideMenuManager.menuFadeStatusBar = false
        SideMenuManager.menuAnimationOptions = .curveEaseInOut
        // animation and presentation
        let snapshot:UIView = (self.eventView.window?.snapshotView(afterScreenUpdates: true))!
        SideMenuManager.menuRightNavigationController?.view.addSubview(snapshot)
        self.appDelegate.window?.rootViewController = SideMenuManager.menuRightNavigationController
        UIView.animate (withDuration: 0.3, animations: { () in
            snapshot.layer.opacity = 0
            snapshot.layer.transform = CATransform3DMakeScale(1.5, 1.5, 1.5)
        }, completion: {
            (value: Bool) in
            snapshot.removeFromSuperview()
        });
    }
```

So here i create my views and then set the right nav as the root (my home view) 

I assume this is already the cause of the issue, but I cant see how i can correctly present it on top of my existing nav controller without taking this route. 

I then try to tap a menu item on the sidebar in the next presented view, and i get that error in the title. But i am able to use swipe gestures set on the nav controller, so im not sure how it can read nil? 

Here is the code for handling cell taps in the sidemenu view controller

```
func pushTappedModule(selected: MenuItem) {
        let selectedModule = selected.pageType
        switch selectedModule {
            
        case "home":
            let pushedController = HomeScreenViewController(homeView: HomeScreenView(frame: UIScreen.main.bounds))
            SideMenuManager.menuRightNavigationController?.pushViewController(pushedController, animated: true)
        default:
            print("failed to match menu item to a viewController")
        }
    }
```

What would be the solution here? I assume it stems from setting as root to replace the previous VC, but i cant set a new Nav controller and set the SideMenuManager.menuRightNavigationController as root in it either. 

Thanks for clarity on how to approach this scenario with the framework, stack couldnt help

**Comment by aurora14** [comment]
@jackdem did you manage to find a solution to this? Having the same issue at the moment, was wondering what I'm missing.

**Comment by trhtkv** [comment]
@aurora14 Thank you very much iv'e used your solution and everything works fine now

**Comment by Idomo** [comment]
@aurora14 May you upload image of your storyboard so it will be more understandable?

**Comment by aurora14** [comment]
> @aurora14 May you upload image of your storyboard so it will be more understandable?

I'll see what I can do. It was done for a client, therefore I may need to redact some things before I can do any screenshots. But if time permits, I'll mock up a sample project. I know it's hard to explain and read a lot of code/conceptual text, and with the project you can explore the structure for yourself :)

**Comment by aurora14** [comment]
![screen shot 2018-10-25 at 1 42 55 pm](https://user-images.githubusercontent.com/16133924/47473140-1c1cae80-d85d-11e8-9f38-914638eefdc8.jpg)

**Comment by kuoliangkwong** [comment]
I got the same error while setting the SideMenu as root view controller. I noticed the suggested solution above requires a different view controller as root to show the SideMenu, but the structure cannot achieve something like this

![interactivesidemenu](https://user-images.githubusercontent.com/8188634/50132377-d7901b00-02c1-11e9-80ff-8367bcf69578.gif)

Is there anyway we can achieve this?

**Comment by myanalysis** [comment]
I was having the same issue and it was because there was not Nav Controller on the MainView controller.
Simple fix.

**Comment by shravanteegala** [comment]
I got same issue.when i embedded  navigation Controller still i got same error.
