### ISSUE TITLE
menuDismissOnPush = NO  don't work. The menu is alway dismiss when push then pop to root viewcontroller.

### ISSUE THREAD

**Issue by abbotdeng** [jonkykong/SideMenu#259]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by risalgue** [comment]
I have the same problem, any suggestion for that problem

**Comment by jonkykong** [comment]
This is fixed in 2.3.4 or later. Make sure to read the README carefully for using this property.
