### ISSUE TITLE
[Feature Request] Supporting Swift 4?

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [jonkykong/SideMenu#262]
Will it support swift 4?

**Comment by moonvader** [comment]
Also interested!

**Comment by jonkykong** [comment]
This is currently supported.

**Comment by moonvader** [comment]
So why it doesn't compile in Xcode 9?

**Comment by jonkykong** [comment]
See 
- https://github.com/jonkykong/SideMenu/commit/6ed444f433c94c55a3f27697237d68b1cdd14782

It's available in 3.0.1.
