### ISSUE TITLE
Status bar goes to black on transition

### ISSUE THREAD

**Issue by saltyskip** [jonkykong/SideMenu#263]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

https://cl.ly/0R0W2m063k27

Xcode 9, ios 11.

Expected behavior is that status bar remains white like previous nav controller

**Comment by jonkykong** [comment]
@saltyskip Please read the README carefully for the property that modifies this behavior.

**Comment by wkwyatt** [comment]
@jonkykong can you please paste the answer from the README here.  I don't see it and I have read it carefully
