### ISSUE TITLE
Property menuPresentMode not accessible in Objective-C anymore 

### ISSUE THREAD

**Issue by herrernst** [jonkykong/SideMenu#265]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

It's not possible to set `menuPresentMode` in Objective-C anymore since a65e26c. 

I think it's because of the removal of the `@objc` attribute for the corresponding enum type here: https://github.com/jonkykong/SideMenu/commit/a65e26cb470939c7ee3e0c0661331c14623aa241#diff-d368002395d8b2848c6e61c50ea8e286L30. Was this change on purpose? If not, would you mind re-adding the `@objc` attribute to the `MenuPresentMode` and probably also to `MenuPushStyle` enum? Thanks!

**Comment by jonkykong** [comment]
Fixed in 3.1.

**Comment by herrernst** [comment]
Thank you very much!

**Comment by slxl** [comment]
am I right that there is no way to use _Code Implementation_ into Obj-C projects (most of properties, incl. menuLeftViewController - are inaccessible from the outside)?

**Comment by jonkykong** [comment]
@slxl the vast majority of functionality was available in Swift 3. Does Swift 4 now require everything to have `@objc` specified?

**Comment by jlubeck** [comment]
I can't access [SideMenuManager default] on objectiveC on the latest build. I had to go back to 3.1.1. Hopefully you'll support this! Thanks!

**Comment by jonkykong** [comment]
See comments on https://github.com/jonkykong/SideMenu/pull/292.
