### ISSUE TITLE
How to set left menu to open top of the center view?

### ISSUE THREAD

**Issue by hemangshah** [jonkykong/SideMenu#267]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
How to make left view open above the center view? Right now when I open the left menu it's under the centered view. Is there a way to set it above the center view so center view looks below the left view?

**Comment by jonkykong** [comment]
It depends on the `menuPushStyle` you use, which are all pre-defined by me. You will have to edit the library to do anything more custom than that.

**Comment by hemangshah** [comment]
I wanted to check whether you have already implemented this or not. Thanks!
