### ISSUE TITLE
How to check if left or right menu is open or close using SideMenu?

### ISSUE THREAD

**Issue by hemangshah** [jonkykong/SideMenu#268]
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I am using SideMenu programmatically. Is there a way to find out whether it's currently open or close?

**Comment by jonkykong** [comment]
Take a look at the demo project.
