### ISSUE TITLE
Push view controller within the menu, instead of the main navigation controller.

### ISSUE THREAD

**Issue by diegomontoyas** [jonkykong/SideMenu#27]
I see the SideMenuNavigationController overrides `pushViewController:animated:` and calls the parent's navigation controller, which is almost always the behavior you want. But what if you want to actually transition within the sidebar itself?

**Comment by jonkykong** [comment]
@diegomontoyas I was shooting for the 80/20 rule with SideMenu and wanted to avoid making it complicated for the average developer, so you are correct in saying it is "almost always the behavior you want."

If you want to deviate from this behavior the solution is still simple: subclass `UISideMenuNavigationController` yourself and override `pushViewController` to not call the parent.

**Comment by diegomontoyas** [comment]
I imagined that. Thanks for the response @jonkykong
