### ISSUE TITLE
Unwanted log message appears after initializing the menu programmatically

### ISSUE THREAD

**Issue by cbrockschmidt** [jonkykong/SideMenu#275]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have implemented SideMenu 3.1 as followed in a clean project, no other changes to `menuLeftNavigationController` made:

``` swift
let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: UIViewController())
SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController
```
When the code is executed, the following log message appears, even though `leftSide` never got modified by the user:

`SideMenu Warning: a menu's leftSide property cannot be changed after it has loaded.`

Can you confirm this issue is not user-code related? I found no way of initializing the side menu programmatically without getting this log message.

**Comment by jonkykong** [comment]
Fixed in 3.1.1.
