### ISSUE TITLE
Different status bar color for SideMenu?

### ISSUE THREAD

**Issue by agordeev** [jonkykong/SideMenu#276]
Is it possible to have a white status bar when SideMenu is presented, but black when it's not? Overriding `preferredStatusBarStyle` for `UISideMenuNavigationController` subclass didn't help me

**Comment by jonkykong** [comment]
@agordeev Yes. There's nothing in SideMenu that's preventing it from happening, so chances are there's something else you're missing to get it working properly. Try researching further or checking on stackoverflow for an answer.

**Comment by nrikiji** [comment]
Setting SideMenuNavigationController#modalPresentationCaptureStatusBarAppearance to true seems to solve the problem.
