### ISSUE TITLE
Visual glitch when sliding to close

### ISSUE THREAD

**Issue by diegomontoyas** [jonkykong/SideMenu#28]
Hi!

There's a visual glitch when you close either one of the side menus by swiping as if you were throwing the menu way. In other words, beginning the swipe and releasing the finger before the menu is fully closed.

**Comment by jonkykong** [comment]
@diegomontoyas can you describe the device and exact steps you would use to reproduce this? Also can you try to describe what the visual glitch is?

**Comment by diegomontoyas** [comment]
Hi @jonkykong It happens in any device, including the simulator. The visual glitch is that the menu seems to "bounce" before closing completely.

**Comment by diegomontoyas** [comment]
I am seeing now that it seems to happen only in the simulator... The visual glitch is that the menu seems to bounce before closing completely. But if it happens in the simulator only it's not a problem really.

**Comment by jonkykong** [comment]
I think I noticed this in the simulator as well. I was testing the app on
my phone and it seems to be fine so if we're in agreement I will close
this.

**Comment by diegomontoyas** [comment]
Sure. No problem. It's strange it only happens on the simulator.
