### ISSUE TITLE
Menu is replacing list page in master detail app (starting with version 3.1.0)

### ISSUE THREAD

**Issue by kamerc** [jonkykong/SideMenu#282]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I have a master detail app that is using SideMenu. It was working great with 3.02 on both the iPad and iPhone ...the side menu would appear to the side of the split screen. However when I updated to 3.1.1 (and I verified it also happens back on 3.1.0), the menu is now completely replacing the list page view. I am seeing this on both the iPhone & iPad. Rather than appearing next to the split screen view, it is now covering it completely. I have attached screenshots to better explain my issue.

I am using the latest XCode & development is Swift 4 & support for iOS11+ only. I have not changed my code except for checking to see if changing all references of SideMenuManager to SideMenuManager.default made a difference.

iPhone with version 3.0.2 (correct view)
![phone-menu-correct](https://user-images.githubusercontent.com/3966567/32011254-3fd0990e-b982-11e7-9adc-ba65dfe82f5e.jpg)

iPad split screen view with version 3.0.2 (correct view)
![ipad-menu-correct](https://user-images.githubusercontent.com/3966567/32011265-4a737912-b982-11e7-9fa3-56dccc568035.jpg)

iPhone with version 3.1.0 & 3.1.1 (incorrect view - menu takes up full screen, completely covering list page)
![phone-menu-incorrect](https://user-images.githubusercontent.com/3966567/32011321-70fc8d9e-b982-11e7-9ee1-1ee308c22961.jpg)

iPad split screen view with version 3.1.0+ & 3.1.1 (incorrect view - menu completely covers list page)
![ipad-menu-incorrect](https://user-images.githubusercontent.com/3966567/32011334-78d23afa-b982-11e7-85a6-9d25e642fd9c.jpg)

**Comment by jonkykong** [comment]
Hi @kamerc, thanks for reporting.

Are you able to provide a sample project or trace through to the problem in SideMenu's code? There was a request for support for `UISplitViewController` probably around the time that you spotted a regression. If you search for `UISplitViewController`in SideMenu's code that's likely to be near the root cause.

All that said, someone else is expecting it to work the way it does currently. Admittedly, it seems odd to me that you would want both a list, and then another list (menu) to pull out from the side of that one.

**Comment by kamerc** [comment]
I've been debugging through this a bit & figured out the fix. Previously my Side Menu Navigation View Controller had a presentation style of "currentContext." If I change it to "fullScreen," it goes back to behaving the way it worked with release 3.0.2. This presentation style didn't matter before but it must matter now since the support for UISplitViewController was added. I will close the ticket, thanks.
