### ISSUE TITLE
Side menu is not getting disabled

### ISSUE THREAD

**Issue by rahulbbit** [jonkykong/SideMenu#283]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Side menu cannot be disabled for particular views.         

> SideMenuManager.default.menuEnableSwipeGestures = false

**Comment by jonkykong** [comment]
Please clarify what you mean by "cannot be disabled for particular views". Do you mean the entire menu cannot be disabled? Just the gestures? Did you read the README regarding `menuEnableSwipeGestures` to understand how it works?
