### ISSUE TITLE
menuEnableSwipeGestures is not working.

### ISSUE THREAD

**Issue by rahulbbit** [jonkykong/SideMenu#284]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

menuEnableSwipeGestures is not working even after declaring it false. still menu is being opened by swipe gesture. Before directly closing the issue, confirm it

**Comment by jonkykong** [comment]
Please read the README carefully:

```swift
/// Enable or disable gestures that would swipe to dismiss the menu. Default is true.
open var menuEnableSwipeGestures: Bool = true
```

**Comment by rahulbbit** [comment]
Take a look at this


![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/11924067/32096749-ff7e057c-bb24-11e7-8bd5-49eb78139981.gif)

**Comment by jonkykong** [comment]
@rahulbbit you aren't reading carefully. The documentation clearly states:

```swift
/// Enable or disable gestures that would swipe to **DISMISS** the menu. Default is true.
open var menuEnableSwipeGestures: Bool = true
```

There are other ways to solve your issue. Please consult the README instead of opening issues.
