### ISSUE TITLE
Warning: Attempt to present 

### ISSUE THREAD

**Issue by mmmcompanies** [jonkykong/SideMenu#288]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

whose view is not in the window hierarchy!

My code is :- 
 let storyboard:UIStoryboard = UIStoryboard(name: "AboutUs", bundle: nil)
                    let becomeGuideVC:UINavigationController = storyboard.instantiateViewController(withIdentifier: "AboutusNav") as! UINavigationController
                    self.present(becomeGuideVC, animated: false)

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com and not an issue specific to SideMenu.
