### ISSUE TITLE
Error! Please, help

### ISSUE THREAD

**Issue by dillidon** [jonkykong/SideMenu#29]
In my project there is following hierarchy:

vc - viewController
nc - navigationController
sm - sideMenu

nc1 - vc1 - ncSM - vcSM - nc2 - vc2 

when call "presentViewController(SideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)" from **vc2**,  there is following error:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <____: 0x7fa0148a7400>

how can I solve the problem?

**Comment by jonkykong** [comment]
@dillidon it's difficult to tell from this what's going on, but that error suggests that you're trying to present a side menu when it's already presented. Make sure you aren't calling present twice in succession.

Feel free to reopen if you're sure you haven't done this - it would be great if you could create a sample project for me to look at to troubleshoot.
