### ISSUE TITLE
Weird Navigation Bar appeared

### ISSUE THREAD

**Issue by keithyeohh** [jonkykong/SideMenu#290]
The navigation bar on SideMenuVC appeared when I tap on the table view cell in SideMenuVC.

Please find the issue from the video link below.
https://drive.google.com/open?id=0B6PyjkS8k4r7VWNTYm5MaUg1V00

**Comment by eciftcioglu** [comment]
I am having a similar issue. When I tap anywhere on the view a navigation bar appears and on the next click it disappears.

**Comment by jonkykong** [comment]
@keithyeohh @eciftcioglu a very quick test of the demo project does not reproduce this problem (something I ask every issue submitter to try). Please investigate further and see if this is something due to your own project code or a SideMenu issue.

**Comment by Salarsoleimani** [comment]
same issue, please help

**Comment by moldis** [comment]
Same issue with me, clicking on any area - appearing navigation bar
