### ISSUE TITLE
Unexpectedly found nil when returning to app

### ISSUE THREAD

**Issue by RamblinWreck77** [jonkykong/SideMenu#293]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello, this is *not* reproducible in the demo project but I think it's something you might want to look at anyways. 

https://imgur.com/a/XPn75

This occurs when the app opens a URL (kicking them out to safari), user interacts with a web page, and then they hit the arrow in the top left sending them back to the app. Would it be possible to handle these unwraps more gracefully?

**Comment by jonkykong** [comment]
This _should_ be reproducible in the app (with a very simple modification) if it's as generic as you describe it. Does this in fact happen? If so, I'd call it a bug.

**Comment by jonkykong** [comment]
I have attempted to reproduce this to no avail.
