### ISSUE TITLE
Side menu takes the whole screen

### ISSUE THREAD

**Issue by minafaw** [jonkykong/SideMenu#294]
in my situation I have 
nav Vc --> Home VC. -->  nav VC --> VC --> SideMenu navigation controller --> menu 
see screen shot 

<img width="656" alt="screen shot 2017-11-12 at 12 25 23 am" src="https://user-images.githubusercontent.com/6320334/32694117-3125ead2-c740-11e7-8c91-9edd27644dc6.png">

in my side menu I have button called Home it should return me to first screen (nav vc --> Home)
when I do that my menu open in full screen

**Comment by jonkykong** [comment]
Please read the README carefully.

**Comment by albanotmakolli** [comment]
@minafaw did you resolve this issue?
