### ISSUE TITLE
Black background on iPhone X status bar

### ISSUE THREAD

**Issue by CaliCastle** [jonkykong/SideMenu#296]
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

My home view:
![simulator screen shot - iphone x - 2017-11-20 at 11 03 57](https://user-images.githubusercontent.com/10830749/33036302-d230a07c-cde2-11e7-9471-95a8201e71cc.png)

After presenting menu:
![simulator screen shot - iphone x - 2017-11-20 at 11 04 01](https://user-images.githubusercontent.com/10830749/33036330-e6374864-cde2-11e7-9061-f1f18bdedc71.png)

As there seems to appear a black background under the status bar in iPhone X which means that the view is only being displayed below the status bar and is there anyway to solve the status bar area from fading out in iPhone X? (Presumably causing because of the safe area insets)

**Comment by jonkykong** [comment]
The example project works as expected on the iPhone X simulator. Please check your configuration and make sure you're following the README carefully.

**Comment by pbrazdil** [comment]
For others, use `SideMenuManager.default.menuFadeStatusBar = false`

**Comment by fraserscottmorrison** [comment]
Thank you @pbrazdil you saved me hours!
