### ISSUE TITLE
viewDidDisappear and viewDidAppear are both called when SideMenu is appeared in ViewController

### ISSUE THREAD

**Issue by yeram0510** [jonkykong/SideMenu#298]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](http://stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
When I present SideMenu in MainViewController, viewDidDisappear and viewDidAppear are both called.
It doesn't happen in 3.0.x version..
![bug](https://user-images.githubusercontent.com/16549266/33355100-5fc4a0f6-d4f9-11e7-9240-251aa50f2c8b.gif)

**Comment by jonkykong** [comment]
This isn't a bug; everything still works as expected. Additionally, a quick debug shows that there's nothing SideMenu is doing that changed this behavior -- it's how the transition APIs work, likely in iOS11 if this wasn't happening before as you say.

**Comment by yeram0510** [comment]
Thanks for your response. But i'm still wondering. Why ViewDidAppear and ViewDidDisappear didn't called at presenting and dismissing menu in older version, and why these events are called in latest version? Can you give some hint?

**Comment by jonkykong** [comment]
@yeram0510 I honestly don't have the answer for you. If you put a breakpoint in and trace the call stack, SideMenu code isn't called.

**Comment by yeram0510** [comment]
@jonkykong I think I found a solution. If I add `modalPresentationStyle = .overFullScreen` to `awakeFromNib()` in `UISideMenuNavigationController` like in SideMenu version 3.0.2, the ViewDidAppear and ViewDidDisappear will not be called in `MainViewController`. Is there a reason why you deleted `modalPresentationStyle = .overFullScreen` in latest version?

**Comment by jonkykong** [comment]
@yeram0510 it was redundant as I set the `modalPresentationStyle` in `SideMenuManager` instead.

It doesn't make sense that setting the transition style in awakeFromNib would cause any change in behavior in the appearance methods being called, since in either place it's set it occurs well before any of the appearance methods should be called.

**Comment by dungkv95** [comment]
@yeram0510 please dismiss SideMenu before you push or present to a new viewcontroller 👍
