### ISSUE TITLE
Dismissing SideMenu calls viewWillAppear and other appearance functions

### ISSUE THREAD

**Issue by erencelik** [jonkykong/SideMenu#299]
When I open SideMenu by swipe (gesture) there is no problem, but if I open it programmatically;
`self.present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)`
when I dismiss the menu by tap or gesture, presented controllers appearance methods getting called. This issue shows up after I upgraded library to last version.

**Comment by jonkykong** [comment]
https://github.com/jonkykong/SideMenu/issues/298
