### ISSUE TITLE
Unable to present a View Controller from Side Menu

### ISSUE THREAD

**Issue by iamchingel** [jonkykong/SideMenu#300]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have a static table view controller as my side menu. There is a logout option in the tableview. The code for the logout is as follows : 
```
// logout of firebase ...
let controller = self.storyboard?.instantiateViewController(withIdentifier: "LoginVC") as! LoginViewController
self.present(controller, animated: true, completion : nil)
```
This leads to a crash with error : "Application trued to present modally an active controller"

I tried to solve this on my own...and ended up writing something like this  : 
```
//logout of firebase..
dismiss(animated: true) {
let controller = self.storyboard?.instantiateViewController(withIdentifier: "LoginVC") as! LoginViewController
self.present(controller, animated: true, completion : nil)
}
```
This led to a warning: "Attempt to present LoginViewController on SideMenuTableViewController whose view is not in the window hierarchy"

Please tell me a way to fix either of problems. I am new to iOS and even newer to Github...Please be kind enough to explain the solution.

Thank you!

P.S.  - dismiss(animated: false) leads to a black screen.

**Comment by jonkykong** [comment]
@iamchingel while I appreciate your honesty as being a new developer, I get too many requests for help here and it takes time out of my day. This is a question better suited for stackoverflow.com.

**Comment by iamchingel** [comment]
Ok Sir, 
I was actually able to logout from side menu....I think there is some issue with SIdeMenu, 
```
dismiss(animated: false, completion : nil)
```
leads to a black screen...

**Comment by jonkykong** [comment]
I have verified it works as expected in the demo project. This is most likely a bug in your code, not SideMenu.

**Comment by SasanSoroush** [comment]
presenting from side menu is buggy sometimes it happens sometimes not and sometimes with a delay

**Comment by paulopio** [comment]
> presenting from side menu is buggy sometimes it happens sometimes not and sometimes with a delay

Please refer to this link on [stackoverflow](https://bit.ly/3bL1t6q).  I don't know how often this happens, but for me was when I use mvvm pattern. In mvc pattern was ok.
