### ISSUE TITLE
Going back to previous screen

### ISSUE THREAD

**Issue by atalayasa** [jonkykong/SideMenu#302]
Hello I have been using that library and every page has that side menu and every page has two buttons  forward and back. When user pressed forward following code is running.

```
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            var destinationVC:UIViewController!
            destinationVC = storyboard.instantiateViewController(withIdentifier: "SecondVC") as! SecondVC
            sideMenuController()?.setContentViewController(destinationVC)
            hideSideMenuView()
```
Is it proper usage or is it wrong because I have 20 pages and in every page I need to implement that code. 
Also, when user pressed previous button it should go back I am trying to use 
navigationController?.popToRootViewController(animated: true) code but it is not working. What is the problem with it. Thanks in advance.

**Comment by jonkykong** [comment]
I wrote a detailed README that explains everything.
