### ISSUE TITLE
When I use menuPushStyle .replace, I cannot go back to MainViewController.

### ISSUE THREAD

**Issue by anelad** [jonkykong/SideMenu#303]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
(Note: This issue description is based on Example Project)
### Description
When I use `menuPushStyle = .replace` I cannot go back to MainViewController.

### Reproduce : 
1. Add below line into `setupSideMenu()`method in **MainViewContoller.swift** file:
`SideMenuManager.default.menuPushStyle = .replace`
2. Run the Exmple project on any device.
3. Open left side menu.
4. Tap on any item inside the left menu.
5. Now you cannot go back to `MainViewController` whatever you do.

### Current Workaround That I Use:
1. Adding a new cell in the `SideMenuTableViewController` at left.
2. Creating a push segue from the new cell to `MainViewController`

### Question:
1. Is this a bug or an expected behavior?
2. If it is an expected behavior; can you explain why and explain the right way to get MainViewController back or verify my current workaround is the right way?
3. If it is a bug, is there any workaround that I can use until the bug is resolved?

**Comment by jonkykong** [comment]
@anelad This is expected of `menuPushStyle = .replace`. Please follow the README carefully.
