### ISSUE TITLE
Rare crash that only occurs in prod

### ISSUE THREAD

**Issue by RamblinWreck77** [jonkykong/SideMenu#304]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [?] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

While I can't reproduce this in any of my dev/test environments, once ~10k people or so have used the latest patch this issue crops up again at a rate of 1-2 crashes a day. My current theory is it seems to be related to launching the app from a push notification, and sometimes these force-unwraps fail:

```
menuView?.frame.origin.x = presentDirection == .left ? -menuView!.frame.width : mainView!.frame.width
```

Any thoughts?

**Comment by jonkykong** [comment]
@RamblinWreck77 That specific line of code is not the source of a problem. If `menuView` is `nil` on the left hand side of the `=`, then the right hand side will never be evaluated.

Please post the call-stack of the crash. I will reopen this if necessary.
