### ISSUE TITLE
Replace center controller when side menu clicked

### ISSUE THREAD

**Issue by Shamsiddin** [jonkykong/SideMenu#305]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How do I change the center view controller depending on cell selection from side menu?
In the documentation I couldn't find the solution for this problem, I see always one controller persists in the center, and I'm not able to replace it with another controller (when another cell clicked from side menu table)

**Comment by jonkykong** [comment]
It's covered in the README.

**Comment by stefgeelen** [comment]
I don't see where this is covered in the README without a storyboard implementation ?

**Comment by jonkykong** [comment]
Please read carefully.

https://github.com/jonkykong/SideMenu#code-implementation

**Comment by stefgeelen** [comment]
Don't really get it. When You push on menuLeftNavigationController it changes the center viewController?

**Comment by BhavinBhadani** [comment]
@stefgeelen got anything?

**Comment by shivali-triffort** [comment]
Very poorly written controller options.

**Comment by jonkykong** [comment]
@shivali-triffort if you can't be constructive, please write your own code or use a different repository.

What you're asking for is **not** something not specific to SideMenu. It is general coding you have to figure out how to write on your own, the same way you would if you were not using SideMenu at all:

1. Write a menu view controller.
2. Write a delegate protocol for that view controller that notifies its delegate when a menu item is tapped.
3. Have the view controller that presents the menu view controller set itself as the delegate so that when it gets notified it can push the appropriate screen.

There are other ways you can solve it, but that one is top of mind.

**Comment by KoD4K** [comment]
Is someone understand this answer?

How I understand this:
You have CenterViewController which create and can open MenuViewController. Something like this
`let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: menuController)
SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController`

After that you can open menu like this
`present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)`

But if you want to change CenterViewController to an other one you create CenterViewControllerDelegate which implements method like this:
`func openAccountScreen() {
        if let controller = AccountViewController.storyboardInstance() {
            navigationController?.pushViewController(controller, animated: true)
        }
    }`
And after choose item Account in MenuViewController you need to do this:
`delegate?.openAccountScreen()`

If I am right this construction is not work! And it's awful! 

Is someone have an other solution for this problem? Thank you in advance!
