### ISSUE TITLE
How to use .viewSlideOut and scale down the main view on top of the menu

### ISSUE THREAD

**Issue by stancho-dynoden** [jonkykong/SideMenu#308]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello guys, I really enjoy using your menu, and I wanted to ask you a question in regards to an implementation I would like to do.
I have tried to create a menu like on the image below
![simulator screen shot - iphone 8 - 2018-01-08 at 12 54 42](https://user-images.githubusercontent.com/21221924/34671946-7635a53e-f474-11e7-80d1-8b13bd0c0468.png)

where the main view will shrink and go to the right, I only manage to do it after changing a few lines in your code, so I was thinking to ask you if that is possible without changing your code. Is there an option that I missed so I can achieve this effect?

Many thanks!

Stan

**Comment by stancho-dynoden** [comment]
Or perhaps I can change your code and upload this new transition if there is no way doing that with the current version

**Comment by jonkykong** [comment]
This is possible with the library as-is without modifying the source. Please read the README carefully.
