### ISSUE TITLE
Present menu over the current view

### ISSUE THREAD

**Issue by nikeshakya** [jonkykong/SideMenu#309]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
 
I am using latest SideMenu library and I have this issue 
I want menu to appear from left with slideIn behavior..
but I don't want my main view to be pushed to the right...Is there any way to present menu view on top of the main view so that main view doesn't get pushed away?

**Comment by jonkykong** [comment]
Please read the README carefully.

**Comment by nikeshakya** [comment]
@jonkykong where is it mentioned about presenting side menu bar over the navigation view controller when presentation style is slideIn ? 
I don't see it in read me...
could you please help me
thanks
