### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by NuelNikhil** [jonkykong/SideMenu#31]
I have successfully implemented SideMenu by following the steps in the GitHub page.  It's Working fine. But amGetting this error right now. So When It occurred... 

I have Different items to display in my Menu list like , Home , Profile , Log Out etc..
for that I am using different cells and created  segue's from each cell . The First Screen to Display when i run the project is  the Home Screen. Then using a Button or gesture I revealed the SideMenu and from the Items in the Menu when I click on the Cell which Navigates back to home I get the error mentioned in the title inside the function **hideMenuStart** at this line 
 `let mainViewController = SideMenuTransition.viewControllerForPresentedMenu!` ... How to fix this.. I am new to iOS...

**Comment by jonkykong** [comment]
Please run `pod update` from the directory containing your .podspec file. This error will be handled in the latest version of SideMenu, which is currently 1.1.7.

The root of your problem is that you are attempting to change the SideMenu while it is actively presented. You should only be setting the SideMenus once, and that code should not be called again.

**Comment by NuelNikhil** [comment]
okay @jonkykong Thank you... let me update it to the new version... and that was a quick response ... :)

**Comment by NuelNikhil** [comment]
one doubt... @jonkykong You mentioned about calling a method once... Did you meanSetting SideMenu once... if so Should I call it in Applegate file ???

**Comment by jonkykong** [comment]
You can call it in the AppDelegate, or inside `viewDidLoad` of your initial screen. In most cases `viewDidLoad` won't be called again, but that can depend on how your app is built.

**Comment by NuelNikhil** [comment]
Again ... that was a fast response and to the matter if I Called it in the initial Screen will it work with the other screens too ??? I mean I got a few items in the menu like Home , Profile  , LogOut etc let's say Home Screen is the Initial Screen from which we calls the Sidemen and the Menu is Shown... I need to navigate to profile Screen from the SideMenu and I need the Profile Screen too to have the SideMenu Functionality...  Can I get the Functionality in every Screen if I called it in the Initial Screen ??? Or Should I Call it i the AppDelegate file ??? :)

**Comment by jonkykong** [comment]
It's designed to be setup once for all screens. I'd suggest you try playing around with it to see what you can get working.

**Comment by NuelNikhil** [comment]
👍 let me try ...

**Comment by NuelNikhil** [comment]
Somehow managed to make things work.... Closing this... 👍

**Comment by NuelNikhil** [comment]
@jonkykong  May I know Why this message in the console  **"SideMenu Warning: menuLeftNavigationController cannot be modified while it's presented."**

**Comment by jonkykong** [comment]
Because you're attempting to change the side menu while it's presented. Put a breakpoint in where you set the side menu to figure out when it's getting set again.

**Comment by NuelNikhil** [comment]
Sure....

**Comment by agravatvivek** [comment]
Do I need to set the menu in all ViewControllers using **segue** or there is any other way to perform it ?
![screen shot 2016-08-30 at 6 47 30 pm](https://cloud.githubusercontent.com/assets/21011903/18090417/458c1aa8-6ee2-11e6-8cf9-8bb9f6276548.png)
