### ISSUE TITLE
SideMenu Warning: menuRightNavigationController cannot be modified while it's presented.

### ISSUE THREAD

**Issue by smiteshwadher** [jonkykong/SideMenu#310]
func setupNavigationBarItems()
    {
        setupSideMenu()
        setupRightNavigationItems()
        setupLeftNavigationItems()
        
        navigationController?.navigationBar.backgroundColor = .black
        navigationController?.navigationBar.isTranslucent = false
        navigationController?.navigationBar.barTintColor = UIColor(red: 0, green: 0/255, blue: 0/255, alpha: 1)
    }
    
    func setupSideMenu()
    {
        SideMenuManager.menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? UISideMenuNavigationController
    }
    
    private func setupRightNavigationItems()
    {
        let menuButton = UIButton(type: .system)
        menuButton.setImage(#imageLiteral(resourceName: "menu-button-of-three-lines-outline (3)").withRenderingMode(.alwaysOriginal),for:.normal)
        menuButton.contentMode = .scaleAspectFit
        menuButton.frame = CGRect(x:0,y:0,width:25,height:25)
        
        menuButton.addTarget(self, action: #selector(menuButtonClicked), for: UIControlEvents.touchUpInside)
        
        navigationItem.rightBarButtonItem = UIBarButtonItem(customView:menuButton)
    }
    
    func menuButtonClicked()
    {
        let storyBoard : UIStoryboard = UIStoryboard(name: "Main", bundle:nil)
        let nextViewController = storyBoard.instantiateViewController(withIdentifier: "UISideMenuNavigationController")
        self.present(nextViewController, animated:true, completion:nil)
    }
    
    private func setupLeftNavigationItems()
    {
        let qwikLogoButton = UIButton(type:.system)
        qwikLogoButton.setImage(#imageLiteral(resourceName: "qwik_white.png").withRenderingMode(.alwaysOriginal),for:.normal)
        qwikLogoButton.contentMode = .scaleAspectFit
        qwikLogoButton.frame = CGRect(x:0,y:0,width:25,height:25)
        
        navigationItem.leftBarButtonItem = UIBarButtonItem(customView:qwikLogoButton)
    }
}

This is the code i m following please help as this warning could not be solved searched a lot.

**Comment by smiteshwadher** [comment]
The function setupNavigationBarItems is called on the home page viewDidLoad: what is the mistake please help !.

**Comment by jonkykong** [comment]
The error is self-explanatory. Do not change the menu while it is in the view hierarchy. It must be dismissed first.

**Comment by smiteshwadher** [comment]
how to dismiss ?.

**Comment by jonkykong** [comment]
Please read the README.
