### ISSUE TITLE
menuFadeStatusBar = false not work

### ISSUE THREAD

**Issue by satoshinosekai** [jonkykong/SideMenu#315]
I use the below code to change status bar color,

extension UIApplication {
    var statusBarView: UIView? {
        return value(forKey: "statusBar") as? UIView
    }
}
UIApplication.shared.statusBarView?.backgroundColor = UIColor.colorPrimaryDark

then i used

SideMenuManager.default.menuFadeStatusBar = false

result
[Image](http://poipoi251.myqnapcloud.com/temp/1b5a1e0c-7f40-4a81-8e51-9f86584c8ae1.jpg)

it's not work, how can i fix it?

thx~ :)

**Comment by jonkykong** [comment]
It works exactly as expected. Please follow the README carefully.

**Comment by Bat-Orshikh** [comment]
How can I set false value from the storyboard implementation?
