### ISSUE TITLE
Type 'SideMenuManager' has no member 'default'

### ISSUE THREAD

**Issue by alqaimsolutions5** [jonkykong/SideMenu#317]
In this line of code
`SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController`
I get the following error:
Type 'SideMenuManager' has no member 'default'

**Comment by jonkykong** [comment]
You're the only person to report this issue; chances are there's something you're doing wrong. I'd suggest making sure you have the latest code or try setting up in a new project to see if it keeps happening.
