### ISSUE TITLE
How to navigate through side menu?

### ISSUE THREAD

**Issue by ysfz** [jonkykong/SideMenu#318]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How should I implement navigation through buttons of Side Menu? For example, I have the same side menu displaying in 5 diffrent tabs and I want to navigate to some ViewController when I tap on button in Side Menu. Segue is not working inside the menu.

**Comment by jonkykong** [comment]
Everything is explained in the README.
