### ISSUE TITLE
how to open this side menu when the button click programmatically in Swift..

### ISSUE THREAD

**Issue by HariNarayanan777** [jonkykong/SideMenu#319]
I need to open this side menu when the button click in the , i tried so much of way to open this side menu. but now one should open this please tell if is there any one of the way to open the side menu programmatically in swift.

## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
Please read the README.

**Comment by HariNarayanan777** [comment]
i read it fully, i cannot understand, for example i have a custom leftBarButtonItem and add a target for this button , inside of the target button function how to open the SideMenuManager.?


let button1 = UIButton(frame: CGRect(x: 0, y: 0, width: 30, height: 30))
     button1.addTarget(self, action: #selector(menu_btn_selector), for: .touchUpInside)
self.navigationItem.leftBarButtonItem = UIBarButtonItem(customView: viewFN)

// Function called
@objc func menu_btn_selector(){
        print("left nav item select and tell how i should open the side menu programmatically")
    }

Normally the pan gesture was opened to view. but how i should open the side menu programmatically when the button clicked. please tell me ,

**Comment by DenisSamokhin** [comment]
@HariNarayanan777 you have to present your UISideMenuNavigationController programmatically.
`let sideMenuNC = self.storyboard?.instantiateViewController(withIdentifier: <Storyboard id of UISideMenuNavigationController>)
  self.present(sideMenuNC!, animated: true, completion: nil)`

**Comment by HariNarayanan777** [comment]
Super awesome its working...
