### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions for

### ISSUE THREAD

**Issue by hr147** [jonkykong/SideMenu#321]
I have created Tabbar Controller and it is not rooted with any NavigationController 

when i select any controller from sidebar then selected controller is pushed on Selected Tab Controller but i got "Unbalanced calls to begin/end appearance transitions for" in xcode logger

**Comment by jonkykong** [comment]
You're the first to report this. Chances are you're doing something wrong with your code in general and not specific to SideMenu. You need to provide a lot more detail about what's going on to further diagnose.
