### ISSUE TITLE
It it possible to make shadow effect outside the  menu. 

### ISSUE THREAD

**Issue by joyalserrao** [jonkykong/SideMenu#325]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I tried many ways, but unable to  shadow & opacity outside the menu .Please tell me any possibility of adding blur or  shadow & opacity to out side menu .

**Comment by jonkykong** [comment]
@joyalserrao this is a question for Stackoverflow.com.

**Comment by joyalserrao** [comment]
@jonkykong Thanks for the responses. Its not only menu, After present Sidemenu,  Outside view  make blur. 
If we apply  shadow and radius = 50, it will effect inside the Menu. but Is it possible to make outside the menu ???

**Comment by umair151** [comment]
I couldn't find the solution on stackoverflow. Can you please help on this?
