### ISSUE TITLE
Grey Bar Side?

### ISSUE THREAD

**Issue by furkankadioglu** [jonkykong/SideMenu#326]
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
![screen shot 2018-02-04 at 23 01 18](https://user-images.githubusercontent.com/5060068/35781793-cc96b896-09ff-11e8-983e-28bf74a04d0f.png)

Hello, How can i remove or change grey area in the navigation menu bar?

**Comment by jonkykong** [comment]
This is a question for Stackoverflow.com.

**Comment by furkankadioglu** [comment]
https://stackoverflow.com/questions/48612686/how-to-remove-the-navigation-controller-grey-bar

**Comment by furkankadioglu** [comment]
@jonkykong Can you answer my question please?
