### ISSUE TITLE
Gray Bar Problem

### ISSUE THREAD

**Issue by furkankadioglu** [jonkykong/SideMenu#327]
Hello,

I created an issue here and you closed my issue but i did not solved. Yes it is stackoverflow question, i sent to you stackoverflow link. It is an issue, not a question. It is not navigation bar, i think it is a bug please examine it, how can i remove this gray bar?

![screen shot 2018-02-04 at 23 01 18](https://user-images.githubusercontent.com/5060068/35815890-999c5440-0aaa-11e8-8dea-9201a24dc1e4.png)

Stackoverflow link: https://stackoverflow.com/questions/48612686/how-to-remove-the-navigation-controller-gray-bar/48617936#48617936

**Comment by jonkykong** [comment]
This is a navigation bar. If it's not a navigation bar, it's something else strange you've done. No one else is reporting this problem with the library. I have not had this problem with the library. It does not happen in the demo project. Please resolve it using general support forums.
