### ISSUE TITLE
SideMenuViewController cell data is not shown in iPad when we use custom type cell.Is it cumpolsory to use static cell.

### ISSUE THREAD

**Issue by ShubhGar** [jonkykong/SideMenu#328]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by ShubhGar** [comment]
I want to contribute in the library and also want to know, is it work only static table view and cell

**Comment by jonkykong** [comment]
There is no limitation with static cells. You have a bug somewhere else you need to investigate. This is not a SideMenu issue.

**Comment by ShubhGar** [comment]
After investigation i raise a bug it work fine in iPhone but not in iPad.In iPad its  load all custom cells but did not show data of cells else when i create basic cell its work fine
