### ISSUE TITLE
Proper way to push view controller

### ISSUE THREAD

**Issue by MEnnabah** [jonkykong/SideMenu#329]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have a `MainViewController` with a `LeftSideMenuTableViewController` that is setup like this:

```     
// HomeViewController - viewDidLoad()   
let sideMenuViewController = LeftSideMenuTableViewController()
let sideMenuNavigationController = UISideMenuNavigationController(rootViewController: sideMenuViewController)
sideMenuViewController.delegate = self
SideMenuManager.default.menuLeftNavigationController = sideMenuNavigationController
SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.view)
SideMenuManager.default.menuFadeStatusBar = false
SideMenuManager.default.menuPushStyle = .subMenu
```

The side menu works perfectly fine.

However, in the side menu, I have 2 cells that should present 2 `ViewController`s.

I tried to implement `didSelectRow` to present the desired ViewController, but it was presented on the side menu only with the side menu side, which makes a lot of sense.

The other option I tried to do is setup a delegate method to the `MainViewController` and it handles all the work of pushing a new view controller. And it failed with error:
```
Warning: Attempt to present <PresentedViewController: 0x108b2bdc0>  on <HomeViewController: 0x10600d600> which is already presenting <SideMenu.UISideMenuNavigationController: 0x10682d800>
```

I am running iOS 11.2.5

**Comment by jonkykong** [comment]
@MEnnabah you have not stated what the actual problem is. You must state the expected result as well as the actual result.

SideMenu `presents` all screens from itself. You cannot present any controller from a screen that is not at the top of the view hierarchy (as required by Apple). You visually have SideMenu dismiss, but it will still remain in the hierarchy.
