### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value rotating device

### ISSUE THREAD

**Issue by alexxover** [jonkykong/SideMenu#33]
Hi, 
i'm very glad to use SideMenu, it looks fantastic!

During testing of my app, the line in presentMenuStart func:
let mainViewController = SideMenuTransition.viewControllerForPresentedMenu!

Cause an EXC_BAD_INSTRUCTION error when i rotate the device. Looking at issues, i tried to update pod and to init menu in AppDelegate without solving the problem.

Thanks

**Comment by jonkykong** [comment]
@alexxover you'll need to provide more info more me to troubleshoot. 
- Is the menu displayed when you rotate?
- are you calling any SideMenu code when you rotate?
- what device is this?
- can you repro this on a blank project? If so, can you share that project with me?

I'll reopen this pending your feedback.
