### ISSUE TITLE
viewWillAppear() from presenting ViewController getting called after segue

### ISSUE THREAD

**Issue by NickSet** [jonkykong/SideMenu#330]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

In the demo project, MainViewController's viewWillAppear() is getting called after both the Left/Right Menu triggered segues. Although it does happen when clicking the bar buttons, swiping does not result in an extra call to viewWillAppear().

This can be repeated by adding `print("viewWillAppear")` to `MainViewController.viewWillAppear()` which results in:
```
SideMenu Appearing! (animated: true)
SideMenu Appeared! (animated: true)
viewWillAppear()
SideMenu Disappearing! (animated: true)
viewWillAppear()
SideMenu Disappeared! (animated: true)
```
appearing in the console after opening the side menu from a bar button and then closing it.

In my own app, I'm using an ARSCNView which is resulting in a black screen flash after the extra `viewWillAppear()` call.

I've been looking into what's causing it by following the call stack, but I can't seem to pinpoint it. Any guidance or help would be appreciated.

**Comment by jonkykong** [comment]
@NickSet as far as I know, it's the result of the Apple APIs that govern custom transitions OR adding/removing view controllers to the view hierarchy. Your best bet is to inspect `presentedViewController` in the appearance methods or use the delegate methods to get the desired results.
