### ISSUE TITLE
Problem with the selection of tableview item

### ISSUE THREAD

**Issue by mrJ0hn** [jonkykong/SideMenu#331]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/22646611/36379583-39c36978-1590-11e8-85d6-e54e779dbca0.gif)

Hello! Please help me. I have problem: if I do starting to swipe side menu, table view item don't react on tap in first time

**Comment by jonkykong** [comment]
@mrJ0hn:

1. You have clearly modified the example project.
2. You have provided no detail to how you have changed it, how you got into a bad state, or steps you've taken to try and investigate/resolve the problem.
3. It's possible your simulator is in a bad state.
4. My example project works as expected.
5. You are the only person reporting this problem, which likely means you've done something that broke the project.

Please follow-up with relevant information for additional support.

**Comment by mrJ0hn** [comment]
I didn't change your example. The issue play on emulator and device (iphone
6). Could you check this problem?

2018-02-19 22:45 GMT+03:00 Jon Kent <notifications@github.com>:

**Comment by jonkykong** [comment]
You have modified the project because there is an indicator on the second item and the demo project has none.

Again, the example project works as expected, even on the iPhone 6 simulator.

**Comment by mrJ0hn** [comment]
Sorry but I don't understand what's happening. I just download your project
now . And I reproduced the issue

2018-02-20 9:43 GMT+03:00 Jon Kent <notifications@github.com>:

**Comment by mrJ0hn** [comment]
I'll record the video for you late

2018-02-20 9:54 GMT+03:00 Евгений Суханов <sukhanovevgeniy96@gmail.com>:

**Comment by jonkykong** [comment]
@mrJ0hn please investigate the issue further to see if you can identify the underlying issue. What version of iOS?

**Comment by mrJ0hn** [comment]
ios 11.2 (simulator) ios 11.2.5 device

2018-02-20 10:40 GMT+03:00 Jon Kent <notifications@github.com>:

**Comment by mrJ0hn** [comment]
​
 Example.mov
<https://drive.google.com/file/d/1Eob8Tb2xTDtddiYEqEX144Eyi_1kneXu/view?usp=drive_web>
​

2018-02-20 11:27 GMT+03:00 Евгений Суханов <sukhanovevgeniy96@gmail.com>:

**Comment by mrJ0hn** [comment]
I hope you'll help me!

2018-02-20 11:52 GMT+03:00 Евгений Суханов <sukhanovevgeniy96@gmail.com>:

**Comment by jonkykong** [comment]
@mrJ0hn okay, then I don't have an answer for you, everything is fine. You'll need to investigate on your own. Try redownloading the code and starting over.

**Comment by mrJ0hn** [comment]
Did you look at my video? Could you comment it?

2018-02-20 11:58 GMT+03:00 Jon Kent <notifications@github.com>:

**Comment by jonkykong** [comment]
Now you have provided enough detail. I'll prepare a fix when I find time.

**Comment by mrJ0hn** [comment]
many thanks! I greatly appreciate you

2018-02-20 13:40 GMT+03:00 Jon Kent <notifications@github.com>:

**Comment by atalayasa** [comment]
Did you find a solution about how this works when didSelect function worked? @mrJ0hn

**Comment by jonkykong** [comment]
Following back up on this... is this still going on? If so, it would be immensely helpful if someone could provide a copy of the demo project modified to reproduce this issue.

**Comment by javmorales** [comment]
i have the same error, Any solution?
