### ISSUE TITLE
SideMenu Warning: menuLeftNavigationController cannot be modified while it's presented. Happening in storyboard integration

### ISSUE THREAD

**Issue by jeslinj** [jonkykong/SideMenu#332]
![img_0055](https://user-images.githubusercontent.com/35517439/36470245-2f6fc1b6-1710-11e8-98fd-d6dade9a08b5.PNG)
![img_0056](https://user-images.githubusercontent.com/35517439/36470251-33cd8fe0-1710-11e8-8d58-993f4d712647.PNG)

## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

First of all thanks for giving me a wonderful library. 

I integrated SideMenu via storyboard. And everything works fine unless I logout and come back to my HomeVC having SideMenu. 

My flow is like this LoginVC(This doesn't have SideMenu) -> HomeVC(with SideMenu).

Problem is when I go back to login screen -> login and I set HomeVC as rootvc to UINavigationController. 

I am getting a log message "SideMenu Warning: menuLeftNavigationController cannot be modified while it's presented." and presenting the sidemenu in fullscreen instead of part of a screen width. 

This will not happen if I relaunch the app. I think I am showing the sidemenu again and again. 

Is there anyway to remove the sidemenu from my view hierarchy when I do logout? Or is there any other workaround?

**Comment by jonkykong** [comment]
SideMenu is a view controller like any other view controller, and as such you cannot remove it from the hierarchy while something is presented over top of it. Consider reworking your hierarchy to a flow supports your goals.

**Comment by jeslinj** [comment]
Sorry. It was my mistake. I should have dismissed the sidemenu before presenting the login vc. 

dismiss(animated: true, completion: {
   //code to logout
}

fixed my issue.

**Comment by gkhanacer** [comment]
Hi, I have same problem, but it couldn't solve @jeslinj @jonkykong . I'm using Xcode 10 and SlideMenu 5.0.1.
