### ISSUE TITLE
How can I show the custom view in the center of the screen after side menu is opened?

### ISSUE THREAD

**Issue by mob-rockstar** [jonkykong/SideMenu#333]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have implemented this SideMenu in my iPad app. I have set  the present mode as SideInOut as followings:
`SideMenuManager.default.menuPresentMode = .viewSlideInOut`
When I tap the cell item in side menu, I am going to display the MBProgressHUD in center of the iPad screen.
So I have set the view as followings:
`let view = sideMenu.view`
`let loadingHud = MBProgressHUD.showAdded(to: view, animated: true)`
As a result, the MBProgressHud is displayed in left side of the screen because the side menu is placed in the left side.

I am not sure how can I set the view to be showed  the progressHud.
Let me know the solution
Thanks
![simulator screen shot - ipad pro 9 7-inch - 2018-02-24 at 14 09 00](https://user-images.githubusercontent.com/16888110/36629807-590fe0e2-196c-11e8-9bec-badc7660d64f.png)

**Comment by jonkykong** [comment]
It's up to you to find the solution. SideMenu is not guaranteed to work with every other library.

**Comment by mob-rockstar** [comment]
If I am going to show the ViewController as modally in the center of the screen, how can I get the container view after side menu is opend?

**Comment by mob-rockstar** [comment]
I noticed that you app is not working whenever change the orientation.
![simulator screen shot - ipad pro 9 7-inch - 2018-02-26 at 16 04 59](https://user-images.githubusercontent.com/16888110/36672013-d1aa31e4-1b0e-11e8-8a8f-9e0cda37261a.png)

**Comment by jonkykong** [comment]
It works as expected with the Example project.
