### ISSUE TITLE
How to set Rootviewcontroller Programmatically 

### ISSUE THREAD

**Issue by tushar666** [jonkykong/SideMenu#334]
Hi,

First of all the Lib is Awesome @jonkykong 

When a user tap on any of  the left menu item, what code/inline should be written within 
`didSelectRowAtIndexPath`

Or Either any below, and how the menu will be set in that case.
- Push
- SetRoot
- Present

**Comment by jonkykong** [comment]
@tushar666 https://github.com/jonkykong/SideMenu#code-implementation
