### ISSUE TITLE
problem when change locale

### ISSUE THREAD

**Issue by maebrahimi** [jonkykong/SideMenu#335]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When I change locale, Instead of opened from left to right, It open up from the bottom up.
and print log -> 'SideMenu Warning: menuLeftNavigationController cannot be modified while it's presented.'
What is the problem?

**Comment by jonkykong** [comment]
Please follow the README carefully.

**Comment by maebrahimi** [comment]
I read the document well, but I did not notice the problem.

**Comment by jonkykong** [comment]
This is not a problem in the demo project. You've missed a step in the README.

**Comment by maebrahimi** [comment]
It works normally right. Only when change locale, opens the menu from bottom to top

**Comment by jonkykong** [comment]
If you can make minimal changes to the Example project that demonstrate this is a true bug in SideMenu and share that modified project, I'll take a look.

**Comment by maebrahimi** [comment]
[SideMenu-master 2.zip](https://github.com/jonkykong/SideMenu/files/1776663/SideMenu-master.2.zip)

I made changes to the example file
The project is attached

**Comment by jonkykong** [comment]
What are the steps to demonstrate the problem?

**Comment by jonkykong** [comment]
This is not an issue with SideMenu.

You're asking me to support a locale switcher library. SideMenu is not guaranteed to work with other libraries.

The locale switcher that reloads the application is strange and not properly releasing the view controllers in the stack, which is why you are getting the error message.

**Comment by maebrahimi** [comment]
There is no problem if we put locale change button on the home screen
It only creates a problem when put locale change button on the menu
So the problem is custom locale lib?

**Comment by jonkykong** [comment]
@maebrahimi you need to investigate this further on your own to find out what the source of the problem is.

**Comment by maebrahimi** [comment]
Thank you for the help me

**Comment by jonkykong** [comment]
You're changing the app's root view controller. Read up and make sure you understand what's going on there.
