### ISSUE TITLE
Using on iPhone X black space on top.

### ISSUE THREAD

**Issue by thunpisit** [jonkykong/SideMenu#337]
## Issue Description

 
Helllo, When I implement it with iPhone X the moment I click it cut the top part out and left it black instead of full screen. Do you have any suggestion how to fix it? Thanks!

![img_4260](https://user-images.githubusercontent.com/3394671/37138324-4d4868ea-226f-11e8-9d65-1d87f9c40bb4.PNG)

![img_4261](https://user-images.githubusercontent.com/3394671/37138436-a78fbb8c-226f-11e8-8e5f-5298db329307.PNG)

**Comment by jonkykong** [comment]
Please read the README carefully.
