### ISSUE TITLE
Disable tap outside dismissal 

### ISSUE THREAD

**Issue by staticdreams** [jonkykong/SideMenu#340]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I haven't found this in the documentation, but is there away to prevent dismissing the SideMenu when user taps outside? I don't want it to be closed by accident. I only want it to be dismissed by explicitly calling a dismiss action.

**Comment by jonkykong** [comment]
Try `menuPresentingViewControllerUserInteractionEnabled`.
