### ISSUE TITLE
Navigate from menu guide?

### ISSUE THREAD

**Issue by BhavinBhadani** [jonkykong/SideMenu#341]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have 2 issues 

1. How to navigate from side menu and click on table cell to move other controllers with code only and toggl to open menu?
2. How to use with 2+ storyboards? (If I have a one storyboard that declares side menu, 2nd for home , 3rd for other then how to mange all?)

I tried to change root view but it crashed same as [#251](https://github.com/jonkykong/SideMenu/issues/251)

**Comment by jonkykong** [comment]
There's a very high chance that your problems have nothing to do with SideMenu but instead the code you've written. Please investigate further into how to use multiple storyboards and read the README thoroughly.

**Comment by BhavinBhadani** [comment]
ohhh come on.. then tell me how to toggle menu .. simple thing with the code as present always gives an error like already presented menu.

I appreciate your work towards this sidemnu but U r always in hurry to closing an issue and same answer always check your code and readme and people cant get enough help. We just ask u because u created it so u have better knowledge of where and what to do but you are always not willing to help others and make sure u close the issue without investigating.

**Comment by jonkykong** [comment]
That’s not a bug with SideMenu. That is a common developer problem. You can
figure it out.

**Comment by BhavinBhadani** [comment]
Ok thanks. Its ur choice to help or not. I'll figure it out what I can do

**Comment by jonkykong** [comment]
Make sure you read the Advanced section as that may be related to your problem.
