### ISSUE TITLE
Gesture issue

### ISSUE THREAD

**Issue by JavilinGarcia** [jonkykong/SideMenu#342]
Hello I am using your library (3.1.5 version) on a project written in swift 4, and I can not disable the pan gesture to show menu with the following code line: 

SideMenuManager.default. menuEnableSwipeGestures = false

I want to disable lateral menu only on pair of view controllers of my application.

Some suggestion?

Thank you very much, and great job!

**Comment by jonkykong** [comment]
Please update to use the latest version of the code. You'll need to investigate more thoroughly to identify the source of the problem as you may be doing something else wrong not related to SideMenu.

To disable the menu on a specific view controller, disable or remove the gestures.
