### ISSUE TITLE
invert right and left side menus (RTL)

### ISSUE THREAD

**Issue by AbubakerM** [jonkykong/SideMenu#343]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [*] My issue is happening in the **latest version** of SideMenu.
- [*] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [*] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [*] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [*] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Dear Developers,
My issue is related to that I'm using RTL Language. In my case, I'm using only one side menu. 
In LTR Language it works perfectly, and the menu is showing from the left but the problem when inverting the language to RTL language the menu still appear from the left (It should be inverted in this case and show from the right)

here is my attempt : 

if currentLanguage() == .English {
        SideMenuManager.default.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? UISideMenuNavigationController
        SideMenuManager.default.menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? UISideMenuNavigationController
        SideMenuManager.default.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
       } else {
        SideMenuManager.default.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? UISideMenuNavigationController
        SideMenuManager.default.menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? UISideMenuNavigationController   
        SideMenuManager.default.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
        }

**Comment by jonkykong** [comment]
You need to troubleshoot further Chris doesn’t appear to be a bug with SideMenu. You’re probably not detecting RTL properly.

**Comment by alshezawi** [comment]
it's working fine with me 
i just created two segues and I gave each one identifier Ex : showLeftMenu , showRightMenu
then i created IBAction for the UIBarButtonItem, check the code below 

      if currentAppLanguage == "ar" {
        performSegue(withIdentifier: "showRightMenu", sender: self)
        }else {
           performSegue(withIdentifier: "showLeftMenu", sender: self)
        }
