### ISSUE TITLE
Unable to provide different widths for left and right side menus

### ISSUE THREAD

**Issue by gozita93** [jonkykong/SideMenu#344]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello I'm a newbie and I've integrated the SideMenu in my project. I am providing menus on both sides of the main controller. When I provide the width of the side menu using

    SideMenuManager.default.menuWidth = view.frame.width

both the left and right side menus are getting presented with same width and covers the entire screen. What I want to do is provide different widths for the left and right menus where left would cover 70% of the screen width and right would cover 100% of the screen width. To achieve this I used the following:

    let storyBoard = UIStoryboard.init(name: "HomeStoryBoard", bundle: nil)
    let rightSideNC = storyBoard.instantiateViewController(withIdentifier: "RightMenuNavigationController") as! UISideMenuNavigationController
    let leftSideNC = storyBoard.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
    rightSideNC.menuWidth = view.frame.width
    leftSideNC.menuWidth = view.frame.width * 0.70

But this will revert to the default settings of side menu. I also tried using this in the left and right menu button actions where if the leftSideMenu button is clicked then

     SideMenuManager.default.menuWidth = view.frame.width * 0.70

and when rightSideMenu button is clicked then

     SideMenuManager.default.menuWidth = view.frame.width

This gives me the desired result but this will not work properly if pan gestures are active. According to the document it should be possible to provide different widths to the two side menus by creating instances of left and right side navigation controllers of type UISideMenuNavigationController. It would be of great help if you could help me with this. Thanks in advance.

**Comment by jonkykong** [comment]
Change the width of the menu right before it's presented.
