### ISSUE TITLE
Save state while transitioning between view controllers

### ISSUE THREAD

**Issue by rip32700** [jonkykong/SideMenu#346]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How can I keep the view controllers instantiated while transitioning between them via the side menu?

I've implemented in currently in the following way:
```
    // navigate to the corresponding view controller
    switch(indexPath.row){
    case 0:
        let launchScreenNC = self.storyboard?.instantiateViewController(withIdentifier: "LaunchScreenNC") as? UINavigationController
        self.navigationController?.pushViewController((self.launchScreenNC?.viewControllers.first!)!, animated: true)
        break
    case 1:
        let connectionNC = self.storyboard?.instantiateViewController(withIdentifier: "ConnectNC") as? UINavigationController
        self.navigationController?.pushViewController((self.connectionNC?.viewControllers.first!)!, animated: true)
        break
    [...]
        break
    default:
        // nothing to do
        break
    }
```

This way it instantiates the controller again every time and thus does not keep state. When I try to keep the references as instance variables within the menu table view controller it does not work either since when clicking on the menu icon from a view, the menu table view controller is also instantiated from scratch each time. How can I save the state?

**Comment by jonkykong** [comment]
This is not a SideMenu issue. You can instantiate things programmatically and preserve the instance at your discretion, SideMenu does not prohibit this.
