### ISSUE TITLE
How Can I enable menu for all screen? I need to avilable sidemenu when I presentview any viewcontroller from side menu.

### ISSUE THREAD

**Issue by elminawim** [jonkykong/SideMenu#347]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
Please follow the README carefully.
