### ISSUE TITLE
SideMenuManager unable to be released from memory when its not being used

### ISSUE THREAD

**Issue by vicky-digiapt** [jonkykong/SideMenu#349]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
In my app, I have screen A and screen B. Screen B will be pushed to navigation by Screen A.

I have implemented **Side Menu in Screen B**. We require it only in Screen B. Once I dismiss/pop Screen B, the menuLeftNavigationController is not removed from memory since its being hold by SideMenuManager.

I am unable to remove both SideMenuManager and menuLeftNavigationController from memory.

The below  screenshot is taken while graphing memory using Xcode when user is in Screen A i.e., Screen B is dismissed/popped from navigation:
![Memory being unreleased](https://user-images.githubusercontent.com/28340233/38353382-e207ce24-38d3-11e8-9dc3-b2cecfd45b68.png)

**Comment by jonkykong** [comment]
This is by design to make the menus very responsive to gestures. To clear it, set menuLeftNavigationController to nil.

**Comment by vicky-digiapt** [comment]
@jonkykong Thanks for quick response. I have already tried setting
 `SideMenuManager.default.menuLeftNavigationController = nil` but still its not released from memory. As you can see in the below screenshot, the MenuListTableViewController is still the child of UISideMenuNavigationController. As I have explained before I also tried dismissing/popping MenuListTableViewController but still its not cleared from memory.
![screen shot 2018-04-06 at 11 10 51 am 2](https://user-images.githubusercontent.com/28340233/38405123-dbb97514-398b-11e8-9adf-ed52bf3c8473.png)

**Comment by jonkykong** [comment]
@vicky-digiapt you can only release a navigation controller when it's not in the view hierarchy, otherwise SideMenu will display a warning in the console.
