### ISSUE TITLE
How to open side menu programmatically?

### ISSUE THREAD

**Issue by roma86** [jonkykong/SideMenu#35]
Hello. Thank you for library.

Can not understand what the correct way to open side menu from code.

Tried use  some segue from root view controller and `performSegueWithIdentifier(_:_:)` but menu just opened modally. 

Thanks in advance.

**Comment by roma86** [comment]
Ooops! `UISideMenuNavigationController` just was not set. 
Perform segue works fine.

Remove this issue, please.

**Comment by hemangshah** [comment]
How to open the left side menu as I don't set any segues inside the Storyboard? @roma86 @jonkykong
