### ISSUE TITLE
Have side menu view stay open, but behind new pushed view controller

### ISSUE THREAD

**Issue by royherma** [jonkykong/SideMenu#350]
## New Issue Checklist

I have read the [x](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I'd like to leave the side menu open when pushing view controllers onto the stack, so that when they pop back to the root, the side menu will still appear. 

For this i set `SideMenuManager.default.menuDismissOnPush = false`.

The issue is the menu is on top of every view controller I push, where as it should be behind, not covering up any of the screen. Is this even possible to do using the library (without adding listeners/callbacks to state changes for each viewcontroller and to decide if i should show or hide the side menu)

Thanks!

![image](https://user-images.githubusercontent.com/3466248/38639105-435284fc-3d9e-11e8-881d-dd40f4f9c9f2.png)

**Comment by jonkykong** [comment]
This isn't a SideMenu issue, this is how the view hierarchy works as defined by Apple. Pushing a view controller maintains them in the same layer. Presenting them creates a new layer on top, hiding the menu. What you're asking for breaks user expectations of how the view hierarchy normally works and isn't supported. If you really want this you'll have to modify it to figure it out on your own.

**Comment by royherma** [comment]
When you push a view controller onto the stack, it usually covers the original view controller's view, doesn't it? I would expect the same when pushing onto the side menu's navigation controller, but if this isn't something thats intended, thats absolutely fine - your design choice.

With that being said, is there a way to access the view controller that presented the side menu view controller, from the side menu view controller?

Thanks for the swift response and the lib @jonkykong

**Comment by jonkykong** [comment]
Yes. It covers the original view's controller view, and nothing more (ie not SideMenu because it is not in the original view's controller view), it is above/below it depending on the style used.

Yes, you can access the view controller that presented the SideMenu easily, see presentedViewController/presentingViewController.

**Comment by royherma** [comment]
Which style property controls whether the side menu is above/below the newly presented view controller?

**Comment by jonkykong** [comment]
The slide outs

**Comment by royherma** [comment]
Yes, still doesn't achieve what i'm trying to do. 

Just to be clear, there is no built in way to push a view controller over an opened menu (and to leave it open), so that the new view controller appears over (and essentially hides) the side menu?

**Comment by jonkykong** [comment]
No. Again, this is how the view hierarchy works as defined by Apple. Pushing a view controller maintains them in the same layer. Presenting them creates a new layer on top, hiding the menu. What you're asking for breaks user expectations of how the view hierarchy normally works and isn't supported. If you really want this you'll have to modify it to figure it out on your own.
