### ISSUE TITLE
Example App Crashes

### ISSUE THREAD

**Issue by twof** [jonkykong/SideMenu#351]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Example app crashes on startup with logs:

```
dyld: Library not loaded: @rpath/SideMenu.framework/SideMenu
  Referenced from: /Users/newuser/Library/Developer/CoreSimulator/Devices/A7888BD3-A6A0-4ACA-8D1B-F60838BEB0D8/data/Containers/Bundle/Application/9121DF64-527F-42F6-B7F7-F05912F7F6AF/Example.app/Example
  Reason: image not found
```

Xcode Version: 9.3
iOS Version: both 10.3.1 and 11.3

Project is unmodified.

**Comment by jonkykong** [comment]
@twof I'm inclined to believe that there's something up with your Xcode or some clash of SideMenu versions as no one else is reporting this and there hasn't been an update in a while now. The one image in the project is clearly included.

**Comment by bnurbekov** [comment]
I have the same issue. Was able to identify where the crash happens on my machine: line 265 in `Pod/Classes/SideMenuManager.swift`.

```
// Ensures minimal lag when revealing the menu for the first time using gestures by loading the view:
let _ = forMenu.topViewController?.view
```

**Comment by Lindoriana** [comment]
I know it's late, but maybe it can help others : I'm using Carthage and I had the same error because I forgot to add the .framework file in the embedded binaries section of the project.
