### ISSUE TITLE
How pass parameter to my SideMenuViewController?

### ISSUE THREAD

**Issue by augustocadini** [jonkykong/SideMenu#354]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
How I pass parameter from my Main ViewController.swift to my SideMenuViewController?
```
// SideMenu
        let menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController

```

My ViewControllerSideMenu.swift

```
class ViewControllerSideMenu: UIViewController {
    

    override func viewDidLoad() {
        print("ViewControllerSideMenu - ViewDidLoad")
                
   
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
    }
```

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.
