### ISSUE TITLE
Why am I seeing the black in the notch?

### ISSUE THREAD

**Issue by takasurazeem** [jonkykong/SideMenu#355]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ x] My issue **is** reproducible in the [demo project](https://bitbucket.org/takasurazeem/slack-clone/src).

## Issue Description

![image](https://user-images.githubusercontent.com/2876680/39229751-61cdfc92-487d-11e8-81b5-29d7ae7861c3.png)

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.

**Comment by AmirHossein1372** [comment]
Based on @takasurazeem solution:
let menu = SideMenuNavigationController(rootViewController: controller)
menu.presentationStyle.backgroundColor = .clear
