### ISSUE TITLE
Black view when use dismiss menu with Gesture (Code Implementation)

### ISSUE THREAD

**Issue by anngdev** [jonkykong/SideMenu#357]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I use code implement in my project (ios 9). I use drag gesture to move (fast move) and release gesture to dismiss menu, a black view will appear (and disappear after ~0.5s)

```
//ViewController is embed in navigation viewcontroller
override func viewDidLoad() {
        super.viewDidLoad()
        self.initMenu()
}

func initMenu(){
        let leftMenu = UIViewController()
        leftMenu.view.backgroundColor = UIColor.orange
        let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: leftMenu)
        SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController
        
        let rightMenu = UIViewController()
        rightMenu.view.backgroundColor = UIColor.green
        let menuRightNavigationController = UISideMenuNavigationController(rootViewController: rightMenu)
        SideMenuManager.default.menuRightNavigationController = menuRightNavigationController
        
        SideMenuManager.default.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
}


@IBAction func showLeftMenu(_ sender: UIButton) {
        present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)
}

@IBAction func showRightMenu(_ sender: UIButton) {
        present(SideMenuManager.default.menuRightNavigationController!, animated: true, completion: nil)
}
```

**Comment by jonkykong** [comment]
@anngdev Does this happen in iOS 9 only?

**Comment by anngdev** [comment]
@jonkykong Yes, I have tested it on 9.x and 11.x. The bug only happen in iOS 9

**Comment by jonkykong** [comment]
I think I'm more likely to upgrade the project to iOS10 than I am to fix this issue in iOS9, unfortunately.

**Comment by anngdev** [comment]
@jonkykong There are many iOS 9 device in my country. But anyway, thank you :D

**Comment by jonkykong** [comment]
@anngdev you're welcome to investigate it further and submit a PR.
