### ISSUE TITLE
I just dont need navigationcontroller for slide menu

### ISSUE THREAD

**Issue by sreeji44** [jonkykong/SideMenu#36]
How can i use side menu without using navigationcontroller...  here i need only one button.. how can i deal with this.. i tried for that i need  your confirmation weather it can be done or not..

**Comment by jonkykong** [comment]
There's no good reason to avoid a navigation controller. Just embed your controller in the NavigationController and you're done.

**Comment by Jauzee** [comment]
@sreeji44 you can embed your `UIViewController` in `UISideMenuNavigationController` and just hide navigation bar in `viewDidLoad` method
