### ISSUE TITLE
iOS 9: menu doesn't work when lock view controller to portrait

### ISSUE THREAD

**Issue by wangqingzhouleo** [jonkykong/SideMenu#361]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

This issue is specific to iOS 9 and not reproducible on later iOS versions.
Reproduced on Xcode 9 and Swift 4.

Steps to reproduce in demo project:
1. Change deployment target to any version between 9.0 and 9.3
2. Add
    ```
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .portrait
    }
    ```
to MainViewController
3. Run app on any iPhone simulator which runs iOS 9
4. Rotate simulator to landscape mode
5. Click on "Button"

**Result:**
Screen auto rotate to landscape even if it's not supported in the view controller. Then menu slide in from left, once animation completed it suddenly disappear without animation.

**Comment by jonkykong** [comment]
@wangqingzhouleo I'd ask that you debug this further. You may need to add that method to the UISideMenuNavigationController as that is the last view controller on the stack. It's very likely this isn't a bug. If you think this is still a bug, please reply with screen captures that show the problem, as well as a sample project.

**Comment by wangqingzhouleo** [comment]
@jonkykong by adding this to `UISideMenuNavigationController` still not working and it doesn't lock app orientation to portrait, unfortunately in my app we do not want to support landscape on iPhone - only on tablets.

**Comment by jonkykong** [comment]
The only way that SideMenu rotates is because the OS is telling it to meaning rotation is enabled. If it's not enabled, there's no way SideMenu would receive a notification to rotate otherwise.

I feel strongly that somewhere there's a missing call to `supportedInterfaceOrientations` somewhere in your code, or some other bug that's enabling rotation. Have you used breakpoints to determine if it's being called? Have other people reported this issue (not related to SideMenu) and any fixes?

**Comment by wangqingzhouleo** [comment]
No one reported the same issue as it’s too specific to iOS version and orientation (portrait works fine). SideMenu works fine on iOS 10 or later, I feel that this could be a iOS 9 bug which been fixed on later versions. Btw, I think we shouldn’t need to call `supportedInterfaceOrientations` as it's been override in view controller.

**Comment by jonkykong** [comment]
That's what I'm trying to determine. If this is indeed an iOS bug then I do not plan on making any changes to SideMenu to counterract it -- you're welcome to submit a PR if you like.

This seems related: https://stackoverflow.com/questions/32782044/ios-9-supportedinterfaceorientations-not-working?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
