### ISSUE TITLE
Conflict with iOS standard "swipe to go back"

### ISSUE THREAD

**Issue by hengchengfei** [jonkykong/SideMenu#362]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
When push to the other viewcontroller from Main ViewController, the swipe-back gesture will show the left menu,But I want to back to the previous viewcontroller.

the code in pushed viewcontroller:
```swift
self.navigationItem.leftBarButtonItem = UIBarButtonItem(image: UIImage(named: "arrow_back"), style: .plain, target: self, action: #selector(back))
```
Thank you!

**Comment by jonkykong** [comment]
This is by design. Disable the menu gestures, or set up a relationship between the gestures so that one takes precedence.
