### ISSUE TITLE
Errors on Download

### ISSUE THREAD

**Issue by RaphaIsCoder** [jonkykong/SideMenu#365]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello,

I recently downloaded your cocoapod. After downloading and opening the xcworkspace of my project I found that multiple errors appeared. I scoured the internet (stackoverflow, your readme, google search) for something that would help me get around this, but I was unable to find much outside of this readme. I also tried to simply "fix" the errors according to Xcode's suggestions, but that only caused more errors to appear. Attached is a screenshot of what I am seeing. I am not sure if I did something wrong on the download or what is going on, but some help would be greatly appreciated. 

<img width="1144" alt="screen shot 2018-05-31 at 10 39 21 pm" src="https://user-images.githubusercontent.com/31522148/40823118-02164db8-6524-11e8-8ea5-ccbe10318f79.png">

Thanks so much!

Raphael M. Hidalgo

**Comment by jonkykong** [comment]
@RaphaIsCoder you are the first to be reporting these issues and I have no issues, so I'm thinking there's a configuration in your project that's causing this.

You might have @objc inference enabled or a Swift versioning setting that's causing these problems. Look into those and report back with your findings.
