### ISSUE TITLE
SideMenu not use all screen height size

### ISSUE THREAD

**Issue by augustocadini** [jonkykong/SideMenu#367]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I've implemented like readme and app example. But, the Height not use all height of screen.
![img_6556](https://user-images.githubusercontent.com/18659348/40953920-603e2bb8-6858-11e8-8765-892d94a7f274.PNG)

**Comment by jonkykong** [comment]
Does this occur in the example project on different screen sizes? If not, then chances are there's something you need to fix with your view controllers or layout.

**Comment by augustocadini** [comment]
Yes, It's run in other screen sizes, but, what can be my problem?

**Comment by jonkykong** [comment]
I’m not sure, you’ll have to investigate further yourself. Try comparing
your screens to the example project or recreating them from scratch.

**Comment by Ljuka** [comment]
In my case this was happening because I was setting corner radius inside `viewDidLoad` in SideMenu ViewController. Just moved that piece of code in `viewWillAppear` solved the issue. The issue was manifesting probably because of the fact I was trying to manipulate the main view in `viewDidLoad` state.
