### ISSUE TITLE
If MainViewController is not the first view controller there is an issue (Unbalanced calls to begin/end appearance transitions) when you push any new view controller.

### ISSUE THREAD

**Issue by Ariel205** [jonkykong/SideMenu#368]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by jonkykong** [comment]
No repro in the latest build using the Example project.

**Comment by Ariel205** [comment]
Sorry. For test in the example you have too create a new view controller ("NewFirst") and push to the Main View Controller.

<img width="1280" alt="screen shot" src="https://user-images.githubusercontent.com/19914584/41456959-70ed9818-7082-11e8-8275-2b9a0fc982c2.png">

In my project, i there is a login storyboard before the Main View Controller.

**Comment by jonkykong** [comment]
You should not be pushing from one navigation controller into another navigation controller.

**Comment by Ariel205** [comment]
Can i use your pod if i have a login controllers before the main view controller?

**Comment by jonkykong** [comment]
Yes.

**Comment by Ariel205** [comment]
Could you be more explicit on how to do it? I tested without push from navigation controller and i obtained the same result.

**Comment by mohsinka** [comment]
@Ariel205  any update on this?
