### ISSUE TITLE
Will You implement variant for iPad where SideMenu can be always opened? 

### ISSUE THREAD

**Issue by YevhenHerasymenko** [jonkykong/SideMenu#37]

**Comment by jonkykong** [comment]
Please see https://developer.apple.com/library/ios/documentation/WindowsViews/Conceptual/ViewControllerCatalog/Chapters/SplitViewControllers.html.

**Comment by YevhenHerasymenko** [comment]
@jonkykong I know about UISplitViewController. But I need custom width of left menu controller. Thats why I use this pod. And now We are planing about adaptation for iPad and I am interested in this pod.

**Comment by jonkykong** [comment]
@YevhenHerasymenko this is the first request for such a feature. Unfortunately, I don't have the time to build this. I would encourage you to do either of the following:

1. Contribute to this library and add to it. Create a pull request with your changes and I can review & integrate it.
2. Subclass this library with your own customizations.
