### ISSUE TITLE
sideMenu doesn't work after modal segue to a previous VC

### ISSUE THREAD

**Issue by seongminchoob** [jonkykong/SideMenu#370]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

<img width="239" alt="screen shot 2018-06-26 at 4 10 50 pm" src="https://user-images.githubusercontent.com/35505959/41894921-85c0ae60-795b-11e8-8310-d2821d542c30.png">

initially the side menu works perfectly. However, if I perform a modal segue to a previous view controller and come back to the View controller with the side menu and press side menu again, 

<img width="337" alt="screen shot 2018-06-26 at 4 12 54 pm" src="https://user-images.githubusercontent.com/35505959/41895009-ce094f10-795b-11e8-9f72-90966ae0fa2e.png">

it doesn't show up as a side menu anymore. 

this issue is reported on Xcode10-beta, for iphone 7 and 8. 

By the way, regardless, thank you for this application

**Comment by jonkykong** [comment]
@seongminchoob does this happen in the Example Project? If so, please reopen, otherwise there is something odd about your implementation.
