### ISSUE TITLE
Impossible to push viewController

### ISSUE THREAD

**Issue by Mihailstoica350** [jonkykong/SideMenu#372]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
Hello and thanks for this great feature.
Here is my problem, hope it isn't that hard.
I am not using any storyboards and I have a navigationController having the rootViewController a tabbar. I'm setting this navigationController as the rootViewController of the window in appdelegate. 
The sideMenu is integrated in the tabBar's viewDidLoad having the rootViewController a viewController.
The thing is that when swiping from left to right, nothing happens, which is normal because I didn't add any pan gestures, but when I'm trying to push a viewController from one of my tabbar's childs, the UI freezes and when i drag from left to right a menu appears from the right side. Too bad that you can't send videos on github, this bug is funny.

**Comment by jonkykong** [comment]
You’ll need to recreate the issue using the example project and share it
with me since there may be a bug in your other app code that’s causing this
problem. I’m only troubleshooting issues that are demonstratable in the
example project.
