### ISSUE TITLE
Not Working on Device

### ISSUE THREAD

**Issue by iTheGentle** [jonkykong/SideMenu#375]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello,
I faced a problem i can't fix it, When i run my app on simulator it's working fine but when i tested it on a real device it's not showing the SideMenu it's showing the menu's viewcontroller as push view controller.
ios: 11.3
device iphonex
my regards.

**Comment by jonkykong** [comment]
Whatever this is, it doesn't sound like a SideMenu bug so you'll need to investigate further to verify if this is in fact a SideMenu issue or something else with your code.

**Comment by Mahmoud3allam** [comment]
still got the same problem , everything works well in simulator but its just present the menu at the real device
