### ISSUE TITLE
Keyboard closing problem

### ISSUE THREAD

**Issue by Mihailstoica350** [jonkykong/SideMenu#376]
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I'm facing the following problem:
I have a textField in the sideMenu and when the keyboard is shown I want that when tapping outside the sideMenu to only close the keyboard and not the sideMenu.

I've seen that you have a `exitTapGesture.addTarget(self, action: #selector(SideMenuTransition.handleHideMenuTap(_:)))`, what can I do to override this?

**Comment by jonkykong** [comment]
You'll need to add a transparent overlay to your presenting controller that handles that tap, as well as handle taps from your SideMenu. You'll want to make sure `menuPresentingViewControllerUserInteractionEnabled` is set to `true`. See the delegate methods for when to add that transparent overlay.
