### ISSUE TITLE
Black overlay on the main viewController when SideMenu is displayed

### ISSUE THREAD

**Issue by nitishmaropost** [jonkykong/SideMenu#379]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I was looking for the feature where a black overlay can be set on the main viewController when the side menu is displayed. I tried checking all the functions provided in SideMenuManager.default but could not find one. Am I missing something ?
This is what I am referring to (check the black overlay on the main VC) :  

<img width="375" alt="screen shot 2018-07-20 at 12 35 42 am" src="https://user-images.githubusercontent.com/37299932/42964522-f0ff7074-8bb4-11e8-83f6-1395bcb13a7a.png">

**Comment by jonkykong** [comment]
Everything you need to know is in the README with regards to functionality. You will want to use the delegate methods to add an overlay to your presenting view controller that includes the white X that you want. If you want it to be that way for all controllers, simply extend `UIViewController` with the delegate methods.

**Comment by EugeneEl** [comment]
Can anyone provide an example how to add backing overlay view for SideMenu?

**Comment by sukhrobkhakimov** [comment]
@EugeneEl See https://github.com/jonkykong/SideMenu/issues/575#issuecomment-801811361
