### ISSUE TITLE
Populate Sidemenu Programatically

### ISSUE THREAD

**Issue by rosensts** [jonkykong/SideMenu#38]
@jonkykong  first of all, thanks so much for this great library! 

I was just wondering how to populate the side menu table view controller from a swift array. Where should the datasouce/ delegate be placed so that the different options can appear in the side menu?

Thanks!

**Comment by jonkykong** [comment]
Hi @rosensts,

SideMenu is actually a navigation controller that slides out over your main view controller. You must create the view controller that goes inside the navigation controller (which in my example is a UITableViewController) and displays the various choices to the user. Simply put, create a UITableViewController or whatever screen you want and that's going inside of SideMenu's navigation controller.

See the example project in the pod if you need to see some code.
