### ISSUE TITLE
Swiping on top navigation bar opens SideMenu

### ISSUE THREAD

**Issue by danishnaeem57** [jonkykong/SideMenu#380]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by danishnaeem57** [comment]
First of all, awesome work. Thanks for this! :) 

I have implemented SideMenu through storyboard. When I swipe on navigation bar of view controller, it tends to open SideMenu. What is the fix for this?

**Comment by jonkykong** [comment]
Please follow the README carefully.

**Comment by hardikamal** [comment]
@danishnaeem57  were you able to fix this?

**Comment by fuad-adetoro** [comment]
@jonkykong It doesn't say anything in the README about this issue, It use to!.
