### ISSUE TITLE
Use SideMenu on Multiple Controllers

### ISSUE THREAD

**Issue by jamessuske** [jonkykong/SideMenu#381]
Hi,

I am trying to apply to the SideMenu to Multiple Controllers like in the image attached
<img width="442" alt="screen shot 2018-07-23 at 12 33 46 am" src="https://user-images.githubusercontent.com/8172382/43057410-1d6a68fa-8e10-11e8-86a9-03c4f8efe12f.png">

But it only works on the inital view controller in my code on each of the controllers I am trying to apply SideMenu to:

@IBAction func menuButtonPressed(_ sender: Any) {
        
        let viewController = storyboard?.instantiateViewController(withIdentifier: "MenuController") as! MenuController
        
        let menuRightNavigationController = UISideMenuNavigationController(rootViewController: viewController)
        
        SideMenuManager.default.menuRightNavigationController = menuRightNavigationController

        present(menuRightNavigationController, animated: true, completion: nil)
        
    }

What do I do to have multiple view controllers use SideMenu?

**Comment by jonkykong** [comment]
It should work. Chances are you're doing something strange with your view controller configuration and I can't tell what from your image. Follow the README carefully.

**Comment by jamessuske** [comment]
Could it be how I am presenting in my other view controllers? My SideMenu is a TableView and when selecting an item another view controller gets presented:

override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
        
        
        if(self.menuItems[indexPath.row] == "Home")
        {
            let viewController = storyboard?.instantiateViewController(withIdentifier: "Home") as! HomeController
            
            let navigationController: UINavigationController = UINavigationController(rootViewController: viewController)
            
            present(navigationController, animated: true, completion: nil)
        }
        
        if(self.menuItems[indexPath.row] == "Login")
        {
            let viewController = storyboard?.instantiateViewController(withIdentifier: "Login") as! LoginController
            
            let navigationController: UINavigationController = UINavigationController(rootViewController: viewController)
            
            present(navigationController, animated: true, completion: nil)
        }
        
        if(self.menuItems[indexPath.row] == "Healthpros")
        {
            let viewController = storyboard?.instantiateViewController(withIdentifier: "Healthpros") as! ProfessionalsController
            
            let navigationController: UINavigationController = UINavigationController(rootViewController: viewController)
            
            present(navigationController, animated: true, completion: nil)
        }
        
        if(self.menuItems[indexPath.row] == "Patients")
        {
            let viewController = storyboard?.instantiateViewController(withIdentifier: "Patients") as! PatientsController
            
            let navigationController: UINavigationController = UINavigationController(rootViewController: viewController)
            
            present(navigationController, animated: true, completion: nil)
        }
        
    }

**Comment by jonkykong** [comment]
Yes. If you present another view controller from SideMenu, you can't show the SideMenu again as it's still in the visual hierarchy. You should push these screens or instantiate another SideMenu instance.

**Comment by atalayasa** [comment]
@jamessuske Did you find any solutions about your problem? How do you push new view controller when didSelectRowAt function worked?

**Comment by javmorales** [comment]
Could you find the solution?

**Comment by jamfly** [comment]
@jamessuske @javmorales Did you guys find any solutions?
