### ISSUE TITLE
challenge with sideMenu

### ISSUE THREAD

**Issue by AliMan68** [jonkykong/SideMenu#383]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

hello jon...thanks for library.
I use right side and when i put a button in Navigation to go another View , in this view I have sideMenu to and I don't need that there....what should I do?

**Comment by jonkykong** [comment]
Please read the README carefully. Make sure you only enable gestures on the screens you want.

**Comment by AliMan68** [comment]
in example you use this --->   SideMenuManager.default.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)**********************which enable SideMenu to all view's(that view we achieve them with 'show'). Now, i don't understand how to enable gestures in specific view while i'm using 'show'. and i need help
