### ISSUE TITLE
Problem with UITabBarController

### ISSUE THREAD

**Issue by alexllao** [jonkykong/SideMenu#384]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ X] My issue is happening in the **latest version** of SideMenu.
- [ X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Instead of using a ViewController I use a UITabBarController and the SideMenu delegate never executes. The code is simple.

`
import UIKit
import SideMenu

class ViewController: UITabBarController {

    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = UIColor.brown
        prepareTabs()
        prepareSideMenu()
    }
    
    func prepareTabs() {
        let tab1 = UIViewController()
        tab1.title = "1"
        tab1.view.backgroundColor = UIColor.green
        
        let tab2 = UIViewController()
        tab2.title = "2"
        tab2.view.backgroundColor = UIColor.purple
        
        let tab3 = UIViewController()
        tab3.title = "3"
        tab3.view.backgroundColor = UIColor.purple
        
        viewControllers = [tab1, tab2, tab3]
    }
    
    func prepareSideMenu() {
        
        let vc = UIViewController()
        vc.view.backgroundColor = UIColor.red
        let leftMenu = UISideMenuNavigationController(rootViewController: vc)
        
        SideMenuManager.default.menuLeftNavigationController = leftMenu
        SideMenuManager.default.menuFadeStatusBar = false
        
        let barButton = UIBarButtonItem(barButtonSystemItem: .add, target: self, action: #selector(showSwipeMenu))
        navigationItem.leftBarButtonItem = barButton
    }
    
    @objc func showSwipeMenu() {
        present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)
    }
}

extension ViewController: UISideMenuNavigationControllerDelegate {
    func sideMenuWillAppear(menu: UISideMenuNavigationController, animated: Bool) {
        print("SideMenu Appearing! (animated: \(animated))")
    }
    
    func sideMenuDidAppear(menu: UISideMenuNavigationController, animated: Bool) {
        print("SideMenu Appeared! (animated: \(animated))")
    }
    
    func sideMenuWillDisappear(menu: UISideMenuNavigationController, animated: Bool) {
        print("SideMenu Disappearing! (animated: \(animated))")
    }
    
    func sideMenuDidDisappear(menu: UISideMenuNavigationController, animated: Bool) {
        print("SideMenu Disappeared! (animated: \(animated))")
    }
}
`

I don't understand it!

**Comment by jonkykong** [comment]
Delegate messages are probably going to your tab controller instead of your view controller, or vice versa. Set the delegate explicitly.

**Comment by alexllao** [comment]
What name does the property have for assigning the delegate?

SideMenuManager.default.xxxxxxxxxxxxx

How can I fix it? The code is theoretically simple.
