### ISSUE TITLE
How to push a new controller into sidemenu?

### ISSUE THREAD

**Issue by padrojacodal** [jonkykong/SideMenu#386]
I want to make a menu with submenu which requires pushing new controller into sidemenu.

How can I achieve this?

**Comment by wakaryry** [comment]
```swift
SideMenuManager.default.menuPushStyle = .subMenu
```

> /**
The push style of the menu.
> There are six modes in MenuPushStyle:
> - defaultBehavior: The view controller is pushed onto the stack.
> - popWhenPossible: If a view controller already in the stack is of the same class as the pushed view controller, the stack is instead popped back to the existing view controller. This behavior can help users from getting lost in a deep navigation stack.
> - preserve: If a view controller already in the stack is of the same class as the pushed view controller, the existing view controller is pushed to the end of the stack. This behavior is similar to a UITabBarController.
> - preserveAndHideBackButton: Same as .preserve and back buttons are automatically hidden.
> - replace: Any existing view controllers are released from the stack and replaced with the pushed view controller. Back buttons are automatically hidden. This behavior is ideal if view controllers require a lot of memory or their state doesn't need to be preserved.
> - subMenu: Unlike all other behaviors that push using the menu's presentingViewController, this behavior pushes view controllers within the menu.  Use this behavior if you want to display a sub menu.
> */
> `open var menuPushStyle: MenuPushStyle = .defaultBehavior`
