### ISSUE TITLE
UISideMenuNavigationController and its subviews are kept in memory after menu is being dismissed

### ISSUE THREAD

**Issue by vkaramov** [jonkykong/SideMenu#388]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

In the viewDidLoad() of UISideMenuNavigationController:

 override open func viewDidLoad() {
        super.viewDidLoad()

        transition.overlayBlock = {[weak self] () -> UIView? in
            guard let strongSelf = self else { return nil }
            return strongSelf.activeDelegate?.sideMenuOverlay?(menu: strongSelf)
        }
        
        if !locked && usingInterfaceBuilder {
            if leftSide {
                sideMenuManager.menuLeftNavigationController = self
            } else {
                sideMenuManager.menuRightNavigationController = self
            }
        }
    }

But menuRightNavigationController and menuLeftNavigationController strongly keeps the reference:

open var menuRightNavigationController: UISideMenuNavigationController?

open var menuLeftNavigationController: UISideMenuNavigationController?

**Comment by jonkykong** [comment]
#349
