### ISSUE TITLE
barPosition Error

### ISSUE THREAD

**Issue by gian88** [jonkykong/SideMenu#39]
When I make click on the bottom for display the menu, show me the following error:

Failed to set (barPosition) user defined inspected property on (UINavigationItem): [<UINavigationItem 0x13dd98d60> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key barPosition.

Any Help?

**Comment by jonkykong** [comment]
This problem doesn't sound specific to SideMenu but is more likely a problem in what you've done in Storyboard. You may have created a connection and then deleted the underlying variable causing this issue. Try searching StackOverflow for this error.
