### ISSUE TITLE
Not able to get Menu action Programmatically i did not want to use Storyboard segue

### ISSUE THREAD

**Issue by shashak005** [jonkykong/SideMenu#390]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by shashak005** [comment]
Hi I want to use this fantastic library by code not from segue. Please let me know the Menu bar action and Cell didselect action .

**Comment by jonkykong** [comment]
All of this is described in the README.

**Comment by KoD4K** [comment]
I can't find in README how to change center view controller. Example code also can't show how to do it programmatically. It use SideMenuController() for this, but I did't find it in current 5.0.2 version of SideMenu.
In my first center view controller in viewDidLoad I created menu view controller
`let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: menuController)`
And after touch Menu button I do
`present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)`
After that I can see my Menu view controller. But how I can change center view controller programmatically? I found that need to use 
`navigationController?.pushViewController(controller, animated: false)`
But It pushes new view controller in my current center view controller not replace it with close menu animation!
Please, help or give link to answer if someone've already asked for this! Thanks!

**Comment by jonkykong** [comment]
#305
