### ISSUE TITLE
How to disable swipe?

### ISSUE THREAD

**Issue by jameszasod** [jonkykong/SideMenu#398]
How to disable swipe?

Thank.

**Comment by chathuralakmal** [comment]
> How to disable swipe?
> 
> Thank.

Check ReadMe File.

`menuEnableSwipeGestures: Bool = true`

**Comment by jameszasod** [comment]
Not works for me 😢

**Comment by chathuralakmal** [comment]
are you getting error? not working?

**Comment by jameszasod** [comment]
not working sir.

**Comment by jonkykong** [comment]
You must disable any gestures you add yourself.

**Comment by Nikoloutsos** [comment]
Can someone help me to remove the gesture?

I am calling `SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: view)`

How can I remove it? Is there any method for that? I don't have a lot of experience in ios field
