### ISSUE TITLE
How to properly make a push segue from the SideMenu

### ISSUE THREAD

**Issue by nahouto** [jonkykong/SideMenu#4]
Hello,

Thank you for this ready-to-use pod !

I am displaying a static table view in the sidemenu. I would like to perform a push segue from a cell of the SideMenu.

How and where can I implement a Navigation Controller to perform a push segue ?

Thanks !

Here is my code : 

    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let cell = tableView.cellForRowAtIndexPath(indexPath)
        
        // get cell identifier if it exists (otherwise, quit the function)
        guard let cellIdentifier = cell?.reuseIdentifier else {return}
        
        switch cellIdentifier {
            
            
        case "settings":
            performSegueWithIdentifier("SettingsSegue", sender: self)
            
        case "help":
            if let url = NSURL(string: "http://www.google.com/") {
                UIApplication.sharedApplication().openURL(url)
            }
            
        case "signout":
                performSegueWithIdentifier("SignInSegue", sender: self)
            
        case "deleteaccount":
                performSegueWithIdentifier("SignInSegue", sender: self)
            
        default: break
            
        }
     }

**Comment by jonkykong** [comment]
Hi @nahouto,

The code above seems okay, but I'm assuming you're running in to a problem if you opened an issue. You'll need to give me more information about the problem you're running into if that's the case. Make sure you're using the right identifier strings and that you've created all of the segues the code is trying to use in storyboard.

When I use SideMenu, I don't even bother implementing `didSelectRowAtIndexPath`. I simply set up the segues I want on the action for each of the static cells I've made, similar to the button in step 3 of the **Code-less Storyboard Implementation** in the [README](https://github.com/jonkykong/SideMenu#code-less-storyboard-implementation).

**Comment by antonioreyna** [comment]
hello @jonkykong  how can I show just two view controllers in the center view? i mean I have a right menu, and when i select each cell on it i want to show the content in the center view, but tapping those cells seems to be creating some kind of "history" in the center view so to go back to the first original view i have to tap back button many times, all the times the user selected in the right menu, how can I just have the main view controller and the one selected on that center view?

i tried this:

```
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        let notaVC = self.storyboard?.instantiateViewControllerWithIdentifier("ShowNewsViewController")
        self.navigationController?.popViewControllerAnimated(false)
        self.navigationController?.pushViewController(notaVC!, animated: true)
        
        self.tableView.deselectRowAtIndexPath(indexPath, animated: true)
    }
```

But its ignoring the pop method.

Thanks
