### ISSUE TITLE
Compatibility with XCode 8

### ISSUE THREAD

**Issue by chriskan0305** [jonkykong/SideMenu#40]
I love SideMenu but when I included it in XCode 8 (announced in WWDC2016) using Cocoapods (use_frameworks), it reported an error, saying that the framework was compiled with an earlier version of compiler. Can you provide one compiled with XCode 8?

**Comment by jonkykong** [comment]
@chriskan0305 if you select SideMenu in your schemes (next to where you choose to build to your phone or simulator) and build, it should compile everything. The pod itself is the original code and not a binary, so you should be able to recompile it yourself.
