### ISSUE TITLE
SideMenu cannot open with Gesture

### ISSUE THREAD

**Issue by chathuralakmal** [jonkykong/SideMenu#400]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Currently SideMenu can only open with button in the Navigation bar. 
but close can be done with the gesture it is mentioned in the ReadMe as well. 
but i want open the SideMenu with Gesture as well. "Swipe to right from the corner and Left SideMenu will be open"

**Comment by jonkykong** [comment]
This exists. Please read the README carefully.
