### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by lflobo** [jonkykong/SideMenu#404]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Would you be so kind to include the Manifest in order to support the  [swift package manager](https://swift.org/getting-started/#using-the-package-manager)?

Thanks in advance,
LL

**Comment by jonkykong** [comment]
Hi @lflobo, unfortunately I do not have the cycles to do this. You're welcome to make the changes yourself and submit a PR. It'd be really helpful to the community using this library.
