### ISSUE TITLE
5.0.1 pod build fails

### ISSUE THREAD

**Issue by hernangonzalez** [jonkykong/SideMenu#405]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

There seems to be a misconfiguration on the pod swift version. I am getting errors like:
```
[...] /SideMenu/Pod/Classes/UISideMenuNavigationController.swift:240:148: 'willChangeStatusBarFrameNotification' has been renamed to 'NSNotification.Name.UIApplicationWillChangeStatusBarFrame'

NotificationCenter.default.addObserver(self.transition, selector:#selector(SideMenuTransition.handleNotification), name: UIApplication.willChangeStatusBarFrameNotification, object: nil)
                     ^
```

**Comment by ciscoflores** [comment]
I experiencing same issue as well. I'm building my project with Xcode 10.0 (10A255). Initially I thought it could be a problem related with the new Xcode's Build System, but it was the same with Legacy Build System.

![screen shot 2018-09-26 at 1 07 00 pm](https://user-images.githubusercontent.com/4073343/46104134-36993480-c198-11e8-827d-87ab36893642.png)

**Comment by jonkykong** [comment]
You need to update your code base to Swift 4.2.

**Comment by aleksey-ho** [comment]
You can also specify old version of SideMenu to work with swift 4.0
`pod 'SideMenu', '~> 4.0.0'`
