### ISSUE TITLE
Status bar turns black on appearence of SideMenu

### ISSUE THREAD

**Issue by hassaan4584** [jonkykong/SideMenu#406]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

When I bring SideMenu, I get a black status bar. I have done some debugging and i believe a black colored view of the size of the status bar gets added at the top level.
Here is a screenshot from the simulator.

![simulator screen shot - iphone 8 - 2018-09-27 at 01 00 56](https://user-images.githubusercontent.com/5270282/46106340-db942b80-c1f1-11e8-8a64-45c39ee33a06.png)

And here is the hierarchical image of the views and we can see a black colored view at the top level. 
![screen shot 2018-09-27 at 1 01 28 am](https://user-images.githubusercontent.com/5270282/46106338-dafb9500-c1f1-11e8-8e30-e92606a377f7.png)

Xcode version is 10.0
Simulator: iPhone 8, iOS 12

**Comment by jonkykong** [comment]
Please read the README.

**Comment by hassaan4584** [comment]
I have read and implemented the readme and tried both the code-less storyboard implementation as well as code implementation.

**Comment by hassaan4584** [comment]
Thank you so much. 👍

**Comment by jaythummar85** [comment]
You can also set setting property "statusBarEndAlpha" = 0
