### ISSUE TITLE
Still not fixed for Swift 4.2 UIApplication.willChangeStatusBarFrameNotification

### ISSUE THREAD

**Issue by atrbx5** [jonkykong/SideMenu#407]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ X] My issue is happening in the **latest version** of SideMenu.
- [ X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by caiodias** [comment]
Where is the issue description?

**Comment by jonkykong** [comment]
@atrbx5 please update your minimum swift version to 4.2.
