### ISSUE TITLE
menuAnimationFadeStrength not working when using menuPresentMode = .viewSlideOut

### ISSUE THREAD

**Issue by Idomo** [jonkykong/SideMenu#408]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi,
First, thank you for building this library, it's grate!
From some reason `menuAnimationFadeStrength` not working right when using `menuPresentMode = .viewSlideOut`, it fades the view, but it do it on the `UISideMenuNavigationController` instead on the existing view controller (as mentioned in the README).
At the end the menu isn't covered by other layer of color, it just fade from the color and the opacity I chose and when it fully open it disappears, but the view controller is still bright and taking the user attention from the open menu.

~BTW, I'm using version `~> 4.0.0` because I have other libraries that haven't upgraded to Swift 4.2 yet, so I can't update my code too.~

Thanks,
Ido.

**Comment by jonkykong** [comment]
This is by design. You can add your own unique styles or customize the transitions in your controller code.
