### ISSUE TITLE
Pod Spec Missing

### ISSUE THREAD

**Issue by seancrowe5** [jonkykong/SideMenu#41]
I'm trying to install via Cocoapods and keep getting this: "Unable to find a specification for `SideMenu (~> 1.1)`" after running pod install. I have no issues installing other cocoa pod frameworks, not sure why it can't find it! I've tried running both:  pod 'SideMenu' and pod 'SideMenu', '~> 1.1'

**Comment by jonkykong** [comment]
@seancrowe5 Check your target dependencies for your podfile. If you aren't including it in the right projects, they can't see SideMenu.
