### ISSUE TITLE
Facing compilation error for SideMenu(5.0.1) in Xcode 10.0

### ISSUE THREAD

**Issue by SelvakumarAnnamalaisamy** [jonkykong/SideMenu#411]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hi,
 I took SideMenu (5.0.1) and integrated into my project. During compilation, I faced few errors in SideMenu framework files, using Xcode 10.0. Please find the attached screenshot for more information.
Please revert back in case of any further information needed.
Thanks and Regards

<img width="1142" alt="sidemenu 5 0 1" src="https://user-images.githubusercontent.com/44020419/46731888-83593100-cca9-11e8-946f-69244b28028d.png">

**Comment by SelvakumarAnnamalaisamy** [comment]
Hi, 
I saw in few of the similar issues, it's advised to change the Swift Language Version to "Swift 4.2" which works for me as well.

Is that is enough or do I need to configure any further?

Thanks and Regards

**Comment by JPMOB** [comment]
No selva, That will not workout, I have tried all the senario's. I think we have to wait for update.

**Comment by jonkykong** [comment]
Yes change to swift 4.2 as the README states.

**Comment by SelvakumarAnnamalaisamy** [comment]
@jonkykong Thanks for the suggestion. It works fine for me.
