### ISSUE TITLE
Getting Error in xcode 10

### ISSUE THREAD

**Issue by JPMOB** [jonkykong/SideMenu#413]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Yesterday I have updated the xCode, Deleted pod.lock and pods file then install and update pods.
I got couple of error in sidemenu code which all are related to the NotificationCenter (UIApplication.method)
<img width="272" alt="screen shot 2018-10-11 at 1 22 12 am" src="https://user-images.githubusercontent.com/18574819/46762198-1dde6200-ccf4-11e8-88d3-a1e0def39dec.png">

**Comment by MSavisko** [comment]
What release version of do you use? 5.0.1?

**Comment by UnionMexicanaDelNorte** [comment]
I have same issues, replace NSNotificaton.Name,UIApplication.... bla bla 
with:  UIApplication.didEnterBackgroundNotification
In google research can found hot fix for every error

**Comment by MSavisko** [comment]
@UnionMexicanaDelNorte 
Do:
1. `pod repo update` to be sure that your local 'podspec' repo actual.
2. Check Podfile `pod 'SideMenu'`
3. Run `pod update SideMenu`
4. Ensure that you see `Using SideMenu (5.0.1)`
5. Clean Xcode Project, delete Derived Data and build.

**Comment by jonkykong** [comment]
Update your swift version.
