### ISSUE TITLE
SideMenu not working after cocoa pods install in Xcode 10 with swift 4.2

### ISSUE THREAD

**Issue by martinmaly21** [jonkykong/SideMenu#414]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Although the files are successfully imported into Xcode, the code in the .swift files is showing many errors saying that this code must be fixed for Swift 4.2. I downloaded the demo project and replaced all the code in the .swift files in my project with the code from the .swift files in the demo project, and no longer have any issues. Why is this the case?

**Comment by jonkykong** [comment]
I don’t know what’s wrong with your project, but the pod has been update for Swift 4.2.
