### ISSUE TITLE
Swift version in Podspec file

### ISSUE THREAD

**Issue by DominikButz** [jonkykong/SideMenu#415]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the 5.0.1 version of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
Hi, great framework! This is a minor issue. can you add the following line to your pod spec file?
s.swift_version = '4.2'
Every time I update my pod file, I have to go to the SideMenu target and set the Swift Language version in the Build Settings Tab to Swift 4.2. Version 5.0.1 won't build with swift 4.0 is set. Without this line, the version defaults to 4.0...  
Thank you
Dominik

**Comment by DominikButz** [comment]
That's what I did. the framework is working. but I had to set it to 4.2 manually. The reason why it defaults to 4.0 in my project might be that the project is still 4.0. I can't convert it currently because I have an issue with my test unit and UI tests.

**Comment by limadeveloper** [comment]
Did you try adding something like this in your pod file?

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['SideMenu'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end
```

**Comment by DominikButz** [comment]
yes, I could do that. But the more elegant and clean way is to add the information to the pod spec file.

**Comment by Wenzhi** [comment]
I support the idea! It definitely make more sense to put the requirement in the podspec file instead of making every library user add extra identical code to their podfile, or ask them to change the pod project's swift version every time they run `pod install/update`.

**Comment by jonkykong** [comment]
This is in for 5.0.2.
