### ISSUE TITLE
Showing error "Command PhaseScriptExecution failed with a nonzero exit code"

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [jonkykong/SideMenu#416]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I have implemented sidemenu in XCode 9 and that was working perfectly. After updation of Xcode 10 it starting to show me following error:

```
fatal error: lipo: can't open input file: /Users/chandra/Library/Developer/Xcode/DerivedData/SpeedMeter-deohoxswhbobltcedqxligizuuxm/Build/Products/Debug-iphonesimulator/SpeedMeter.app/Frameworks/SideMenu.framework/SideMenu-x86_64 (No such file or directory)
rm: /Users/chandra/Library/Developer/Xcode/DerivedData/SpeedMeter-deohoxswhbobltcedqxligizuuxm/Build/Products/Debug-iphonesimulator/SpeedMeter.app/Frameworks/SideMenu.framework/SideMenu-x86_64: No such file or directory
Replacing original executable with thinned version
mv: rename /Users/chandra/Library/Developer/Xcode/DerivedData/SpeedMeter-deohoxswhbobltcedqxligizuuxm/Build/Products/Debug-iphonesimulator/SpeedMeter.app/Frameworks/SideMenu.framework/SideMenu-merged to /Users/chandra/Library/Developer/Xcode/DerivedData/SpeedMeter-deohoxswhbobltcedqxligizuuxm/Build/Products/Debug-iphonesimulator/SpeedMeter.app/Frameworks/SideMenu.framework/SideMenu: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by jonkykong** [comment]
This problem has nothing to do with SideMenu. There’s something wrong with your project, you should try cleaning out your drive data and compiling again.

**Comment by nitishmaropost** [comment]
That's not true. I downloaded the code from your master branch and compiled it. Getting the same error.
