### ISSUE TITLE
Handling safe area insects for landscape mode (Notch cutting menu in iPhone X and above)

### ISSUE THREAD

**Issue by aksswami** [jonkykong/SideMenu#417]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Any idea, how to handle the safe area insect for the side menu transition? I am trying to use the side menu (left) in portrait and landscape mode. For portrait mode safe area insect is zero so it doesn't have any issue. But in case of landscape, I have 44.0 safe area insect, but the side menu disregards this and starts from zero. And when the menu gets closed this will end up a jerky animation.

This is important for iPhone X, XS and above, as they have notch and I don't want menu cells cut off by notch.

Thanks in advance.

**Comment by jonkykong** [comment]
This is not an issue with SideMenu. This is a question for StackOverflow.com.

**Comment by aksswami** [comment]
@jonkykong This is an issue with SideMenu lib itself, I will try to create a demo project as soon as possible. 

SideMenu doesn't respect the SafeArea insects and this needs to be handled in the library itself. You can see this issue easily with latest iPhone Simulators and presentation mode "slideOut".

**Comment by petr-fiala** [comment]
@aksswami did you find any workaround?
