### ISSUE TITLE
Swipe behaviour of the side menu comes in all screens.

### ISSUE THREAD

**Issue by rohith-experion** [jonkykong/SideMenu#418]
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
Swipe behaviour of the side menu comes in all screens, not able to exclude the unwanted screens.
May be it's because of the same navigation stack, but there should be an option to avoid the swipe feature in some screens.
SideMenuManager.default.menuEnableSwipeGestures is not working.
NB : This issue only comes with the viewcontrollers that's pushed from the side menu integrated controller and not on the presented viewcontrollers.

**Comment by jonkykong** [comment]
It's very unlikely this is a SideMenu bug. If you're adding gestures to a navigation controller, it will be shown on all screens within that navigation controller. `menuEnableSwipeGestures` is only for menu dismissal.

**Comment by AndyDunn** [comment]
So @jonkykong what's the best way to prevent this swipe gesture on all screens? For example after the menu is closed, I don't want the user to be able to pull it open again by swiping from the left.

**Comment by AndyDunn** [comment]
Actually, it seems this code removes the gestures, if called in `viewDidLoad`.

`self.navigationController?.view.gestureRecognizers = nil`
