### ISSUE TITLE
With XCODE 10.1 AND POD INSTALLATION WITH COCOAPOD 1.6.0 BETA.2 any class of SideMenu called in the ViewDidLoad doesn't appear 

### ISSUE THREAD

**Issue by dipcse07** [jonkykong/SideMenu#422]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I am Using latest XCODE and cocoapod 1.6.0 beta.2 and installed SideMenu but after import SideMenu  there was not error message . But when I tried to call The SideMenuManager or any of ther classes the xcode does not recognize that Class and auto completion does't show any referrence of those classes...

So I checked The Linked Framework and Libreries 
 
![sidemenu classes not responding](https://user-images.githubusercontent.com/19185636/48044746-c4186d00-e1b7-11e8-8bf1-93be7428ba8b.png)

So I added SideMenu.framework to the linked framework and Libreries and then that problem was solved . 

![sidemenu](https://user-images.githubusercontent.com/19185636/48045058-fd051180-e1b8-11e8-960b-834749e1d43c.png)

Now the if i call any class from sidemenu it works.. I guess it's a minor bug of xcode or cocoapod...
But for learners like me It will be very helpfull if you mention to add SideMenu.framework to the Linked 
Framework and Libreries   before importing SideMenu to any project class...

Thanks for this pod and continue your good work...

**Comment by jonkykong** [comment]
You forgot to import `SideMenu`.

**Comment by dipcse07** [comment]
As I had said... I had imported SideMenu to my ViewController Class.. but before linking the SideMenu.framework the the xcode IDE did not show any suggestion or even recognize any subclass call to my view controller
