### ISSUE TITLE
open side menu from child controller 

### ISSUE THREAD

**Issue by MhmdRizk** [jonkykong/SideMenu#424]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello, my issue is that when I open the side menu, and navigate into a child controller inside it ,
the child controller is not inheriting the side menu navigation bar button , 
I want to check if there is a feature that allows the child to inherit the side menu button, and allow toggling the side menu from inside the child screen, not navigating back home.

**Comment by jonkykong** [comment]
This is a general coding question not specific to SideMenu. Please seek help at stackoverflow.com.

**Comment by MhmdRizk** [comment]
sorry but my question that, is there a feature in this sidemenu to handle this case ?

**Comment by KingOlami** [comment]
is there any?
