### ISSUE TITLE
UITableViewVibrantCell on UITableView

### ISSUE THREAD

**Issue by NTruchaud** [jonkykong/SideMenu#426]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
Hi,
I would like to know if it was possible to use UITableViewVibrantCell on a UITableView (not controller). I can't figure out how to do it.

I'm doing :

```
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = self.tableView(tableView, cellForRowAt: indexPath) as! UITableViewVibrantCell

        cell.blurEffectStyle = SideMenuManager.default.menuBlurEffectStyle

        return cell
    }
```

My UIViewController inherit from UITableViewDataSource and UITableViewDelegate.

Thank you for your help :)

**Comment by jonkykong** [comment]
Yes it's possible. Please take your question to stackoverflow.com for help.

**Comment by NTruchaud** [comment]
If someone can help me on this please :)

https://stackoverflow.com/questions/53515448/uitableviewvibrantcell-on-uitableview

Thank you guys !
