### ISSUE TITLE
return homevc like amazon or twitter

### ISSUE THREAD

**Issue by javmorales** [jonkykong/SideMenu#427]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
How i can return to my homeVC from side menu like amazon or twitter, thank u

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.
