### ISSUE TITLE
SlideMenu version 5.0+ doesn't support iOS 8 as minimum target

### ISSUE THREAD

**Issue by shubham321mishra** [jonkykong/SideMenu#428]
<img width="532" alt="screenshot 2018-11-28 at 4 39 44 pm" src="https://user-images.githubusercontent.com/26704035/49148120-7dd4aa80-f32c-11e8-89ed-83a2446ca891.png">

I am having minimum build target as iOS 8.0(compulsory in our case), And i am planning to convert my swift 3 code to swift 4.2. But the problem is if i use 5.0.3 version of SlideMenu Pod, it supports iOS 10 onwards. Now project is big enough so i am stuck. Please help!

**Comment by jonkykong** [comment]
Use an older version.
