### ISSUE TITLE
Call Side Menu in Each Child View Controller

### ISSUE THREAD

**Issue by ininex** [jonkykong/SideMenu#43]
Hi jonkykong, your side menu is awesome, looks really smooth and responsive. My purpose is to build a menu similar to that of Lyft or Uber: each child view controller should be able to call this menu independently without a intermediate step to go back to "home" screen. In your example, each child view controller is triggered by a push segue but then the menu button just redirects me to the main screen instead of the menu. In my own code, I used 
`presentViewController(SideMenuManager.menuLeftNavigationController!, animated: true, completion: nil)` 
for the menu button but the automatic generated "back" button will always should on the top of my menu button to prevent me from doing the right thing and then I will go back to the initial screen... Is there any neat way to make your menu behave like a normal slide-out menu?

**Comment by jonkykong** [comment]
The library is very straight forward. If you want to show the menu from any
screen, just add button with the appropriate segue where you want it to
appear. If you want gesture support, then those need to be added in code
when that view controller loads.

**Comment by ininex** [comment]
Thanks for your confirmation. I realized I made a mistake in code.

**Comment by dimovskidamjan** [comment]
@ininex How did you end up implementing this? I'm looking for the same implementation as you described in your original question.
