### ISSUE TITLE
Use of menuAllowPushOfSameClassTwice if there are multiple entries with the same class

### ISSUE THREAD

**Issue by richardtop** [jonkykong/SideMenu#430]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

My side menu has multiple controllers of the same class, populated with different data.
The menu structure looks like this:

ControllerClass1 - Home
ControllerClass1 - News
ControllerClass2 - Settings
ControllerClass3 - More

The effect I'm trying to achieve is not to push a new controller in case it shows the same screen.
But if the user switches e.g. from "Home" to "News", i.e. the controllers are of the same class, so no push occurs.
Is there any way to achieve similar behavior without creating a separate classes for Home and News?

**Comment by jonkykong** [comment]
Create a simple subclass of your common class for each screen.
