### ISSUE TITLE
iPhone PortraitUpsideDown Orientation reverts to Portrait when pushing to menu navigation

### ISSUE THREAD

**Issue by cerupcat** [jonkykong/SideMenu#432]
I have an iPhone app that supports `UIInterfaceOrientationMask.portrait` and `UIInterfaceOrientationMask.portraitUpsideDown` and a SideMenu of type `subMenu`. When orientation is `.portraitUpsideDown` and I push a new view controller within the SideMenu, the orientation is forced back to `.portrait`. This only happens the first time. If the SideMenu is re-opened and the same ViewController is pushed, it will remain in the correct orientation.

I've tried setting the shouldAutorotate and supportedInterefaceOrientations on the SideMenuNavigation and each submenu viewcontroller, but nothing seems to work. 

```
extension UISideMenuNavigationController {

    override open var shouldAutorotate: Bool {
        return true
    }

    override open var supportedInterfaceOrientations: UIInterfaceOrientationMask {
            return [UIInterfaceOrientationMask.portrait, UIInterfaceOrientationMask.portraitUpsideDown]
    }
```

Is there somewhere else the SideMenu should know about the expected orientation?

**Comment by jonkykong** [comment]
There is nothing else in SideMenu that would be causing this behavior to my knowledge - no specific loading of this functionality. This is either a bug in Apple code or there's something you're missing in your solution the problem. Try investigating the child controllers as well as the navigation controllers, or using subclasses instead of extensions.

**Comment by cerupcat** [comment]
@jonkykong My implementation is fairly basic, so I'll see if I can get a sample project together to illustrate it.

**Comment by cerupcat** [comment]
@jonkykong I was able to reproduce this on the sample project, however, it appears to only occur on older devices (independent of iOS version). So I'm going to say it's an iOS bug.
