### ISSUE TITLE
Getting multiple issue when installing SideMenu

### ISSUE THREAD

**Issue by yasodhar12590** [jonkykong/SideMenu#433]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [y ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [y] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [y] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [y] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [y] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Issue is**
I followed the instructions to install SideMenu using cocoapods. When I build and run im getting multiple errors. Please see the screenshot attached. 
My xcode version - 10.0
Swift version - 4.2

What could be the issue? Someone please guide

**Screenshots**

<img width="442" alt="screen shot 2018-12-24 at 6 56 10 pm" src="https://user-images.githubusercontent.com/43932735/50400577-aa55d800-07ad-11e9-92f1-5c8560b41d56.png">

**Comment by limadeveloper** [comment]
The latest version works fine for me. As I can see in your screenshots, you need to update SideMenu pod.

Make sure you set the latest version in your Podfile:
```ruby
pod 'SideMenu', '~> 5.0'
```
and run 
```script
pod repo update; pod update
```

**Comment by yasodha12590** [comment]
I already have updated to 5.0. But still im getting the same error.

**Comment by limadeveloper** [comment]
Have you try to create a new sample project?

**Comment by limadeveloper** [comment]
I've do this few minutes ago, and everything works as I expected. 

<img width="748" alt="screen shot 2018-12-24 at 15 14 24" src="https://user-images.githubusercontent.com/12019206/50404439-052c0700-078f-11e9-8dd0-d7c31f8fb4dc.png">

**Comment by limadeveloper** [comment]
Ok, README file has instructions to install SideMenu, supporting Swift 4.1

<img width="950" alt="screen shot 2018-12-24 at 15 58 27" src="https://user-images.githubusercontent.com/12019206/50404984-66ef6f80-0795-11e9-8d65-35761dc7d725.png">

**Comment by yasodha12590** [comment]
Yes. I tried with both the versions 4.0.0 and 2.3.4.
What I did is,
1. I created a sample project
2. I added pod SideMenu (tried with all the mentioned versions)
3. I did pod install
4. Compiling the project gives me those issues above. 
My xcode version - 9.4.1 and swift version - 4.1

What Am I missing here?

**Comment by yasodha12590** [comment]
I haven't changed anything. But now version 4.0 works for me.  Thanks for your help.
