### ISSUE TITLE
when open sidemenu for second time cells dose not expand and collapse

### ISSUE THREAD

**Issue by MohsenMoghimi** [jonkykong/SideMenu#434]
I implemented expandable cells in my side menu . when side menu shows for first time every thing works great but for second time and after that when open side menu tableview cells dose not expand and collapse. what should i do???!?!?!?!?!?!??!?!?!?!**

**Comment by jonkykong** [comment]
Menus aren't released from memory for speed. Reset your content to its original state on each new appearance.

**Comment by romeugodoi** [comment]
> Menus aren't released from memory for speed. Reset your content to its original state on each new appearance.

Hello!.. Can you explain it better please? I've this problem too.

**Comment by romeugodoi** [comment]
@jonkykong ☝️

**Comment by jonkykong** [comment]
@romeugodoi these are fundamental developer concepts. Please seek help on stackoverflow.com.

**Comment by romeugodoi** [comment]
@jonkykong I had confused the question, so I opened another issue, forget this questioning.
