### ISSUE TITLE
PresentedViewController deinit not called

### ISSUE THREAD

**Issue by josipbernat** [jonkykong/SideMenu#435]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**
1. Download SideMenu from master branch and open up SideMenu.xcworkspace
2. Choose Example from targets menu
3. Open up PresentedViewController and override deinit. Put breakpoint there
4. Run example project, open up left / right side menu and pick one of options. After you press dismiss (when presenting modally) or back button (when being pushed) deinit won't be called.

**Expected behavior**
After dismissing view controller or after pop to root view controller, view controller should release from memory.

**Comment by jonkykong** [comment]
This is by design. View controllers are held on to to ensure fast side menu responsiveness with gestures. You can set the side menu to nil when it disappears if you don't want it to be held.

**Comment by xakacuk** [comment]
@jonkykong Hi! I can’t understand where and what code I need to write, please help

> This is by design. View controllers are held on to to ensure fast side menu responsiveness with gestures. You can set the side menu to nil when it disappears if you don't want it to be held.
