### ISSUE TITLE
Sidemenu present problem.

### ISSUE THREAD

**Issue by riteshpatel0** [jonkykong/SideMenu#436]
Hello,

sometime, when i open the menu it open like normally(It push to open menu view controller.) and sometime menu controller is opening it's presenting the menu view controller. I was tried to nil leftsidemenucontroller, but my issue is not solved. I thought navigationcontroller is nil, but i also get the navigation controller. 

thanks.

**Comment by jonkykong** [comment]
Please follow the README instructions carefully.
