### ISSUE TITLE
Present VC modally from menu

### ISSUE THREAD

**Issue by LuisBelo** [jonkykong/SideMenu#437]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When i click on menu item, i want to show a vc modally. I use self.navigationController?.present(tutorialPager, animated: true, completion: nil) in my class to do this. But, when i back to main VC (VC that have menu button) the menu presentation is showed like full screen modal and not left menu.

**Comment by t0milee** [comment]
@LuisBelo I have the same problem, was this resolved somehow, did you find a solution?

**Comment by fvonk** [comment]
+++

**Comment by LuisBelo** [comment]
I'll see this problem later. I think that this issue was solved, I don't remember how. I put the resolution at night if possible

**Comment by LuisBelo** [comment]
sorry for being late, I forgot! To "solve" this problem I use present on navigation. Example:
`        let yourVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "yourVC") as! YourVC
        yourVC.fromMenu = true
        self.navigationController?.present(yourVC, animated: true, completion: nil)`

If this solves your problem, give me feedback.

**Comment by LuisBelo** [comment]
This is on MenuViewController. Add gesture for button and on click event call "navigationController?.present..."

**Comment by LuisBelo** [comment]
Strangely it worked. I do not remember what I did besides, I will investigate. Tell me the result you had.
