### ISSUE TITLE
When open sidemenu for second time, menu view controller does not expand and collapse anymore

### ISSUE THREAD

**Issue by romeugodoi** [jonkykong/SideMenu#440]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When side menu shows for first time every thing works great, but from the second time when open side menu the menu view controller and another view controllers begins to be shown as a normal present modally upwards and not a left side animation.

**To Reproduce**
1. Create a Menu ViewController on storyboard like on the readme;
2. Make 2 segues (modally or push) from Menu VC tableViewCell to Another 2 different NavigationViewController with a menu button inside navbar to present Menu VC;
3. After open menu from the second time in one of the another 2 VC, the menu animation left-side not work anymore.

I look on the README and in Demo project but without success until now.

Can anyone help me?

**Comment by jonkykong** [comment]
@romeugodoi if you can reproduce your problem using the demo project then it is a bug, otherwise it sounds more like a problem with how you set it up in your project, or another bug altogether. Please investigate further.

**Comment by romeugodoi** [comment]
@jonkykong I can reproduce it using the demo project exactly like i wrote above (look
 the screeshot). 
I can't create a segue from a CHILD of another UINavigationController directly to the UISideMenuNavigationController

**Segue on SB**
![captura de tela 2019-01-30 as 13 35 36](https://user-images.githubusercontent.com/556442/51992511-400f1200-2494-11e9-90cb-defb32ab5275.png)

**After it:**
![image](https://user-images.githubusercontent.com/556442/51993023-35a14800-2495-11e9-86b1-3c8c82f182a3.png)
