### ISSUE TITLE
how to use side menu with tab bar controller

### ISSUE THREAD

**Issue by PramodShukla10** [jonkykong/SideMenu#442]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shayneoneill** [comment]
Did you forget to fill in the template?

**Comment by PramodShukla10** [comment]
How to solve this issue?

**Comment by shayneoneill** [comment]
Use the template dude. Theres a process.
