### ISSUE TITLE
Side menu should appear from Every view controller in menu table it self

### ISSUE THREAD

**Issue by PrashantKT** [jonkykong/SideMenu#443]
Hey thanks for amazing library I have read full readme.txt file but I have question 

What I was expected is Suppose in left menu I have 3 items 
Left1
left2
left3

and at a time Left1 is selected means Left1 is  in center view controller 

Now When I select left2 I wanted to left 2 to be center view controller and from left2 There should be drawer button  also to change further from Left1 and Left3

Is it possible with current implementation ? Please suggest     

Just like

![simulator screen shot - iphone 8 - 2019-02-05 at 16 59 05](https://user-images.githubusercontent.com/35359315/52270570-625ad100-2967-11e9-86ee-0339389f01c9.png)

![simulator screen shot - iphone 8 - 2019-02-05 at 16 59 06](https://user-images.githubusercontent.com/35359315/52270581-6d156600-2967-11e9-948f-6a2161a1ead9.png)

![simulator screen shot - iphone 8 - 2019-02-05 at 16 59 02](https://user-images.githubusercontent.com/35359315/52270584-70105680-2967-11e9-8634-3cd5ec22e4e3.png)

**Comment by jonkykong** [comment]
It's possible. Read the README.

**Comment by PrashantKT** [comment]
@jonkykong  Thanks for reply .

I have question then. 

I need to set `SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController` In every view controller where  ever I  . want to show Side menu ?
