### ISSUE TITLE
Not using navigationcontroller

### ISSUE THREAD

**Issue by KingOlami** [jonkykong/SideMenu#444]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ x] My issue is happening in the **latest version** of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Awesome Library, I want to ask if it is possible to use this library without using Navigation controller for the MainViewController. In my application, I do not want to use a Navigation controller. is this possible and how do I go about it?

**Comment by jonkykong** [comment]
Use a navigation controller. Turn off the navigation. It looks the same.
