### ISSUE TITLE
Drawer is taking over whole screen

### ISSUE THREAD

**Issue by philipborbon** [jonkykong/SideMenu#446]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Drawer is taking over whole screen after presenting initial view controller from drawer view.

**To Reproduce**
1) Launch initial view controller from drawer view controller i.e.
```
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    let storyBoard = UIStoryboard(name: "Main", bundle: Bundle.main)

    if let viewController = storyBoard.instantiateInitialViewController() {
        viewController.modalTransitionStyle = .crossDissolve
        present(viewController, animated: true, completion: nil)
    }
}
```

**Expected behavior**
Drawer should not take whole screen.

**Screenshots**
<img src="https://user-images.githubusercontent.com/31846503/54176246-113f7f00-44c9-11e9-8c3f-811373830001.png" width="300" height="533"/>
<img src="https://user-images.githubusercontent.com/31846503/54176247-113f7f00-44c9-11e9-9fa7-4797f23d6246.png" width="300" height="533"/>

**Comment by jonkykong** [comment]
Don’t set the mod transition style.

**Comment by philipborbon** [comment]
Removing modalTransitionStyle is still showing same behavior.

```
let storyBoard = UIStoryboard(name: "Main", bundle: Bundle.main)
```

Main.storyboard is the same storyboard where it's presented from.

**Comment by jonkykong** [comment]
The steps are not reflecting my suggested change. This should be your code:
```swift
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    let storyBoard = UIStoryboard(name: "Main", bundle: Bundle.main)

    if let viewController = storyBoard.instantiateInitialViewController() {
        // viewController.modalTransitionStyle = .crossDissolve
        present(viewController, animated: true, completion: nil)
    }
}
```

**Comment by philipborbon** [comment]
With or without it, it causes same behavior in drawer. This happens only when the presented controller is the same navigation controller connected to SideMenu.

It's presenting ok, but opening the right menu again takes over the whole screen.

I think, I will change my approach that I don't have to present again the view controller connected to Drawer.

**Comment by jonkykong** [comment]
Please provide a modified demo project that demonstrates the behavior.
