### ISSUE TITLE
Extra space in viewSlideInOut 

### ISSUE THREAD

**Issue by toseefkhilji** [jonkykong/SideMenu#447]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
There some extra space with .viewSlideInOut mode when menu presents.

**To Reproduce**
1. Set menu Present mode to .viewSlideInOut
2. set width 60%
3. set .menuAnimationTransformScaleFactor = 0.8

**Expected behavior**
There should be no extra space.

**Screenshots**
![Simulator Screen Shot - iPhone 8 Plus - 2019-03-12 at 16 47 46](https://user-images.githubusercontent.com/2367614/54196578-c719c600-44e7-11e9-981d-736fa73b46ec.png)

**Additional context**

**Comment by jonkykong** [comment]
The space is due to the transform. This is by design.
