### ISSUE TITLE
Menu Closed Auto Closed When applicationenterbackground

### ISSUE THREAD

**Issue by fcoskun** [jonkykong/SideMenu#448]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.

## Issue Description

Side menu closed when i click home button, how i can we prevent this. I want to stay opened enterbackground and didbecomeactive. How will i do that?

**Comment by jonkykong** [comment]
By design. Please read the README carefully.

**Comment by fcoskun** [comment]
I read it carefully. You dont have to help me but i asked two times but i dont know why you closed the issue.

**Comment by jonkykong** [comment]
Unfortunately this is missing from the README, I stand corrected:

```swift
    /// Automatically dismisses the menu when app goes to the background.
    open var menuDismissWhenBackgrounded = true
```

**Comment by jonkykong** [comment]
Sorry I get a lot of simple questions from devs that don't read the README and my time is very limited hence my quick closures.
