### ISSUE TITLE
Menu bar is not show correctly

### ISSUE THREAD

**Issue by ok31719** [jonkykong/SideMenu#450]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I having a problem with my project. I followed code-less strotyboard implementation. My menubar isn't show correctly as you can see my pictures below.  I also read a example of yours but I could not find solution. Thank you. Sorry for your inconvenience.
<img width="914" alt="Screen Shot 2562-03-17 at 23 58 47" src="https://user-images.githubusercontent.com/37831372/54494828-06de1480-4911-11e9-84a1-3bbf03a93696.png">
<img width="466" alt="Screen Shot 2562-03-18 at 00 01 31" src="https://user-images.githubusercontent.com/37831372/54494829-06de1480-4911-11e9-91e7-ad12baafadce.png">

**Comment by jonkykong** [comment]
You’re adding your navigation bar manually which is atypical. This is a question for stackoverflow.com.

**Comment by ok31719** [comment]
May I ask you how to solve the problem. I have posted this problem on the stackoverflow and I am waiting for the answer but If you can help. It will much more easier. Thank you
