### ISSUE TITLE
Question - cleanest way to setup 'open menu' button in each presented VC

### ISSUE THREAD

**Issue by az-oolloow** [jonkykong/SideMenu#451]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com). -> Maybe, but there is no tag which to use specified?

- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I am using the storyboard declarative setup as outlined in Readme and the sample project.

Unfortunately, it is not immediately clear on what is the cleanest way to set this up so that the navigation bar item in each of the `push` presented view controllers would take the user to the menu, not BACK to the initial VC.

I found that i can override the left bar item in the storyboard and just setup the segue to the side menu again; all that's left to do then is `popViewController` in the handler for my menu item so that we don't end up with leaky duplicates.

Unfortunately, this is somewhat laborious (i plan to have some 14 menu items) because i have to setup a segue and a button for each VC. Is there a smarter way that i am missing?

**Comment by jonkykong** [comment]
This is answered in the README.

**Comment by az-oolloow** [comment]
@jonkykong i am sorry, i read `README` several times, both before and after you mentioned it.

All it says in the readme that is semi-relevant is `Global menu configuration. Set-up once and be done for all screens.`

There is also a `Set up any Triggered Segues you want in that view controller. ` 

Could you maybe point me to WHERE in the README does it say how to wire opening the menu from all the derived controllers left bar items?
