### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by usamabinattique** [jonkykong/SideMenu#452]
![Screenshot 2019-03-19 at 12 20 22 PM](https://user-images.githubusercontent.com/24874043/54587405-d053e700-4a41-11e9-885f-50fb92f94430.png)

I would like to add a button that would extend the trailing edge to meet my requirements. Will you point me in the right direction to achieve the desired output

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com
