### ISSUE TITLE
Doesn't work with reusable cell UITableViewController (can't find cell by ID) 

### ISSUE THREAD

**Issue by anonym24** [jonkykong/SideMenu#455]
```
class ViewControllerTable: UITableViewController {

     ...

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MyTableViewCell", for: indexPath) as! KpopTableViewCell
        
        return cell
    }

}
```

So I set this VC to your SideMenu API:

`UISideMenuNavigationController(rootViewController: ViewControllerTable())`

But when I try to open SideMenu it crashes with:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier MyTableViewCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'`

![image](https://user-images.githubusercontent.com/8851301/54882184-17861180-4e60-11e9-8f9e-b16b0756a208.png)

`ViewControllerTable` works fine if I start it with navigation controller as root VC instead of SideMenu:

![image](https://user-images.githubusercontent.com/8851301/54882269-e6f2a780-4e60-11e9-8276-4dbd8ec34997.png)

Full code:

```
let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: ViewControllerTable())
SideMenuManager.default.menuLeftNavigationController = menuLeftNavigationController
        SideMenuManager.default.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.default.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
SideMenuManager.default.menuFadeStatusBar = false

// start
present(SideMenuManager.default.menuLeftNavigationController!, animated: true, completion: nil)
```

**Comment by anonym24** [comment]
For now I will use static cells. But it's still an issue when it doesn't work with dynamic cells and can't find cell to reuse by id

**Comment by jonkykong** [comment]
@anonym24 there's absolutely nothing preventing you from using dynamic cells from SideMenu. You're running into a basic coding problem. Please ask this question on StackOverflow.com.

**Comment by anonym24** [comment]
@jonkykong  it's not a coding problem. Because Table View Controller works fine with dynamic cells if I don't use your library but just starting this VC with default navigation controller 

Did you try it yourself or did you only test with static cells?

**Comment by jonkykong** [comment]
This is not a SideMenu issue.

The way you programmatically loaded your menu does not use storyboard, which means your cells are not registered so you have to register them programmatically.

Follow the README for an example of how to load your menu from the storyboard in code.
