### ISSUE TITLE
Is it possible to have different presentation styles for each menu?

### ISSUE THREAD

**Issue by andrewfashion** [jonkykong/SideMenu#456]
I would left the menuPresentMode to be different for each menu. The left would be it's own effect, and the right would come in differently, is that possible? Thanks!

**Comment by andrewfashion** [comment]
I just saw something somewhat similar I think issue #78 . But I am actually not to familiar on how to subclass each side menu, would anyone be a gentleman and a scholar and maybe show a little example? Thank you so much !

**Comment by andrewfashion** [comment]
@jonkykong Would love some suggestions if you have time! :)

**Comment by jonkykong** [comment]
You can change the present style in the menu just before you present it for now. A future update will split this logic so you can assign different animations, but I have limited time to get it together.
