### ISSUE TITLE
Keeping the menu open for some items

### ISSUE THREAD

**Issue by richardtop** [jonkykong/SideMenu#458]
SideMenu currently meets the majority of people's needs with the features it already has. However, this is a great opportunity for you to [join the proud members](https://github.com/jonkykong/SideMenu/graphs/contributors) who have contributed to this open source project! Feel free to open an issue to ask any clarifying questions for your new feature before you start building. Open a [pull request](https://github.com/jonkykong/SideMenu/pull/new/master) when you're ready for me to merge it.

**Describe the solution you'd like**
Is there a way to keep the menu open for some tabs, similar to UISplitViewController on iPad, while keeping the selected tab with a smaller width.

The end result should look to `UISplitViewController` with `preferredDisplayMode = .allVisible`.

It should be possible to select, clicking on which rows would not hide the menu.

**Comment by jonkykong** [comment]
The README details how to keep the menu open after a selection.

**Comment by richardtop** [comment]
Yes, but the detail controller is not resized to a “split view” size. This is a different task 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
