### ISSUE TITLE
When push a view controller and go back not viewWillAppear called !

### ISSUE THREAD

**Issue by wonder2011** [jonkykong/SideMenu#460]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [X ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

When i open sideMenu and from there push a view controller, when pop to main screen of app the viewWillAppear and viewDidAppear from this viewcontroller is not called.
**To Reproduce**

**Expected behavior**
View Controller viewWillAppear and viewDidAppear not called.
**Screenshots**

**Additional context**

**Comment by jonkykong** [comment]
Please provide a modified version of the demo project that shows this behavior and reopen this issue.
