### ISSUE TITLE
Home screen controller is a UINavigationController.  Pushing a UISideMenuNavigationController seems odd, and making my rootview a UISideMenuNavigationController results in error.

### ISSUE THREAD

**Issue by bhartsb** [jonkykong/SideMenu#461]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
My app's home screen controller is a UINavigationController.  Pushing a UISideMenuNavigationController onto the homescreen UINavigationController seemed odd, but making my rootview a UISideMenuNavigationController instead of a UINavigationController as below results in error. 'Application tried to present modal view controller on itself. Presenting controller is <MyApp.UISideMenuNavigationController: 0x1070cea00>.'

`DispatchQueue.main.async {
            
            let storyBoard = UIStoryboard(name: "HomeScreen", bundle: nil)
            let controller = storyBoard.instantiateViewController(withIdentifier: "HomeScreenViewController")
            let navigationController = UISideMenuNavigationController(rootViewController: controller)
            
            let appDelegate = UIApplication.shared.delegate as! AppDelegate
            
            appDelegate.window!.rootViewController = navigationController
        }`

When I do it the other way, rootview controller is just a UINavigationController and UISideMenuNavigationController is pushed then when the menu row is selected and pushes another view and then returns it doesn't go to the side menu rather unwinds all the way back.  

`DispatchQueue.main.async {
            
            let storyBoard = UIStoryboard(name: "HomeScreen", bundle: nil)
            let controller = storyBoard.instantiateViewController(withIdentifier: "HomeScreenViewController")
            let navigationController = UINavigationController(rootViewController: controller)
            
            let appDelegate = UIApplication.shared.delegate as! AppDelegate
            
            appDelegate.window!.rootViewController = navigationController
        }`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bhartsb** [comment]
Possibly the answer here is that a UISideMenuNavigationController is being presented not pushed.  If that is the case then my rootview controller being a UINavigationController is fine since the UISideMenuNavigationController is being presented over it.  Please confirm. Thanks.

**Comment by jonkykong** [comment]
Please follow the README carefully. You present SideMenu, not push.

**Comment by bhartsb** [comment]
That is what I said in my second comment.  However, there is still an issue of when I present UISideMenuNavigationController on the right side, and then from the side menu push seque the closing of UISideMenuNavigationController causes an unwanted visual artifact (it closes the UISideMenuNavigationController and then seques) . In your example program you have a UISideMenuNavigationController on the left side that pushes so this artifact isn't appearing during the seque.

**Comment by jonkykong** [comment]
I changed the demo project to do as you said and it works exactly as expected.
