### ISSUE TITLE
Is possible to have in iPad the menu controller fixed opened and to show CenterController?

### ISSUE THREAD

**Issue by HaraldBregu** [jonkykong/SideMenu#462]
SideMenu currently meets the majority of people's needs with the features it already has. However, this is a great opportunity for you to [join the proud members](https://github.com/jonkykong/SideMenu/graphs/contributors) who have contributed to this open source project! Feel free to open an issue to ask any clarifying questions for your new feature before you start building. Open a [pull request](https://github.com/jonkykong/SideMenu/pull/new/master) when you're ready for me to merge it.

**Describe the solution you'd like**

**Ask any questions you have related to developing your solution**
A clear and concise set of questions you'd like to ask.

**Comment by jonkykong** [comment]
This is the entire purpose of a split view controller. Use that instead of SideMenu.

**Comment by HaraldBregu** [comment]
Thanks, i'm using it.
