### ISSUE TITLE
Status bar gets cut

### ISSUE THREAD

**Issue by alex-vydrin** [jonkykong/SideMenu#465]
I'm using the menu Slide Out type, when dragging menu by screen edge pan gesture and release the finger in less then a middle of menu width it goes back (hides), but the status bar gets cut with menuAnimationBackgroundColor from top. The logic for hiding this view is located in SideMenuTransition.hideMenuStart() but it's not called if transition was interrupted and not completed.

1. Set menuAnimationBackgroundColor
2. Drag the menu by screen edge pan gesture
3. Release the finger as the menu partly appears on the screen
4. See the cut of status bar.

In such case (releasing the finger with partly shown menu) should also remove this top inset. 

Before dragging menu
![IMG_4B2DB0A9C0CF-1](https://user-images.githubusercontent.com/18283203/55780604-015b9080-5ab1-11e9-8716-606f83124ebb.jpeg)

Release the finger during screen edge pan gesture
![IMG_92BD7EEB2163-1](https://user-images.githubusercontent.com/18283203/55783583-6ade9d80-5ab7-11e9-9163-888e7fa6e221.jpeg)

Menu is hidden, but the status bar is cut.
![IMG_04E79942BFA2-1](https://user-images.githubusercontent.com/18283203/55780387-767a9600-5ab0-11e9-95c5-7b81720fb933.jpeg)

 Thanks for helping.

**Comment by jonkykong** [comment]
Does this happen in the demo project?

**Comment by steveGates890** [comment]
> I'm using the menu Slide Out type, when dragging menu by screen edge pan gesture and release the finger in less then a middle of menu width it goes back (hides), but the status bar gets cut with menuAnimationBackgroundColor from top. The logic for hiding this view is located in SideMenuTransition.hideMenuStart() but it's not called if transition was interrupted and not completed.
> 
> Steps to reproduce the behavior:
> 
>     1. Set menuAnimationBackgroundColor
> 
>     2. Drag the menu by screen edge pan gesture
> 
>     3. Release the finger as the menu partly appears on the screen
> 
>     4. See the cut of status bar.
> 
> 
> In such case (releasing the finger with partly shown menu) should also remove this top inset.
> 
> Before dragging menu
> ![IMG_4B2DB0A9C0CF-1](https://user-images.githubusercontent.com/18283203/55780604-015b9080-5ab1-11e9-8716-606f83124ebb.jpeg)
> 
> Release the finger during screen edge pan gesture
> ![IMG_92BD7EEB2163-1](https://user-images.githubusercontent.com/18283203/55783583-6ade9d80-5ab7-11e9-9163-888e7fa6e221.jpeg)
> 
> Menu is hidden, but the status bar is cut.
> ![IMG_04E79942BFA2-1](https://user-images.githubusercontent.com/18283203/55780387-767a9600-5ab0-11e9-95c5-7b81720fb933.jpeg)
> 
> Thanks for helping.

Youv've to just add 
`SideMenuManager.default.menuFadeStatusBar = false`

**Comment by alex-vydrin** [comment]
SideMenuManager.default.menuFadeStatusBar is false. Also this appears in demo @jonkykong :
![image](https://user-images.githubusercontent.com/18283203/56129445-bea32800-5f8a-11e9-9d7e-428eabfcdef2.png)

**Comment by inamsystemsltd** [comment]
Same issue.

**Comment by steveGates890** [comment]
In demo you only can make `SideMenuManager.default.menuFadeStatusBar` to make `true` or `false` by using `UiSwitch` state `On` and `Off` to perform .

**Comment by inamsystemsltd** [comment]
Problem is menuAnimationTransformScaleFactor when we fiddle with that status bar gets disturbed.

**Comment by jonkykong** [comment]
https://github.com/jonkykong/SideMenu/issues/258
