### ISSUE TITLE
Wrong behavior when swipe fast to opposite visible menu

### ISSUE THREAD

**Issue by joseantoniogarciay** [jonkykong/SideMenu#466]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [X] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
If you swipe to any side, menu is going to be visible, but if you swipe fast to the other side  then "SideMenu" doesn't show the right side menu and the direction is inverted.

**To Reproduce**
See gif attached

**Expected behavior**
Opposite menu must be visible or no menus visible.

**Video**
![BugSideMenu](https://user-images.githubusercontent.com/2782293/56029129-0111fe00-5d1a-11e9-974f-416f848a7e76.gif)

**Comment by jonkykong** [comment]
This issue should now be resolved in version 6.0.0+ of SideMenu. Please run `pod update` and reopen this issue if the problem persists.
