### ISSUE TITLE
Doesn't support a segue to a navigation controller nor reusing the left side menu in other parts of the storyboard

### ISSUE THREAD

**Issue by nkavian** [jonkykong/SideMenu#468]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
If you open the left side menu from other places in the storyboard, you get a wrong width side menu and other buggy behavior.

As a developer, I want to use the left side menu in various places in my storyboard and not just on the main or first controller in the app.

**To Reproduce**
I've modified the storyboard here and is easily reproducible: https://github.com/nkavian/SideMenu/commit/3fffd859f3e415148ea34dca390282a5bbe10d33

1. Embed the red controller into a navigation controller.
2. Add a left bar button named `Left Menu`.
3. Add a modal segue to this button back to the left side menu.
4. Run the app, and open the red page, see that it loads properly.
5. Press the bar button and see that the direction it is presented from is incorrect as well as the width of the side menu.

As well, reproduces: https://github.com/jonkykong/SideMenu/issues/370

**Expected behavior**
I expect the framework to support opening and using the side menu from any view controller.
or
I expect the README to explicitly say this is not a supported feature.

**Comment by Satchitananda** [comment]
Having the same issue

**Comment by jonkykong** [comment]
This issue should now be resolved in version 6.0.0+ of SideMenu. Please run `pod update` and reopen this issue if the problem persists.
