### ISSUE TITLE
Instead of pushing/presenting new controllers return a value to the main controller

### ISSUE THREAD

**Issue by anelad** [jonkykong/SideMenu#472]
**Describe the solution you'd like**
I would like to use the side menu for not pushing/presenting new controllers; instead, I want to return a variable back to the main VC and reload its data using that variable. Maybe using something like delegating.

For example; in a blog app, the side menu lists categories and when the user clicks on a category, the main controller dismisses the old posts and fetch the news posts of that category.

**Ask any questions you have related to developing your solution**
I couldn't find a way in the existing code yet. If it is possible please lead me, else I can implement it and create a PR.

**Comment by aornano** [comment]
I've created a useful extension with a private internal property:

```
extension SideMenuManager {
    private static var _menuCenterNavigationController: UINavigationController?
    var menuCenterNavigationController:UINavigationController? {
        get {
            return SideMenuManager._menuCenterNavigationController ?? nil
        }
        set(newValue) {
            SideMenuManager._menuCenterNavigationController = newValue
        }
    }
}
```

When you set your left and right, you can set also menuCenterNavigationController.
So when you are in the left or right viewcontroller, to pass some property to the center view controller you can do:

```
if let centerVC = SideMenuManager.default.menuCenterNavigationController?.viewControllers.first {
            // do whatever you want with centerVC
}
```

**Comment by jonkykong** [comment]
@anelad you need to create a delegate in your menu and send tap actions back for another controller to react/refresh.

**Comment by Gadiq** [comment]
But how to acces that view controller to set delegate?

**Comment by parveenBanuS** [comment]
hi jonky, can you help me in objective c and swift 4 coding?
because i update the Xcode 10.2 to 10.3 so it affect my coding... can you
please me?
