### ISSUE TITLE
Receiving warning "Low Priority" 

### ISSUE THREAD

**Issue by BanenoLuso** [jonkykong/SideMenu#475]
The side menu is working fine but i'm receiving this warning: 

<CATransformLayer: 0x281580d80> - changing property contentsGravity in transform-only layer, will have no effect
SideMenu Warning: menuAddScreenEdgePanGesturesToPresent was called before menuRightNavigationController was set. The gesture will not work without a menu. Use menuAddScreenEdgePanGesturesToPresent(toView:forMenu:) to add gestures for only one menu.

I'm doing anything wrong?

**Comment by jonkykong** [comment]
Just as the warning states, use the method where you specify the menu. Its safe to ignore the warning too.
