### ISSUE TITLE
menuFadeStatusBar option adds black box after device orientation change

### ISSUE THREAD

**Issue by sarahfmurray** [jonkykong/SideMenu#476]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example). => _I spent an hour trying to get the example project up and running but I couldn't so I don't know if this is replicable in that project or not, sorry._

**Describe the bug**
With the 'menuFadeStatusBar' option set to 'false', the menu is overlaid with a black box after changing the orientation of an iPad from landscape to portrait. It only happens after changing from landscape to portrait, it's working correctly from portrait to landscape. I tried switching the 'menuFadeStatusBar' option off, and it worked as expected without the black box so I'm assuming it's a bug related to that.

**To Reproduce**
1. Set the 'menuFadeStatusBar' option to 'false'
2. Open the menu in landscape orientation on an iPad
3. Rotate the iPad to portrait
4. The menu is now mostly covered with a black box

**Expected behavior**
The menu should always be visible without black boxes covering it.

**Comment by jonkykong** [comment]
Without it being reproduced in the demo project I am not confident if its a bug in SideMenu or in the layout of your application. Please verify in the demo project and reopen this issue as needed.
