### ISSUE TITLE
Functionality in landscape mode?

### ISSUE THREAD

**Issue by JustinM1** [jonkykong/SideMenu#48]
Hey,

The SideMenu has been working great. I have a tableView with static cells for my sidemenu, however, when I'm in landscape mode the menu doesn't scroll so the bottom part is inaccessible. I know the entire menu won't fit on screen in landscape but do you have a recommendation on how to make it so it will scroll in landscape? 

Thanks!

**Comment by jonkykong** [comment]
Your menu needs to implement some form of UIScrollView for that.. You can either embed everything in one yourself, or use a UITableViewController or UICollectionViewController which use UIScrollView.
