### ISSUE TITLE
Global menu configuration. Set-up once and be done for all screens. how can it be done......

### ISSUE THREAD

**Issue by MHamayun** [jonkykong/SideMenu#480]
SideMenu currently meets the majority of people's needs with the features it already has. However, this is a great opportunity for you to [join the proud members](https://github.com/jonkykong/SideMenu/graphs/contributors) who have contributed to this open source project! Feel free to open an issue to ask any clarifying questions for your new feature before you start building. Open a [pull request](https://github.com/jonkykong/SideMenu/pull/new/master) when you're ready for me to merge it.

**Describe the solution you'd like**

**Ask any questions you have related to developing your solution**
A clear and concise set of questions you'd like to ask.

**Comment by jonkykong** [comment]
This issue is not providing enough context or a clear question to give a response.
