### ISSUE TITLE
When i animate the Side Menu diagonally it hide and show the status bar,Like the image below,after animat on the diagonal.

### ISSUE THREAD

**Issue by mbhanen** [jonkykong/SideMenu#487]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** 

- rep
![IMG_E0055](https://user-images.githubusercontent.com/44843385/60104891-a574df80-9762-11e9-8537-9218f67d0e22.JPG)
![IMG_E0056](https://user-images.githubusercontent.com/44843385/60104939-b7ef1900-9762-11e9-8f9c-3b82b2ac934f.JPG)

roducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jonkykong** [comment]
@mbhanen you must complete the template and reproduce your problem in the demo project for me to be able to investigate. You haven't provided any details in this ticket, and there could be other code outside of SideMenu that is causing this issue (which is why you must modify and provide the demo project).

**Comment by mbhanen** [comment]
Thank you. I couldn't send my code because it is professionally.  And you find below a demo.
In the API SideMenu, I just modified the class SideMenuTransition.swift, I added the line  "mainView?.frame.origin.y =  60", in the methodiscardableResult internal func presentMenuStart() -> SideMenuTransition 

it became : 
    @discardableResult internal func presentMenuStart() -> SideMenuTransition {


        let menuView = menuViewController?.view

        let mainView = mainViewController?.view

        

        menuView?.alpha = 1

        menuView?.transform = .identity

        menuView?.frame.size.width = menuWidth

        let size = SideMenuManager.appScreenRect.size

        menuView?.frame.origin.x = presentDirection == .left ? 0 : size.width - menuWidth

       // mainView?.transform = .identity

        mainView?.frame.size.width = size.width

        let statusBarOffset = size.height - (menuView?.bounds.height ?? 0)

        mainView?.bounds.size.height = size.height + statusBarOffset

        mainView?.frame.origin.y = 0

        var statusBarFrame = UIApplication.shared.statusBarFrame

        // For in-call status bar, height is normally 40, which overlaps view. Instead, calculate height difference

        // of view and set height to fill in remaining space.

        if statusBarOffset >= CGFloat.ulpOfOne {

            statusBarFrame.size.height = statusBarOffset

        }

        tapView?.transform = .identity

        tapView?.bounds = mainView!.bounds

        statusBarView?.frame = statusBarFrame

        statusBarView?.alpha = 1

        

        switch sideMenuManager.menuPresentMode {

            

        case .viewSlideOut, .viewSlideInOut:

            mainView?.layer.shadowColor = sideMenuManager.menuShadowColor.cgColor

            mainView?.layer.shadowRadius = sideMenuManager.menuShadowRadius

            mainView?.layer.shadowOpacity = sideMenuManager.menuShadowOpacity

            mainView?.layer.shadowOffset = CGSize(width: 0, height: 0)

            let direction:CGFloat = presentDirection == .left ? 1 : -1

            

            mainView?.frame.origin.x =  -3*(size.width/5)

            mainView?.frame.origin.y =  60

            

        case .menuSlideIn, .menuDissolveIn:

            if sideMenuManager.menuBlurEffectStyle == nil {

                menuView?.layer.shadowColor = sideMenuManager.menuShadowColor.cgColor

                menuView?.layer.shadowRadius = sideMenuManager.menuShadowRadius

                menuView?.layer.shadowOpacity = sideMenuManager.menuShadowOpacity

                menuView?.layer.shadowOffset = CGSize(width: 0, height: 0)

            }

            mainView?.frame.origin.x = 0

        }

        

        if sideMenuManager.menuPresentMode != .viewSlideOut {

            mainView?.transform = CGAffineTransform(scaleX: sideMenuManager.menuAnimationTransformScaleFactor, y: sideMenuManager.menuAnimationTransformScaleFactor)

            if sideMenuManager.menuAnimationTransformScaleFactor > 1 {

                tapView?.transform = mainView!.transform

            }

            mainView?.alpha = 1 - sideMenuManager.menuAnimationFadeStrength

        }

        

        return self
    }

Thank you for your help, I appreciate it ,    Le mardi 25 juin 2019 à 21:30:10 UTC+1, Jon Kent <notifications@github.com> a écrit :  
 
 
Closed #487.
