### ISSUE TITLE
When i animate the Side Menu diagonally it hide and show the status bar,Like the image below,after animat on the diagonal. 

### ISSUE THREAD

**Issue by mbhanen** [jonkykong/SideMenu#488]
When i animate the Side Menu diagonally it hide and show the status bar,Like the image below,after animat on the diagonal. Any help 
![IMG_E0055](https://user-images.githubusercontent.com/44843385/60105708-2385b600-9764-11e9-971d-50cc3bc28e13.JPG)
![IMG_E0056](https://user-images.githubusercontent.com/44843385/60105738-2e404b00-9764-11e9-9c73-88db4c6475ba.JPG)

**Comment by jonkykong** [comment]
@mbhanen can
