### ISSUE TITLE
left menu not closing on single click

### ISSUE THREAD

**Issue by lakhwinder-nextpage** [jonkykong/SideMenu#489]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Comment by lakhwinder-nextpage** [comment]
i am having a table in left side menu and on didselectrow main viewcontroller is opened. I am facing problem that that left sidemenu is not closed on one click it is closing on second click with the option selected on first click.Tableview delegate is working fine but there is some issue with side menu closing

**Comment by jonkykong** [comment]
Please reproduce this problem using the demo project. If it's not happening in the demo, then chances are there's something other than SideMenu that's not working.
