### ISSUE TITLE
menuFadeStatusBar - Not working

### ISSUE THREAD

**Issue by cemalsayin** [jonkykong/SideMenu#490]
I read all menuFadeStatusBar issues but **menuFadeStatusBar = false** not working. I imported "**import SideMenu**" in viewcontrollers i used. I called pod file like this " **pod 'SideMenu', '~> 5.0'** " Could you help me?

**Comment by jonkykong** [comment]
I'm missing a lot of context. Is the menu working at all? If so you've imported it fine.

What do you mean by menuFadeStatusBar = false is not working? What does not working mean?

**Comment by cemalsayin** [comment]
Yes it hadn't work but yesterday when close&open my computer it has started work. My status bar seem .light anymore. Did you change anything?
