### ISSUE TITLE
menuAddScreenEdgePanGesturesToPresent not available in Objective-C

### ISSUE THREAD

**Issue by richardtop** [jonkykong/SideMenu#491]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
menuAddScreenEdgePanGesturesToPresent not available in Objective-C.

**To Reproduce**
1. Import SideMenu in the Objective-C project
2. Try to configure the menu in the Objective-C file
3. The line `[SideMenuManager.defaultManager menuAddScreenEdgePanGesturesToPresent: self.nvc.view];` would not compile.

**Expected behavior**
`[SideMenuManager.defaultManager menuAddScreenEdgePanGesturesToPresent: self.nvc.view];` compiles

**Screenshots**
![image](https://user-images.githubusercontent.com/8013017/60591802-e34bb680-9da7-11e9-91f8-c9464a860853.png)

**Additional context**

**Comment by jonkykong** [comment]
This issue should now be resolved in version 6.0.0+ of SideMenu. Please run `pod update` and reopen this issue if the problem persists.
