### ISSUE TITLE
iOS 13: menu opens on full screen

### ISSUE THREAD

**Issue by EvGeniyLell** [jonkykong/SideMenu#492]
please add support XCode 11 / iOS 13. now menu animation rules don't works

**Comment by mrarronz** [comment]
If you use storyboard, click the `Storyboard segue`(the line connects view controllers), on the right panel of Xcode, set `Presentation` from `Same As Destination` to `Full Screen`. This will make the destination view shows correctly.

If you implement with code, just set the `modalPresentationStyle` of the destination Controller to `UIModalPresentationFullScreen` will solve the problem.
```
desinationViewController.modalPresentationStyle = UIModalPresentationStyle.fullScreen
```
Guess maybe you have solved this issue...

**Comment by jonkykong** [comment]
I have not yet installed the beta release of Xcode to investigate this. For now, I've switched the `modalPresentationStyle` to `overFullScreen` in version 6.0.0+ of SideMenu. Please run `pod update` to see if that resolves this issue and reopen this if it's still occurring.

**Comment by charleshberlin** [comment]
Can we reopen this?

I just updated to the most recent version (6.2.3) using Xcode 11.0 beta 5 with iOS 13 simulator.  When I present the side menu through a storyboard with the Presentation set to Full Screen it shows like a normal modal, animating up from the bottom and covering the full screen rather than from the left and only showing partially.

**Comment by jonkykong** [comment]
@charleshberlin I am testing it now in Xcode 11 best 6 and it is working as expected.

In code, the `modalPresentationStyle = .overFullScreen` is set programmatically by SideMenu.

**Comment by Mahmoud3allam** [comment]
Still got the same issue , xCode 11.2

**Comment by mabosafia** [comment]
I have big problem , two days try to change Menu width but no effect , it still appear with the default width ignoring the change .

Methods used to change Menu Width 

1- rightMenuNavigationController.settings.MenuWidth = 400

2-rightMenuNavigationController.MenuWidth = 400
3- Create new Setting then set menuwidth, then change the rightMenuNavigationController setting

**Comment by AnmolRattan007** [comment]
Got the same issue in Xcode11.3

**Comment by mabosafia** [comment]
I have Solved this Issue by every time I need to show the menu i should set the menu width -- 
==========
in old version you were set the width only in Side Menu Setup - but new version it must set every time you need to show the menu

**Comment by EbrahimElsify** [comment]
If You look For Full Screen :-

 let screenSize = UIScreen.main.bounds
        let screenWidth = screenSize.width
        menu?.menuWidth = screenWidth

#and close the controller opened  by dismiss it

**Comment by SamirBromio** [comment]
I'm having the same trouble as @mabosafia I'm trying to change menuWidth but it doesn't change at all, I even tried @mabosafia solution of changing the size when showing the menu but it didn't help. I hope someone has stumbled upon a solution. 

Xcode 12.1
iOS: 14.1
