### ISSUE TITLE
Programmatically implementing SideMenu

### ISSUE THREAD

**Issue by Chingiz2727** [jonkykong/SideMenu#494]
New ways of making SideMenu makes issue when I try to make menu programmatically.

Use of unimplemented initializer 'init(nibName:bundle:)' for class 'SideMenu.UISideMenuNavigationController'

This is my code
  let newBtn = UIBarButtonItem(image: #imageLiteral(resourceName: "icon_menu_white"), style: .plain, target: self, action: #selector(imageTapped))
        self.navigationItem.leftItemsSupplementBackButton = true
        self.navigationItem.leftBarButtonItem = newBtn
        var setting = SideMenuSettings()
        setting.menuWidth = view.frame.width - view.frame.width*0.2
        setting.pushStyle = .preserveAndHideBackButton
        setting.allowPushOfSameClassTwice = true
        let menuLeft = UISideMenuNavigationController(rootViewController: SideMenuTableViewController(), settings: setting)
        SideMenuManager.default.leftMenuNavigationController = menuLeft

**Comment by jonkykong** [comment]
https://github.com/jonkykong/SideMenu/issues/495
