### ISSUE TITLE
6.0.0 fails to build for non-Pods target

### ISSUE THREAD

**Issue by benphung** [jonkykong/SideMenu#497]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
SideMenu target in the SideMenu project fails to build due to missing source files in "Compile Sources". The SideMenu target in the Pods projects builds fine. This causes Carthage to fail.

**To Reproduce**
1. Open SideMenu workspace
2. Try building "SideMenu (Sidemenu project)" scheme

**Comment by jonkykong** [comment]
Fixed in 6.0.2.
