### ISSUE TITLE
Shadows dissappeared

### ISSUE THREAD

**Issue by llKoull** [jonkykong/SideMenu#499]
Hello!

Using the new version (6.0.2) the menu shadows did disappear (no matter which animation i use).

Is there any way to show them again?

Thanks and best regards!

**Comment by jonkykong** [comment]
See the `SideMenuPresentationStyle` settings.

**Comment by llKoull** [comment]
Hi @jonkykong !

Thanks for your answer! I did it and i tried all the possibilities, no one adds the shadow layer (i tried it in a new project that i've just started two days ago and in an old project that was using version 5.X with the shadows, after the update to the 6.0.2 i've lost them).

Best regards!

**Comment by raid5** [comment]
I'm curious about this as well. I'm using the `slideIn` presentation style and I'm trying to figure out how to get the semitransparent black overlap to show up over the view controller the menu is now partially covering.

**Comment by jonkykong** [comment]
The latest is currently 6.0.3.

You want to take a look at `UISideMenuNavigationController.presentationStyle.onTopShadowOpacity`.

**Comment by llKoull** [comment]
Yeah! Thanks @jonkykong I've downloaded the version 6.0.4 and it worked just adding the line that you've commented ;)

Best regards!
