### ISSUE TITLE
After reload page with 2 side menu, one of it,not open again

### ISSUE THREAD

**Issue by iDuke** [jonkykong/SideMenu#5]
Im implement codeless version of sidemenu on left and right sides.
When you reload page from left side menu(for example place button which handle presentviewController at same page), then try to open right side menu, it will crashes.

**Comment by jonkykong** [comment]
Hi @iDuke,

I'm not clear on the issue you're having:
- Are you reloading the side menu or the view controller that's presenting the side menu?
- Which controller is calling reload? The side menu or the view controller that's presenting the side menu?
- What is the crash? Please provide the file and line number.

It would also be extremely useful if you could post a sample github project that demonstrates this issue.

I am closing this issue until you provide more information.
