### ISSUE TITLE
Black Strip Top

### ISSUE THREAD

**Issue by Zarjagen** [jonkykong/SideMenu#50]
<img width="377" alt="2016-07-19 8 13 20" src="https://cloud.githubusercontent.com/assets/14882968/16970890/47aac21e-4ded-11e6-9c4b-6a94ba09d41d.png">
<img width="376" alt="2016-07-19 8 13 08" src="https://cloud.githubusercontent.com/assets/14882968/16970891/47b21faa-4ded-11e6-86c7-3dff58082e21.png">
I use the method in Storyboard but it has that small black area that disturbs me and I don't know how to get rid of it. I have also tried your programmatically implementing method which gives the same result. Is it a common issue?

**Comment by jonkykong** [comment]
Please read the README thoroughly. Use the `menuFadeStatusBar` to remove the bar or use `menuAnimationBackgroundColor` to remove it.
