### ISSUE TITLE
menuAnimationBackgroundColor 6.0.0 ?

### ISSUE THREAD

**Issue by sphairo** [jonkykong/SideMenu#500]
I used the version
pod 'SideMenu', '~> 6.0.0'
 
but my Status bar of the transitioned view is black as you can see in the next screenshot

![Simulator Screen Shot - iPhone Xʀ - 2019-07-16 at 13 38 41](https://user-images.githubusercontent.com/4241383/61330492-53fdc480-a7e5-11e9-8221-ed2c6521e86e.png)

**Comment by 131e55** [comment]
Try as follows😆

#### Status bar
- v5 `manager.menuFadeStatusBar = false`
- v6 `sideMenuNav.statusBarEndAlpha = 0`

#### menuAnimationBackgroundColor
- v5
```
manager.menuPresentMode = .viewSlideInOut
manager.menuAnimationBackgroundColor = .black
manager.menuAnimationFadeStrength = 0.5
```
- v6
```
sideMenuNav.presentationStyle = .viewSlideOutMenuIn
sideMenuNav.presentationStyle.backgroundColor = .black
sideMenuNav.presentationStyle.presentingEndAlpha = 0.5
```
