### ISSUE TITLE
UI Becomes unresponsive after dismissing with a swipe

### ISSUE THREAD

**Issue by nikolouzos** [jonkykong/SideMenu#501]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**
1. In the demo project, you use UIButtons for the left and right navigation bar button items and add a target to them programmatically. 
2. Remove the segues to the UISideMenuNavigationControllers on the storyboard
3. You initialize the leftMenuNavigationController and rightMenuNavigationController programmatically by instantiating the UISideMenuNavigationControllers from the storyboard using their IDs
4. The actions on the UIButtons present the side menu controllers
5. You open the side menu using any method (UIButton or swipe)
6. You CLOSE the side menu using a SWIPE
7. You TAP on the UIBUTTON to open the same side menu.
8. The UI becomes unresponsive.

**Expected behavior**
The side menu should open as expected. And the UI should not be unresponsive

**Screenshots**
Video of the bug: https://streamable.com/1y7b2
Screenshot of the layout inspector while the UI is unresponsive: 
![Screenshot 2019-07-17 at 10 37 42](https://user-images.githubusercontent.com/8012468/61356639-70e6d600-a87f-11e9-8080-597fe0bbd696.png)

**Additional context**
The layout inspector shows the side menu on top of the view hierarchy.

The code needed to reproduce:

```
override func viewDidLoad() {
        super.viewDidLoad()
        configureSideMenu()
		
		addLeftButtonAction()
		addRightButtonAction()
    }
	
	func addLeftButtonAction() {
		leftButton.addTarget(self, action: #selector(onLeftMenuButtonTap), for: .touchUpInside)
	}
	
	func addRightButtonAction() {
		rightButton.addTarget(self, action: #selector(onRightMenuButtonTap), for: .touchUpInside)
	}

	@objc func onLeftMenuButtonTap() {
		if let leftSide = SideMenuManager.default.leftMenuNavigationController {
			present(leftSide, animated: true)
		}
	}
	
	@objc func onRightMenuButtonTap() {
		if let rightSide = SideMenuManager.default.rightMenuNavigationController {
			present(rightSide, animated: true)
		}
	}
	
	/// Configures the SideMenu options
	func configureSideMenu() {
		// If the menuLeftNavigationController doesn't exist, create it
		guard SideMenuManager.default.leftMenuNavigationController == nil else { return }
		
		// Add the UISideMenuNavigationController for the left side menu
		if let leftSideMenu = storyboard?
			.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? UISideMenuNavigationController {
			
			leftSideMenu.settings = SideMenuSettings()
			
			SideMenuManager.default.leftMenuNavigationController = leftSideMenu
		}
		
		// Add the UISideMenuNavigationController for the right side menu
		if let rightSideMenu = storyboard?
			.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? UISideMenuNavigationController {
			
			rightSideMenu.settings = SideMenuSettings()
			
			SideMenuManager.default.rightMenuNavigationController = rightSideMenu
		}
	}
```

**Comment by jonkykong** [comment]
Thank you for reporting. This is fixed in 6.0.3.
