### ISSUE TITLE
Odd error with alerts

### ISSUE THREAD

**Issue by llKoull** [jonkykong/SideMenu#503]
Hello!

Using the version 6.0.4 of SideMenu i detected an odd error when i try to show a popup view. For example, i use this library (https://github.com/Orderella/PopupDialog) to show some custom popUp views so they work nicely until I open the SideMenu. Once i open it, the method present() doesn't show anything and the button touches of the view get unresponsive (like a layer were shown over them).

I attach a video, but i seems like something in the view hierarchy are getting wrong once the menu gets open.

[ScreenRecord.zip](https://github.com/jonkykong/SideMenu/files/3407068/Grabacion.de.pantalla.2019-07-18.a.las.16.45.45.zip)

When i was using SideMenu 5.X all was working correctly.

Thanks and best regards!

**Comment by jonkykong** [comment]
Thank you for reporting. This is fixed in 6.0.5.

**Comment by llKoull** [comment]
Yeah It is working now! Thanks for all your work @jonkykong !!
