### ISSUE TITLE
Present and animation for Segue quits working after update to SideMenu 6.0.4

### ISSUE THREAD

**Issue by Brandon-316** [jonkykong/SideMenu#504]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [X] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When it happens:
Bug happens after returning to MainViewController after dismissing a ViewController which was segued to from SideMenu. 
SideMenu worked great for me until updating to Swift 5 and version 6.0.4

What happens:
After returning to MainViewController animations on segues from Main are lost.
When attempting to present programmatically the view of the presented ViewController does not load.
Views for UIAlerts also do not load. You can still tap where the button would be to get a reaction however.

**To Reproduce**
I reproduced this in the demo project for you. My code is in an extension at the bottom of MainViewController.
[SideMenu-master.zip](https://github.com/jonkykong/SideMenu/files/3407518/SideMenu-master.zip)

**Expected behavior**
Segues to maintain animations and for views to load in programmatically presented ViewControllers.

**Video**
Unlisted YouTube video.
https://youtu.be/OIEdmGIj628

**Comment by jonkykong** [comment]
Thank you for reporting. This is fixed in 6.0.5.

**Comment by Brandon-316** [comment]
No thank you!
