### ISSUE TITLE
Cannot Sub Class 'SideMenuPresentationStyle'

### ISSUE THREAD

**Issue by philipborbon** [jonkykong/SideMenu#506]
Cannot inherit from non-open class 'SideMenuPresentationStyle' outside of its defining module

```swift
class MenuPresentationStyle: SideMenuPresentationStyle {
}
```

**Comment by jonkykong** [comment]
Fixed in 6.0.6.

**Comment by daltondanis** [comment]
SideMenuPresentationStyle is still refusing to be override, "Method does not override any method from its superclass".. example presentationTransitionWillBegin. Referenced the Readme.

**Comment by az-oolloow** [comment]
@jonkykong the above still seems to be an issue.
