### ISSUE TITLE
Handle menu dismiss on tap manually

### ISSUE THREAD

**Issue by uddinr** [jonkykong/SideMenu#507]
When tapping on any control e.g. a button within the menu view the menu view auto dismisses, there is no option to handle dismissing the menu manually like in 5.0.3, i would like the menu to remain presented until i want to dismiss it, i have noticed there is Tap gesture on the view which dismisses the view, can this be made optional?

**Comment by jonkykong** [comment]
```swift
SideMenuManager.default.rightMenuNavigationController?.dismissOnPush = false
SideMenuManager.default.rightMenuNavigationController?.dismissOnPresent = false
```
