### ISSUE TITLE
Navigation bar issue

### ISSUE THREAD

**Issue by mobileAppdeveloper03** [jonkykong/SideMenu#508]
Hello Team,

I am using latest version of xcode and your library (6.0.6) , i older version i am not faceing this issue related to UI when we open side menu.

1) showing proper from top part when menu is close
![Screenshot 2019-07-20 at 12 41 34 AM](https://user-images.githubusercontent.com/53097205/61559826-4320ad80-aa88-11e9-8b98-6015f8f02689.png)

2) when we open menu is shows black part 
![Screenshot 2019-07-20 at 12 41 45 AM](https://user-images.githubusercontent.com/53097205/61559829-4451da80-aa88-11e9-8e7c-c585257197c9.png)

Regarding my view controller for top view, i am giving top constrains from superview so it not give any space for safe area.

**Comment by jonkykong** [comment]
`UISideMenuNavigationController.statusBarEndAlpha = 0`

**Comment by preetamjadakar** [comment]
how to achieve this, if I'm using `SlideMenuControllerSwift`?
