### ISSUE TITLE
Having problem with split view controller

### ISSUE THREAD

**Issue by Trexology** [jonkykong/SideMenu#51]
When attempting to push a view from the sideBarTableView controller, there is an error

`SideMenu Warning: cannot push a ViewController from a ViewController without a NavigationController. It will be presented it instead.`

attached a sample setup below

![screen shot 2016-07-20 at 2 51 15 pm](https://cloud.githubusercontent.com/assets/3056348/16977575/72ccfed4-4e89-11e6-8074-cd745132ea7c.png)

**Comment by jonkykong** [comment]
You are seeing that window because you are attempting to push a view controller from a view controller that does not have a navigation controller.

Embed the view controller in a navigation controller and it will solve your problem.
