### ISSUE TITLE
set the MenuNavigationController of Both sides(leftAndRight), but only right side works

### ISSUE THREAD

**Issue by SunsetWan** [jonkykong/SideMenu#510]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
I have set the MenuNavigationController of both sides(left and right), but the only right side works.

**To Reproduce**
my implementation is programmatic.
```
let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: LeftMentViewController())
SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
        
let menuRightNavigationController = UISideMenuNavigationController(rootViewController: LeftMentViewController())
SideMenuManager.default.rightMenuNavigationController = menuRightNavigationController
        
SideMenuManager.default.addPanGestureToPresent(toView: self.navigationController!.navigationBar)
SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
```
my LeftMentViewController simply  contains a UILabel whose current title is "World"

**Expected behavior**
I can use pan gesture to make left menu slide in from the left

**Screenshots**
![Kapture 2019-07-22 at 15 00 46](https://user-images.githubusercontent.com/16316111/61612603-9e71bc00-ac91-11e9-8c74-0b6d7b82e482.gif)

**Comment by jonkykong** [comment]
This is by design. The `leftSide` property is what defines the side the menu appears on. If you use a single instance on both sides the leftSide property isn't changing. You need to change it programmatically.

**Comment by SunsetWan** [comment]
Thanks, but when I run the code segment below:
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let menuLeftNavigationController = UISideMenuNavigationController(rootViewController: LeftMentViewController())
        SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
        
//        let menuRightNavigationController = UISideMenuNavigationController(rootViewController: LeftMentViewController())
//        SideMenuManager.default.rightMenuNavigationController = menuRightNavigationController
        
        SideMenuManager.default.addPanGestureToPresent(toView: self.navigationController!.navigationBar)
        SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
    }
```
I still can't use gesture to make the left menu slide in. And the console says: 
```
SideMenu Warning: (
    "addScreenEdgePanGesturesToPresent(toView:forMenu:)",
    menuRightNavigationController,
    "addScreenEdgePanGesturesToPresent(toView:forMenu:))"
) was called before (null) was set. The gesture will not work without a menu. Use (null) to add gestures for only one menu.
```
Actually, I really don't know how to fix it. 
Could you please give me some hints about this problem?
Thank you for your attention to this matter.
