### ISSUE TITLE
Missing Shadow on Top ViewController

### ISSUE THREAD

**Issue by Pikorua** [jonkykong/SideMenu#514]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
YES
- [X] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

In an older version of SideMenu (I'm not sure which version I was using before updating to V6.0.9 ), the top controller shadow was working. It is no longer working in the latest version.

Using 
```SideMenuManager.default.leftMenuNavigationController?.settings.presentationStyle.onTopShadowOpacity = 0.5```
doesn't not display the shadow. 

**To Fix the bug**
In SideMenuPresentationController.swift.
In function:
```func addShadow(to view: UIView) {
        view.layer.shadowColor = config.presentationStyle.onTopShadowColor.cgColor
        view.layer.shadowRadius = config.presentationStyle.onTopShadowRadius
        view.layer.shadowOpacity = config.presentationStyle.onTopShadowOpacity
        view.layer.shadowOffset = CGSize(width: 0, height: 0)
    }
```
Add
```
 view.clipsToBounds = false
```
Shadows are not displayed when clipsToBounds = true since shadows are by definition outside of the view bounds.

Fixed function:
```
func addShadow(to view: UIView) {
        view.layer.shadowColor = config.presentationStyle.onTopShadowColor.cgColor
        view.layer.shadowRadius = config.presentationStyle.onTopShadowRadius
        view.layer.shadowOpacity = config.presentationStyle.onTopShadowOpacity
        view.layer.shadowOffset = CGSize(width: 0, height: 0)
        view.clipsToBounds = false
    }
```

**To Reproduce**
Display a SideMenu and set onTopShadowOpacity > 0

**Expected behavior**
Shadow should be displayed when onTopShadowOpacity is not 0

**Screenshots**
Old Version of SideMenu:
![IMG_8781](https://user-images.githubusercontent.com/18665128/61822377-414f4500-ae0e-11e9-96d0-c2967b6f40c0.PNG)

New Version of SideMenu (V6.0.9):
![IMG_8787](https://user-images.githubusercontent.com/18665128/61822406-51ffbb00-ae0e-11e9-8f07-60855ca407a7.PNG)

Proposed fix with view.clipsToBounds = false:
![IMG_8788](https://user-images.githubusercontent.com/18665128/61822427-5b892300-ae0e-11e9-9dfb-8ea24f2a6057.PNG)

**Additional context**
N/A

**Comment by jonkykong** [comment]
The default value for ‘clipsToBounds’ is ‘false’, therefor you must be setting it to true elsewhere in your code. Shadows work fine in another project of mine without your proposed fix.

**Comment by Pikorua** [comment]
Hey Jon,
I'm not setting it elsewhere! 
And also your demo code is failing too exactly in the same way my app is...
The shadow is never shown... 
I did check thoroughly before opening the bug report... 
I'll record a video of your demo app so you can see for yourself...

**Comment by Pikorua** [comment]
**This is a video of your original code:**
You can see that the shadow never gets displayed...
https://blissmore.app/SideMenu/originalCode.mp4

**This is a video of your code with the additional line for the clipsToBounds:**
Now the shadow works... 
https://blissmore.app/SideMenu/modifiedCode.mp4

**Comment by jonkykong** [comment]
I'm at a loss. The demo project works exactly as intended without your suggested fix. I simply set `presentationStyle.onTopShadowOpacity = 1` and I see a shadow.

**Comment by Pikorua** [comment]
Well unfortunately it doesn't for me :( Neither your demo or my app work without the fix...
On what devices / version of iOS have you tested it? 
Thanks Jon

**Comment by jonkykong** [comment]
In the demo, printing `clipsToBounds` in the console returns `false` as expected, both on app start and when SideMenu is displayed. There is nowhere in my code that I set it to `true`.

I generally test on iPhone XR with the latest, which is currently 12.4.

**Comment by bull-xu** [comment]
Hi @Pikorua, I'm not sure what iOS version you are using. For me, when I use iOS 13 for my project, the clipsToBounds for a navigation controller's view is true, as well as the contentView of a table view cell. So you need to make sure you set the view's `clipsToBounds` of the presentingViewController of the side menu to false: `navigationController?.view.clipsToBounds = false` and this brings back the shadow.
