### ISSUE TITLE
Sidemenu Delegate Method WillDissapear not firing 

### ISSUE THREAD

**Issue by NPSconsultingLLC** [jonkykong/SideMenu#516]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
In the latest version of the pod (6.0.9) "SideMenuWillDissapear" is not triggered when the user closes (dismisses) the side menu, it is only triggered when there is a segue to a new screen

**Comment by NPSconsultingLLC** [comment]
The bug is in the view will disappear method of the UISideMenuNavigation controller, but I don't understand the complexity of the project to understand what it is that is happening here. 

This is the version that is working (6.0.0)

`    override open func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)

        // When presenting a view controller from the menu, the menu view gets moved into another transition view above our transition container
        // which can break the visual layout we had before. So, we move the menu view back to its original transition view to preserve it.
        if dismissOnPresent && !isBeingDismissed {
            // We're presenting a view controller from the menu, so we need to hide the menu so it isn't showing when the presented view is dismissed.
            if let presentingView = presentingViewController?.view, let containerView = presentingView.superview {
                containerView.addSubview(view)
            }

            transitionController?.transition(presenting: false, animated: animated, alongsideTransition: { [weak self] in
                guard let self = self else { return }
                self.activeDelegate?.sideMenuWillDisappear?(menu: self, animated: animated)
            }, complete: false, completion: { [weak self] _ in
                guard let self = self else { return }
                self.activeDelegate?.sideMenuDidDisappear?(menu: self, animated: animated)
                self.view.isHidden = true
            })
        } else {
            activeDelegate?.sideMenuWillDisappear?(menu: self, animated: animated)
        }
    }`

and this is the latest 6.0.9 that does not call the delegate method when being dismissed: 

`   override open func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)

        if !isBeingDismissed {
            // When presenting a view controller from the menu, the menu view gets moved into another transition view above our transition container
            // which can break the visual layout we had before. So, we move the menu view back to its original transition view to preserve it.
            if let presentingView = presentingViewController?.view, let containerView = presentingView.superview {
                containerView.addSubview(view)
            }

            if dismissOnPresent {
                // We're presenting a view controller from the menu, so we need to hide the menu so it isn't showing when the presented view is dismissed.
                transitionController?.transition(presenting: false, animated: animated, alongsideTransition: { [weak self] in
                    guard let self = self else { return }
                    self.activeDelegate?.sideMenuWillDisappear?(menu: self, animated: animated)
                    }, complete: false, completion: { [weak self] _ in
                        guard let self = self else { return }
                        self.activeDelegate?.sideMenuDidDisappear?(menu: self, animated: animated)
                        self.view.isHidden = true
                })
            } else {
                activeDelegate?.sideMenuWillDisappear?(menu: self, animated: animated)
            }
        }
    }`

**Comment by daltondanis** [comment]
Receiving the same problem, also getting the
`
SideMenu Warning: (
    menuLeftNavigationController
) cannot be modified while it's presented.
`
In conjunction of this. I can make a seperate ticket but it seems to be a result of this error.

**Comment by jonkykong** [comment]
This is fixed in 6.1.0.

**Comment by NPSconsultingLLC** [comment]
Confirmed this is fixed in version 6.1.1 (it also fixed a bug where swipe to dismiss was causing an issue with subsequent touch events. Thanks!

**Comment by parveenBanuS** [comment]
can you share the link?or gif code
