### ISSUE TITLE
Install with cocoapods PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by sphairo** [jonkykong/SideMenu#517]
SideMenu.framework/SideMenu: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

Every time I run my project it marks the error, I am cleaning my project every time I try to run it in my simulator because otherwise it marks error, I am using XCode 10.2

pod 'SideMenu' 6.0.9

**Comment by jonkykong** [comment]
I have SideMenu in use on another project of mine and not encountering this problem. This leads me to believe there may be something off with your project setup. If other people report this issue then I may investigate further.
