### ISSUE TITLE
SideMenuPresentationStyle memory leak

### ISSUE THREAD

**Issue by Khainarbyek** [jonkykong/SideMenu#518]
**Screenshots**
![image](https://user-images.githubusercontent.com/53472764/62120725-b6ca8200-b2f4-11e9-8f0b-5c616e1b2a3a.png)

**Comment by jonkykong** [comment]
It's not clear from this ticket that there is a memory leak. SideMenuPresentationStyle is retained by `UISideMenuNavigationController`, which in turn is retained by `SideMenuManager` for gesture support.

**Comment by Khainarbyek** [comment]
Sorry for unclear information. But the only memory leak caused from SideMenu section. Please re-check this screenshot. Thank you.
![image](https://user-images.githubusercontent.com/53472764/62179951-d5765a80-b380-11e9-9a53-97f02701d556.png)

**Comment by jonkykong** [comment]
This appears to be a leak in your project, not mine (eg. HomeController). You have not provided any specific steps, only a screenshot. My leak testing of the demo project does not produce leaks.

**Comment by aspek** [comment]
I've got same issue. I created by programmatically with very basic code base on iOS 11.3 -> 12.4 . 
Setup view
```Swift
override func viewDidLoad() {
        super.viewDidLoad()
        
        view.backgroundColor = .blue
        
        setView()
    }

fileprivate func setView() {
    let button = UIButton()
    button.setTitle("Show Left Menu", for: .normal)
    button.translatesAutoresizingMaskIntoConstraints = false
    
    view.addSubview(button)
    
    button.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
    button.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
    
    button.addTarget(self, action: #selector(buttonPressed(sender:)), for: .touchUpInside)
}
```
action 

```Swift
@objc
fileprivate func buttonPressed(sender: UIButton) {
    let menuPage = MenuViewController()
    var setting = SideMenuSettings()
    setting.statusBarEndAlpha = 0
    setting.menuWidth = UIScreen.main.bounds.width / 1.3
    let sideMenu = SideMenuNavigationController(rootViewController: menuPage, settings: setting)
    sideMenu.leftSide = true
    
    DispatchQueue.main.async {
        self.present(sideMenu, animated: true, completion: nil)
    }
}
```
<img width="1260" alt="Screen Shot 2562-09-22 at 21 34 08" src="https://user-images.githubusercontent.com/2587452/65389467-c01a1d00-dd80-11e9-8540-c9ee08f50016.png">

**Comment by jonkykong** [comment]
Hi folks, I appreciate the investigation. Since we're talking about an isolated leak on a very small object I'm not inclined to invest the effort to investigate. If anyone on this thread wants to investigate and put out a PR, I'll happily see that it gets merged.

**Comment by jonkykong** [comment]
@Khainarbyek @aspek

**Comment by aayush-ksolves** [comment]
> 

That makes sense, but even after dismissal of UISideMenuNavigationController and its root , the deinit never calls. 

How to generate?
On your storyboard
Window's root => MyVC (presents on button click) => UISideMenuNavigationController (Has a root) => List Menu

When I get change window root, and config is like below (After changing Window's root, ie. removing `MyVC` )
Window's root => Some other VC 

Still the `deinit` inside UISideMenuNavigationController **never** gets called.

I am surprised how anyone has never noticed this.

I am happy to attach my Test Project here - [ It should not take more than 15 min to localise this ]
[testme.zip](https://github.com/jonkykong/SideMenu/files/8838396/testme.zip)
