### ISSUE TITLE
Is possible to hide or close  the SideMenu on orientation change if and when it is opened ?

### ISSUE THREAD

**Issue by korantengNanaYaw** [jonkykong/SideMenu#519]
Is possible to hide or close the SideMenu on orientation change if and when it is opened , when my app rotates i want any side menu opened to close, i could not find this in the docs

**Comment by yawboafo** [comment]
`SideMenuManager.default.menuDismissOnPush = true`

However i cant find dismiss on rotation

**Comment by leo150** [comment]
```
/// Automatically dismisses the menu when the screen is rotated.
var dismissOnRotation: Bool = true
```

**Comment by yawboafo** [comment]
`	lazy var mainViewController : UISideMenuNavigationController = {
		let viewController  =  UISideMenuNavigationController(rootViewController: MainViewController())
		let leftmenuViewController = UISideMenuNavigationController(rootViewController: NavigationSideMenuViewController() )
		SideMenuManager.default.menuRightNavigationController = leftmenuViewController
		let rightMenuNavigationController = UISideMenuNavigationController(rootViewController: ShopingCartViewController() )
		SideMenuManager.default.menuRightNavigationController = rightMenuNavigationController
		SideMenuManager.default.menuLeftNavigationController = leftmenuViewController
		SideMenuManager.default.menuPresentMode = .viewSlideInOut
		SideMenuManager.default.menuFadeStatusBar = false
		SideMenuManager.default.menuDismissOnPush = true
		let width = UIDevice.current.userInterfaceIdiom == .pad ?  300  :  (UIScreen.main.bounds.width / 2) + 50
		SideMenuManager.default.menuLeftNavigationController?.menuWidth = width
		
		let CartIpadwidth = UIDevice.current.userInterfaceIdiom == .pad ? (UIScreen.main.bounds.width - (UIScreen.main.bounds.width / 3)) : (UIScreen.main.bounds.width - 40)
		SideMenuManager.default.menuRightNavigationController?.menuWidth = CartIpadwidth
		SideMenuManager.default.menuDismissOnPush = true
		SideMenuManager.default.menuShadowOpacity = -1
		return viewController
	}()`


In my case the menu is not closed when my view is rotated , where can i set this value ?

**Comment by jonkykong** [comment]
Thanks @leo150. @yawboafo you are using an old version of SideMenu. Please update to the latest.
