### ISSUE TITLE
Sample without Storyboard 

### ISSUE THREAD

**Issue by tharak** [jonkykong/SideMenu#52]
Hey, great work with this menu! 
I have a project without storyboard, so I cant use segues. I did manage to make it work using pushViewController but the first time I click the cell on the menu the push fails, on the second time and afters it works just fine. 
Maybe I set something wrong and after the first click your code fix it. Can you Make a sample without a storyboard?

Thanks

**Comment by jonkykong** [comment]
Hi @tharak, thanks for the compliment.

There's no requirement that this repo needs storyboards. You should try putting in breakpoints in several places to figure out what's being called on tap and what isn't to track down the problem first. If you want to share a link to your sample project, I'd be willing to take a look.

**Comment by tharak** [comment]
https://github.com/tharak/SideMenu

**Comment by jonkykong** [comment]
Thanks for sharing.

It looks like you're doing something atypical that wasn't accounted for in the design of this library.

Namely, you're adding a UITableView directly to the view of a UINavigationController. UINavigationControllers are meant to host other viewControllers, not serve as a viewController themselves.

The preferred setup is to set the rootViewController of a UINavigationController to a UITableViewController.

**Comment by tharak** [comment]
Do you mind fixing the project as you thought it to be?

**Comment by jonkykong** [comment]
Unfortunately, I don't have the time to develop for every possible corner case of this repo. Currently, it meets 90%+ of people's desired use cases.

Your problem is very solvable by following Apple's preferred and supported view hierarchy models. I suggest you do some quick rework of your project and you'll find your problem goes away.

**Comment by tharak** [comment]
I will try to do it, thanks for you help. =]

**Comment by tharak** [comment]
managed to make it work, problem was that when I looked at the  [https://github.com/jonkykong/SideMenu/raw/master/etc/Screenshot3.png](third image) the little arrow on the left gave the impression that that view controller was the window.rootViewController.  This detail shows some errors that I went on fixing, resulting on the first code I shared with you.
Now I will move the code to my project, thanks for everything!

**Comment by jonkykong** [comment]
It is the window's root view controller.

The problem was that you physically inserted a UITableView inside of UISideMenuNavigationController. You shouldn't do that.

Instead, do UISideMenuNavigationController(rootViewController: someUITableViewController).
