### ISSUE TITLE
SideMenu will not dismiss if swiped open

### ISSUE THREAD

**Issue by matcartmill** [jonkykong/SideMenu#520]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
*Note: this is only reproducible on a physical device so far*
*Note: we use the library programmatically*

When the SideMenu is swiped open, and an item on the menu is tapped, the menu UI will not close however when connecting to the UI debugger, the menu appears to be dismissed.

I'm assuming there's something in our project that could be causing an issue, but I'm not sure where to start looking. I have tried pushing the dismissal to the main thread, etc, and haven't found a fix yet.

So far the only way to dismiss it without killing the app is to minimize the app and bring it back to the foreground after ~1 second. Then you can swipe to dismiss the menu again.

**To Reproduce**
1. Swipe open the menu
2. Tap a menu item

**Expected behavior**
I expect the menu to dismiss the same way it does if I tap the icon to show the menu.

**Comment by jonkykong** [comment]
@matcartmill this is the first report of this issue. Unfortunately, unless this is reproducible in the demo project I'm led to believe this is a project specific issue. If you're able to repro it in the demo project feel free to reopen this ticket with the additional details.

**Comment by jonkykong** [comment]
Fixed in 6.1.2.

**Comment by matcartmill** [comment]
Verifying. Will report back asap.

**Comment by matcartmill** [comment]
@jonkykong Gave it a shot and it's still behaving the same. I'm not seeing any methods getting fired on either the `viewWillDisappear`or `viewDidDisappear` lifecycle methods. I will set up a demo project that closely resembles how my team is using SideMenu so you can check it out.

**Comment by matcartmill** [comment]
@jonkykong Never mind, seems to work. Had a weird caching issue with the Pod. Appreciate you getting this sorted so quickly.
