### ISSUE TITLE
Present Menu without animation

### ISSUE THREAD

**Issue by Alexookah** [jonkykong/SideMenu#521]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

I tried to show the menu

```
if let rightSideMenu = SideMenuManager.default.rightMenuNavigationController {	
    present(rightSideMenu, animated: true)
}
```

and it seems that the menu shows full screen 

**To Reproduce**

**Expected behavior**

**Screenshots**

check here: 
https://streamable.com/kbidr

**Additional context**

**Comment by jonkykong** [comment]
This is not a problem in the demo project. Please follow the README carefully.

**Comment by philipborbon** [comment]
Does this mean it's not possible to present SideMenu without animation?
