### ISSUE TITLE
Swift 5 "upgrade" warning -- needs to be Swift '5.0' instead of just '5'

### ISSUE THREAD

**Issue by jimduchek** [jonkykong/SideMenu#522]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Installed using CocoaPods, Xcode creates a warning that 'Swift 5 conversion is available' for this library (although it IS Swift 5)

**To Reproduce**
Build a project using SideMenu... look at warnings

**Expected behavior**
No warning :)

**Screenshots**
none

**Additional context**
The problem is that s.swift_version is '5' and not '5.0'.  CocoaPods copies this setting directly into SWIFT_VERSION=... in the xcodeproj without any checking, and Xcode, I guess, doesn't think '5' >= '5.0'.

**Comment by jonkykong** [comment]
Fixed in 6.1.3.
