### ISSUE TITLE
preserve push style is not working

### ISSUE THREAD

**Issue by Navoda-BrightSparks** [jonkykong/SideMenu#523]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
when the push style is "preserve" side menu always shows the rootviewcontroller.but if i change it to default it always recreate new viewcontroller and push. 
**To Reproduce**
1.change push style to preserve
2. And change items in menu
3. It always show the first Root viewcontroller the request view is not showing 

**Expected behavior**
when i change menu it should show requested view

**Screenshots**

**Comment by jonkykong** [comment]
Fixed in 6.1.4.
