### ISSUE TITLE
InitializableStruct access control

### ISSUE THREAD

**Issue by leo150** [jonkykong/SideMenu#525]
First of all, thank you for maintaining SideMenu.

I have a question, is it possible to keep `InitializableClass` internal instead of [public](https://github.com/jonkykong/SideMenu/commit/2de8d7f7582bc03740c023e809939eb5afdffb0d)? 

The problem is in Swift it's impossible to keep extension with protocol conformance internal:
> You can’t provide an explicit access-level modifier for an extension if you’re using that extension to add protocol conformance. Instead, the protocol’s own access level is used to provide the default access level for each protocol requirement implementation within the extension.

As result, `extension NSObject: InitializableClass {}` is extending `NSObject` with `InitializableClass` everywhere in a project where `SideMenu` was imported. It interferes with the custom implementation of `func with(_ block: (Self) -> Void) -> Self` that pod client may have in their projects. We have such an implementation used in 95% of our files. 

Thanks.

**Comment by jonkykong** [comment]
Fixed in 6.2.0.
