### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Ludicrous2k** [jonkykong/SideMenu#528]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Just wanted to point out the documentation under usage is out of date or was just mis-typed.
In Step 1: "Navigation Controller to be SideMenuNavigationController in the Identity Inspector"
The class should be "UISideMenuNavigationController". The screen shot under it also doesn't show the correct class. The correct class is being used in the demo app.

**Comment by jonkykong** [comment]
Hi @Ludicrous2k, `UISideMenuNavigationController` was actually deprecated in favor of `SideMenuNavigationController` in the latest release. Please update your source accordingly. Thank you.

**Comment by Ludicrous2k** [comment]
Oh thanks for the heads up. Sorry I didn't realize.

**Comment by jonkykong** [comment]
No worries. I appreciate the effort.
