### ISSUE TITLE
Swipe is not working with PageMenu libraray. only woking when we swipe from navigation.

### ISSUE THREAD

**Issue by Sahilberi** [jonkykong/SideMenu#530]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

Hi,
I really Liked your library. but I am having an issue. Actually I am adding a custom control to MenuViewController( page menu) but it doesn't work when I swipe from MenuController. Side menu only opens from the navigation bar. Seems like gesture is not taking. can you help?

**Comment by jonkykong** [comment]
SideMenu is not guaranteed to work with other libraries.

You need to setup dependencies on your gestures to fail. Please go to StackOverflow.com for more help.

**Comment by Sahilberi** [comment]
Thanks for the reply. I figured out how to work with that.
