### ISSUE TITLE
LeftMenu's viewDidLoad method is being called.

### ISSUE THREAD

**Issue by eldarkk** [jonkykong/SideMenu#531]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

At first, Thank you for creating such good framework like this.
So my question is.
Im using TableView as LeftSideMenu. So if i make swipe from mainVC i can see left menu in actual current state (menu's viewDidLoad method is not being called). But if i use present(leftMenuVC) by tapping on button, i see that leftManu(tableView) is reloading (menu's viewDidLoad method is being called). 

I want not to call viewDidLoad by tapping button (calling preset(menuVC)). How can i do this?

**Comment by jonkykong** [comment]
This is not a bug in SideMenu. Please ask this question on StackOverflow.com.
