### ISSUE TITLE
6.2.7.

### ISSUE THREAD

**Issue by wpk0927** [jonkykong/SideMenu#536]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Tried to update an app's SideMenu pod from 5.0.3 release to 6.2.6/6.2.7.
- 6.2.6 has an infinite loop issue upon startup which seems to be fixed by 6.2.7
- 6.2.7 has another (Infinite loop?) issue when pushing a submenu

more details to follow...

**Comment by jonkykong** [comment]
The latest is 6.2.8.
