### ISSUE TITLE
Compilation fails due to SideMenu.h not found

### ISSUE THREAD

**Issue by vkaramov** [jonkykong/SideMenu#537]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Compilation Fails on Xcode 10.3 for target 'SideMenu' with reason: "Umbrella header 'SideMenu.h' not found"

**Expected behavior**
Compilation succeeds

**Screenshots**
<img width="496" alt="Снимок экрана 2019-09-10 в 09 50 30" src="https://user-images.githubusercontent.com/5604492/64590638-afe16580-d3b0-11e9-8f04-cb7619b7d724.png">

**Comment by jonkykong** [comment]
I am unable to repro. Clean your project. Build first for the framework (in screenshot) then build for the demo. Works for me.

**Comment by vkaramov** [comment]
@jonkykong It works after downgrading to 6.2.4. Thanks for the "great" support!

**Comment by jonkykong** [comment]
I'm guessing the "great" is meant to be snide. I wrote you a bunch of code for free. If you don't like it, write your own. Don't be disrespectful to me because I'm not giving you all my spare time.
