### ISSUE TITLE
Wrong MainViewController frame after rotation

### ISSUE THREAD

**Issue by Jauzee** [jonkykong/SideMenu#54]
If we rotate device while `SideMenu` is on screen with `MenuPresentMode` equals to `InOut` &  `MenuTransformScaleFactor` equals to less than `1` we'll catch a bug: `MainViewController` will be cut out his height.

**Comment by jonkykong** [comment]
Hi @Jauzee, I have just verified that this is in fact a bug. Thanks for finding it!

It looks like the transformed view isn't resized appropriately after rotation. The solution is likely to be to use `viewWillTransitionToSize` in `UISideMenuNavigationController` to restore the correct size, or to completely prevent rotation while a menu is presented.

I love when people help contribute to this repo through finding bugs and making fixes. Are you interested in making a fix to this repo?

**Comment by Jauzee** [comment]
I'll make a pull request if I can fix it

**Comment by jonkykong** [comment]
Fixed in branch 1.2.0.
