### ISSUE TITLE
SideMenu loads all view controllers inside him

### ISSUE THREAD

**Issue by eitanaviv** [jonkykong/SideMenu#542]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained) - **(version 6.3.0)**.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the demo project - **an issue for me**.

**Describe the bug**
When leaving the app and returning back to it, SideMenu loads almost completely black and all view controllers i'm trying to load via the navigation controller are loading inside of the SideMenu.

After putting app in background and return back to it:
![IMG_0002](https://user-images.githubusercontent.com/35567702/64954709-196ce280-d88f-11e9-950f-1febff01b964.PNG)
![IMG_0003 (1)](https://user-images.githubusercontent.com/35567702/64954708-196ce280-d88f-11e9-8d94-c5c6b5c21b39.png)

**To Reproduce**
1. Implement SideMenu via StoryBoard.
2. Init SideMenu as following:
```
  override func viewDidLoad() {
        super.viewDidLoad()

        let myPresentStyle = SideMenuPresentationStyle.menuSlideIn
        myPresentStyle.presentingEndAlpha = 0.4
        
        let menuLeftNavigationController = storyboard?.instantiateViewController(withIdentifier: "drawerMenu") as! SideMenuNavigationController
        menuLeftNavigationController.pushStyle = .preserve
        menuLeftNavigationController.presentationStyle = myPresentStyle
        menuLeftNavigationController.menuWidth = sideMenuWidth
        menuLeftNavigationController.statusBarEndAlpha = 0
        
        if appLanguage == .Hebrew {
            SideMenuManager.default.rightMenuNavigationController = menuLeftNavigationController
            SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: self.view, forMenu: .right)
        } else {
            SideMenuManager.default.leftMenuNavigationController = menuLeftNavigationController
            SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: self.view, forMenu: .left)
        }
}
```
3. Use class "DrawerViewController" as SideMenu's view controller.
4. After clicking on one of the items the following code gets executed:
```
if let vc = storyboard?.instantiateViewController(withIdentifier: "profileVC") {
      self.navigationController?.pushViewController(vc, animated: true)
}
```
4. SideMenu closes and pushes the selected view controller.

**Expected behaviour**
Push the profile view controller instead of loading it inside SideMenu and don't show the whole app with strange black color.
![IMG_0001 (1)](https://user-images.githubusercontent.com/35567702/64954650-e9254400-d88e-11e9-8b5d-4ed5e1a07f39.png)
-- After clicking "Profile" from the menu.
![IMG_0004 (1)](https://user-images.githubusercontent.com/35567702/64954649-e9254400-d88e-11e9-866f-247d1f799675.png)

**Screenshots**
See above.

**Additional context**
Seems to be working fine on SideMenu 5 latest version.

**Comment by eitanaviv** [comment]
After downgrading to version 5.0.3 is still seems to happen (bug is happening in a different way - transparent colors instead of black colors and view controllers won't load at all), probably related to some code I changed in the project.
Will update this post for others who encounter this issue.

**Comment by jonkykong** [comment]
@eitanaviv it's kind of unclear what the issue you're having is. It sounds like it's working as expected from the steps to reproduce, and the problem you're having has something to do with later opening the app.

It would be really helpful if you could include a video demonstrating the issue and/or modify the demo project to reproduce it. If you can't make it happen in the demo project, it's more likely that there's something strange going on in your project that's creating this behavior.

I keep tickets closed whenever I respond; if you reply please reopen.
