### ISSUE TITLE
Unable to integrate SideMenu with AZTabBarController

### ISSUE THREAD

**Issue by mubashirhussain** [jonkykong/SideMenu#543]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
I have a tabbar controller(AZTabBarController) and I have option from every tab's root controller to open the right side menu.

So the storyboard approach wouldn't work here as I have to open side menu from different tabs. I have created a SideMenu storyboard but does not and it is appearing from every controller but when I push some controller from side menu it is pushing inside the menu controller not on center controller.

I am pushing from SideMenuController using the following code,

`performSegue(withIdentifier: "show_login_view", sender: self)`

**To Reproduce**
<img width="329" alt="Screen Shot 2019-09-18 at 5 39 44 PM" src="https://user-images.githubusercontent.com/1871447/65158935-fb90b080-da3b-11e9-83e1-bd6e6c4fd516.png">
<img width="329" alt="Screen Shot 2019-09-18 at 5 43 17 PM" src="https://user-images.githubusercontent.com/1871447/65158936-fb90b080-da3b-11e9-9559-7f90606df030.png">

**Expected behavior**
Should work with TabBar but it does not.

**Screenshots**

**Additional context**

**Comment by jonkykong** [comment]
This is by design.

1. Tab Bar doesn't support pushing. You need to embed a navigation controller inside a Tab Bar for it to work that way.
2. SideMenu is not guaranteed to work with other third party libraries.
3. You segue needs to be called on your Tab Bar/Navigation Controller object, not on your menu. SideMenu does not by default delegate segues.
