### ISSUE TITLE
buttonaction is not work correctly

### ISSUE THREAD

**Issue by Hwamyo** [jonkykong/SideMenu#546]
let menu = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as! UISideMenuNavigationController
        menu.sideMenuManager.menuPushStyle = .subMenu
        menu.sideMenuManager.menuPresentMode = .menuSlideIn
        menu.sideMenuManager.menuFadeStatusBar = false
        present(menu, animated: true, completion: nil)

this is my code and i want menu slide in.
gesture action in work correctly. but action in button,  menu is popover from bottom to top.
how can i fix it?

**Comment by jonkykong** [comment]
Please follow the README carefully.
