### ISSUE TITLE
Shadow disappeared for iOS 13

### ISSUE THREAD

**Issue by skatolyk** [jonkykong/SideMenu#549]
**Describe the bug**
Shadow disappeared on the top most view after I have updated to Xcode 11 and iOS 13.

Here is my code where I set onTopShadowOpacity to have shadow. Other values I don't touch at all.

`let sideMenuNavigationController = SideMenuNavigationController(rootViewController: vc)
        sideMenuNavigationController.isNavigationBarHidden = true
        sideMenuNavigationController.menuWidth = UIScreen.main.bounds.width - 50
        sideMenuNavigationController.statusBarEndAlpha = 0
        sideMenuNavigationController.presentationStyle.onTopShadowOpacity = 0.7`

P.S.: Before update all worked fine.

**Comment by jonkykong** [comment]
Fixed in `6.4.1`
