### ISSUE TITLE
SidMenu not able to present half of the screen in ios13, but working in ios12

### ISSUE THREAD

**Issue by Imtiazaa** [jonkykong/SideMenu#552]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Imtiazaa** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-24 at 20 19 30](https://user-images.githubusercontent.com/51320784/65522635-adcaeb00-df08-11e9-96a8-4eb5e912f3ed.png)

**Comment by mateoquiceno** [comment]
I have the same problem...

**Comment by haroldogtf** [comment]
Same here...

**Comment by haroldogtf** [comment]
@Imtiazaa I suggest you edit and check. (Latest Version, README, StackOverflow, Not new functionality)

**Comment by jonkykong** [comment]
It's unclear what the problem is from this issue but in iOS 13 modals are presented differently by default.

**Comment by haroldogtf** [comment]
@Imtiazaa the issue https://github.com/jonkykong/SideMenu/issues/492 could help you!

**Comment by denniskeithgaso** [comment]
You might want to set the `modalPresentationStyle = .fullscreen`
