### ISSUE TITLE
What replaced menuShadowRadius?

### ISSUE THREAD

**Issue by MalkaBar** [jonkykong/SideMenu#553]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.

**Describe the bug**
Probably not a bug, but I was working on a Swift 4 project and moved it to Swift 5.
I upgraded the SideMenu to version 6.0.0 and the following line was no longer compiling:
`SideMenuManager.default.menuShadowRadius = shadowRadius`
I couldn't find what replaces this shadowRadius on github or google...

Thanks for the help!

**Comment by jonkykong** [comment]
Do a quick search for shadow in the README and you'll find your answer.
