### ISSUE TITLE
Missing Shadow for Top View from side separating menu and main view controllers

### ISSUE THREAD

**Issue by winstonmachado7** [jonkykong/SideMenu#557]
Couldn't set shadow for top view from side between Main view and Menu view.

**Comment by jonkykong** [comment]
Update to the latest.

**Comment by az-oolloow** [comment]
Just in case somebody comes across this - for me just updating to the latest wasn't enough, i had to set the shadowPath of the view that was being presented. 
This may be because i am presenting all my viewcontrollers inside another UINavigationController (without the shadowPath my shadow was below the navigationbar of the UINavigationController presented by SideMenu).

**Comment by jonkykong** [comment]
The latest code puts shadows on the highest container view controller.

**Comment by sercanorhangazi** [comment]
I had the same issue on version 6.4.2 and added shadow manually

**Comment by winstonmachado7** [comment]
@jonkykong already updated but it doesn't show the shadow so i have added the shadow manually.

**Comment by jonkykong** [comment]
I need more information. Can one of you investigate? I don't know how your project is organized. When I tested this on the Example project, it works as expected.

SideMenu finds the largest containing ViewController, turns off `clipsToBounds` and applies the shadows. You'll have to inspect the view hierarchy to figure out what had the shadow applied to it and what is preventing it from being shown.

**Comment by sercanorhangazi** [comment]
This is what my storyboard looks like

![Ekran Resmi 2019-09-27 09 32 19](https://user-images.githubusercontent.com/32338956/65747503-42e90200-e10a-11e9-8ae9-7f228ef95c47.png)


And this is what my code looks like

```
// I call setupSideMenu() in viewDidLoad()

 private func setupSideMenu() {
    SideMenuManager.default.leftMenuNavigationController = storyboard!.instantiateViewController(withIdentifier: String(describing: MenuViewController.self)) as? SideMenuNavigationController
    SideMenuManager.default.addPanGestureToPresent(toView: self.navigationController!.navigationBar) 
    SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: self.navigationController!.view, forMenu: .left)
      
    SideMenuManager.default.leftMenuNavigationController!.settings = makeSettings()
}
    
private func makeSettings() -> SideMenuSettings {
    var presentationStyle = SideMenuPresentationStyle()
    presentationStyle = .viewSlideOutMenuIn
    presentationStyle.backgroundColor = .clear
    presentationStyle.onTopShadowOpacity = 1
    presentationStyle.onTopShadowOffset = CGSize(width: 5, height: 5)
    presentationStyle.onTopShadowColor = .black
    presentationStyle.onTopShadowOpacity = 1

    var settings = SideMenuSettings()
    settings.presentationStyle = presentationStyle
    settings.menuWidth = traitCollection.isIphone ? view.bounds.width - 60 : 350

    return settings
}
```

**Comment by jonkykong** [comment]
For the presentation style you've chosen, the shadow is applied to the main view controller, not the side menu as the main view controller is top most per the style.

`presentationStyle.menuOnTop = true`

**Comment by sercanorhangazi** [comment]
I thought we were talking about the shadow itself not the direction of it. Shadow is still not visible without these lines:
```
presentationStyle.onTopShadowOpacity = 0.5
presentationStyle.onTopShadowRadius = 5
presentationStyle.onTopShadowColor = .black
```
Anyway, thanks for the great work, man. Best sidemenu i have seen so far!

**Comment by KING5399** [comment]
@sercanorhangazi Can you please tell me where and how to access presentationStyle.

**Comment by sercanorhangazi** [comment]
@KING5399 you can see it on my previous reply, the one with an image and a chunk of code. (`makeSettings() -> SideMenuSettings`)

**Comment by KING5399** [comment]
@sercanorhangazi i was doing the same but i got this problem thats why i asked where and how to do this
![Screenshot 2019-10-17 at 11 26 13 AM](https://user-images.githubusercontent.com/40310604/66981415-451efa80-f0d1-11e9-9671-c75b27959251.png)
