### ISSUE TITLE
there is gap on the top of controller

### ISSUE THREAD

**Issue by huangmaoyixxx** [jonkykong/SideMenu#560]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
there is a gap on the top of controller

**To Reproduce**
1. Go to 'example'
2. Click on 'Right Menu'
3. Click on any menu item

**Expected behavior**
there is gap on top

**Screenshots**

![image](https://user-images.githubusercontent.com/12968613/65936699-0db51a80-e450-11e9-8d0d-d24f32baa3ca.png)
**Additional context**

**Comment by jonkykong** [comment]
This is iOS13 default functionality. Please read up on the latest documentation from Apple.
