### ISSUE TITLE
New Presentation Of iOS 13 Inconsistent with default present of SideMenu ?!

### ISSUE THREAD

**Issue by Mohamed-Akl** [jonkykong/SideMenu#562]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Mohamed-Akl** [comment]
i am use this for present side menu in old version of iOS
let vc = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "RightSideMenuShow") as! UINavigationController
 self.present(vc, animated: true , completion: nil)
now this code not working with me in iOS 13 ... the Menu is show over background View not from Side right or left.

**Comment by ezzmoaz** [comment]
Change the UINavgationController to SideMenuNavigationController in the storyboard
and try the following code

let VC = storyboard?.instantiateViewController(withIdentifier: "RightSideMenuShow") as! SideMenuNavigationController
        VC.presentationStyle = .viewSlideOutMenuIn
        VC.presentingViewControllerUserInteractionEnabled = false
        SideMenuManager.default.leftMenuNavigationController = VC
        present(SideMenuManager.default.leftMenuNavigationController!, animated: true, completion: nil)


Hope it is helpful ..

**Comment by Mohamed-Akl** [comment]
it working .... thank you
