### ISSUE TITLE
Not Compatible for swift 5 and IOS 13.

### ISSUE THREAD

**Issue by Hzy5** [jonkykong/SideMenu#564]
i just converted my code from swift 4 to swift 5. by pressing the side menu the side menu is not opening from left to right it is just popping out from the bottom.

**Comment by mrsnax** [comment]
Yes same here

**Comment by pengleng** [comment]
Yes, me too. :(

**Comment by mrsnax** [comment]
Hmmm i got solution of this

Because default iOS 13 is card. May you change segue into like this :
![image](https://user-images.githubusercontent.com/6369589/66695955-7ecabc80-ecf1-11e9-97d7-67a73cfa4444.png)

Set to Present Modally and Full Screen

**Comment by jonkykong** [comment]
The demo project works as expected. Make sure you're using the latest Xcode or can reproduce your issue in the demo project.

**Comment by Hzy5** [comment]
I did the same as you say. But got same issue.

**Comment by jonkykong** [comment]
What version of Xcode are you using?

**Comment by Hzy5** [comment]
11.1

**Comment by jonkykong** [comment]
Clean your project and make sure you have the latest. Unless you can reproduce this issue in the demo project or determine the root cause, I don't know what the issue you're hitting is. The problem line of code is clearly wrapped in an available check, and the underlying API is restricted to 13.

**Comment by jonkykong** [comment]
You're all most likely not using the latest version of SideMenu. If you don't update, you'll see the issue you're hitting.

**Comment by Hzy5** [comment]
My sideMenu pod version is 6.4.3

**Comment by jonkykong** [comment]
Compare your project to the demo for issues. If the demo project works, SideMenu works.

**Comment by Hzy5** [comment]
Ok

**Comment by mbhanen** [comment]
I have the same issue, "i just converted my code from swift 4 to swift 5. by pressing the side menu the side menu is not opening from left to right it is just popping out from the bottom."
