### ISSUE TITLE
Double height status bar causing layout issues in iOS 10 and iOS 12 when Xcode 11 and iOS 13 SDK is used

### ISSUE THREAD

**Issue by djdirtycake** [jonkykong/SideMenu#566]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
After updating our app to support iOS 13 we found some layout issues on older iOS version if double height (call, some map navigation stuff or hotspot is active).
On iOS 11 navigation bar becomes taller than it should be (I guess it wrongly adds 20 px of status bar height). On iOS 12 it jumps under the half of the status bar

**To Reproduce**
on iOS 12.1
1. Trigger double status bar (Toggle in-call status bar in simulator for example)
2. Launch the demo app
3. Click on 'Left Menu' button in the demo app
4. Dismiss the menu using 'Left Menu' button again or by tapping on the non-menu controller
5. Navigation bar jumps under the half of the status bar
note: Pressing "Debug View Hierarchy" and then "Continue program execution" somehow fixes the layout

on iOS 10.3.1
1. Trigger double status bar (Toggle in-call status bar in simulator for example)
2. Launch the demo app
3. Click on 'Left Menu' button in the demo app
4. Navigation bar on the non-menu controller becomes 20 px taller  

**Expected behavior**
Navigation bar doesn't change it's height and did not overlap double height status bar

**Screenshots**
<img width="432" alt="Screenshot 2019-10-14 at 16 29 06" src="https://user-images.githubusercontent.com/2623510/66756042-db6cd980-eea1-11e9-8e12-3a1b3ccb6146.png">
<img width="432" alt="Screenshot 2019-10-14 at 16 29 38" src="https://user-images.githubusercontent.com/2623510/66756024-d445cb80-eea1-11e9-9cee-f2b7bc30196c.png">

**Comment by jonkykong** [comment]
This behavior is going away in iOS 13+.

**Comment by djdirtycake** [comment]
Sure thing, yet we got dozens of older devices like iPhone 6 or previous gen of iPod Touch for which iOS 13 is unavailable. Since all of or apps are enterprise and used mostly on corporate devices we couldn't just drop support for older iOS like if we were in the App Store.

**Comment by jonkykong** [comment]
Mostly fixed in `6.4.5` with some minor animation issues when revealing the bar while SideMenu is exposed.

If this doesn't resolve your issues then I'd suggest dismissing SIdeMenu when you detect changes in the status bar to prevent animation issues.
