### ISSUE TITLE
While opening side menu background view does not get dark

### ISSUE THREAD

**Issue by KING5399** [jonkykong/SideMenu#567]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jonkykong** [comment]
Customize the presentation style as described in the README.

**Comment by KING5399** [comment]
still not working

**Comment by afzal01** [comment]
same issue background controller is not getting transparent view using presentation style menuslidein in Xcode 11 using iOS 13

**Comment by KING5399** [comment]
> was having this issue use
> presentingEndAlpha = 0.5
> should be able to work
> 
> > still not working
@afzal01 plz tell me where and how to use this presentingEndAlpha = 0.5

**Comment by KING5399** [comment]
@afzal01 please tell me where and how to use this presentingEndAlpha = 0.5

**Comment by emurgophi** [comment]
Hi @KING5399, 
YourSideMenuNavigationController.presentationStyle.onTopShadowOpacity = 0.5

**Comment by afzal01** [comment]
@KING5399 ,
  let menu = storyboard!.instantiateViewController(withIdentifier: "yoursidemenunavigationcontroller") as! SideMenuNavigationController
        var set = SideMenuSettings()
        set.statusBarEndAlpha = 0
       set.presentationStyle = SideMenuPresentationStyle.menuSlideIn
        set.presentationStyle.presentingEndAlpha = 0.5
        menu.settings = set
        SideMenuManager.default.leftMenuNavigationController = menu
        present(SideMenuManager.default.leftMenuNavigationController!, animated: true, completion: nil)

I used this and it worked

**Comment by KING5399** [comment]
@afzal01 Thanx man it worked
