### ISSUE TITLE
addScreenEdgePanGesturesToPresent Warning

### ISSUE THREAD

**Issue by perryhoekstra** [jonkykong/SideMenu#568]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Seeing the following warning when using only the right side menu configuration:

SideMenu Warning: addScreenEdgePanGesturesToPresent(toView:forMenu:) was called before leftMenuNavigationController was set. The gesture will not work without a menu. Use addScreenEdgePanGesturesToPresent(toView:forMenu:)) to add gestures for only one menu.

Per the example, I am creating/configuring the rightMenuNavigationController as:

SideMenuManager.default.rightMenuNavigationController = storyboard?.instantiateViewController(withIdentifier: "RightMenuNavigationController") as? SideMenuNavigationController

SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: view)
SideMenuManager.default.addPanGestureToPresent(toView: navigationController!.navigationBar)
        
var settings = SideMenuSettings()
SideMenuManager.default.rightMenuNavigationController?.settings = settings

**Expected behavior**
No warning and that the rightMenuNavigationController slides away when a selection is tapped.

How is my configuration wrong for a single MenuNavigationController?

**Comment by jonkykong** [comment]
You're setting gestures for both sides. Set it for one. Please read the README.

**Comment by guneshasancan** [comment]
SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: view, forMenu: .left)
