### ISSUE TITLE
black screen when open sidemenu

### ISSUE THREAD

**Issue by selaysoysal** [jonkykong/SideMenu#57]
When i click UIBarButton side menu appears black. I did not changed any default settings. Where am i wrong? Can you help me with that issue? I am new with swift. Thank you in advance!

**Comment by jonkykong** [comment]
Hi @selaysoysal,

I recognize that it can be frustrating when you're learning something and things don't work like you expect.

Unfortunately, I don't have the time to help all the beginners learn how to use Swift. To help with that I wrote very detailed instructions on the README that show how to implement SideMenu. If it's not working for you, I'd suggest re-reading the instructions or trying to install it on a brand new project. Be persistent and creative in your problem solving and you'll figure out what's wrong without needing anyone else's help.

**Comment by djdance** [comment]
Man, readme is not enough. Really.

**Comment by selaysoysal** [comment]
@jonkykong if i did not try it 3 times i did not write here. Unfortunately swReveal is more easier to use. Thank you for your help.

**Comment by jonkykong** [comment]
There are thousands of other developers using this repository successfully. If they're able to get it to work, then you also have the ability to work things out.

If you guys would have looked at the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example), you would have seen the proper instantiation for view controllers from storyboard when setting up gestures. If you are instantiating them using just `UISideMenuNavigationController()`, you'll get a black menu.

```swift
// Define the menus
SideMenuManager.menuLeftNavigationController = storyboard!.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as! UISideMenuNavigationController
SideMenuManager.menuRightNavigationController = storyboard!.instantiateViewController(withIdentifier: "RightMenuNavigationController") as! UISideMenuNavigationController
        
// Enable gestures. The left and/or right menus must be set up above for these to work.
// Note that these continue to work on the Navigation Controller independent of the View Controller it displays!
SideMenuManager.menuAddPanGestureToPresent(toView: self.navigationController!.navigationBar)
SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
```

**Comment by andrei115** [comment]
This has been indeed frustrating for me. I have both the menu and the status bar of black color. After digging up, I have found the following solution:

sideMenuManager.menuAnimationBackgroundColor = .white // or whatever color you want
sideMenuManager.menuFadeStatusBar = false

**Comment by mawais91** [comment]
Anyone facing this issue.. I have just fixed this black screen issue by setting "Presentation" property in "Segue" properties to "Same as Destination". Try this fix

**Comment by manee1982** [comment]
for any one using none-storyboard approach use:
menu.presentationStyle.backgroundColor =  YOUR_COLOR

**Comment by safecan** [comment]
> this

Working, but notch is now black. Is there any way to show/dismiss the menu without black notch?
