### ISSUE TITLE
Could not cast value

### ISSUE THREAD

**Issue by bhanuAnnam** [jonkykong/SideMenu#571]
I just updated my Xcode, pod, macOS.
And once I run the application and by clicking on menu button am getting below error and it is crashing. Until this morning it worked.

Could not cast value of type 'UINavigationController' (0x7fff896bf8d0) to 'SideMenu.SideMenuNavigationController' (0x1107728a8).

Here is the code which am trying

```
    @IBAction func didTapMenu(_ sender: Any) {
        let sideMenuNavController: SideMenuNavigationController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SideMenuNavigationController") as! SideMenuNavigationController
        self.present(sideMenuNavController, animated: true, completion: nil)
    }

```

**Comment by jonkykong** [comment]
Side menu tests are passing as expected. Please clean your project and try again. This sounds like a local issue and nothing wrong with SideMenu.

**Comment by pmusolino** [comment]
Same crash here, after updating from version 6.0.2 to 6.4.4.
Clean the project and delete derived data doesn't work.

**Comment by pmusolino** [comment]
I tried to go back from v6.4.4 to v.6.1.5 and now everything works fine. From version 6.2 something changed and broke everything.

**Comment by bhanuAnnam** [comment]
@jonkykong, But am getting this error after updating pod. Previous it is working fine.

**Comment by jonkykong** [comment]
My guess is that your storyboards are still referencing `UISideMenuNavigationController` and not `SideMenuNavigationController`.

**Comment by meeraRchillar** [comment]
Any fix for this issue..facing the same problem in ios13 ..but works fine in version 12 and below

**Comment by rmalmoe** [comment]
> Any fix for this issue..facing the same problem in ios13 ..but works fine in version 12 and below

The fix for this is to open up your storyboard and modify the class name of UISideMenuNavigationController to SideMenuNavigationController.

Worked for me.
