### ISSUE TITLE
it is taking two clicks to present UIAlertController on sidemen's table view cell click.

### ISSUE THREAD

**Issue by monkeyDkishan** [jonkykong/SideMenu#573]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
let alert = UIAlertController(title: "Confirmation Alert!", message: "Are you sure you want to logout?", preferredStyle: UIAlertController.Style.alert)
           alert.addAction(UIAlertAction(title: "CANCEL", style: UIAlertAction.Style.default, handler: nil))
           
           alert.addAction(UIAlertAction(title: "OK", style: .default, handler:
               {
               action in
               if let appDelegate = UIApplication.shared.delegate! as? AppDelegate
                  {
                      appDelegate.PresentLoginNavigationControllerScreen()
                  }
                   }))

            present(alert, animated: true, completion: nil)
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="265" alt="Screenshot 2019-11-05 at 3 25 20 PM" src="https://user-images.githubusercontent.com/43228546/68197630-93dcf780-ffe0-11e9-97c1-8b1035732888.png">
<img width="229" alt="Screenshot 2019-11-05 at 3 25 30 PM" src="https://user-images.githubusercontent.com/43228546/68197640-97707e80-ffe0-11e9-8923-c0bf7a2ca71f.png">

**Additional context**

**Comment by jonkykong** [comment]
It's highly unlikely this is a bug with SideMenu. You're likely trying to display SideMenu off of the main thread. Please ask your question at stackoverflow.com.
