### ISSUE TITLE
How do I proper close SideMenu?

### ISSUE THREAD

**Issue by DouglasHennrich** [jonkykong/SideMenu#574]
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

How can I proper close SideMenu? I open this framework after login, but If I logout (change rootViewController of my app) and then login again, that creates SideMenu, I get crash on `deinit` function of framework:

<img width="1680" alt="Captura de Tela 2019-11-07 às 18 00 50" src="https://user-images.githubusercontent.com/10107024/68427272-91b59d00-0188-11ea-966c-9cb5303d096b.png">

**Comment by jonkykong** [comment]
Call `dismiss` the same as any other view controller.

**Comment by brianguertin** [comment]
@jonkykong Call `dismiss` on what? This is still undocumented, I'm can't figure out how to close the menu either.
