### ISSUE TITLE
Sidemenu overlays on top if the view as a new view

### ISSUE THREAD

**Issue by AbdullahFaiz** [jonkykong/SideMenu#576]
![Simulator Screen Shot - iPhone 8 - 2019-11-12 at 16 49 31](https://user-images.githubusercontent.com/49398076/68667704-a91bce00-056c-11ea-9075-482ba447e714.png)
![Simulator Screen Shot - iPhone 8 - 2019-11-12 at 16 52 29](https://user-images.githubusercontent.com/49398076/68667805-de282080-056c-11ea-9dd8-97e7f2725aa4.png)

## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ ] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

On click left side menu or the right side menu button, controller is displayed on top of the home controller. Swipe gesture works fine. Having this issue after updating xcode to 11 - ios 13. Worked fine for mu previous projects.
Swift version - 4.2

**Comment by Sinan-Noureddine** [comment]
Same problem happening with me... @AbdullahFaiz, Please label this issue as Bug

**Comment by jonkykong** [comment]
Hi @AbdullahFaiz, I have just tested this in the latest version of SideMenu using the demo project and everything works as expected. Please make sure you're following the README carefully, or provide more details using the demo project to reproduce this problem and reopen this issue.
