### ISSUE TITLE
Version 6.0 not found 😊

### ISSUE THREAD

**Issue by FerasFarhan** [jonkykong/SideMenu#577]
[!] CocoaPods could not find compatible versions for pod "SideMenu":
  In Podfile:
    SideMenu (~> 6.0)

Specs satisfying the `SideMenu (~> 6.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by jonkykong** [comment]
> Specs satisfying the SideMenu (~> 6.0) dependency were found, but they required a higher minimum deployment target.

Search the web for your solution 🙂
