### ISSUE TITLE
Black blink after dismissing any viewController presented with full screen presentation

### ISSUE THREAD

**Issue by albertvc10** [jonkykong/SideMenu#579]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Xcode 11 - swift 5. 
Black blink after dismissing any viewController presented with full screen presentation. viewWillAppear not called anymore from MainViewController. 

**To Reproduce**
1. Go to Example project.
2. Click on Right menu and try to present first viewController wich is the only one with full screen presentation and then try to dismiss multiple times.

**Expected behavior**
The expected behaviour is that the menú will dismiss that viewController but suddenly you can see a black blink on the screen. Also if you override viewWillAppear method in the MainViewController that method is not called anymore after dismissing the VC as it happened before in XCode 10 implementations.

**Comment by jonkykong** [comment]
Update to `6.4.7`.

**Comment by albertvc10** [comment]
Great! Thanks! 😄

**Comment by kaaaaai** [comment]
> Update to `6.4.7`. 更新到 `6.4.7` .

It's not working, can you update it
