### ISSUE TITLE
*** IMPORTANT: PLEASE READ BEFORE YOU OPEN A NEW ISSUE! ***

### ISSUE THREAD

**Issue by jonkykong** [jonkykong/SideMenu#58]
Thank you for your interest in SideMenu!

I have received a surprising amount of questions about SideMenu since putting it up here. A few people in the community have identified some problems and helped contribute to SideMenu to make it better for everyone and I'm truly grateful for the support! Keep them coming!

I have also received a number of questions about people having issues implementing SideMenu, mostly from beginners learning how to code. As much as I would love to help all of you, I simply do **not** have the time to teach you. That's why I spent a lot of time putting together a detailed [README](https://github.com/jonkykong/SideMenu/blob/master/README.md), adding comments about usage in code, and providing a [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example). These will give you all the information you need to work through any problem and also save me the time it takes to personally respond. It is faster for you to figure it out for yourself instead of waiting for me to respond to you.

### If your question begins with _"How do I..."_
- It's **not** a bug. Stay persistent, try a few different things, and you will figure it out! I also recommend searching and posting your questions on [stackoverflow.com](stackoverflow.com). Or, if you're interested in hiring me to teach you, please email me using the email address listed at the bottom of my [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).

### If your question begins with _"Can I..."_
- That's a **new feature request**. I am no longer investing my personal time to implement one-off features because SideMenu currently meets the majority of people's needs with the features it already has. However, this is a great opportunity for you to contribute to this open source project! Feel free to open an issue to ask any clarifying questions for your new feature before you start building. Open a [pull request](https://github.com/jonkykong/SideMenu/pull/new/master) when you're ready for me to merge it.

**Again**, please do **not** email me or open any issues if you want to know how to use SideMenu or are having trouble getting it to work. However, if you think you found a bug, open an issue and I will respond to it as quickly as I can. You should be able to demonstrate the bug in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example) which has a minimal amount of code.

Thanks again for your support and for being respectful of my time.

**Comment by amjad401** [comment]
Can I contact with you by email?
I have some a little trouble in SideMenu and I want to ask you about it

**Comment by jp-dubey07** [comment]
There are many issues when I converted my project to Swift 3 syntax.
Have a look at below screenshot.

![screen shot 2016-10-11 at 16 57 18](https://cloud.githubusercontent.com/assets/5441735/19268709/9977ab66-8fd3-11e6-8da6-cdfa9aaccae7.png)

**Comment by jonkykong** [comment]
@jp-dubey07 First, you're reporting a problem under a different issue when you should have started a new issue.

Second, I have had no issues using this project with Swift 3. Xcode is most likely trying to interpret the code as Swift 2.3. You need to research the solution elsewhere instead of asking here.

I will delete your comments and my response here in the next 24 hours as off-topic.

**Comment by dubayb** [comment]
hello! something odd is happening in my implementation of your cocoapod. I have tried it in code and in storyboard. the slide out action works great, but the presented view controller only shows up as i slide back to the root view controller. no matter how long i wait it doesn't show until i slide back.

**Comment by jonkykong** [comment]
@dubayb First, please open new issues instead of replying to this existing issue. I'm going to delete comments here as off-topic.

The extremely simple demo project does not have these problems. Because of this, there is something else going on in your code likely to be causing this problem and you need to investigate more to solve it.

Again, do not reply here, I will delete off-topic comments shortly.

**Comment by sebbean** [comment]
i appreciate you! @jonkykong

**Comment by jonkykong** [comment]
Closing in favor of using issue template.

**Comment by stealdre** [comment]
stupid devs...

**Comment by jonkykong** [comment]
@stealdre who are you directing that comment at?

**Comment by stealdre** [comment]
what do you think?

**Comment by jonkykong** [comment]
@stealdre I assume that you are directing it at me.

**Comment by jonkykong** [comment]
@stealdre:

1. This is free code I have provided to this community through my own time. I am not being paid. Other developers have graciously contributed their time to add to it, all for free. You are welcome to use this code as you see fit, using all of the resources provided on how to implement it, as well as to feel empowered to find issues and report them.
2. You are not entitled to anything. I do not owe you any answers or help. Other developers do not owe you any answers or any help.
3. Despite the several notices on this GitHub repository for you to follow the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) when opening an issue, you failed to follow those requirements and continued to request help. I fail to see why I should spend my time helping someone who has no respect for time.
4. There are other menu libraries available. If this one doesn't meet your needs, use a different one.

If you aren't going to follow my requests, respect my time, and insult myself or other developers here, I will happily block you from this repository. You need to learn how to work with others and drop your condescending and entitled attitude immediately. This will be my one and only warning to you. Don't waste my time.

**Comment by stealdre** [comment]
Ok for your time but: You're closing all new errors because you don't want to waste your time; why don't let other devs help people? 
Ok so that's for yours. Now let's talk about my time. I don't want to waste my time trying to understand the code of another dev without his help.

**Comment by jonkykong** [comment]
@stealdre I don't close all new errors. I address the ones that properly follow the template. The template is helpful to _all_ devs, not just me. You are saving everyone time by using it. You provide any dev with information you've done through your own testing and research instead of leaving others to verify your problem (where often the problem is some other part of your project, not SideMenu). You might perceive this as "wasting" your time, but the reality is not doing it is lazy and you're expecting others to make up for your laziness by spending their time instead of yours.

Again, if you don't want to rely on another dev's code, simply don't use it and write your own. This is the classic dilemma with using 3rd party libraries. Again: you're not entitled to any support from the developers who create code you use.
