### ISSUE TITLE
allowPushOfSameClassTwice = true not working

### ISSUE THREAD

**Issue by SerggioC** [jonkykong/SideMenu#582]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
I am trying to push the same viewController more than one because I want to reuse it but allowPushOfSameClassTwice true/false does not make any difference in the behaviour. 

**To Reproduce**

A side menu with items linking to the same view controller always displays the current VC content.

**Expected behavior**
It should create a new viewcontroller on each menu item click.

**Screenshots**

**Additional context**

**Comment by jonkykong** [comment]
This is working as expected in the demo project in the latest code. The default is `true`. After you set it to `false` make sure you're not overwriting this setting by using a brand new set of configs.
