### ISSUE TITLE
statusbar shows black and 'leftMenuNavigationController.statusBarEndAlpha = 0' can not solve

### ISSUE THREAD

**Issue by markinlkn** [jonkykong/SideMenu#584]
The true solution is:
SideMenuManager.default.menuFadeStatusBar = false

**Comment by jonkykong** [comment]
Please update to the latest SDK.

**Comment by vkolosovsky** [comment]
latest SDK contains no `menuFadeStatusBar` option. Moreover related toggle in example project does nothing
<img width="377" alt="Screen Shot 2020-01-02 at 14 55 59" src="https://user-images.githubusercontent.com/10945964/71668012-03b4f780-2d70-11ea-95cc-738c81c216f6.png">

Please clarify
