### ISSUE TITLE
UISideMenuNavigationControllerDelegate not work

### ISSUE THREAD

**Issue by fuatkarip** [jonkykong/SideMenu#585]
public func sideMenuDidDisappear(menu: UISideMenuNavigationController, animated: Bool)
 not call on ios versiyon 13.2

**Comment by paystar** [comment]
did you got the answer, i have the same issue in SideMenuNavigationControllerDelegate.

**Comment by fuatkarip** [comment]
yes !! this is my solution

leftMenuNavigationController.modalPresentationStyle = .overCurrentContext
