### ISSUE TITLE
problems with the navigation bar

### ISSUE THREAD

**Issue by JJunLLee** [jonkykong/SideMenu#586]
hello..whats all this about?
<img width="812" alt="WeChat9da41ff19c44e21cc7d58d00263bf034" src="https://user-images.githubusercontent.com/19901455/70502998-4f072c00-1b5d-11ea-8e78-18f32687ad16.png">

**Comment by jonkykong** [comment]
You've provided no details about the screenshot or how it got into this state.

I've run the demo project on the iPhone 11 Pro Max and it works as expected.
