### ISSUE TITLE
Problems with the navigation bar

### ISSUE THREAD

**Issue by JJunLLee** [jonkykong/SideMenu#587]
<img width="812" alt="WeChat9da41ff19c44e21cc7d58d00263bf034" src="https://user-images.githubusercontent.com/19901455/70585727-19ffe580-1c00-11ea-8319-0b670dfe66ec.png">
1. Go to 'Presenting Scale Factor' and change value
2. Click on 'Left Menu' and Click on 'Push VC'
3. See error
I'm sorry I didn't elaborate yesterday.

**Comment by jonkykong** [comment]
This is related to https://github.com/jonkykong/SideMenu/issues/258. See that issue for a better history.
