### ISSUE TITLE
dyld: Symbol not found:

### ISSUE THREAD

**Issue by obaidrehman** [jonkykong/SideMenu#588]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [✓] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [✓] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [✓] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [✓] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [✓] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug** 
Xcode Version: 11.2.1
iOS Version: 12.3.1(real device)

After I have update my pod and run the project this give me an error that is:
dyld: Symbol not found: _$s8SideMenu0aB20NavigationControllerC010transitionD033_F0C9FDFE3A8708DF0D9E44D2303FDBB2LLAA0ab10TransitionD0CSgvM
Referenced from: /var/containers/Bundle/Application...
Expected in: /private/var/containers/Bundle/Application...

**Comment by nvdmcs** [comment]
delete dervied data of xcode , and also delete from bin
clean build folder ( shift + command + K)
run project
