### ISSUE TITLE
Menu swipe in not working

### ISSUE THREAD

**Issue by Severon96** [jonkykong/SideMenu#589]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I'm currently trying to setup the Sidemenu in my new App. 

I've tried to implement it by using the the Example-Project as reference. But the the Swipe-In of the Menu isn't working. I'm feeling pretty helpless at the moment because it's working in the example-App but not in my project and I can't find the problem in my Code. 

My implementation looks like this:

``` swift
override func viewDidLoad() {
        super.viewDidLoad()
        
        self.collectionView!.register(UICollectionViewCell.self, forCellWithReuseIdentifier: reuseIdentifier)
        setupSideMenu()
    }
    
    private func setupSideMenu() {
        SideMenuManager.default.leftMenuNavigationController = storyboard?.instantiateViewController(withIdentifier: "LeftMenuNavigationController") as? SideMenuNavigationController
        
        SideMenuManager.default.addPanGestureToPresent(toView: navigationController!.navigationBar)
        SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: view)
    }
```

The goal is to implement it into an UICollectionViewController, but I don't think that this should do any trouble with the Side Menu implementation since this is also an ViewController...

My Configuration of the SideMenuNavigationController looks like this:
![image](https://user-images.githubusercontent.com/8166975/71367429-4d9a2280-25a5-11ea-88c9-3ed9c022fa8f.png)
![image](https://user-images.githubusercontent.com/8166975/71367437-55f25d80-25a5-11ea-8244-8d9f85002859.png)

I'm really confused because, as far as I see, I do everything like it's documented in the Readme..

I would be really glad if anyone could help me.

**Comment by jonkykong** [comment]
https://github.com/jonkykong/SideMenu/issues/595
