### ISSUE TITLE
Thin hairline between SideMenu and UIViewController

### ISSUE THREAD

**Issue by pennywise94** [jonkykong/SideMenu#591]
**Describe the bug**
I added SideMenu to a new project and set up some customizations. Basically, my main UIViewController has a (mostly) white background, and so does SideMenu. When the SideMenu is shown, I want the main UIViewController to be blacked out (.5 opacity). However, there is a thin hairline visible between the UIViewController and the SideMenu that is caused by `presentationStyle.backgroundColor`.

**To Reproduce**
```
let leftMenuNavigationController = SideMenuNavigationController(rootViewController: SideMenuController())
SideMenuManager.default.leftMenuNavigationController = leftMenuNavigationController        
SideMenuManager.default.leftMenuNavigationController?.presentationStyle = .viewSlideOutMenuIn
SideMenuManager.default.leftMenuNavigationController?.presentationStyle.onTopShadowRadius = 0
SideMenuManager.default.leftMenuNavigationController?.presentationStyle.onTopShadowOpacity = 0
SideMenuManager.default.leftMenuNavigationController?.presentationStyle.onTopShadowOffset = .zero
SideMenuManager.default.leftMenuNavigationController?.presentationStyle.onTopShadowColor = UIColor.clear
SideMenuManager.default.leftMenuNavigationController?.presentationStyle.backgroundColor = UIColor.black
SideMenuManager.default.leftMenuNavigationController?.presentationStyle.presentingEndAlpha = 0.5
leftMenuNavigationController.menuWidth = UIScreen.main.bounds.width - 200
leftMenuNavigationController.statusBarEndAlpha = 0
```

**Expected behavior**
I would like the shadow/hairline border to disappear.

**Screenshots**
[With `backgroundColor` set to .black](https://user-images.githubusercontent.com/7414814/71544673-d092f280-2982-11ea-8c3d-0b868935c23b.png)
[With `backgroundColor` set to .red](https://user-images.githubusercontent.com/7414814/71544676-e0123b80-2982-11ea-829d-bc3aa55d5048.png)

**Comment by jonkykong** [comment]
I copied this code into the demo project and was not able to reproduce your problem.

Please modify the demo project to demonstrate this issue and reopen. Also state what simulator or device you are testing on.
