### ISSUE TITLE
Why I am not getting left SideMenu over the existing view in swift5?

### ISSUE THREAD

**Issue by SwiftSamples** [jonkykong/SideMenu#593]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue **is** reproducible in the [demo project](https://github.com/SwiftSamples/sideMenuDemo).

**Describe the bug**
I am using left SideMenu over the existing view from this framework, in swift 4 it was working fine, recently I have updated pod to **Swift 5** ` pod 'SideMenu', '~> 6.0'`  here I am not getting left SideMenu over the  existing view, here existing view also moving along with sidemenu

**Expected behavior**
Want left sidemenu over the existing view in swift 5 like below
![image](https://user-images.githubusercontent.com/27500812/71898249-d48ef380-317e-11ea-8de0-9f0d48601ea7.png)

**Screenshots**
in swift 5 getting like below why?
![image](https://user-images.githubusercontent.com/27500812/71898209-b45f3480-317e-11ea-99b5-5f2c5095fd47.png)

**This is my demo project on swift 5 with issue**  [https://github.com/SwiftSamples/sideMenuDemo](url)

Please help me in the above issue.

**Comment by SwiftSamples** [comment]
Please do help some one.. here.. got stuck from long time

**Comment by jonkykong** [comment]
Please read the README carefully and change the `presentationStyle`.
