### ISSUE TITLE
how can i set color for VC which is behind SideMenu?

### ISSUE THREAD

**Issue by bizibizi** [jonkykong/SideMenu#594]
my code

 nvc.leftSide = true
        nvc.menuWidth = round(UIScreen.main.bounds.width * 0.78)
        nvc.presentationStyle = .menuSlideIn
        nvc.statusBarEndAlpha = 0
        

was trying that:

     extension SideMenuPresentationStyle {
    static var menuSlideInCustom: SideMenuPresentationStyle {
        let item = SideMenuPresentationStyle.init()
        item.menuOnTop = true
        item.menuTranslateFactor = -1
        item.onTopShadowColor = UIColor(red: 0.024, green: 0.075, blue: 0.176, alpha: 1)
        item.onTopShadowOpacity = 0.6
        return item
    }
}

but do not have any change for color. color is clear...

**Comment by sagarsukode** [comment]
//To aply background color/shadow behind menu
SideMenuManager.default.menuAnimationFadeStrength = 0.4

**Comment by kaaaaai** [comment]
> //To apply background shadow opacity behind menu SideMenuManager.default.menuAnimationFadeStrength = 0.4

It's not working now. Is there any other solution?
