### ISSUE TITLE
menuWidth

### ISSUE THREAD

**Issue by poffel1976** [jonkykong/SideMenu#6]
Hi,

simple and really cool menu you did here. I have just one question. Is it correct that you can't have different menuWidth for left and right controller?

Best,
Lars

**Comment by jonkykong** [comment]
Thanks @poffel1976!

The `menuWidth` property is a global value for both menus to keep things simple and consistent. It wouldn't be hard to modify the library yourself to handle different sizes. Alternatively, you could set the `menuWidth` property just before the menu appears by overriding any method that's called as part of the presenting process. If you're using storyboard, I'd say you could do this easily by overriding `awakeFromNib` for each menu and setting `menuWidth` there.
