### ISSUE TITLE
Circular reference internal typealias Model Xcode 11.4

### ISSUE THREAD

**Issue by bryan1anderson** [jonkykong/SideMenu#600]
Using Xcode 11.4, and SIdeMenu from SPM, you cannot build and receive this error
`Circular reference`

On this line
`    internal typealias Model = MenuModel & PresentationModel & AnimationModel
`

**Comment by bryan1anderson** [comment]
There was a pull request that solved this. My bad

**Comment by timbms** [comment]
Same error occurs also with CocoaPods instead of SPM

**Comment by laszlo-major** [comment]
Will there be a cocoapods release to fix this in the near future?
Cheers

**Comment by CLoutas** [comment]
Same on Xcode 11.4 beta 3 (11N132i) on the Cocoapods release.
