### ISSUE TITLE
Pushed viewcontroller appeared in the sidemenu controller

### ISSUE THREAD

**Issue by mEldewaik** [jonkykong/SideMenu#601]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
i have a sidemenu in my project it presented as expected. i have a button in my sidemenu and when i make push to new viewcontroller it pushed but in the viewcontroller of sidemenu

**To Reproduce**

**Expected behavior**
i expect that the sidemenu disapeared and a new view controller pushed but i have the new viewcontoller in the same sidemenu controller

**Screenshots**
![Image from iOS (2)](https://user-images.githubusercontent.com/29314628/74658572-42293900-519b-11ea-97b1-19385434e60b.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/29314628/74658578-435a6600-519b-11ea-9d78-1a8cbbff78fc.png)

**Additional context**

    `@IBAction func editProfileBtnPressed(_ sender: UIButton) {
        if let vc = UIStoryboard(name: "ProvProfile", bundle: nil).instantiateViewController(withIdentifier: "ProviderProfileVC") as? ProviderProfileVC {
            self.navigationController?.pushViewController(vc, animated: true)
        }
    }`
    `@IBAction func menuBtnPressed(_ sender: UIBarButtonItem) {
        
        if let rightMenu = SideMenuManager.default.rightMenuNavigationController {
            present(rightMenu, animated: true, completion: nil)
        }
    }`

    `class func makeSettings() -> SideMenuSettings {
            let presentationStyle: SideMenuPresentationStyle = .menuSlideIn
            presentationStyle.backgroundColor = .clear
        
            var settings = SideMenuSettings()
            settings.presentationStyle = presentationStyle
            settings.menuWidth = UIScreen.main.bounds.width * 0.75
            settings.alwaysAnimate = true
            settings.usingSpringWithDamping = 0.9
            settings.blurEffectStyle = .regular
            settings.statusBarEndAlpha = 0
            settings.dismissOnPush = true
            return settings
        }
    
        class func setupSideMenu(storyBoard: UIStoryboard,_ viewcontroller: UINavigationController) {
            let menu = storyBoard.instantiateViewController(withIdentifier: "SideMenu") as? 
    SideMenuNavigationController
        
            SideMenuManager.default.rightMenuNavigationController?.settings = 
    HelperMethods.makeSettings()
            SideMenuManager.default.rightMenuNavigationController = menu
            SideMenuManager.default.addPanGestureToPresent(toView: viewcontroller.navigationBar)
            SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: viewcontroller.view)
       
    }`

**Comment by naveen204pauly** [comment]
@mEldewaik  You can't push a controller from the presented view controller. So make sure your main view controller which is going to show your side menu view controller should be embedded in a Navigation controller. 

**This piece of code works fine because the navigation controller is embedded in window**

`        self.window = UIWindow.init(frame: UIScreen.main.bounds)

        let navigationController = UINavigationController.init()

        let mainView = UIStoryboard.init(name: UserManager.isLoggedIn ? "Main" : "Login",
                                         bundle: Bundle.main).instantiateInitialViewController()!

        navigationController.viewControllers = [mainView]

        self.window?.rootViewController = navigationController`

**Without the navigation controller as root, I can experience the same issue as you described**

`
        self.window = UIWindow.init(frame: UIScreen.main.bounds)

        let mainView = UIStoryboard.init(name: UserManager.isLoggedIn ? "Main" : "Login",
                                         bundle: Bundle.main).instantiateInitialViewController()!

        self.window?.rootViewController = mainView
`

**Comment by jonkykong** [comment]
Please follow the README instructions carefully.

**Comment by Dave181295** [comment]
Stuck hours with this, give us a real example with the storyBoard please

**Comment by Dave181295** [comment]
what if I got a login screen and want to redirect user if hes signed in directly to the main screen
(the vc that present the sideMenu) ?
