### ISSUE TITLE
Migrating from 6.4.7 to 5.0.3

### ISSUE THREAD

**Issue by tedgonzalez** [jonkykong/SideMenu#603]
Hi what is the equivalent of SideMenuManager.menuFadeStatusBar in SideMenuNavigationController ?

**Comment by kennyevo** [comment]
From the documentation:

`// (Optional) Prevent status bar area from turning black when menu appears:
leftMenuNavigationController.statusBarEndAlpha = 0`

`statusBarEndAlpha` is the property you're looking for I think
