### ISSUE TITLE
Xcode 11.4 beta2 Support.

### ISSUE THREAD

**Issue by yadav-anil92** [jonkykong/SideMenu#604]
I'm getting an error while compiling with Xcode 11.4 beta2.
Please see the attachment for the error reference.
![Screenshot 2020-02-22 at 6 34 47 PM](https://user-images.githubusercontent.com/45240311/75092870-5659a580-55a2-11ea-903b-7b54bbbdabe7.png)

Could you please guide me. How to solve this?

**Comment by yadav-anil92** [comment]
> I'm getting an error while compiling with Xcode 11.4 beta2.
> Please see the attachment for the error reference.
> ![Screenshot 2020-02-22 at 6 34 47 PM](https://user-images.githubusercontent.com/45240311/75092870-5659a580-55a2-11ea-903b-7b54bbbdabe7.png)

Could you please guide me on it?

**Comment by drewmclean** [comment]
Has this been resolved in a public release yet?

**Comment by dgoodine** [comment]
Not as of right now. And now that Xcode 11.4 has been released, this is going to be a serious problem. I'm looking into it, but as usual the compiler error isn't particularly useful.

**Comment by jonkykong** [comment]
Solved in `6.4.8`.
