### ISSUE TITLE
I get "circular reference error" on Xcode Beta-2 11.4 

### ISSUE THREAD

**Issue by MakwanaVihas** [jonkykong/SideMenu#607]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
At line 112 of SideMenuNavigationController(given line):
  **internal typealias Model = MenuModel & PresentationModel & AnimationModel**

I get the error:
Circular reference
Through reference here

**To Reproduce**
Build the project and install 6.4.6 version of SideMenu and while building it you will get a compile error

**Expected behavior**
I expected it to run

**Screenshots**
<img width="852" alt="Screenshot 2020-03-01 at 2 39 56 AM" src="https://user-images.githubusercontent.com/43501553/75615145-46bffb00-5b66-11ea-85a3-ae5052bf43b1.png">

**Comment by richardtop** [comment]
Having the same issue:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/8013017/75887672-d26dac00-5e32-11ea-927a-e66845304d50.png">

**Comment by OmarHassan25** [comment]
Having the same issue,

**Comment by kamerc** [comment]
I'm also having this issue

**Comment by seanhamstra** [comment]
Same here!

**Comment by CLoutas** [comment]
Same on Xcode 11.4 beta 3 (11N132i)

**Comment by jorgifumi** [comment]
A lot of people with the same problem. Please @jonkykong accept #598 pull request and release a new version. Thanks!

**Comment by stelabouras** [comment]
Xcode 11.4 stable has been released (Version 11.4 (11E146)) and the issue is still there.

**Comment by linhth-0720** [comment]
same isuse

**Comment by jorgifumi** [comment]
> Xcode 11.4 stable has been released (Version 11.4 (11E146)) and the issue is still there.

> same isuse

The issue is already solved in the 6.4.8 version released today.

You can see here #616 

This issue can be closed now

**Comment by keshav-ujjainia** [comment]
Issue is solved by updating the pods, 
$ pod update
