### ISSUE TITLE
SideMenu with TabBar - swiping frame issue

### ISSUE THREAD

**Issue by w33z** [jonkykong/SideMenu#608]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When i'm using presentingScaleFactor property tabbar starts changing frame height. If swiping gesture did start it's jumping. 

**To Reproduce**
1. Click on 'tab bar item'
2. Start swiping gesture on menu controller

**Expected behavior**
Tabbar frame height stop changing

**Screenshots**
[Video](https://vimeo.com/user109195699/review/394883872/4c57a09f3c)

**Additional context**
Issue only on iphone with notch

     func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        if viewController is SideMenuNavigationController {
            // menu init SideMenuNavigationController from storyboard

            menuVC.presentationStyle = .viewSlideOut
            menuVC.presentationStyle.presentingScaleFactor = 0.92
            menuVC.menuWidth = 280

            present(menuVC, animated: true, completion: nil)

            return false
        }

        return true
    }

**Comment by jonkykong** [comment]
Hello,

In order for me to troubleshoot your issues, you must provide me with a modified version of the demo project that demonstrates the issue. That way I can confidently eliminate any issues in your own code that don't play well with SideMenu, as it has performed as expected in my own projects.

Please provide a modified demo project and reopen this issue.
