### ISSUE TITLE
Layout Custom Tab Bar Layout hide after dismiss menu right 

### ISSUE THREAD

**Issue by hafiz013** [jonkykong/SideMenu#609]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**
1. Go to button to appear right side menu
2. Side menu right appear with tab bar bottom appear 
3. After that dismiss side menu right, tab bar bottom hide bottom.

**Expected behavior**
Either click button to appear side menu right show with tab bar bottom or dismiss from side menu tab bar bottom should appear as well.

**Screenshots**
![before_click](https://user-images.githubusercontent.com/6707224/75847484-4c456b80-5e1a-11ea-9527-132e75244e69.png)
![while_click](https://user-images.githubusercontent.com/6707224/75847503-5d8e7800-5e1a-11ea-9c16-bae10ea011a8.png)
![after_click](https://user-images.githubusercontent.com/6707224/75847518-6da65780-5e1a-11ea-99f3-3a5e15a6c194.png)
![configuration](https://user-images.githubusercontent.com/6707224/75847528-74cd6580-5e1a-11ea-8d8b-b54f06f282e2.png)

Please help ..

**Additional context**

**Comment by w33z** [comment]
Change presentation style of your **_SideMenuNavigationController_** to 
`presentationStyle = .menuSlideIn`

And you can also increase you menu width from 250 to bigger value

**Comment by hafiz013** [comment]
It is have to do programmatically code or in storyboard?

**Comment by caglayansever** [comment]
I have same issue with splitview.

**Comment by jonkykong** [comment]
Hello,

In order for me to troubleshoot your issues, you must provide me with a modified version of the demo project that demonstrates the issue. That way I can confidently eliminate any issues in your own code that don't play well with SideMenu, as it has performed as expected in my own projects.

Please provide a modified demo project and reopen this issue.
