### ISSUE TITLE
Swift 3 (Xcode Beta 5) support

### ISSUE THREAD

**Issue by gabrielPeart** [jonkykong/SideMenu#61]
@jonkykong thanks for creating a very nice/handy class. I have tried it and works just fine, but is not working properly for Swift 3 projects.
I did a quick test using the suggested migration (via Xcode) and managed to get it running, but got some bugs (not displaying the menu as it suppose to) and other issues.

The key part is, are you working on the Swift 3 version? Or should I fix it myself and do a Pull Request?

**Comment by lemonandlime** [comment]
@jonkykong Im having the same issue afterSwift 3 update. The menu transition makes it go full screen and calls to willDisappear seams to be a little of after update.

**Comment by jonkykong** [comment]
Hi @gabrielPeart, @lemonandlime,

First off, thanks for both of you being awesome enough to report this and offer to fix it!

I myself have not yet tested this for Swift 3, but I don't doubt your claims. I'd be happy to take a look at any fixes you propose, however I have these concerns:

1. Given that Swift 3 is still in beta, it's possible that any proposed fixes are not real issues when Swift 3 is released, or are still broken after it is released.
2. I want to make sure the component is still functioning as expected prior to Swift 3 until it is released.

Thoughts?

**Comment by gabrielPeart** [comment]
@jonkykong Hi, thanks for answering.

I believe that you have valid points, just adding on top of that the fact that Swift 3 is going to be released soon (September 7) and mostly applications are being developed and will be tested/submitted before that. That is why is a good idea to make it compatible.

As soon as we have a Swift 3 branch up and running without any bug, when Apple release new Xcode beta versions (if will have breaking changes they will be minimal).

I extremely recommend you to create a new branch called swift3 and perform all the necessary adjusts to support it. It won't be difficult since Xcode will migrate the code to the new format and suggest changes. You will only face some logical issues that aren't hard to fix.

Let me know if you will need any help with this topic.

**Comment by jonkykong** [comment]
@gabrielPeart Fair points.

Feel free to take a stab at Swift 3 support. There are a few open PRs already I haven't had a chance to get to yet because I am working on another project, so I won't be able to take a look until next week or the following.

**Comment by gabrielPeart** [comment]
@jonkykong Cool. Thank you!

**Comment by jonkykong** [comment]
@gabrielPeart @lemonandlime I have updated the code base for Swift 3 support here: https://github.com/jonkykong/SideMenu/tree/2.0.0

Can you please verify that it's working for you?

**Comment by jonkykong** [comment]
You should be able to update your podfile in the short term with the following to run it in your projects:

```ruby
pod 'SideMenu', :git => 'https://github.com/jonkykong/SideMenu.git', :branch => 'swift3'
```
