### ISSUE TITLE
Side menu not working in Xcode 11.3.1,App will be crashed when i click on side menu

### ISSUE THREAD

**Issue by shaikhmoin** [jonkykong/SideMenu#612]
Side menu was working fine before Xcode 11 updated (Side menu width = 240 Fix) But after the Xcode 11 update side menu shows to full screen.So how can i handle it in Xcode 11 Or Above

**Comment by shaikhmoin** [comment]
Now I have updated Xcode 11.3.1 So,I Reinstall Side menu pod 'SideMenu', '~> 6.0' But when i click on side menu then my app will crashed And display error is like ....."SideMenu was compiled with optimization - stepping may behave oddly; variables may not be available." 
     So what can i do in this situation?

**Comment by jonkykong** [comment]
You need to reproduce this in the demo project which is working as expected; otherwise I'm inclined to believe that there is something atypical with your project causing this issue.
