### ISSUE TITLE
Side Menu Opening in every screen in App when i swipe

### ISSUE THREAD

**Issue by ramakrishna013** [jonkykong/SideMenu#614]
In my app, I'm showing the Side Menu when the button clicked in the Dashboard screen. It's working fine. But when I enter into another view controller and swipe from left the Side Menu show. How can stop that? I want to show the side menu when the user swipes in Only  Dashboard screen, not in other screens.

**Comment by shaikhmoin** [comment]
You want side menu only in dashboard screen But not wants to another screen right? So you can remove the trigger segue from your all pages Also you can remove side menu images from leftone side of screens.

**Comment by shtefane** [comment]
When you configure your menu add gesture to the desired ViewController view only.
`SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: view, forMenu: .left)` 
instead of self.navigationController!.view
