### ISSUE TITLE
Xcode 11.4 Circular Reference errors

### ISSUE THREAD

**Issue by pawargb** [jonkykong/SideMenu#617]
![Screenshot 2020-03-28 at 9 22 45 AM](https://user-images.githubusercontent.com/33100445/77814293-b8438880-70d5-11ea-8a2e-c6b93a391fd8.png)

Getting this error when upgraded Xcode to 11.4. Earlier it was working fine.

**Comment by jonkykong** [comment]
Use the latest code.

**Comment by YuryRadchenko** [comment]
Xcode Version 11.4 (11E146). Circular reference error too.

**Comment by alijaza** [comment]
When will 6.4.8 be available for Cocoapods?

**Comment by YuryRadchenko** [comment]
I changed only one number to 8. Work.
<img width="262" alt="Untitled" src="https://user-images.githubusercontent.com/2685560/77818547-f6dc4180-70db-11ea-9376-47159ec8c265.png">
