### ISSUE TITLE
Can't build project after updating Xcode to version 11.4 (Circular reference)

### ISSUE THREAD

**Issue by nikolaveljic64** [jonkykong/SideMenu#619]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

After updating Xcode to version 11.4 , i can't build project. We now have error.

**To Reproduce**

1. Build project

**Expected behavior**
Build to succeed.

**Screenshots**
<img width="793" alt="Screen Shot 2020-03-30 at 11 21 16 AM" src="https://user-images.githubusercontent.com/18101315/77897381-e1048300-7279-11ea-98ca-11e18c9d5d1a.png">

**Additional context**
Nothing.

**Comment by jonkykong** [comment]
Update to the latest.
