### ISSUE TITLE
/SideMenuNavigationController.swift:112:24: Circular reference

### ISSUE THREAD

**Issue by linocoiasoft** [jonkykong/SideMenu#620]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [ x] My issue is happening in the **latest version** of SideMenu.
- [ x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

After the update to XCode 11.4 it returns the error indicated in the title: "/Pods/SideMenu/Pod/Classes/SideMenuNavigationController.swift:112:24: Circular reference"

**Comment by jonkykong** [comment]
Update to the latest.
