### ISSUE TITLE
Circular reference error

### ISSUE THREAD

**Issue by saidbicer** [jonkykong/SideMenu#621]
XCode 11.4
Error : Circular reference
Code : 

internal typealias Model = MenuModel & PresentationModel & AnimationModel

**Comment by rickrvo** [comment]
I did a local fix for this but my CI/CD is not working...

changing:
internal typealias Model = MenuModel & PresentationModel & AnimationModel 
to
internal typealias ModelSideMenu = MenuModel & PresentationModel & AnimationModel

in SideMenuNavigationController.swift

then updating the alias in the class Inheritance that was using Model to ModelSideMenu worked

**Comment by jonkykong** [comment]
Update to the latest.

**Comment by songhku925** [comment]
thank you so much.

**Comment by Revanth-Kausikan** [comment]
Thanks, can you also please publish this pod?
