### ISSUE TITLE
Getting compier

### ISSUE THREAD

**Issue by ixcoder001** [jonkykong/SideMenu#623]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
-  My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.

**Describe the bug**
Getting Compiler error
I just installed latest sidemenu version using pod and run the project it is showing the following error

**To Reproduce**
1. install the latest version SideMenu (6.4.8)
2. open the project
3. run the project

**Expected behavior**
Compiler error should not happen

**Screenshots**
<img width="1141" alt="screen" src="https://user-images.githubusercontent.com/48469278/78969502-b42b5800-7b24-11ea-8c57-af8454a53760.png">

**Comment by jonkykong** [comment]
https://developer.apple.com/documentation/uikit/uiwindow/3197962-windowscene

`windowScene` exists in iOS13+. Please make sure you're using the latest version of Xcode.
