### ISSUE TITLE
Add and remove Gestures

### ISSUE THREAD

**Issue by mrgaolei** [jonkykong/SideMenu#624]
When I add:
```
SideMenuManager.default.addScreenEdgePanGesturesToPresent(toView: self.navigationController!.view)
```

How to remove the gestures?

**Comment by khasanoff** [comment]
SideMenuManager.default.enableSwipeGestures = false not works

**Comment by khasanoff** [comment]
@mrgaolei did you find solution to disable gesture???

**Comment by jonkykong** [comment]
`addScreenEdgePanGesturesToPresent` returns the gesture that was created. If you want to remove it, simply remove that returned gesture from the desired view or disable the gesture.
