### ISSUE TITLE
I cannt back to the main view

### ISSUE THREAD

**Issue by amjad401** [jonkykong/SideMenu#63]
I pushed all viewControllers programmatically, it's work by use `didSelectRowAtIndexPath`
but I tried to back to main view , that's not work
I set this `SideMenuManager.menuAllowPopIfPossible = true`
and I tried using all of this : 
`presentingViewController!.dismissViewControllerAnimated(true, completion: nil)`
`self.navigationController!.popToRootViewControllerAnimated(false)`
```
            let viewControllers: [UIViewController] = self.navigationController!.viewControllers as [UIViewController];
            self.navigationController!.popToViewController(viewControllers[viewControllers.count ], animated: true);
```

all of these not work, why? :(

**Comment by jonkykong** [comment]
There's not enough information here to tell you why. I would suggest using breakpoints to walk through the code to figure out what's going on. It's possible you're setting up your viewcontrollers in a way that wasn't accounted for with the library.
