### ISSUE TITLE
Pop gesture not working when SideMenu dismisal was cancelled before

### ISSUE THREAD

**Issue by herrernst** [jonkykong/SideMenu#630]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Pop gesture not working when SideMenu dismisal was cancelled before

**To Reproduce**
1. Run the example
2. Click on "Left Menu"
3. Drag back the main screen slightly, but cancel it before it comes in
4. Click on some Push View Controller
5. Pop gesture to go back in navigation hierarchy by swiping from left side doesn't work anymore

**Expected behavior**
Swipe to go back is possible

**Screenshots**
Video showing the problem: First it works, but after cancelling SideMenu dismal once, it doesn't work anymore

![swipe-back](https://user-images.githubusercontent.com/20795/84889989-0dba8080-b09a-11ea-9ed0-f6694d700a4a.gif)

**Additional context**
Xcode 11.5, iOS 13.5

**Comment by jonkykong** [comment]
@herrernst good find. It's a one-liner fix... I'll get to it when I can.

**Comment by herrernst** [comment]
Thanks, that would be great! (I couldn't find the cause at first sight.)

**Comment by jonkykong** [comment]
Fixed in `6.4.9`.

**Comment by herrernst** [comment]
Thank you very much!
