### ISSUE TITLE
How to pass info from SlidMenu to HomeViewController using segue?

### ISSUE THREAD

**Issue by sulabh9999** [jonkykong/SideMenu#632]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ ] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ ] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
I am trying to pass flag from SlidMenu rootViewController to my HomeViewController, don't want to push any ViewController. Here i'm using Storyboard and segue. i tried to check other open/closed issues but couldn't find answer.

**Comment by umbrellait-evgeny-mokeev** [comment]
If I understand your issue correctly, I did it with a callback. Here is a tutorial video. It is in Russian, but you can check code:
https://www.youtube.com/watch?v=SiMPvYjLlJk

**Comment by jonkykong** [comment]
This question is more appropriate for StackOverflow.com.
