### ISSUE TITLE
Safe Area

### ISSUE THREAD

**Issue by aabaza97** [jonkykong/SideMenu#634]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ +] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ +] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ +] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [+ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ +] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Whenever presenting the side menu, the area above the safe area goes black.

**To Reproduce**
1- click the menu bar button
2- the menu slides in and the area above the safe area goes black.

**Expected behavior**
the area above the safe area should be the same as the background of the toolbar of the navigation controller

**Screenshots**
![image](https://user-images.githubusercontent.com/32808494/87233203-b0c69780-c3c5-11ea-9f8f-0ca06c743f4b.png)
![image](https://user-images.githubusercontent.com/32808494/87233207-bc19c300-c3c5-11ea-9009-dbc48df2a921.png)

**Comment by vvit** [comment]
Just set the `settings.statusBarEndAlpha = 0`

**Comment by jonkykong** [comment]
> Just set the `settings.statusBarEndAlpha = 0`
