### ISSUE TITLE
Menu appears modally instead from left side

### ISSUE THREAD

**Issue by lfmorales** [jonkykong/SideMenu#639]
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

After updating to the latest pod version, in iOS 13.5.1, side menu appears modally over the app instead from the left side, as it was working up to now. Anyone has experienced that?

**Comment by JaDenis** [comment]
.viewSlideOutMenuZoom option scales menu instead of presenting view for me
iOS 3.5.1

I tried switching presenting and presented views inside the pod, but no luck

**Comment by lfmorales** [comment]
Thank you. I've finally solved it. In the updating process there was a change in the naming of classes, from SideMenuNavigationController to UISideMenuNavigationController. Don't know why it happened, but after renaming the classes (both in Storyboard and code), it's working right now.

Thanks
