### ISSUE TITLE
Enable interaction with background view controller

### ISSUE THREAD

**Issue by gunnarblom** [jonkykong/SideMenu#64]
Hi.

Good job with the side menu!

One good feature to add is to enable interaction with the view controller that is presenting the menu. E.g. in my case the side menu shows a list of geographical places, and when you click them in the menu it zooms to them on the map. And to be able to pan around on the map or do other stuff at the same time would be awesome.

I would gladly help contributing if you could guide me where to start, I'm not familiar with custom transitions and the architecture around them.

Keep up the good work,
Gunnar

**Comment by jonkykong** [comment]
Fixed in branch 1.2.0. Please note that using this property without properly managing presenting menus when they're already shown can cause unexpected crashes or visual problems.
