### ISSUE TITLE
It closes on rotation without any interaction

### ISSUE THREAD

**Issue by StefaniOSApps** [jonkykong/SideMenu#646]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
When rotating, the menu closes without a SideMenu function being called.

**To Reproduce**
1. start example im simulator
2. open sidemenu
3. rotate device
4. the menu was closed by framework

**Expected behavior**
If the menu was opened before the rotation, it should remain open after the rotation. If the menu was opened before the rotation, it should remain open after the rotation.

**Comment by StefaniOSApps** [comment]
my bad .. :D

**Comment by oussa005** [comment]
@StefaniOSApps: i have the same problem, how did you resole it ?
thx

**Comment by StefaniOSApps** [comment]
@oussa005 read doc first ... 

```
/// Automatically dismisses the menu when the screen is rotated.
var dismissOnRotation: Bool = true
```
