### ISSUE TITLE
Xcode 12 Building for iOS Simulator, but the linked framework 'SideMenu.framework' was built for iOS.

### ISSUE THREAD

**Issue by williamhqs** [jonkykong/SideMenu#647]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [ y] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [ y] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [y ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [y ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.

**Describe the bug**
`Building for iOS Simulator, but the linked framework 'SideMenu.framework' was built for iOS.`

**To Reproduce**
Upgrade to Xcode 12 get this error.

**Comment by jonkykong** [comment]
Until Xcode 12 is non-beta, this is not supported for backwards compatibility.

**Comment by williamhqs** [comment]
@jonkykong It's already released.
