### ISSUE TITLE
How to include in Objective-C project?

### ISSUE THREAD

**Issue by zionun** [jonkykong/SideMenu#651]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**

Hello, sorry if this has been asked before, but I couldn't find anything that could help me.
I'm trying to use this project inside my Objective-C code (I saw the @objc/@objcMembers syntax so I'm guessing it should be possible) and I'm not using storyboards.
Can the controller be used in this scenario? If so, how?
It seems I correctly imported the module as I'm able to see the classes with autocompletion, but if I try to instantiate a SideMenuNavigationController, I cannot access the initWithRootViewController method.
What am I doing wrong?
Thank you

**Comment by jonkykong** [comment]
This is a question for stackoverflow.com.

**Comment by DanielFontes** [comment]
I had the same problem because some method weren't accessible in obj-c. I had to change some data types (InitializableClass -> NSObject for example). https://github.com/DanielFontes/SideMenu

**Comment by zionun** [comment]
> I had the same problem because some method weren't accessible in obj-c. I had to change some data types (InitializableClass -> NSObject for example). https://github.com/DanielFontes/SideMenu

Works perfectly. Thank you @DanielFontes

**Comment by lexuanquynh** [comment]
how to import header file in objective-c?
