### ISSUE TITLE
Menu won't open on iOS 14.2 beta 2

### ISSUE THREAD

**Issue by DanielFontes** [jonkykong/SideMenu#652]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [✔] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [✔] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [✔] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [✔] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [✔] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
Menu won't open on iOS 14.2 beta 2. App stops responding.

**To Reproduce**
1. Install iOS 14.2 beta 2 or download Xcode 12.2 beta 2.
2. Run the demo either on device or in the simulator.
3. Try to open the menu.

**Expected behavior**
Menu should open. App should stay responsive.

**Comment by RMSchlachter** [comment]
Yeah this is giving a memory leak for me as well.

**Comment by jonkykong** [comment]
Betas being what they are, I am not supporting anything until it is released. You're welcome to produce a fix to support others updating for beta until then. Please reopen this issue if it persists after release.

@RMSchlachter, SideMenu is held in memory deliberately to increase gesture responsiveness for reveal.
