### ISSUE TITLE
Swipe gesture for deleting a UITableViewCell does not work when Side Menu exists

### ISSUE THREAD

**Issue by lane-faison** [jonkykong/SideMenu#657]
**I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand**
- [x] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

**Describe the bug**
- I have a `UIViewController` that I can swipe left-to-right to open my Side Menu. On my VC I have a `UITableView` with cells that should be individually editable / deletable by swiping right-to-left. The presence of the Side Menu makes it so that my cell swipe gestures are not recognized.

**To Reproduce**
1. Create a `UIViewController` with a left Side Menu
2. Add a `UITableView` to the VC
3. Implement the `func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath)` method on the tableView
4. See that swiping right-to-left on the cells do not trigger the cell editing feature

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jonkykong** [comment]
This is not a bug in SideMenu; this is behavior defined by gestures. Your options are to:
1. Disable gesture swiping to reveal SideMenu
2. Configure your preferred gestures to require failure of other gestures for the desired behavior.
