### ISSUE TITLE
Removing presented controller causing Black Screen.

### ISSUE THREAD

**Issue by ashokTEZSOL** [jonkykong/SideMenu#659]
func presentViewControollerFull(vc : UIViewController) {
//        vc.modalPresentationStyle = .fullScreen
        let navi = UINavigationController(rootViewController: vc)
//        navi.modalPresentationStyle = .fullScreen
        self.present(navi, animated: true, completion: nil)
    }

when I try to remove it

self.dismiss(animated: true, completion: nil)

result is black screen.

**Comment by kaaaaai** [comment]
I had the same problem. How did this one work out?
