### ISSUE TITLE
How to do get background view as blur while sidemenu is opened

### ISSUE THREAD

**Issue by Elamuruga** [jonkykong/SideMenu#675]
@jonkykong While showing the side menu parent view of the side menu should blur or dimmed. Could you please help me with this?

**Comment by gaoqh** [comment]
I have a same question

**Comment by XingXiaoWu** [comment]
presentingendAlpha

**Comment by Elamuruga** [comment]
> presentingendAlpha

@XingXiaoWu Could you please help me with a clear code sample? Thanks in advance that will help me a lot.

**Comment by elhajjajiamine** [comment]
same here ✌️

**Comment by elhajjajiamine** [comment]
`        SideMenuManager.default.menuAnimationFadeStrength = 0.8
`

**Comment by Elamuruga** [comment]
> default.menuAnimationFadeStrength = 0.8

@elhajjajiamine @XingXiaoWu  Thank you for your immediate responses. I tried your solution but it's not working and the above method you mentioned was deprecated I think so. Could you please help me with this? thanks in advance. The expected result sample screenshot I attached below. Captured in Gmail App in iOS mobile.
![2021-07-22](https://user-images.githubusercontent.com/40588914/126737305-6ef55641-d663-4d8b-9500-7f15da6436ad.jpeg)

**Comment by XingXiaoWu** [comment]
```
var menu = SideMenuNavigationController(rootViewController: SideMenuController.init())
menu.settings = makeSettings()
```
```
private func makeSettings() -> SideMenuSettings{
        let presentationStyle = SideMenuPresentationStyle.menuSlideIn
// -----look at this line-----start
        presentationStyle.presentingEndAlpha = CGFloat.init(0.5)
// -----look at this line-----end
        var settings = SideMenuSettings()
        settings.presentationStyle = presentationStyle
        return settings
    }
```

**Comment by XingXiaoWu** [comment]
![image](https://user-images.githubusercontent.com/22769131/127148393-824e4e86-b831-40cc-909c-ea39abbe9b55.png)
like this

**Comment by balashekar3** [comment]
@Elamuruga use this code: leftMenuNavigationController.presentationStyle.presentingEndAlpha = 0.5

**Comment by Elamuruga** [comment]
> @Elamuruga use this code: leftMenuNavigationController.presentationStyle.presentingEndAlpha = 0.5

@balashekar3 Thank you lot solution you were provided were working fine.

**Comment by Elamuruga** [comment]
> @Elamuruga use this code: leftMenuNavigationController.presentationStyle.presentingEndAlpha = 0.5

@gaoqh You can use this it's working fine. once again thank you @balashekar3
