### ISSUE TITLE
Programatically push new ViewController

### ISSUE THREAD

**Issue by ptishu** [jonkykong/SideMenu#71]
Hello,

I have a SideMenu containing a SideMenuNavigationController with one rootView, all created programatically:
   
    let menuNavigationController = MenuNavigationController(rootViewController: MenuRootViewController())

    override func viewDidLoad() {
        super.viewDidLoad()
        
        menuNavigationController.leftSide = true
        SideMenuManager.menuRightNavigationController = menuNavigationController
    }

where MenuNavigationController is simply
```
class MenuNavigationController : UISideMenuNavigationController, UINavigationControllerDelegate
{
    override func viewDidLoad() {
        super.viewDidLoad()
        self.delegate = self
    }
    
    func camTapped()
    {
        let camController = CamSetViewController()
        self.pushViewController(camController, animated: true)
    }
}
```

And on a specific action I open the SideMenu from my MainViewController as follows

```
presentViewController(SideMenuManager.menuRightNavigationController!, animated: true, completion: {
                () -> Void in
            }) 
```

This opens fine and renders my MenuRootViewController fine. When selecting an event though, I want to push the second level submenu as the active view in the SideMenu. I call the following code from MenuRootViewController

```
self.navigationController?.camTapped()
```

But this throws the following waning and presents the submenu fullscreen instead of showing it in the SideMenu
`SideMenu Warning: cannot push a ViewController from a ViewController without a NavigationController. It will be presented it instead.`

I don't really understand this warning. I am pushing from a ViewController that has a NavigationController. I have tried to use my same MenuRootViewController in a regular NavigationController without using SideMenu, and the same code pushed it correctly inside the NavigationController, the navigation bar updates with the back button, all as expected. Is there anything specific to do with when using the SideMenu?

Thanks

**Comment by jonkykong** [comment]
I suggest looking at the source code for SideMenu to understand the warning better.
