### ISSUE TITLE
SSASideMenu Library Implementation Problem

### ISSUE THREAD

**Issue by iamasimkhan** [jonkykong/SideMenu#73]
I'm using this library 
[https://github.com/SSA111/SSASideMenu](url)
When it is used as it is, it works.
However, I'm implementing this for my overall app, I mean in every ViewController, I want to use the same side bar menu, that must appear on the click of Menu bar button item. Due to spare navigation problems I guess, is not working on navigation from one control to other.

**Comment by jonkykong** [comment]
@iamasimkhan I'm not sure why you're posting an issue here about some other library. I am only supporting my library, please open an issue with the other author.

**Comment by iamasimkhan** [comment]
Great .... 
Ok if I use your's library, then is there a way for 'Parallax effect' for side menu.

**Comment by jonkykong** [comment]
Read the README and decide for yourself. I wrote it so I wouldn't have to respond to everyone individually.
