### ISSUE TITLE
parallax effect in Sidebar menus with given library

### ISSUE THREAD

**Issue by iamasimkhan** [jonkykong/SideMenu#74]
I'm thankful of your in time reply, please will you please guide me .. If I use yours library which I already have downloaded and tested, but my designer is attending parallax effect in sidebar menu, so how is it become possible?

**Comment by jonkykong** [comment]
This is my last response to you. I do not have time to answer your questions. I have provided all the necessary information in the README and you are ignoring that and choosing to ask me instead. Please respect my time and instead investigate this yourself.
