### ISSUE TITLE
Support of submenus

### ISSUE THREAD

**Issue by ogezue** [jonkykong/SideMenu#76]
Currenty I'm using a main view controller, that lets open your menu and a sub menu.

The behavior should be that your submenu is a child of the menu. But the menu is a child of the main view controller. Is there an example how to accomplish it?

Why are views that are pushed from the menu not on the same stack as the menu?

I saw that all that is necessary is to comment out pushViewController in UISideMenuNavigationController. So before I would create my own modification - wouldn't it be great if you could add another setting that would do exactly this? `menuPushViewControllersOnMenuController = true`

**Comment by jonkykong** [comment]
I'm sorry, but I don't understand your question or problem.

**Comment by ogezue** [comment]
I just want to have the same pushViewController behavior inside your menu as on every other view controller. So I'm able to implement submenus on child pages. 
This could be configurable by a setting. So developers can switch between current behavior and the submenu support.

**Comment by jonkykong** [comment]
The current behavior is less confusing for the 80%+ case, but a
configuration might be useful. Would you like to add this config and submit
a PR?

**Comment by ogezue** [comment]
Yes - will do it

**Comment by dmitryLagoda** [comment]
Hi, guys. Want to achieve the same behavior of pushing view controllers inside the menu. But even with menuAllowSubmenus = true I'm unable to do this.

**Comment by jonkykong** [comment]
@dmitryLagoda This is working as expected in the example project. The error you see in the log (past the line you cited) describes the problem you're facing very precisely. Please continue to troubleshoot yourself and you'll figure it out soon.

**Comment by dmitryLagoda** [comment]
Thanks for response! In deed it works. Will check, why it doesn't in my project!
