### ISSUE TITLE
Local settings for each menu

### ISSUE THREAD

**Issue by Xioshock** [jonkykong/SideMenu#78]
Hey, nice library 👍 . Would you be so kind to add a separate settings for each side menu? I currently need a regular side menu on left side and then a second one on the right side, with different settings, mainly the width.

I think having the static SideMenuManager is not bad, but it could be maybe overriden by another instance of it in SideMenu.

**Comment by jonkykong** [comment]
Just subclass each side menu and change settings on init.

**Comment by Xioshock** [comment]
It works, I had to add it to viewWillAppear as well, seems kinda messy, but thanks :)
