### ISSUE TITLE
Open menu by tap action

### ISSUE THREAD

**Issue by yurevich1** [jonkykong/SideMenu#79]
Please, provide an example, how to it is possible to expand menu by simple tapping on a button. As I've found in the code only swipe gestures are allowed.

**Comment by jonkykong** [comment]
I don't understand what you mean by "expand menu".

**Comment by yurevich1** [comment]
I mean open those left and right menu by tapping somewhere using this API.
In your example there are two buttons: "left menu" and "right menu".

If found this solution:
...
```self.navigationItem.leftBarButtonItem = UIBarButtonItem(barButtonSystemItem: .Cancel, target: self, action: #selector(MyViewController.btnTapped(_:)))
        self.navigationItem.leftBarButtonItem!.tag = 1
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .Save, target: self, action: #selector(MyViewController.btnTapped(_:)))
        self.navigationItem.rightBarButtonItem!.tag = 2```
...


```
func btnTapped(barButtonItem: UIBarButtonItem) {
        guard let menu = barButtonItem.tag == 1 ? SideMenuManager.menuLeftNavigationController : SideMenuManager.menuRightNavigationController else { return }
        self.navigationController!.presentViewController(menu, animated: true, completion: nil)
    }


```


Is there any method in your framework with the same behaviour?

**Comment by jonkykong** [comment]
As stated in the README and the examples I've already provided... this
library uses interactive transitions, meaning you use the standard
presentViewController methods to display the menu. There is no need for a
special API to display the menu.
