### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by hedtech** [jonkykong/SideMenu#80]
Hello,

Nice job !
It will be also nice to be able to remove the UIApplicationDidEnterBackgroundNotification which hides the menu. 
Do you have any workaround currently ? (the class is private)

Thanks and keep up this nice library,
Jean

**Comment by jonkykong** [comment]
Why is there a need to do this?

You can subclass the menu and unregister it for notifications right after
it registers if you want.

**Comment by hedtech** [comment]
Hi,

To keep the menu open when you come back on foreground.

The class is internal, impossible to subclass.

Thanks

**Comment by jonkykong** [comment]
@hedtech I understand it's internal.

Why does the menu need to stay open when you come back from the foreground?

**Comment by juliengdt** [comment]
@jonkykong to summarize :

Sometimes, `Client > all`

😺 

This is not a bad idea to customize this "feature" instead of subclassing a whole class just for this

**Comment by jonkykong** [comment]
@juliengdt I will not be building this feature.

Feel free to read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and open a pull request with your changes.
