### ISSUE TITLE
A tiny detail about menuAllowPushOfSameClassTwice

### ISSUE THREAD

**Issue by Bubcho** [jonkykong/SideMenu#88]
Hello @jonkykong,
Congratulations on your good library! I'm using it in my project, though in a slightly different manner than it's meant to be used. :-) I noticed something small that's not worth of a pull request and I thought I would share it here. 

The `menuAllowPushOfSameClassTwice` option was not working at first. By digging in the code I noticed that on line 157 in `UISideMenuNavigationController.swift` the `if` statement fails because the `last` property of a collection returns an optional value. So i fixed it by unwrapping the optional returned by `last`.

Thank you for the quality framework again. Have a good day. :-)

**Comment by jonkykong** [comment]
Fixed in 2.0.5.
