### ISSUE TITLE
How can I push a controller from SideMenu?

### ISSUE THREAD

**Issue by alexsanderkhitev** [jonkykong/SideMenu#95]
Hello! Thanks for this beautiful framework.
My architecture

`TabBarController` ( this is main controller) -> `UITableViewController` ( this is a left side controller). I tried to push another controller from  `UITableViewController` but I got this error  "SideMenu Warning: attempt to push a ViewController from a ViewController without a NavigationController. Your ViewController must be embedded in a NavigationController for this to work."

So I initialize the controller left

```
private func setupSideMenu() {
        let storyboardManager = StoryboardManager()
        let leftMenuController = storyboardManager.leftMenu.instantiateViewControllerWithIdentifier(MainMenuLeftTableViewController.self)
        
        let leftNaviController = UISideMenuNavigationController(rootViewController: leftMenuController)
        leftNaviController.leftSide = true
        
        SideMenuManager.menuLeftNavigationController = leftNaviController
        
        // Gestures
        SideMenuManager.menuAddPanGestureToPresent(toView: view)
        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: view)
    }
```

Then I try to push from `UITableVIewController` so 

```
     let settingsTVC = storyboardManager.leftMenu.instantiateViewControllerWithIdentifier(LeftSettingsTableViewController.self)
navigationController?.pushViewController(settingsTVC, animated: true)
```

How can I fix it or remake?

I made it in storyboard, but I all the same got this error 
![new](https://cloud.githubusercontent.com/assets/12511909/20170437/9eec84ca-a745-11e6-9f59-4ecbf56cac89.png)

**Comment by rjcristy** [comment]
from Left/Right Menu Controller

    navigationController?.pushViewController(vc, animated: true)
