### ISSUE TITLE
How to change the width of the pushed controller from SideMenuController? 

### ISSUE THREAD

**Issue by alexsanderkhitev** [jonkykong/SideMenu#96]
How to change the width of the pushed controller from SideMenuController? I want that the pushed controller width will equals to the device screen width. Now the pushed controller width is equals to SideMenuController width. I tried some different variants but they didn't help me.

**Comment by jonkykong** [comment]
@alexsanderkhitev I don't understand your question. If you push a view controller from a SideMenu, it is pushed onto the view stack of the view controller that presented it and is full-width. This works as expected. You need to provide more detail.
