### ISSUE TITLE
Little bounce animation

### ISSUE THREAD

**Issue by Fr3E** [jonkykong/SideMenu#97]
Is possible to do a bounce animation of sidemenu to remind user about it when viewController is shown?
Thanks

**Comment by jonkykong** [comment]
@Fr3E it's possible but not trivial. There's no property in SideMenu that does this or enables you to add it in a simple way. To do it yourself you would either need to write your own custom transition or override SideMenuTransition (SideMenu uses custom transitions to be displayed).

You can learn more about custom transitions here: https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/CustomizingtheTransitionAnimations.html
